### ISSUE TITLE
Problem defining a Markov mixture model using GMM

### ISSUE THREAD

**Issue by leizeng2** [jmschrei/pomegranate#1000]
**Describe the bug**
I defined two Markov chains and then defined a GMM as the mixture of the two Markov chains, but get an error. Any idea why that is the case? Is it that the GMM does not support Markov chains as components?

from pomegranate import *
c1 = DiscreteDistribution({'A': 0.25, 'B': 0.75})
c2 = ConditionalProbabilityTable([['A', 'A', 0.1],
                                      ['A', 'B', 0.9],
                                      ['B', 'A', 0.6],
                                      ['B', 'B', 0.4]], [c1])

mc1 = MarkovChain([c1, c2])

e1 = DiscreteDistribution({'A': 0.3, 'B': 0.7})
e2 = ConditionalProbabilityTable([['A', 'A', 0.2],
                                      ['A', 'B', 0.8],
                                      ['B', 'A', 0.6],
                                      ['B', 'B', 0.4]], [e1])

mc2 = MarkovChain([e1, e2])

clf = GeneralMixtureModel([mc1, mc2])

Everything is fine until the last command was executed. The following is the error message:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-df33732a0274> in <module>
     23 mc2 = MarkovChain([e1, e2])
     24 
---> 25 clf = GeneralMixtureModel([mc1, mc2])

/opt/conda/lib/python3.7/site-packages/pomegranate/gmm.pyx in pomegranate.gmm.GeneralMixtureModel.__init__()

/opt/conda/lib/python3.7/site-packages/pomegranate/bayes.pyx in pomegranate.bayes.BayesModel.__init__()

AttributeError: 'pomegranate.MarkovChain.MarkovChain' object has no attribute 'd'

**Comment by leizeng2** [comment]
Still trying to figure this one out. Anyone had experience defining a mixture of two (or multiple) markov chains using General Mixture Model functionality of Pomegranate and fitting it with data? (I know how to do it with a single Markov chain) I am working on a project, any help would be really appreciated. Jacob, do you know if this is possible with Pomegranate? Thanks

**Comment by jmschrei** [comment]
Hi @leizeng2. Sorry that you're encountering issues. Conceptually, this should be possible. You can fix this specific issue by adding `mc1.d = 1` and `mc2.d = 1`. However, I've never tried making a mixture of Markov chains myself so I'm not sure if there's some minor technical issue that will prevent it from working.

If that doesn't work, you should check out https://github.com/jmschrei/torchegranate where I'm rewriting pomegranate using torch with completely rewritten internals. I don't have Markov chains implemented quite yet, but they're the next thing on my list.

**Comment by leizeng2** [comment]
Hi @jmschrei, do you mean to add them like the following:

from pomegranate import *
c1 = DiscreteDistribution({'A': 0.25, 'B': 0.75})
c2 = ConditionalProbabilityTable([['A', 'A', 0.1],
['A', 'B', 0.9],
['B', 'A', 0.6],
['B', 'B', 0.4]], [c1])

mc1 = MarkovChain([c1, c2])

e1 = DiscreteDistribution({'A': 0.3, 'B': 0.7})
e2 = ConditionalProbabilityTable([['A', 'A', 0.2],
['A', 'B', 0.8],
['B', 'A', 0.6],
['B', 'B', 0.4]], [e1])

mc2 = MarkovChain([e1, e2])

mc1.d = 1
mc2.d =1



clf = GeneralMixtureModel([mc1, mc2])

But I again got an error message. What did I do wrong, and what do they mean? Thanks

**Comment by denklewer** [comment]
@leizeng2 
Just create your own class which will be child of MarkovChain.  I am also not sure if this will work for your future steps. But in this way you can set 'd' attribute
`from pomegranate import *
c1 = DiscreteDistribution({'A': 0.25, 'B': 0.75})
c2 = ConditionalProbabilityTable([['A', 'A', 0.1],
                                  ['A', 'B', 0.9],
                                  ['B', 'A', 0.6],
                                  ['B', 'B', 0.4]], [c1])

class MyMarkovChain(MarkovChain):
    pass



mc1 = MyMarkovChain([c1, c2])

e1 = DiscreteDistribution({'A': 0.3, 'B': 0.7})
e2 = ConditionalProbabilityTable([['A', 'A', 0.2],
                                  ['A', 'B', 0.8],
                                  ['B', 'A', 0.6],
                                  ['B', 'B', 0.4]], [e1])



mc2 = MyMarkovChain([e1, e2])
mc1.d = 1
mc2.d = 1

clf = GeneralMixtureModel([mc1, mc2])`

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
