### ISSUE TITLE
Wrong Markov Chain initial state distribution

### ISSUE THREAD

**Issue by angelo5d0** [jmschrei/pomegranate#1004]
Hello everybody!

Can anyone please explain me the initial state distribution resulting from .from_samples()?

Thank you!

```
import numpy as np
from pomegranate import *

np.random.seed(137)
seq_data = np.random.randint(0, 10, (1, 1000))

markov_chain = MarkovChain.from_samples(seq_data)

print(markov_chain.distributions[0])

n = seq_data.shape[0] * seq_data.shape[1]

for i in range(10):
    print(i, ':', len(np.where(seq_data == i)[0]) / n)
```

![image](https://user-images.githubusercontent.com/47897437/200566866-f12f4839-8859-49ea-90ea-d17930deb5d4.png)

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
