### ISSUE TITLE
[BUG] HiddenMarkovModel().sample() doesn't finish

### ISSUE THREAD

**Issue by kaare-mikkelsen** [jmschrei/pomegranate#1013]
**Describe the bug**
When I create a small model with 2 states and ask it for a small sample, the code hangs. 

**To Reproduce**
  ```
import pomegranate as pg
  s1 = pg.State(pg.PoissonDistribution(10))
  s2 = pg.State(pg.PoissonDistribution(30))
  
  HMM = pg.HiddenMarkovModel()
  HMM.add_states(s1, s2)
  HMM.add_transition(HMM.start, s1, 1.0)
  HMM.add_transition(s1, s1, 0.7)
  HMM.add_transition(s1, s2, 0.3)
  HMM.add_transition(s2, s2, 0.8)
  HMM.add_transition(s2, s1, 0.2)
  HMM.bake()
  
  data = HMM.sample(10)
```

**Comment by jmschrei** [comment]
You've defined a model with no explicit end state, and also have not defined a length of the sample. This means that it is generating sequences of infinite length because it doesn't know when to stop. Either pass in an explicit length, or include edges to the end state.

**Comment by kaare-mikkelsen** [comment]
ok, I assumed it worked like sample() for markov chains, where first input is length.

However, this also doesn't finish:

`data = HMM.sample(n=1,length=10,path=True)`

**Comment by kaare-mikkelsen** [comment]
(or, it's been running for 10 minutes now, which seems excessive)

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
