### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by darik0d** [jmschrei/pomegranate#1021]
Hi,

I want to build a left-to-right Hidden Markov Model from samples. To do this, I first need to remove/disable/set to 0 some transitions between states (because in left-to-right HMMs there are no transitions to the previous state). Is it possible to do this in pomegranate? Or maybe there is another solution/approach?

Thank you in advance!

**Comment by AKuederle** [comment]
You should be able to provide an initial transition matrix to the model, with all value sthat are not allowed set to 0 or define sparse edges for the SparseHMM. This way you can restrict which edges are allowed

**Comment by jmschrei** [comment]
Yes -- you can pass in your own edge initialization when creating the model. For instance;

```python
dists = [Normal(), Normal()]
edges = [[0.5, 0.5],
    [0.0, 0.7]]
ends = [0.0, 0.3]
starts = [1.0, 0.0]

model = DenseHMM(dists, edges=edges, ends=ends, starts=starts)
```

I haven't run the above code so there might be a syntax error but that's the gist.

**Comment by jmschrei** [comment]
Closing this for now. Please re-open or open another issue if you have further questions.
