### ISSUE TITLE
Question about the role of "weights" in GeneralMixtureModel

### ISSUE THREAD

**Issue by youngwk** [jmschrei/pomegranate#1028]
Hi,
I came here from the website below:
https://stackoverflow.com/questions/36423741/python-fitting-weighted-data-with-gaussian-mixture-model-gmm-with-minimum-on-c

Can you explain how the "fit" function operates when "weights" is passed as an argument?

If certain data points are assigned a weight of 2 while others are assigned a weight of 1, does that mean those points are being oversampled twice?

**Comment by jmschrei** [comment]
Yes -- weights can be thought of as the number of times that observation occurs in the data.

**Comment by youngwk** [comment]
I understood! Thanks
