### ISSUE TITLE
[BUG] Bernoulli does not accept all values between 0 and 1

### ISSUE THREAD

**Issue by timo-a** [jmschrei/pomegranate#1044]
**Describe the bug**
I want to initialize a probability distribution with two values `sunny`, `rainy` so that one value is certain, i.e. p(`sunny`) = 1 and p(`rainy`) = 0. Use case is initializing a HMM when I already know the parameters and for some states the emissions are deterministic.
I want to use `Bernoulli` for this. As far as I understand the documentation all I have to do is pass a list with `1` and that will be  the `p` parameter. I am using pomegranate `1.0.0` And I expect the following to work: 

**To Reproduce**
```python
from pomegranate.distributions import Bernoulli

a = Bernoulli([0.9]) #works
b = Bernoulli([1.0]) #does not work
```
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.../venv/lib/python3.11/site-packages/pomegranate/distributions/bernoulli.py", line 59, in __init__
    self.probs = _check_parameter(_cast_as_parameter(probs), "probs", 
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.../venv/lib/python3.11/site-packages/pomegranate/_utils.py", line 181, in _check_parameter
    raise ValueError("Parameter {} must have a maximum value below"
ValueError: Parameter probs must have a maximum value below 0.9999998807907104
```

I understand that the value I provide is larger than allowed, but I do not understand why. I would expect any value within `[0,1]` to be allowed.

**Comment by FBruzzesi** [comment]
`Bernoulli` probs are checked to be in the range `[eps, 1-eps]`, where `eps = torch.finfo(torch.float32).eps`. 
Hence `Bernoulli([0.0])` and `Bernoulli([1.0])` will always fail to initialize. I have no idea if there is a particular reason behind such design.

Here is the [source code](https://github.com/jmschrei/pomegranate/blob/master/pomegranate/distributions/bernoulli.py#L60).

**Comment by jmschrei** [comment]
The reason for this is that there was a propagation of NaNs when handling probabilities of 0.0. For consistency, I made it within the range of eps and 1-eps. Hopefully, using 1-eps instead of 1 is sufficient for your applications.
