### ISSUE TITLE
HMM sampling does not work when end_state is None

### ISSUE THREAD

**Issue by balabanmetin** [jmschrei/pomegranate#1046]
It raises an error in the following line 

https://github.com/jmschrei/pomegranate/blob/d9d3748c6a7e433c4661231a9dcd2c9ef19071fc/pomegranate/hmm/dense_hmm.py#L254

when `self.ends` is `None`.

Once the line above is corrected, it raises another error in the following line because `edge_probs` have `self.n_distributions` elements when `self.ends` is `None`.
 
https://github.com/jmschrei/pomegranate/blob/d9d3748c6a7e433c4661231a9dcd2c9ef19071fc/pomegranate/hmm/dense_hmm.py#L265C1-L266C27

**Comment by marcel-goldschen-ohm** [comment]
Is anyone working on this? Being able to sample from an HMM seems pretty fundamental to me.

**Comment by jmschrei** [comment]
This should be fixed in v1.1.0. Let me know if you still encounter issues.
