### ISSUE TITLE
Anaconda repository outdated

### ISSUE THREAD

**Issue by cleitonmoya** [jmschrei/pomegranate#1047]
Pomegranate pakage in Anaconda repository is outdated (version 0.14.4). 
Would nice to have the option to install the last version (1.0.0) using conda.

**Comment by jmschrei** [comment]
I don't actually maintain the conda package and am not sure who put it there. Unfortunately, at this point I don't really have time to learn how to make the package conda-installable. Sorry for the inconvenience
