### ISSUE TITLE
I can't import GeneralMixtureModel from Pomegranate

### ISSUE THREAD

**Issue by Fdm8610** [jmschrei/pomegranate#1051]
from pomegranate import GeneralMixtureModel
​
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 from pomegranate import GeneralMixtureModel

ImportError: cannot import name 'GeneralMixtureModel' from 'pomegranate' (/Users/federico.d/opt/anaconda3/lib/python3.9/site-packages/pomegranate/__init__.py)

it looks like it tries all the time to import from __init__py

I don't know how to solve this

Thank you

**Comment by jmschrei** [comment]
pomegranate v1.0.0 introduced several breaking changing, including to the naming scheme. Please see the README for more details. You can install the older version using instructions there.
