### ISSUE TITLE
[BUG] Normal distribution with single dimension does not work

### ISSUE THREAD

**Issue by YuriOsokin** [jmschrei/pomegranate#1055]
**Describe the bug**
Single dimension normal distribution does not work in pomegranate 1.0.0.

**To Reproduce**

      NormalDistribution([1.], [1.])

raises the error

      RuntimeError: linalg.cholesky: The input tensor A must have at least 2 dimensions.

**Comment by christer-watson** [comment]
The following code works and probably does what you want:
`
distributions.Normal([1.],[[1.]])`

**Comment by jmschrei** [comment]
You can also try adding `covariance_type='diag'`. It should probably default to that if the means/covars are only 1D but it currently assumes a full covariance matrix.
