### ISSUE TITLE
[FEATURE] Viterbi for hidden Markov models has not yet been implemented

### ISSUE THREAD

**Issue by Koen1999** [jmschrei/pomegranate#1061]
As mentioned in the README since the v1 update (rewrite), the Viterbi algorithm for hidden Markov models has not yet been implemented. This issue is intended to keep track of the implementation progress / discussion.

**Comment by majgah** [comment]
Any idea when it will be completed?

**Comment by marcel-goldschen-ohm** [comment]
Also interested in this. Any updates?

**Comment by jmschrei** [comment]
This has been added to v1.1.0, which will be released shortly.
