### ISSUE TITLE
Unresolved reference in Pycharm

### ISSUE THREAD

**Issue by pipobingo** [jmschrei/pomegranate#1066]
I have installed the package Pomegranate on my project. I use Pycharm. I then import at the beginning of my file with the command :

import pomegranate, time, seaborn, numpy
from pomegranate import *
states = [MultivariateGaussianDistribution(means[i], numpy.eye(means.shape[1])) for i in range(transmat.shape[0])]
model = HiddenMarkovModel.from_matrix(transmat, states, start_probs, merge='None')

Unfortunatly, Pycharm does not recognise the references MultivariateGaussianDistribution and HiddenMarkovModel. It states : Unresolved reference 'HiddenMarkovModel'. I have reinstalled the package many times but that doesn't change anything.

Can someone help ?

**Comment by jmschrei** [comment]
`MultivariateGaussianDistribution` and `HiddenMarkovModel` are objects in pomegranate before the recent rewrite. Please see the README for reasoning. What you're looking for is `Normal` (https://github.com/jmschrei/pomegranate/blob/master/pomegranate/distributions/normal.py#L22) and either `SparseHMM` or `DenseHMM` (probably `DenseHMM`).

**Comment by pipobingo** [comment]
Thank you very much for your help. Things have sundenly become clearer.
