### ISSUE TITLE
Transition matrix

### ISSUE THREAD

**Issue by Koenig128** [jmschrei/pomegranate#1073]
Hi, 

I again have a question and would be very happy if you could help once again. 

1)
How can I access the transition matrix? I saw that `transmat_` does not exist as attribute of DenseHMM anymore... I checked the tutorial and examples but I did not find it.

Thank you very much for your help!

**Comment by jmschrei** [comment]
I'm not sure `transmat_` was ever an attribute of pomegranate HMMs. Try `edges`? https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm/dense_hmm.py#L104

**Comment by Koenig128** [comment]
Thank you very much!
