### ISSUE TITLE
[BUG]Speed issue

### ISSUE THREAD

**Issue by tanyasarkjain** [jmschrei/pomegranate#1075]
**Describe the bug**
A clear and concise description of what the bug is, including what you were expecting to happen and what actually happened. Please report the version of pomegranate that you are using and the operating system. Also, please make sure that you have upgraded to the latest version of pomegranate before submitting the bug report.

I am using the latest version of pomegranate. My code is taking an incredibly slow amount of time to run, all I am doing is creating an uninitialized hmm and fitting it to my data. The model is 2 states, and the emissions are multivariate (2 features), that take on a range of about 20 numbers each. Furthermore, when I print out the predictions I am only getting a state assignment of 1. I tried it on just 2 iterations and it took about 6 minutes. 

**To Reproduce**
Please provide a snippet of code that can reproduce this error. It is much easier for us to track down bugs and fix them if we have an example script that fails until we're successful.

import pomegranate
import seaborn; seaborn.set_style('whitegrid')
import torch
#https://pomegranate.readthedocs.io/en/latest/tutorials/B_Model_Tutorial_4_Hidden_Markov_Models.html#Initializing-Hidden-Markov-Models

print(pomegranate.__version__)

from pomegranate.hmm import DenseHMM

Here is a snippet of what mv_emissions looks like: [[[16, 11],
 [16, 12],
 [13, 12],
 [15, 12],
 [15, 9],
 [14, 6],
 [15, 3],
 [9, 6],]]
**Response time**
Although I will likely respond during weekdays if I am not on vacation, I am not likely to be able to merge PRs or write code until the weekend.

**Comment by tanyasarkjain** [comment]
This is my code:

`starts = [0.5, 0.5]
d = Categorical().fit(mv_emissions)

model = DenseHMM([d, d], starts = starts, max_iter=2, verbose=True)
model.fit(all_sequences
`
I realized I had an issue with my sequences. My sequences are all variable lengths (with d-dimensional observations). I am unable to fit because ' Parameter X must have 2 dims'. Does this fit method not work for sequences of variable lengths?

**Comment by jmschrei** [comment]
When you pass in `DenseHMM([d, d])` I'm pretty sure you're passing in the same object to each state and so both will always be identical. Try making two copies of the object?
