### ISSUE TITLE
[Suggestion] Better description of how to implement HMM's

### ISSUE THREAD

**Issue by kaare-mikkelsen** [jmschrei/pomegranate#1084]
Would it be possible to better explain how to implement HMM's using pomegranate? A common treatment of HMM's deals with transition probabilities and emission probability (see, e.g, Bishop: https://www.microsoft.com/en-us/research/uploads/prod/2006/01/Bishop-Pattern-Recognition-and-Machine-Learning-2006.pdf), not 'edges'. It's not readily apparent how to translate between the two pictures.

**Comment by jmschrei** [comment]
Howdy. When you have a dense transition matrix you can pass that in to `edges`. See the section "Dense and Sparse HMMs": https://github.com/jmschrei/pomegranate/blob/master/docs/tutorials/B_Model_Tutorial_4_Hidden_Markov_Models.ipynb

Is that not sufficient?
