### ISSUE TITLE
Dynamic bayesian network to be fitted with hybrid variables(consist of discrete and continuous variable)

### ISSUE THREAD

**Issue by yfpeng1234** [jmschrei/pomegranate#1101]
Hi, I hope to use a time series data to fit a dynamic bayesian network. But after looking up the docs, I didn't find dynamic bayesian network class.
I'm wondering is there any easy method to extent the bayesian network to dynamic bayesian network.
By the way, do pomegranate support structure and parameter learning of hybrid variables(consist of discrete and continuous variable)

**Comment by jmschrei** [comment]
Howdy

Currently, dynamic Bayesian networks are not supported and only categorical Bayesian networks are supported. Sorry for the inconvenience.

**Comment by yfpeng1234** [comment]
Thanks so much for your prompt reply, Jacob. pomegranate is already a powerful library. But if you know any other library that support continuous and discrete variables simultaneously in DBN, please share some of them. 
Best regards

**Comment by jmschrei** [comment]
Unfortunately, I don't. Please let me know if you find one, though!
