### ISSUE TITLE
structure learning for hybird DBN

### ISSUE THREAD

**Issue by yfpeng1234** [jmschrei/pomegranate#1103]
Dear Jacob,
I implemented the distributions I needed to construct my hybrid DBN. And next I hope to implement structure learning algorithm (possibly dmmhc). I noted that you have implemened structure learning algorithm for categorical BN. Do you think it's practical to build dmmhc algorithm for hybrid DBN structure learning based on pomegranate or could you give me some suggestions on it?
Best regards!

**Comment by jmschrei** [comment]
Unfortunately, my knowledge of DBNs and their structure learning algorithms has escaped me. I'm happy to help out, and to include your implementation in pomegranate if you get it all worked out, but I don't think I can offer much assistance.
