### ISSUE TITLE
Any planned support to draw / plot HMMs?

### ISSUE THREAD

**Issue by fountaindive** [jmschrei/pomegranate#1118]
Just curious if the newer versions of pomegranate will have a `model.plot()` method so that we can visualise hidden markov models. Thanks!

**Comment by jmschrei** [comment]
I wasn't planning on it. I haven't added it yet because I didn't want to have to add in plotting dependencies, and this process was made easier in the past because the HMM was in a networkx object, which already had most of the plotting built-in.

**Comment by fountaindive** [comment]
ah ok, thanks for replying!
