### ISSUE TITLE
AttributeError in HMM tutorial

### ISSUE THREAD

**Issue by gcmallya85** [jmschrei/pomegranate#112]
I was going through the [HMM tutorial](https://github.com/jmschrei/pomegranate/blob/master/tutorials/Tutorial_3_Hidden_Markov_Models.ipynb), and I encountered the following error in the third cell block i.e. at `hmm_predictions = hmm.predict( seq )`:

> 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-a76c4632755c> in <module>()
----> 1 hmm_predictions = hmm.predict(seq)
pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.predict (pomegranate\hmm.c:24491)()
pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.maximum_a_posteriori (pomegranate\hmm.c:24834)()
pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel._maximum_a_posteriori (pomegranate\hmm.c:24932)()
AttributeError: 'pomegranate.hmm.HiddenMarkovModel' object has no attribute '_posterior'

Any suggestions? Did not face any issues with Tutorial 1 and 2. Thanks in advance.

**Comment by jmschrei** [comment]
This is an error on my end. I will fix promptly.

**Comment by gcmallya85** [comment]
No rush! Thank you for the quick response.

**Comment by jmschrei** [comment]
This is actually a much deeper error than expected. The original bug was caused by me renaming _posterior to _predict_log_proba and not updating all calls. But there is a problem with GMMs handling discrete data which I'm working on as well. More unit tests coming to ensure this doesn't happen again!

**Comment by jmschrei** [comment]
Should be resolved now. Reopen if not.

**Comment by gcmallya85** [comment]
I am new to github and python, therefore naive. This is what I did, I executed the following command `pip install --upgrade pomegranate`. Upon successful upgrade, I executed the cell block from the HMM tutorial - but encountered the same error. I know I am doing something wrong, probably the way I am upgrading the module is incorrect. Kindly let me know when you get a chance, no rush at all.

**Comment by jmschrei** [comment]
I usually only upload bigger releases (or critical bugfixes) to PyPI. Youneed to clone the github repo and install from there to get the latest update. If you're on Ubuntu or Mac you can type:

```bash
git clone https://github.com/jmschrei/pomegranate
cd pomegranate
python setup.py install
```

If you're on windows, you can either download GitHub Desktop (or some other git for windows distribution) and follow similar steps. The important part is the `python setup.py install` command, which will install it to the proper place on your computer.
