### ISSUE TITLE
AttributeError: object has no attribute '_posterior'

### ISSUE THREAD

**Issue by fpdx** [jmschrei/pomegranate#113]
hi. With version 0.4.0. After baking my model, `model.predict(sequence,'viterbi')` works fine. Instead, both `model.predict(sequence, 'map')` and `model.maximum_a_posteriori(sequence)` give the following error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-144-3d244665da8d> in <module>()
----> 1 model.maximum_a_posteriori(sequence)

pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.maximum_a_posteriori (pomegranate/hmm.c:24834)()

pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel._maximum_a_posteriori (pomegranate/hmm.c:24932)()

AttributeError: 'pomegranate.hmm.HiddenMarkovModel' object has no attribute '_posterior'
```
Any idea?
(btw, great job)

**Comment by jmschrei** [comment]
Howdy. This issue was pointed out in #112 and has since been fixed. Please clone the latest version of the code and let me know if that fixes the issue!

**Comment by fpdx** [comment]
I see, sorry I missed #112. It works.
