### ISSUE TITLE
Yet Another Mac OS installing issue

### ISSUE THREAD

**Issue by Randyjp** [jmschrei/pomegranate#115]
This is more of a cry for help than a new bug because it seems like it should be around the ones of the issues #53 #43 #48 or #35.  But I still can't figure it out, this is the version of everything I'm using and the errors I'm getting. 

OS: Mac OS 10.11.14
Python 2.7.11 : Anaconda 4.0.0 (x86_64)
cython : 0.23.4
joblib: 0.9.4  
decorator:4.0.9 
numpy:1.10.4
networkx:1.11
gcc: 4.9.3

So after reading issue #43 I noticed that I couldn't rely on the gcc that comes with the mac so I did this export CC=/usr/local/Cellar/gcc/4.9.3/bin/gcc-4.9. Now I try ti install via pip or building it myself and I get the following errors:

`Randys-MacBook-Pro:pomegranate randyjp$ python setup.py install
missing cimport in module '.base': pomegranate/BayesianNetwork.pyx
missing cimport in module '.utils': pomegranate/BayesianNetwork.pyx
missing cimport in module '.distributions': pomegranate/BayesianNetwork.pyx
missing cimport in module '.base': pomegranate/FactorGraph.pyx
missing cimport in module '.distributions': pomegranate/FactorGraph.pyx
missing cimport in module '.utils': pomegranate/NaiveBayes.pyx
missing cimport in module '.distributions': pomegranate/NaiveBayes.pyx
missing cimport in module '.utils': pomegranate/base.pyx
missing cimport in module '.distributions': pomegranate/base.pyx
missing cimport in module 'distributions': pomegranate/base.pxd
missing cimport in module '.utils': pomegranate/distributions.pyx
missing cimport in module '.base': pomegranate/fsm.pyx
missing cimport in module '.distributions': pomegranate/gmm.pyx
missing cimport in module '.utils': pomegranate/gmm.pyx
missing cimport in module '.base': pomegranate/hmm.pyx
missing cimport in module '.distributions': pomegranate/hmm.pyx
missing cimport in module '.utils': pomegranate/hmm.pyx
//anaconda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running build_ext
running install_lib
creating //anaconda/lib/python2.7/site-packages/pomegranate
copying build/lib.macosx-10.5-x86_64-2.7/pomegranate/__init__.py -> //anaconda/lib/python2.7/site-packages/pomegranate
creating //anaconda/lib/python2.7/site-packages/pomegranate/pomegranate
copying build/lib.macosx-10.5-x86_64-2.7/pomegranate/pomegranate/base.so -> //anaconda/lib/python2.7/site-packages/pomegranate/pomegranate
copying build/lib.macosx-10.5-x86_64-2.7/pomegranate/pomegranate/BayesianNetwork.so -> //anaconda/lib/python2.7/site-packages/pomegranate/pomegranate
copying build/lib.macosx-10.5-x86_64-2.7/pomegranate/pomegranate/distributions.so -> //anaconda/lib/python2.7/site-packages/pomegranate/pomegranate
copying build/lib.macosx-10.5-x86_64-2.7/pomegranate/pomegranate/FactorGraph.so -> //anaconda/lib/python2.7/site-packages/pomegranate/pomegranate
copying build/lib.macosx-10.5-x86_64-2.7/pomegranate/pomegranate/fsm.so -> //anaconda/lib/python2.7/site-packages/pomegranate/pomegranate
copying build/lib.macosx-10.5-x86_64-2.7/pomegranate/pomegranate/gmm.so -> //anaconda/lib/python2.7/site-packages/pomegranate/pomegranate
copying build/lib.macosx-10.5-x86_64-2.7/pomegranate/pomegranate/hmm.so -> //anaconda/lib/python2.7/site-packages/pomegranate/pomegranate
copying build/lib.macosx-10.5-x86_64-2.7/pomegranate/pomegranate/MarkovChain.so -> //anaconda/lib/python2.7/site-packages/pomegranate/pomegranate
copying build/lib.macosx-10.5-x86_64-2.7/pomegranate/pomegranate/NaiveBayes.so -> //anaconda/lib/python2.7/site-packages/pomegranate/pomegranate
copying build/lib.macosx-10.5-x86_64-2.7/pomegranate/pomegranate/utils.so -> //anaconda/lib/python2.7/site-packages/pomegranate/pomegranate
byte-compiling //anaconda/lib/python2.7/site-packages/pomegranate/__init__.py to __init__.pyc
running install_egg_info
Writing //anaconda/lib/python2.7/site-packages/pomegranate-0.4.0-py2.7.egg-info
`

**Now when I try to import it, I get this:**

`In[2]: from pomegranate import *
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-f670013b5ac0>", line 1, in <module>
    from pomegranate import *
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/pomegranate/__init__.py", line 38, in <module>`

**Any ideas? Suggestions? I would really appreciate a hand here as I need this package for my capstone project. **

**Comment by jmschrei** [comment]
I have been able to `pip install pomegranate` on unmodified Macs before with clang. Try removing all cached files and trying again?

**Comment by Randyjp** [comment]
You are right, I was able to do it with clang and pip. The problem was me, I left the pomegranate directory in my project so the import statement was trying to pull from there instead of the installed package. Thanks

**Comment by jmschrei** [comment]
Coolios. Good luck on your capstone project.
