### ISSUE TITLE
Mild Pandas Support for ConditionalProbabilityTables

### ISSUE THREAD

**Issue by koaning** [jmschrei/pomegranate#116]
I'll gladly have an attempt at implementing this is you agree with its utility. 

Suppose that I want to do some graphical modelling and that my original data in pandas. In this example I'm analysing the effect of diet and time on the weight of chickens. 
#### Generating the data in Pandas

```
import pomegranate as pg
import pandas as pd

df = pd.read_csv('http://koaning.github.io/data/pydata/chickweight.csv')
df['weight_bucket'] = (df['weight'] / 20).apply(int)
df.weight_bucket.unique()

def to_prob(df):
    s = df.count()['weight']
    return df.groupby('weight_bucket')['weight'].count() / s
prob_table = df.groupby(['Diet', 'Time']).apply(to_prob).reset_index()
```
#### Converting to list of lists for pg

Pomegranate needs to have a lists of lists, which we can get from pandas. 

```
prob_list = prob_table.values.tolist()
```

The edge-case seems that we expect the user to understand that the ordering matters and that the user should deal with missing values. It seems like we could easily do a check for this and convert when the object for the probability table is created. 
#### From here back to normal use

Once we have this, it's back to normal use. 

```
diet = DiscreteDistribution( { 1 : 0.25, 2 : 0.25, 3 : 0.25, 4 : 0.25 } )
time = DiscreteDistribution( {0: 1./12 , 2: 1./12 , 4: 1./12, 6: 1./12, 
                              8: 1./12, 10: 1./12, 12: 1./12, 14: 1./12, 
                              16: 1./12, 18: 1./12, 20: 1./12, 21: 1./12} )

weight = ConditionalProbabilityTable(prob_list, [diet, time])

s0 = State(diet, name="diet" )
s1 = State(time, name="time" )
s2 = State(weight, name="weight" )
network = BayesianNetwork( "chickweight" )
network.add_nodes([s0, s1, s2])
network.add_edge(s0, s2)
network.add_edge(s1, s2)
network.bake() 
network.predict_proba({'diet' : 2})
```

Such an interaction with pandas might be a nice gateway to this library for new users as pandas is a standard of PyData. Potentially the network can also ingest a pandas dataframe for prediction instead of learning as well .

**Comment by jmschrei** [comment]
I'm all for supporting Pandas, as it is an extremely valuable tool. What do you see as the new format for initializing and using models with pandas dataframes?

pomegranate doesn't need a list of lists for the conditional probability table. If you give it a numpy array of entirely numerical values it should handle it properly. The issue is that many people want to use strings as the emissions, and you can't have strings for some elements in the array and numerics for others, which is why list of lists seemed more intuitive.

**Comment by koaning** [comment]
For discrete models like we have support for now I guess initially I would argue that instead of doing this (from the above example); 

```
weight = ConditionalProbabilityTable(prob_list, [diet, time])
```

... you could also do this; 

```
weight = ConditionalProbabilityTable(prob_table, [diet, time])
```

The idea being that the `ConditionalProbabilityTable` internally does a check to see if it is a pandas table and if the input is allowed. You could even go as far as allowing this for `DiscreteDistribution` as long as the pandas DataFrame does not have more than 1 row.

**Comment by jmschrei** [comment]
I support adding pandas functionality for CPT, JPT, and DiscreteDistribution. Do you think this is something which you could add? I'd love to see a PR about this.

**Comment by jeev20** [comment]
@koaning you mentioned 

> "The edge-case seems that we expect the user to understand that the ordering matters and that the user should deal with missing values. It seems like we could easily do a check for this and convert when the object for the probability table is created." 

Could you elaborate how this can be achieved? I followed the code snippet you included above, but an "key error (1, 0, 3.0)" pops up when network.bake() is run. I am suspecting this is the edge-case you mean (all combinations need to be included). I am just wondering how to achieve it, tried googling a lot on this, no luck. Could you guide us on this?

**Comment by koaning** [comment]
I'm surprised the code even runs, the URL is stale. This is the correct one;

```
http://koaning.io/old/theme/data/chickweight.csv
```

As far as that message goes, that was years ago and I can't recall the details. Also; I sort of started playing with my own library that deals with the use-case I was thinking about; https://github.com/koaning/brent.

**Comment by jeev20** [comment]
Thank you for replying. I had browsed through and got the right link from your repo to try the code. I know both you and @jmschrei  are busy, but would really appreciate help on this. As of now this is the code 
`df = pd.read_csv ("http://koaning.io/old/theme/data/chickweight.csv")

df['weight_bucket'] = (df['weight'] / 20).apply(int)
df.weight_bucket.unique()

def to_prob(df):
    s = df.count()['weight']
    return df.groupby('weight_bucket')['weight'].count() / s
prob_table = df.groupby(['Diet', 'Time']).apply(to_prob).reset_index()

prob_list = prob_table.values.tolist()


diet = DiscreteDistribution( { 1 : 0.25, 2 : 0.25, 3 : 0.25, 4 : 0.25 } )
time = DiscreteDistribution( {0: 1./12 , 2: 1./12 , 4: 1./12, 6: 1./12, 
                              8: 1./12, 10: 1./12, 12: 1./12, 14: 1./12, 
                              16: 1./12, 18: 1./12, 20: 1./12, 21: 1./12} )
print (prob_list)
weight = ConditionalProbabilityTable(prob_list, [diet, time])

s0 = State(diet, name="diet" )
s1 = State(time, name="time" )
s2 = State(weight, name="weight" )
network = BayesianNetwork( "chickweight" )
network.add_nodes(s0, s2)
network.add_edge(s0, s2)
network.add_edge(s1, s2)
network.bake() 
print (network.predict_proba({'diet' : 4}))`

The error I get 
![error](https://user-images.githubusercontent.com/19647823/56474086-1b17b300-6475-11e9-9420-7a07affdf1f6.JPG)

I know this is related to the missing combinations the variables, but cannot find a way to code this and make it work.

**Comment by koaning** [comment]
could you turn the snippet into something i can copy and paste? ill have a quick look, but it helps if you can turn the code into markdown and that you include the imports to make the error reproducible.

**Comment by jeev20** [comment]
> could you turn the snippet into something i can copy and paste? ill have a quick look, but it helps if you can turn the code into markdown and that you include the imports to make the error reproducible.

I have updated the code in the above comment. Should run with the two dependencies (pandas and pomegranate). Cheers.

**Comment by koaning** [comment]
I see some parts in your code that are **different** than mine. 

```
network = BayesianNetwork( "chickweight" )
network.add_nodes(s0, s1, s2)
network.add_edge(s0, s2)
network.add_edge(s1, s2)
network.bake() 
```

Notice the `network.add_nodes` part.

**Comment by koaning** [comment]
mhm. bad news. 

```
[1]    59802 segmentation fault  ipython
```

Something is up with the most recent version of pomegrenate. But I do have a hint. The errors are probably due to the "keys" of the distribution. If you pay attention you might notice that they might be "floats","int" or "float" depending on what object (dataframe/distribution) they are. Enforcing this is probably the way forward.

**Comment by jeev20** [comment]
That's true. Now the nodes in pomegranate allow direct input of nodes to network.add_nodes. 

What I understand from your earlier comments is that, although the data covers some combinations, other combinations are omitted while calculating prob_table. 
For example if one event has a probability = 1, all other conditioned events also need to be included with probablility =0. I don't understand how to get such a dataframe or a table. If I understand how to do it in your example data, I hope to port it to my weather data samples.
