### ISSUE TITLE
serialization with to_json and from_json

### ISSUE THREAD

**Issue by shpigi** [jmschrei/pomegranate#12]
(sorry for the long post...)

In the current system, the` to_json` methods cause the stringification of the inner-most objects (the distributions) with `json.dumps`  and these strings are put in dictionaries by their parents (their containing classes) which in turn are stringified by calls to `json.dumps` and used by _their_ parents (e.g. for distributions within states within models) . The resulting json has strings within strings so that `json.loads(model.to_json())` returns something ugly (i.e. a dictionary where the inner objects are all strings). 
I made some code changes so that when the parent object performs `to_json`, it embeds serialized inner objects with `json.loads` so there are no more strings within strings.

e.g. the State.to_json() becomes:
<pre>
def to_json( self ):
	"""
	Convert this state to JSON format.
	"""

	return json.dumps( { 	'class' : 'State',
				'distribution' : None if self.is_silent() else <b>json.loads(self.distribution.to_json()),</b>
				#'distribution' : None if self.is_silent() else str( self.distribution ),
				'name' : self.name,
				'weight' : self.weight
				})
</pre>

Where similar appropriate changes are done to the `from_json` code. 
For example, the State.from_json code is:
<pre>
	def from_json( cls, s ):
		"""
		Read a State from a given string formatted in JSON.
		"""
		
		# Load a dictionary from a JSON formatted string
		d = json.loads( s )

		# If we're not decoding a state, we're decoding the wrong thing
		if d['class'] != 'State':
			raise IOError( "State object attempting to decode {} object".format( d['class'] ) )

		# If this is a silent state, don't decode the distribution
		if d['distribution'] is None:
			return cls( None, str(d['name']), d['weight'] )

		# Otherwise it has a distribution, so decode that
		return cls( Distribution.from_json( <b>json.dumps(d['distribution'])</b> ),
					name=str(d['name']), weight=d['weight'] )
</pre>

The result is that now models can be read into simple python structures 

For example:
```
from pomegranate import *
import json
model = HiddenMarkovModel(name="ExampleModel")
distribution = UniformDistribution(0.0, 1.0)
state = State(distribution, name="uniform")
state2 = State(NormalDistribution(0, 2), name="normal")
silent = State(None, name="silent")
model.add_state(state)
model.add_state(state2)

model.add_transition(state, state, 0.4)
model.add_transition(state, state2, 0.4)
model.add_transition(state2, state2, 0.4)
model.add_transition(state2, state, 0.4)

model.add_transition(model.start, state, 0.5)
model.add_transition(model.start, state2, 0.5)
model.add_transition(state, model.end, 0.2)
model.add_transition(state2, model.end, 0.2)

model.bake()
json.loads(model.to_json())
```

results in:

```
{u'class': u'HiddenMarkovModel',
 u'distribution ties': [],
 u'edges': [[3, 0, 0.5, 0.5, None],
  [3, 1, 0.5, 0.5, None],
  [0, 0, 0.4, 0.4, None],
  [0, 2, 0.20000000000000004, 0.2, None],
  [0, 1, 0.4, 0.4, None],
  [1, 0, 0.4, 0.4, None],
  [1, 2, 0.20000000000000004, 0.2, None],
  [1, 1, 0.4, 0.4, None]],
 u'end': {u'class': u'State',
  u'distribution': None,
  u'name': u'ExampleModel-end',
  u'weight': 1.0},
 u'end_index': 2,
 u'name': u'ExampleModel',
 u'silent_index': 2,
 u'start': {u'class': u'State',
  u'distribution': None,
  u'name': u'ExampleModel-start',
  u'weight': 1.0},
 u'start_index': 3,
 u'states': [{u'class': u'State',
   u'distribution': {u'class': u'Distribution',
    u'frozen': False,
    u'name': u'NormalDistribution',
    u'parameters': [0, 2]},
   u'name': u'normal',
   u'weight': 1.0},
  {u'class': u'State',
   u'distribution': {u'class': u'Distribution',
    u'frozen': False,
    u'name': u'UniformDistribution',
    u'parameters': [0.0, 1.0]},
   u'name': u'uniform',
   u'weight': 1.0},
  {u'class': u'State',
   u'distribution': None,
   u'name': u'ExampleModel-end',
   u'weight': 1.0},
  {u'class': u'State',
   u'distribution': None,
   u'name': u'ExampleModel-start',
   u'weight': 1.0}]}
```
So far I modified hmm.pyx, base.pyx and  distributions.pyx but I can adapt gmm.pyx and fsm.pyx if you are interested (I haven't used them so far in my own code). Note that nosetests runs smoothly (so I guess it doesn't check serialization)

Let me know if you'd like to make these changes to your package and we can figure out how to do it (a pull request?)

**Comment by jmschrei** [comment]
I'm unsure what the change is here. Can you post a small HMM's JSON with both versions?

**Comment by shpigi** [comment]
ok,
Running this code:
```
from pomegranate import *
import json
model = HiddenMarkovModel(name="ExampleModel")
distribution = UniformDistribution(0.0, 1.0)
state0 = State(distribution, name="uniform")
model.add_state(state0)
model.add_transition(model.start, state0, 0.5)
model.add_transition(state0, model.end, 0.5)
model.bake()
json.loads(model.to_json())
```
the current  version returns
```
{u'class': u'HiddenMarkovModel',
 u'distribution ties': [],
 u'edges': [[0, 2, 1.0, 0.5, None], [1, 0, 1.0, 0.5, None]],
 u'end': u'{\n    "distribution" : null,\n    "class" : "State",\n    "weight" : 1.0,\n    "name" : "ExampleModel-end"\n}',
 u'end_index': 2,
 u'name': u'ExampleModel',
 u'silent_index': 1,
 u'start': u'{\n    "distribution" : null,\n    "class" : "State",\n    "weight" : 1.0,\n    "name" : "ExampleModel-start"\n}',
 u'start_index': 1,
 u'states': [u'{\n    "distribution" : "{\\n    \\"frozen\\" : false,\\n    \\"class\\" : \\"Distribution\\",\\n    \\"parameters\\" : [\\n        0.0,\\n        1.0\\n    ],\\n    \\"name\\" : \\"UniformDistribution\\"\\n}",\n    "class" : "State",\n    "weight" : 1.0,\n    "name" : "uniform"\n}',
  u'{\n    "distribution" : null,\n    "class" : "State",\n    "weight" : 1.0,\n    "name" : "ExampleModel-start"\n}',
  u'{\n    "distribution" : null,\n    "class" : "State",\n    "weight" : 1.0,\n    "name" : "ExampleModel-end"\n}']}
```
See how the values of states  are strings. in fact 
`json.loads(state0.to_json())['distribution']` 
is also a string
```
Out[4]: u'{\n    "frozen" : false,\n    "class" : "Distribution",\n    "parameters" : [\n        0.0,\n        1.0\n    ],\n    "name" : "UniformDistribution"\n}'
```
to unpack distribution as a python dictionary starting from state you'd have to do
`json.loads(json.loads(state.to_json())['distribution'] )`


In my modified version,  `json.loads(model.to_json())` returnes a fully unpacked structure:
```
{u'class': u'HiddenMarkovModel',
 u'distribution ties': [],
 u'edges': [[0, 2, 1.0, 0.5, None], [1, 0, 1.0, 0.5, None]],
 u'end': {u'class': u'State',
  u'distribution': None,
  u'name': u'ExampleModel-end',
  u'weight': 1.0},
 u'end_index': 2,
 u'name': u'ExampleModel',
 u'silent_index': 1,
 u'start': {u'class': u'State',
  u'distribution': None,
  u'name': u'ExampleModel-start',
  u'weight': 1.0},
 u'start_index': 1,
 u'states': [{u'class': u'State',
   u'distribution': {u'class': u'Distribution',
    u'frozen': False,
    u'name': u'UniformDistribution',
    u'parameters': [0.0, 1.0]},
   u'name': u'uniform',
   u'weight': 1.0},
  {u'class': u'State',
   u'distribution': None,
   u'name': u'ExampleModel-start',
   u'weight': 1.0},
  {u'class': u'State',
   u'distribution': None,
   u'name': u'ExampleModel-end',
   u'weight': 1.0}]}
```

I find this to be a friendlier interface for someone wanting to do something with the model outside the package.
