### ISSUE TITLE
NaN in Baum Welch training

### ISSUE THREAD

**Issue by narendramukherjee** [jmschrei/pomegranate#120]
I'm trying to fit a HMM with Poisson emissions to neuronal activity count data, here's some data and code that reproduces the issue I am facing:
[pomegranate_feedforward.zip](https://github.com/jmschrei/pomegranate/files/226865/pomegranate_feedforward.zip)

The data has 10 sequences - each sequence is 250 time points long and has 27 neurons. So basically, at each time point, there's a 27 dimensional emission vector of count data - and each dimension is being modelled as an independent Poisson distribution. I am trying to fit a reduced, feed-forward HMM to the data - basically, we go from model.start to state 0 with probability 1, transitions from a state back to itself have a high probability (something like 0.95-0.99) and transitions from a state to lower states (like from state 1 to 0, from state 2 to 1 or 0) have probability 0. So the model can only go from model.start to state 0 to state 1 to state 2 and so on..

After a few iterations of Baum-Welch training (I fixed it at 10 in the sample code), the training improvement becomes a NaN. This happens almost always (with any initial combination of transition probabilities) if the number of states is higher (4 or 5) and only sometimes if the number of states is 2 or 3. I am not sure if this is something that is normal and because of the kind/size of data I am trying to fit? I might be naively missing something here, so thought of asking..

Thanks so much for the help as always!

**Comment by jmschrei** [comment]
someone else has reported an issue with independentcomponentdistribution giving NaN values.. I'll look into it asap.

**Comment by narendramukherjee** [comment]
Thanks so much Jacob, let me know when you've looked into it..

**Comment by jmschrei** [comment]
I've been able to reproduce the error on a single state HMM. It's a bit more elusive than I expected. I'll track it down soon though!

**Comment by narendramukherjee** [comment]
Thanks for the update Jacob - just to point out, the error does come up on multi-state HMMs too, but not always. It seems to depend upon the initial conditions being used (like in the example code I posted) - so on running several initializations/seeds, you see it cropping up sometimes. 
Thanks for your help as always, I'll wait for your updates..

**Comment by jmschrei** [comment]
The problem is with IndependentComponentsDistribution, not with HMMs or the individual distributions. Right before convergence it will kinda die and return a log prob of -inf, so a single state HMM gets to that faster. It should all be a single underlying bug.

**Comment by narendramukherjee** [comment]
Ah, that makes sense! Let me know when you find out more..

**Comment by jmschrei** [comment]
I can't reproduce this error anymore so I'm going to assume it's fixed, but I'm not sure what in particular fixed it. Try getting the latest code.

**Comment by narendramukherjee** [comment]
I just pulled the latest code, but I can still reproduce the error on the example I posted earlier. Here's the data and code again:
[pomegranate_feedforward.zip](https://github.com/jmschrei/pomegranate/files/235805/pomegranate_feedforward.zip)
As previously, the error comes up sometimes if n_states = 3 in pomegranate_feedforward.py. If you set n_states = 5, it will come up almost always - just rerun the code a couple times in case the error doesn't come up on the first attempt. Let me know what you think!

**Comment by jmschrei** [comment]
I've been able to reproduce the error and have been working a bit on it, but this week has been very busy and I haven't had any time to look into it. Sorry!

**Comment by narendramukherjee** [comment]
No issues Jacob, thanks for looking into it. I will wait for your updates once you have looked into the issue!

**Comment by jmschrei** [comment]
Alright so this should be resolved now. The issue boiled down to some poisson distributions were getting means of 0 because they were exposed to entirely 0's in the training step. This causes all log probabilities to be undefined, and then in the next step there would be numerical errors with trying to update with poorly defined weights.

So I went ahead and added more error handling to make sure this doesn't work, I ran your script 100 times and it hasn't errored on any of them. However--this makes me think the Poisson distribution may not be the correct distribution for you, if you're dealing with values of 0 or 1 entirely. Does your data ever go above 1? If not, you may want to use a bernoulli distribution, which emits a 1 with probability p, and a 0 with probability 1-p, and learns this parameter p from the data. I don't have bernoulli distributions explicitly implemented, but you could use the DiscreteDistribution with just those emissions until I explicitly add it.

**Comment by Randyjp** [comment]
Hi Jacob,

I want to try it the fix with my script, should I clone the repo or can I get it through pip?

**Comment by jmschrei** [comment]
Most changes need to be gotten through cloning the repo. I don't want there to be version bloat, as I need to upload a new version to pip each time. Let me know if it's not working for you now

**Comment by narendramukherjee** [comment]
Thanks so much for that Jacob, and sorry for the late reply. It seems to work great now!

You are right in that sometimes my data doesn't go above 1, but that's not always the case. It usually ranges from 0-5 or so - it does go over 1, but at times, there might be components that don't exceed 1. I could, however, model the components that do not exceed 1 as a Bernoulli (or DiscreteDistribution as you pointed out) and let the rest be Poisson. If I run into this problem again, I will try that fix, thanks for the suggestion :)

**Comment by jmschrei** [comment]
Has this been resolved?

**Comment by jmschrei** [comment]
Re-open if not resolved.
