### ISSUE TITLE
Fit with labelled data

### ISSUE THREAD

**Issue by jmgo** [jmschrei/pomegranate#121]
Hi!

What I want to know is not much of an issue, but it go me a bit confused.

In the documentation of pomegranate, in the HMM section the API on the 'fit' method refers that 3 algorithms are available: 'viterbi', 'bauch-welch' and 'labelled'. However, when I looked at the code here in github I only found the first 2. Is the 'labelled' algorithm working?

I would like to perform supervised training, so that algorithm would be useful to me.

Regards,
jmgo

**Comment by jmschrei** [comment]
Howdy

I had removed it recently because it didn't jive well with the rest of the fitting procedures. I intend to add it back in soon, but have been very busy these last few weeks.

**Comment by jmgo** [comment]
Hi, 

Thanks for the quick answer. I'll be looking forward to that addition. 

Regards,
jmgo

**Comment by gustavofuhr** [comment]
Hello @jmschrei, can you indicate the commit in which you removed, so we can use it this version?

**Comment by jmschrei** [comment]
Looks like it was this commit: https://github.com/jmschrei/pomegranate/commit/5b61faddc19815964ac35f29701ab1c6ec1155ad

It was removed because I was simplifying the internals for EM, which led to a pretty significant HMM speed gain. I have not had the opportunity to reimplement the labelled training due to taking my qualifying exam this quarter, but this is still on my radar.

**Comment by lxkain** [comment]
I would be interested in using an HMM with supervised training as well!

**Comment by jmschrei** [comment]
Hi. Labeled training should be implemented now. Try passing into a corresponding list of lists of labels. I'll admit I haven't documented it as well as I should have.

**Comment by lxkain** [comment]
Great, I see that the master branch contains this, but the latest pip-install does not, so I'll build from the repo directly to try this.

```
def fit( self, sequences, weights=None, labels=None, stop_threshold=1E-9, min_iterations=0,
        max_iterations=1e8, algorithm='baum-welch', verbose=True,
        transition_pseudocount=0, use_pseudocount=False, inertia=None, edge_inertia=0.0,
        distribution_inertia=0.0, n_jobs=1  ):
```
