### ISSUE TITLE
HMM Memory leak

### ISSUE THREAD

**Issue by fcaldas** [jmschrei/pomegranate#126]
Hi,

  I'm using a simple HMM model to calculate the probability of a chain being generated by the model  using the Viterbi algorithm, my problem is that when called multiple times, the method consumes an enormous amount of RAM (16GB) and therefore my script is killed. 
  Looking at the code in the file ```HMM.pyx``` the method ```_viterbi()``` allocates a few variables like ```tracebackx, tracebacky, ...``` but never explicitly releases them, since I have no real experience with Cython could someone please take a look into that?

Best regards

**Comment by jmschrei** [comment]
Hi @fcaldas. You're absolutely right about those matrices not being freed. Sorry for not responding sooner, I saw this in a rush and marked it as read. I'll fix this tomorrow morning.

**Comment by jmschrei** [comment]
Should be fixed. Reopen if not.
