### ISSUE TITLE
change HMM state parameters after bake?

### ISSUE THREAD

**Issue by kern-lab** [jmschrei/pomegranate#128]
hi there-- what is the correct way to change the emission parameters of a hidden state for an HMM once the model has been "baked?" 

I'm trying to manually change the parameters of a discrete distribution but it doesn't seem to be working properly.

thanks!

**Comment by jmschrei** [comment]
It seems to be working for me.

```Python
>>> from pomegranate import *
>>> a = DiscreteDistribution({'A': 0.5, 'B': 0.5})
>>> b = State(a, name="a")
>>> 
>>> model = HiddenMarkovModel()
>>> model.add_state(b)
>>> model.add_transition( model.start, b, 0.5 )
>>> model.add_transition( model.start, model.end, 0.5 )
>>> model.add_transition( b, b, 0.9 )
>>> model.add_transition( b, model.end, 0.1 )
>>> model.bake()
>>> 
>>> model.states
[{
    "distribution" : {
        "frozen" : false,
        "class" : "Distribution",
        "parameters" : [
            {
                "A" : 0.5,
                "B" : 0.5
            }
        ],
        "name" : "DiscreteDistribution"
    },
    "class" : "State",
    "weight" : 1.0,
    "name" : "a"
}, {
    "distribution" : null,
    "class" : "State",
    "weight" : 1.0,
    "name" : "None-start"
}, {
    "distribution" : null,
    "class" : "State",
    "weight" : 1.0,
    "name" : "None-end"
}]
>>> a
{
    "frozen" :false,
    "class" :"Distribution",
    "parameters" :[
        {
            "A" :0.5,
            "B" :0.5
        }
    ],
    "name" :"DiscreteDistribution"
}
>>> a.parameters
[{'A': 0.5, 'B': 0.5}]
>>> a.parameters['A'] = 0.9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: list indices must be integers, not str
>>> a.parameters[0]['A'] = 0.9
>>> a.parameters[0]['B'] = 0.1
>>> model.states
[{
    "distribution" : {
        "frozen" : false,
        "class" : "Distribution",
        "parameters" : [
            {
                "A" : 0.9,
                "B" : 0.1
            }
        ],
        "name" : "DiscreteDistribution"
    },
    "class" : "State",
    "weight" : 1.0,
    "name" : "a"
}, {
    "distribution" : null,
    "class" : "State",
    "weight" : 1.0,
    "name" : "None-start"
}, {
    "distribution" : null,
    "class" : "State",
    "weight" : 1.0,
    "name" : "None-end"
}]
```

**Comment by kern-lab** [comment]
Thanks for the quick response. I should have been more clear. I can change the parameters of my discrete distrb, but there is was effect on HMM calculations. Perhaps it was due to the sequence I was feeding it-- I'll try again later today. 

One more question-- do I need to call bake() again once the model parameters have changed?

**Comment by jmschrei** [comment]
This is a mistake on my part. Discrete distributions have two levels; the python level which is a dictionary, and the cython level which stores probabilities as a vector for faster comptuation. Updating the dictionary doesn't update the cython level, and so all cython calculations remain the same. I'd recommend just creating two models for now.

**Comment by kern-lab** [comment]
ok. so how would you recommend I train a model in a case where I will be writing my own EM alg that will depend on numerical maximization rather than vanilla Baum-Welch? Each step in the EM I will be estimating new emission parameters, is there a better way using your library to deal with this or should I just brute force this an each iteration create a new model? 

Also maybe I could contribute to your project and help this out-- where in the code are you setting the emission probs?

**Comment by jmschrei** [comment]
I would follow the same format I use to run EM. I'm going to assume that basically you're calculating the responsibility matrix in a novel way, but using a normal maximization step (weighted MLE based on this responsibility matrix.)

In that case I would do something like the following:

```Python
def expectation( model, sequence ):
    """Your novel method for expectation calculation goes here."""

    r = <some len_sequence, n_states matrix of normalized probabilities>
    for i in range( model.silent_start ):
        model.states[i].distribution.summarize( sequence, weights=r[:,i]

def EM( model, sequences ):
    while not converged:
        for sequence in sequences:
            expectation( model, sequence )
        model.from_summaries()
    
    return model
```

Does that seem like it would work? Summarize for a distribution based stores the sufficient statistics for a weighted MLE, and from_summaries will update all the states from these sufficient statistics. 

What do you mean setting the emission probs?

**Comment by jmschrei** [comment]
Was this able to work for you?

**Comment by jmschrei** [comment]
Re-open if you want to talk further!
