### ISSUE TITLE
initialization of HMM multivariateGaussionDistribution

### ISSUE THREAD

**Issue by huiyuHarvey** [jmschrei/pomegranate#129]
Hi, could someone help with my problem? 
```
start = np.array([1.0, 0.0, 0.0])
end = np.array([[0.0, 0.0, 1.0]])
transmat = np.array([[0.5, 0.5, 0.0],
                     [0.0, 0.6, 0.4],
                     [0.0, 0.0, 1.0]])
dist1 = MultivariateGaussianDistribution([5,4,0,0,0,0,0,0,0,0,0,0], np.eye(12))
dists = [dist1, dist1, dist1]
h = model.from_matrix(transmat, dists, start, end)
```
I got the following error message when trying to initialize HMM from matrix. 
```
h = model.from_matrix(transmat, dists, start, end)

File "pomegranate/hmm.pyx", line 3095, in pomegranate.hmm.HiddenMarkovModel.from_matrix (pomegranate\hmm.c:36672)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
when using the other way to initialize, still couldn't get pomegranate work.
```
s1 = State(Distribution(dist1))
s2 = State(Distribution(dist1))
s3 = State(Distribution(dist1))
        
h = HiddenMarkovModel()
h.add_states(s1, s2, s3)
```
```
h.add_states(s1, s2, s3)

File "pomegranate/hmm.pyx", line 270, in pomegranate.hmm.HiddenMarkovModel.add_states (pomegranate\hmm.c:5578)

File "pomegranate/hmm.pyx", line 246, in pomegranate.hmm.HiddenMarkovModel.add_state (pomegranate\hmm.c:5263)

ValueError: A state with name '506050344' already exists
```
Since I'm new to Cpython, could someone teach me how to view the source code cz the files in `Lib\site-packages\pomegranate` are pyd files, full of numbers.

**Comment by jmschrei** [comment]
Howdy

Sorry you're having problems with pomegranate. I think the first way is incorrect because ends should be a vector, not a (n,1) dimensional matrix. The second was is being initialized incorrect, you shouldn't wrap a distribution in the Distribution object, that's the base class all other distributions inherit from. You should do something like the following:

```Python
from pomegranate import *

dist1 = MultivariateGaussianDistribution([5,4,0,0,0,0,0,0,0,0,0,0], np.eye(12))

s1 = State(dist1, name="s1")
s2 = State(dist1, name="s2")
s3 = State(dist1, name="s3")

model = HiddenMarkovModel()
model.add_states(s1, s2, s3)

#add appropriate transitions...
model.add_transition( model.start, ...., ... )
...
model.add_transition( ...,, model.end, ... )

model.bake()
```

However, you should be aware that passing the same distribution object into multiple states means that you are tying those emissions together, which is useful, but possibly not what you want. If you want to start from the same point, but not tie the emisisons together, you should write the following:

```Python
s1 = State(dist1.copy(), name="s1")
s2 = State(dist1.copy(), name="s2")
s3 = State(dist1.copy(), name="s3")
```

Also, if you initialize all your states to the same parameters, you're unlikely to get what you want when you train the model, since the EM algorithm is unsupervised.

**Comment by jmschrei** [comment]
As for viewing Cython files, .pyd and .so files are binary, so you can't read those. The cython files are .pyx, and you can view them on github. pip installing doesn't give you the cython files, just the binaries.

**Comment by huiyuHarvey** [comment]
Thanks so much Jacob!
and what kind of problem would lead to a `nan` result after `model.fit()`?
In my case, my input data is 2d numpy array. (length=43 * n_features=12)

**Comment by jmschrei** [comment]
Apologies for the late response, I saw this in a rush when you first posted it and so wiped it off my 'unread' messages.

Basically nan should never occur, and is always a problem on our side for not raising an error. I'd have to look more at your code, but we didn't handle something correctly, I would assume. You should feed your data in as a list of 2d arrays, where each sequence you see is an element in that list. It sounds like you're doing that correctly though. Can you show me specifically some inputs/outputs?

**Comment by huiyuHarvey** [comment]
You already help me a lot. Thx, man!!
The Nan problem is due to the wrong input format. I didn't put my ndarray into a list.
It works now. But I suggest to check the input data format in your code.

**Comment by huiyuHarvey** [comment]
Sorry to bother you again.
In your doc, it is not very clear about how to freeze some of the transitions. for example,  I need to train a left-right hmm model, some of transitions must stay 0 or any other certain possibility.

and could you give an example on how to check the transition matrix after fitting?(using method `dense_transition_matrix()` ?)

**Comment by jmschrei** [comment]
Since the HMM is defined in a sparse manner, 0 probability edges simply aren't included in the model, and aren't updated by training. If there are individual edges which you want to stay put during training, you can write `model.add_transition( a, b, pseudocount=1e8 )` and then toggle use_pseudocount=True when training, aka `model.fit( data, use_pseudocount=True )`. If you want ~all~ edges to stay the same, you can use `model.fit( data, edge_inertia=1.0 )` and that will ignore any update to edges.

**Comment by huiyuHarvey** [comment]
Hi, 
I assume the `dense_transition_matrix()` is to check the log probability of transition matrix, which means the `numpy.exp(tran)` is the real transition matrix.
After initialization,
```
dist1 = MultivariateGaussianDistribution([-4.54,3.91,0.02,1.08,-0.15,0.51,-0.18,0.53,-0.02,0.20,-0.13,0.12], np.eye(12))
dist2 = MultivariateGaussianDistribution([-4.50,4.03,-0.01,1.11,-0.04,0.56,-0.17,0.57,-0.01,0.22,-0.15,0.27], np.eye(12))
dist3 = MultivariateGaussianDistribution([-4.76,3.88,0.02,0.98,-0.20,0.60,-0.14,0.50,-0.02,0.25,-0.14,0.20], np.eye(12))

s1 = State(dist1, name='s1')
s2 = State(dist2, name='s2')
s3 = State(dist3, name='s3')
        
h = HiddenMarkovModel()
h.add_states(s1, s2, s3)
        
h.add_transition(h.start, s1, 1)
h.add_transition(s1, s1, 0.6)
h.add_transition(s1, s2, 0.4)
h.add_transition(s2, s2, 0.5)
h.add_transition(s2, s3, 0.5)
h.add_transition(s3, s3, 1)
        
h.bake()

tran = h.dense_transition_matrix()
tran = np.exp(tran)
```
I get the result as below:
![image](https://cloud.githubusercontent.com/assets/6173911/15442167/981ceeee-1edf-11e6-8d82-d50f7e0b2492.png)
I run again. However, I got the new transition matrix as below
![image](https://cloud.githubusercontent.com/assets/6173911/15442179/b7a1b66e-1edf-11e6-9559-22ddbb5c8511.png)

Could you plz tell me what I did to cause the change?
Since sometimes after `fit()`, I'm kind of confused with the second less meaningful matrix.

**Comment by jmschrei** [comment]
The ordering of states is not necessarily stable in older versions. I thought I had fixed that though. Can you clone the latest version of the code from github and see if that fixes the issue?

**Comment by huiyuHarvey** [comment]
Works now! Thanks!!!
Impressive project!
