### ISSUE TITLE
difference between fit() and from_summaries() in HMM

### ISSUE THREAD

**Issue by huiyuHarvey** [jmschrei/pomegranate#133]
Hi, 
I just wonder whether the fit() and from_summaries() should lead to the same result.
Below is my code:
```
    def train_hmm_fit(self, h):

        flst = self._add_direct(self.HMM_TRAIN_DIR)
        ccs = []
        for f in flst:
            print f
            cc = _get_cc(f)
            ccs.append(cc)

        x = h.fit(ccs, edge_inertia=0.5, distribution_inertia=0.5)

        tran = h.dense_transition_matrix()
        tran = np.exp(tran)
        return tran
        
    def train_hmm_sum(self, h):

        flst = self._add_direct(self.HMM_TRAIN_DIR)
        for f in flst:
            print f
            cc = _get_cc(f)
            h.summarize(cc)
    
        h.from_summaries(edge_inertia=0.5, distribution_inertia=0.5)

        tran = h.dense_transition_matrix()
        tran = np.exp(tran)
        return tran
```
I get the result as below:
![image](https://cloud.githubusercontent.com/assets/6173911/15470404/cb5f8a06-20f0-11e6-9c39-48bffc993a38.png)
![image](https://cloud.githubusercontent.com/assets/6173911/15470429/f8b816a8-20f0-11e6-8f62-f0452348399d.png)

**Comment by huiyuHarvey** [comment]
same issue for the distributions

**Comment by jmschrei** [comment]
HMMs use expectation-maximization to train, which is an iterative algorithm. from_summaries() will update the model for one iteration of this algorithm. If you run fit(max_iterations=1), you should get the same result.

**Comment by huiyuHarvey** [comment]
Thx a lot.
