### ISSUE TITLE
Inference in Bayesian Networks

### ISSUE THREAD

**Issue by EdiGNR** [jmschrei/pomegranate#136]
I have this code:

```
from pomegranate import *

Rain = DiscreteDistribution({'Yes': 0.2, 'No': 0.8})

Sprinkler = ConditionalProbabilityTable([['No', 'Off', 0.6],
                                         ['No', 'On', 0.4],
                                         ['Yes', 'Off', 0.99],
                                         ['Yes', 'On', 0.01]],
                                        [Rain])

Grass = ConditionalProbabilityTable(
        [['Off', 'No', 'Dry', 1.0],
         ['Off', 'No', 'Wet', 0.0],
         ['Off', 'Yes', 'Dry', 0.2],
         ['Off', 'Yes', 'Wet', 0.8],
         ['On', 'No', 'Dry', 0.1],
         ['On', 'No', 'Wet', 0.9],
         ['On', 'Yes', 'Dry', 0.01],
         ['On', 'Yes', 'Wet', 0.99], ],
         [Sprinkler, Rain])

sRain = Node(Rain, name="Rain")
sSprinkler = Node(Sprinkler, name="Sprinkler")
sGrass = Node(Grass, name="Grass")

network = BayesianNetwork("Wet Grass Network")

network.add_nodes([sRain, sSprinkler, sGrass])

network.add_edge(sRain, sSprinkler)
network.add_edge(sRain, sGrass)
network.add_edge(sSprinkler, sGrass)
network.bake()
```
And here's the diagram:
[https://en.wikipedia.org/wiki/File:SimpleBayesNet.svg](url)

How can I infer the probability of grass wet, sprinkler off and rain yes? Because I have done it manually and must be 0.1584. I want to know if there is a way to do P(Rain = Yes, Sprinkler = Off, Grass = Wet) = 0.1584.

Thanks in advance

**Comment by jmschrei** [comment]
Yep. You should be able to that by the `log_probability` method present in all pomegranate objects. In your case it should be `network.log_probability(['Off', 'Yes'. 'Wet'])`. You input your arguments in the same order you add nodes in the model.add_nodes step. I got the answer you expected using the following:

```
>>> network.log_probability(['Off', 'Yes', 'Wet'])
-1.8426317996018113
>>> numpy.e**network.log_probability(['Off', 'Yes', 'Wet'])
0.15840000000000004
```

**Comment by EdiGNR** [comment]
Yes, that did it! Thank you so much, I'm new to Python so I got a little confused. You saved my life, haha.

**Comment by minelminel** [comment]
For anyone who may stumble upon this in the future, some minor modifications are required to work with the latest version of the package (0.13.3). `add_nodes` no longer takes a list, but rather the unpacked list elements ([#169](https://github.com/jmschrei/pomegranate/issues/169#issuecomment-248776000)). I also had to swap the order of the list elements in the `log_probability` call, making sure to match the order used for `add_nodes`. Finally, I had to manually cast the input to `log_probability` to a Numpy array. This is discussed in [#672](https://github.com/jmschrei/pomegranate/issues/672#issuecomment-599262158) and it appears that simply nesting an additional list level would also suffice. The complete code is included below for reference
```python
from pomegranate import *
import numpy as np

Rain = DiscreteDistribution( {"Yes": 0.2, "No": 0.8} )

Sprinkler = ConditionalProbabilityTable(
    [
        ["No", "Off", 0.6],
        ["No", "On", 0.4],
        ["Yes", "Off", 0.99],
        ["Yes", "On", 0.01],
    ], [Rain]
)

Grass = ConditionalProbabilityTable(
    [
        ["Off", "No", "Dry", 1.0],
        ["Off", "No", "Wet", 0.0],
        ["Off", "Yes", "Dry", 0.2],
        ["Off", "Yes", "Wet", 0.8],
        ["On", "No", "Dry", 0.1],
        ["On", "No", "Wet", 0.9],
        ["On", "Yes", "Dry", 0.01],
        ["On", "Yes", "Wet", 0.99],
    ], [Sprinkler, Rain]
)

sRain = Node(Rain, name="Rain")
sSprinkler = Node(Sprinkler, name="Sprinkler")
sGrass = Node(Grass, name="Grass")

model = BayesianNetwork("Wet Grass Network")

model.add_nodes(sRain, sSprinkler, sGrass)
model.add_edge(sRain, sSprinkler)
model.add_edge(sRain, sGrass)
model.add_edge(sSprinkler, sGrass)
model.bake()

arr = np.array(["Yes", "Off", "Wet"], ndmin=2)
ans = np.e ** model.log_probability(arr)
print(ans)
```
which yields the output `0.15840000000000004`

Hope this helps someone else!

**Comment by jmschrei** [comment]
Thanks for adding this clarification. Did you encounter any examples in the current documentation or tutorials that had the incorrect notation? I should fix those, if so.

**Comment by minelminel** [comment]
[This docstring](https://github.com/jmschrei/pomegranate/blob/master/pomegranate/BayesianNetwork.pyx#L171) contains only a singly-nested list, which should either be a double-nested list `[[ ]]` or a manually-cast Numpy array if I'm not mistaken.

**Comment by jmschrei** [comment]
Ah, good catch. I'll try to fix that soon. Would you like to open an issue pointing out that issue (and any others that you've found) so I don't forget? I have a few things I need to do before I can put out another release.

**Comment by minelminel** [comment]
I'd be happy to. I'll take some time and see if there's any other references that I can find as well. I have only really used the Bayesian Network portion of the library so far, so I am unsure if this may be duplicated in other modules of the package.

**Comment by jmschrei** [comment]
Thanks! The Bayesian network portion of the API differed a bit from the rest of the package due to some initial poor choices in design. The inconsistencies you're seeing are a result of incomplete attempts to bring the API back in line with everything else. It's possible that there are issues elsewhere but I'm thinking most would be for Bayesian networks.
