### ISSUE TITLE
HMMs with an nth order transition matrix

### ISSUE THREAD

**Issue by bensteers** [jmschrei/pomegranate#138]
I've been looking through the source and it doesn't seem possible to add higher order transition probabilities to an HMM. Would it be trivial to add support for them? 

By nth order I just mean:
Transition Probability of (a-b-c-d) -> e, instead of just d -> e

**Comment by jmschrei** [comment]
Currently pomegranate does not support higher order HMMs. This is a feature I would like to add once I have more time, sometime over the summer. Are you dealing with continuous or discrete observations? You may be able to hack the current model to work by pretending its a multivariate distribution, where each dimension is a previous observation (e.g. "ABCD" becomes "[- A], [A B], [B C], [C D], [D -]"

**Comment by bensteers** [comment]
I'm working with multivariate distributions typically (audio feature vectors), but that's a clever work around! Although I assume that'd only work with univariate distributions? It's not something that I needed to use urgently, but I do think it would be a valuable feature so I'll happily help with the implementation when the time comes. Thanks!

**Comment by jmschrei** [comment]
Great, thanks for the offer! It doesn't necessarily need to be a univariate distribution, it just gets more ad-hoc the more dimensions there are. I agree that it would be a valuable feature, and it's been requested before. I'll let you know when I've made progress on this.

**Comment by B4marc** [comment]
@jmschrei I didn't find it in the release history, is it already implemented?

**Comment by jmschrei** [comment]
It's not currently implemented, and I don't think I'll have time to implement it. I'll open a PR should I ever get around to it, though.
