### ISSUE TITLE
Memory use when creating many HMM's with DiscreteDistributions

### ISSUE THREAD

**Issue by wiehan-a** [jmschrei/pomegranate#139]
Hi

I'm noticing steadily increasing memory usage when creating HMM's with DiscreteDistributions in a loop:
```python
while True:
    model = HiddenMarkovModel()
    state = State(DiscreteDistribution({"a" : 1.0}))
    model.add_transition(model.start, state, 1.0)
    model.add_transition(state, model.end, 1.0)
    model.bake()
```

This example is a bit silly, but I'm doing embedded training that requires creating many large temporary HMMs on the fly, so the leak gets problematic fairly early. The memory leak appears to be introduced during `model.bake()`, and also does not occur when I change the state distribution to a NormalDistribution.

**Comment by wiehan-a** [comment]
Ok, I just tested the bleeding edge (e5cc2d0c82cb78229ee69fc7fb51a4d431da3272), and it seems to be resolved.

**Comment by jmschrei** [comment]
Great. Glad it was resolved.
