### ISSUE TITLE
calling MultivariateGaussianDistribution.to_json() fails

### ISSUE THREAD

**Issue by shpigi** [jmschrei/pomegranate#14]
```
import pomegranate
d=pomegranate.MultivariateGaussianDistribution([0,0],[[1.0],[0,1]])
d.to_json()
```
causes
```
TypeError: array([0, 0]) is not JSON serializable
```
It seems the parameters are stored as numpy arrays and these are not serializable
Perhaps you could hold them as lists and convert to numpy array only when you need to use them?

(BTW, I'm pretty sure this a a bug that's unrelated to my recent tinkering with the to_json() code. I checked on a fresh install of pomegranate from the current source).

**Comment by jmschrei** [comment]
This is a bug introduced by a recent commit, and you're correct. Added to my todo list.

**Comment by anujkhare** [comment]
Hi, I am facing the same problem. Is it possible to bypass it by reverting to an older commit?

**Comment by jmschrei** [comment]
Unfortunately not. I always used numpy arrays for the underlying internals of MultivariateGaussians. All distributions are currently broken for serialization, but my next PR is about fixing that (including MultivariateGaussians). If you can hold on for a few days a new version should come out.

**Comment by jmschrei** [comment]
The latest commit should fix serialization issues. Please let me know if this solves your issues. I will be writing unit tests ensuring it works on everything soon, but I figured I'd let you know ASAP.

**Comment by jmschrei** [comment]
I'm going to close this now, as I have added unit tests for all distributions, general mixture models, and hidden Markov models. Please re-open if you experience issues. Tables are currently not supported, but should be soon.

**Comment by anujkhare** [comment]
Thanks for the quick repy and resolution! I will try it again today.
