### ISSUE TITLE
HMM for MFCC features 

### ISSUE THREAD

**Issue by epratheeban** [jmschrei/pomegranate#141]
I have a MFCC features of an audio file in a numpy array of (20 x 56789). I am trying to learn HMM  and train on it my data. My ultimate aim is to create a audio vocabulary for each window. I did  some basic initialization and tried observe the states. After training it seems like I have only 5 active states and it stays most of the time in a single state, But I am expecting around 10 or 11 states. This is the first time using pomegranate for an audio features. It will be helpful if you could able advice me, where I am going wrong in the coding part.

```
import numpy as np
from pomegranate import *
from pomegranate import HiddenMarkovModel as Model
from collections import Counter

data = getMFCC(1)    # input data 

N = 100      # No of  states
D = 20       
M = array(mean_list)
mean = [M for i in range(N)]
mu = np.mean(data, axis=1)
covar = np.cov(data)
distributions = [MultivariateGaussianDistribution(np.random.multivariate_normal(mu, covar, 1).squeeze() , covar) for i in range(N)]
transition = np.ones((N, N)) / N
starts = np.ones(N) / N
ends = np.ones(N) / N
hmm = HiddenMarkovModel.from_matrix(transition, distributions, starts, ends)
hmm.fit([data], algorithm='baum-welch', verbose=True, min_iterations=5)
path = hmm.viterbi(data.T)[1]
x=[state for state, _ in path]
count = Counter(x)
vocabulary.append([count])
print(vocabulary) # vocabulary has [Counter({51: 45244, 72: 11584, 64: 1, 100: 1, 101: 1})]

```

Is there anything wrong with my initialization or in understanding towards HMM?

Thanks

**Comment by jmschrei** [comment]
Hi @epratheeban. Are you sure that your data can't just be modeled with a few states? If you're going in with the assumption that the HMM with figure everything out, you may find it more difficult than if you initialize the HMM structure from prior knowledge about signal in your data.

Regarding initialization, you're determining mean and covariance from the entire dataset. I don't think this is optimal. You should try initializing with a unit covariance (diagonals of 1) and choosing a random sample for each of your means. You should also print out the distribution of the states afterwards so that you can see which ones look reasonable and which ones are unreasonable. I think it's not likely to work well if you just throw your data at a randomly initialized dense HMM without incorporation of prior knowledge in the structure.

Let me know if you have any further questions!

**Comment by epratheeban** [comment]
Yes, I am sure that my model can't just be modeled with few states., because I have 10 speakers in the audio file and I am considering 50 states per speaker which gives 500 states totally. Using 500 states will be computationally inefficient for initial trials. So I decided to use 100.

Yes, I did tried initialization life you said by keeping unit covariance (np.eye(D)). Then I  took the random sample of mean from each of the means. It throws a exception like this below. For each iteration it shows the same.
```
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._baum_welch_update'
Traceback (most recent call last):
  File "pomegranate/distributions.pyx", line 2378, in pomegranate.distributions.MultivariateGaussianDistribution.from_summaries (pomegranate/distributions.c:38986)
  File "/Users/elancheliyan/anaconda/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 526, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/Users/elancheliyan/anaconda/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
```

Will you please tell me how to print out the distribution and transition matrix after fitting ?

**Comment by jmschrei** [comment]
Ugh. Singular matrices are a huge problem with multivariate Gaussian HMMs, usually because some components become ill-defined. 

You can print out those using the following:

```Python
for state in model.states:
    d = state.distribution
    print d.name
    print d.mu
    print d.cov

print
print numpy.e**model.dense_transition_matrix()
```

**Comment by epratheeban** [comment]
Thank you ! 

I have done what you said before 
1. I tried by initializing with a unit covariance (diagonals of 1) and choosing a random sample for each of your means.
```
>> mu = np.mean(data, axis=1)
>>covar = np.eye(D)
>>distributions = [MultivariateGaussianDistribution(np.random.multivariate_normal(mu, covar, 1).squeeze() , covar) for i in range(N)]

```
But after fitting, the states dint moved at all. It stayed completely in 4. I printed the distribution and transition matrix, now my question what I should observe from the distribution ? 

I attached my notebook [hmm](http://nbviewer.jupyter.org/urls/bitbucket.org/pratheeban/public_files/raw/70439694d7e9817633fddd23691c503b2f22fae2/Notes/Hmm.ipynb).

**Comment by jmschrei** [comment]
You should take a look at your data. Plot some of the raw data, and look at the differences which seem to emerge when different characters speak. I would also avoid setting a specific min_iterations unless it's taking way too many to train (looks like you have some negative improvement there, meaning the model fits worse than before). Maybe try running with a single feature and see what happens? 

I think that just throwing a big model at a huge amount of data and expected it to work out of the box is not usually going to yield good results.

**Comment by jmschrei** [comment]
The singular matrix issue should be fixed now, as I implemented a more stable version of multivariate Gaussian updates. Were you able to figure out what might've been the issue?

**Comment by epratheeban** [comment]
@jmschrei  I recently received mail about it. I will try with new version and get back to you.
