### ISSUE TITLE
HMM.fit() does not update transitions out of silent states

### ISSUE THREAD

**Issue by wiehan-a** [jmschrei/pomegranate#149]
Hi,

I don't know if this is working as intended (perhaps you sometimes don't want to update these), but in my case I am definitely interested in re-estimating the transitions out of e.g. the start-state.

I suspect the problem may be with the following iteration:
```cython
for k in range( self.silent_start ):
	for l in range( self.out_edge_count[k], self.out_edge_count[k+1] ):
		li = self.out_transitions[l]
		prob = self.out_transition_log_probabilities[l]
		self.graph[self.states[k]][self.states[li]]['probability'] = prob
```

Which could be changed to something like this:
```cython
for k in range( self.n_states ):
    ...
```
The change does not appear to break anything (unit tests are OK, and produces the correct results in the cases I tested), but I haven't read the surrounding code carefully enough to be confident that it's 100% correct in all cases.

**Comment by jmschrei** [comment]
Your solution was the correct one. This issue should be fixed now, please check out the latest code and let me know if it works.

**Comment by wiehan-a** [comment]
Hi, that change works for me, thanks!
