### ISSUE TITLE
pomegranate does not install dependencies when installing from scratch

### ISSUE THREAD

**Issue by jmschrei** [jmschrei/pomegranate#150]
See #114 , look into how other packages (like pandas) handle dependency installation.

**Comment by nelson-liu** [comment]
if anything, more info about the dependencies in the readme would be welcome as well

**Comment by jmschrei** [comment]
I think the ultimate solution to this is to figure out how sklearn and other packages build their wheels on the server side so that users don't need to have their own C++ compiler. I'm sure it's not extremely complicated, I just haven't put in the time to figure out how wheels work.

**Comment by DeoLeung** [comment]
I ran into this problem when installing `0.6.1`
```sh
import pomegranate
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-f115d95d8f94> in <module>()
----> 1 import pomegranate

/xxx/lib/python3.5/site-packages/pomegranate/__init__.py in <module>()
     36     pyximport.install()
     37
---> 38 from .hmm import *
     39 from .kmeans import *
     40 from .BayesianNetwork import *

pomegranate/hmm.pyx in init pomegranate.hmm (pomegranate/hmm.c:52722)()

pomegranate/base.pyx in init pomegranate.base (pomegranate/base.c:10447)()

pomegranate/distributions.pyx in init pomegranate.distributions (pomegranate/distributions.c:76643)()

ImportError: No module named 'pomegranate.utils'
```
when do `pip uninstall pomegranate && pip install --no-cache-dir  pomegranate`
```sh
import pomegranate
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-f115d95d8f94> in <module>()
----> 1 import pomegranate

/xxx/lib/python3.5/site-packages/pomegranate/__init__.py in <module>()
     46 from .NaiveBayes import *
     47 from .MarkovChain import *
---> 48 from .parallel import *
     49
     50 __version__ = '0.6.1'

pomegranate/parallel.pyx in init pomegranate.parallel (pomegranate/parallel.c:12069)()

ImportError: cannot import name HiddenMarkovModel
```
I downgraded to `0.6.0` and it works now

**Comment by jmschrei** [comment]
That's weird. I'm not sure what the best way is to completely clean the prior version of pomegranate off your computer, but if you can make sure it is deleted then reinstalling should work fine.

**Comment by kitkat2233** [comment]
@DeoLeung's fix worked for me too
`pip uninstall pomegranate &&  pip install pomegranate==0.6.0 --no-cache-dir`

**Comment by jmschrei** [comment]
This should be fixed through the use of wheels for Windows. Please re-open if not the case.
