### ISSUE TITLE
stop token markov chain 

### ISSUE THREAD

**Issue by koaning** [jmschrei/pomegranate#164]
This is a feature request. 

Sometimes you want to simulate a markov chain that goes on and on until it samples a `<STOP>` token. Would this be something that other people might want out of this library?

**Comment by jmschrei** [comment]
This is a feature I'd like to see to. Ultimately I think the best way to deal with this is to have some unique value correspond to STOP, and keep sampling until you see it (and have the appropriate input tables have it)

**Comment by jmschrei** [comment]
Given the strength of other Markov chain packages out there I'm not going to have time to develop them further. Sorry :(
