### ISSUE TITLE
Link to GitHub repo in documentation is broken

### ISSUE THREAD

**Issue by rasbt** [jmschrei/pomegranate#167]
Hi, Jacob,
just noticed the links to the GitHub repo on http://pomegranate.readthedocs.io/en/latest/ seems to be broken. Here:

![screen shot 2016-09-17 at 3 16 25 pm](https://cloud.githubusercontent.com/assets/5618407/18610420/ec78a2d6-7ce9-11e6-9fb2-7a815b8d6eed.png)

and here:

![screen shot 2016-09-17 at 3 16 30 pm](https://cloud.githubusercontent.com/assets/5618407/18610421/ee2215cc-7ce9-11e6-89fc-c44064792c7a.png)

Cheers,
Sebastian

**Comment by jmschrei** [comment]
Thanks for pointing that out, I'll look into how to fix that.

**Comment by jmschrei** [comment]
Do you know how to fix the Edit on GitHub button? I can't find where that link is. I've fixed the other one.

**Comment by rasbt** [comment]
Honestly, I don't have much experience with this since I am usually using mkdocs, but I think the relevant part is in the lines 

```python
github_doc_root = "https://github.com/jmschrei/pomegranate/docs/source"
MarkdownParser.github_doc_root = github_doc_root
source_parsers = {
    '.md': MarkdownParser,
}

# The suffix(es) of source filenames.
source_suffix = ['.rst', '.md']
```

in your `docs/source/conf.py`

Maybe check on https://github.com/scikit-learn/scikit-learn/blob/master/doc/conf.py how they handle that; looks like it requires some workaround (see the lines at the bottom)

**Comment by rasbt** [comment]
oh that's fixed, awesome! Thanks, and I have to look at the commit since I was having the same issues with the readthedocs template lately :)

**Comment by jmschrei** [comment]
tbh I don't think I did anything, I just noticed it was fixed a little bit ago myself.
