### ISSUE TITLE
Any way to serialize/save a Bayesian Network?

### ISSUE THREAD

**Issue by andrew8088** [jmschrei/pomegranate#168]
I can't seem to find any method to save the parameters of a Bayesian Network, nothing like the `to_json` / `from_json` that HMMs have. Is there any way to do this?

**Comment by jmschrei** [comment]
Currently there is not, but it's due entirely to me not giving bayesian networks enough love. I'm focusing all my attention on bayesian networks now and so I'll roll out these methods asap.

**Comment by andrew8088** [comment]
Thanks! I appreciate that!

**Comment by jmschrei** [comment]
This should be added in. Let me know if they work for you.
