### ISSUE TITLE
Structural Optimization of the HMM topology

### ISSUE THREAD

**Issue by Narsail** [jmschrei/pomegranate#188]
Hello Jacob,

do you have any plans to implement a separate or joint (merged fitting and topology training methods) topology training for the HMMs? There is the possibility to further increase the precision of the models through incorporating splitting and pruning of states.

**Comment by jmschrei** [comment]
I am looking to try to add a structure learning method at some point in the next few months, but I don't currently have plans to add in a merged fitting and structure modification step. Do you have a good paper for the procedure you're looking for? It'd help me figure out approximately how much time adding it would take.

**Comment by Narsail** [comment]
Not yet. I'm looking into this matter myself but it is hard to find complete literature about this problem. Hopefully i can tell you more in the next few days.

**Comment by jmschrei** [comment]
Great. If you can find a structure + parameter learning algorithm directly from data that'd be the best for pomegranate. Have you seen this paper? http://repository.cmu.edu/cgi/viewcontent.cgi?article=2324&context=compsci

**Comment by Narsail** [comment]
At the moment i'm looking into: http://www.sciencedirect.com/science/article/pii/S0031320399002265 and i'm planning to lend tomorrow the following book: http://www.springer.com/us/book/9783662533000 from my local library. Thanks for the paper!

**Comment by Narsail** [comment]
I don't have a clear course yet but what i will do is to implement the pruning and splitting of states for the HMM. Hopefully i can provide you a pull request soon.

**Comment by Narsail** [comment]
So i added the pruning of transitions as well as the splitting of a existing state in the pull request #194.

For the state splitting it is necessary to split the distribution as well. At the moment there are only implementations for the Normal and the IndependentComponentDistribution (because those are in use in my project^^)

**Comment by jmschrei** [comment]
Thanks for taking the time to try to incorporate this work into pomegranate. Unfortunately, I got side tracked in the last year and this never made it into pomegranate. If you'd like to propose a structure learning addition, it should follow the format of `HiddenMarkovModel.from_samples`, which learns a dense graph. Please open a new issue/PR if you do, and I'll try to provide guidance!
