### ISSUE TITLE
HMM: No baking required after extending model

### ISSUE THREAD

**Issue by Narsail** [jmschrei/pomegranate#196]
Is it intentional that you can fit a HMM Model after the following process?:

hmm -> add states/edges -> bake -> fit -> add new state/edges

Shouldn't there a bake necessary first?

**Comment by jmschrei** [comment]
There is. You're fitting a model, but it's not the correct model, when you do that. You need to bake whenever you change the topology or emissions of the model.

**Comment by Narsail** [comment]
But shouldn't there be an error which will notify the user?

**Comment by jmschrei** [comment]
Yes. Unfortunately pomegranate lacks error messages in many locations.
