### ISSUE TITLE
Segfault and bad function call with BayesianNetwork.from_samples

### ISSUE THREAD

**Issue by wbthomason** [jmschrei/pomegranate#202]
When using BayesianNetwork.from_samples I get two distinct errors, depending on whether I specify `algorithm='exact'` or not. If I do, the code segfaults (I haven't yet tracked down where). If I don't, line 1524 of pomegrante/distributions.pyx, in pomegranate.distributions.DiscreteDistribution.from_samples, fails by trying to use the itertools.izip method (Python 3 has no izip in itertools). I will try to add more detail to this/look further into it later.

**Comment by wbthomason** [comment]
Can't reproduce the segfault, now that I'm looking into it further. The izip problem remains.

**Comment by jmschrei** [comment]
That's a mistake on my part then. I'll add a fix to it promptly and let you know. I'll need more info on the segfault or some minimally reproducing code if you can.

**Comment by wbthomason** [comment]
Sure, I'm intending to dive into it with lldb this weekend; I'll try to
post a minimal example before that. At this point, all I know is that it
happens when I'm trying to use the exact algorithm for a moderately large
network (7 variables).

**Comment by nickynicolson** [comment]
I just hit the same problem: `distributions.pyx` needs a single line fix - line 1524:
```python
    for character, weight in it.izip(items, weights):
```
to
```python
    for character, weight in izip(items, weights):
```
 
As the class tests for python 2 or 3 (line 32) and aliases it.izip / zip appropriately

**Comment by jmschrei** [comment]
I just pushed a fix for the izip issue. If you pull the latest code from github it should work. Let me know!

**Comment by wbthomason** [comment]
Haven't yet had a chance to track down the segfault, but the izip issue is fixed. Thanks!

**Comment by jmschrei** [comment]
Great. I'm going to close this now then and if you find the source of the segfault open a new issue to let me know.
