### ISSUE TITLE
allow finer tuning of constraint graph?

### ISSUE THREAD

**Issue by michaelMinar** [jmschrei/pomegranate#211]
Fantastic package! I've been playing around with it for a few days now trying to train up some Bayesian Networks. I had a question related to the constraint graph functionality. Is there a way to tune the scoring functions so that you enforce dependencies between particular layers or nodes? I find that if I run `from_samples` on a bayesian models I quickly see the algorithm drop evidentiary nodes I know have some causal affect in favor of others that are stronger drivers. I would like to enforce the causal layers via the constraint graph, but also enforce that every node in layer 1 is connected to a particular node in layer 2.

Hope this makes sense, thanks so much for any guidance.

**Comment by jmschrei** [comment]
You're looking for a whitelist, where edges in the structure are forced to exist, and the rest of the graph is learned on top of it? I think I can add that in, as well as a corresponding blacklist for edges which can't exist

**Comment by michaelMinar** [comment]
Yes that is exactly what I am looking for. Thank you so much for the quick response and in advance for any feature work in this area!
