### ISSUE TITLE
Unbound var when baking an HMM containing only silent states

### ISSUE THREAD

**Issue by danwilhelm** [jmschrei/pomegranate#212]
When an HMM is baked containing only silent states, the bake function fails as follows:

    == File "pomegranate/hmm.pyx", line 1042, in pomegranate.hmm.HiddenMarkovModel.bake (pomegranate/hmm.c:16320)
    == UnboundLocalError: local variable 'dist' referenced before assignment

**Why?** 
In hmm.pyx, the variable 'dist' is only defined if there are non-silent states (the line of code is linked below). This line is immediately followed by an if statement that incorrectly assumes 'dist' always exists:

https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L1039

**Comment by jmschrei** [comment]
Howdy!

Good question. A HMM doesn't really exist if there are only silent states. How would it model anything? I should probably raise a warning there, but in what situation would you only have silent states?

**Comment by danwilhelm** [comment]
I second your suggestion of gracefully raising a warning. 

The solution I adopted was to test whether data exists prior to creating the HMM. (For context, I was batch creating HMMs. I occasionally filtered my training data so much that none was left. I failed to test for this edge case, accidentally passing it on to pomegranate.)

That said, I believe it would be ideal for pomegranate to gracefully exit. Failing due to an unbound error should likely be avoided!

**Comment by jmschrei** [comment]
Ah, gotcha. I admit that I don't have as many graceful exits as I should, so I'm glad you found another one for me to add! I'll close this issue for now, let me know if you have any other troubles with pomegranate.

**Comment by chananshgong** [comment]
Why do I get the same error for non silent states? ( I am not sure what silent state means anyway - how can a state have no emissions?)

            model.from_matrix(transition_probabilities=self.transition_matrix.values, # matrix
                              distributions=self.gmm_model, # list of multivariate gaussian distributions
                              starts=self.start_prob.values, # start probability array
                              name=self.state_names) # list of state names
            model.bake()

>   File "pomegranate/hmm.pyx", line 1042, in pomegranate.hmm.HiddenMarkovModel.bake (pomegranate\hmm.c:16320)
> UnboundLocalError: local variable 'dist' referenced before assignment
>

**Comment by jmschrei** [comment]
Silent states are mostly used for bookkeeping. They allow you to move through the model without moving through the sequence when you try to align a sequence to the model. They can drastically speed up computation in some types of graphs, particularly those used in bioinformatics. All models with silent states can be represented as a model without silent states but more edges.

Can you report what "self.gmm_model" is? The only reason you'll get that error is if you've passed entirely "none"s in. It is also possible that your transition probabilities are incorrect and the automated pruning aspect is removing all your states. You should make sure that they are all correct.
