### ISSUE TITLE
Support for tied covariance matrices in Baum-Welch (with gaussian emissions)?

### ISSUE THREAD

**Issue by anntzer** [jmschrei/pomegranate#213]
Can pomegranate's Baum-Welch implementation fit to a gaussian emission model with tied covariance matrices?  (i.e. all states share the same covariance matrix)

cf "covariance_type" argument in [hmmlearn](http://hmmlearn.readthedocs.io/en/latest/api.html#hmmlearn.hmm.GaussianHMM).

Thanks in advance.

**Comment by jmschrei** [comment]
This is not currently built in to pomegranate unfortunately. However, my understanding of tied covariance matrices is that you could run Baum-Welch for one iteration, manually update each covariance matrix to be the sum of all the tied covariance matrices, and then re-run for a second iteration, repeating this until convergence.

**Comment by anntzer** [comment]
I think it's probably the average of the covariances weighted by the posterior sums.  I'm not familiar with pomegranate's internals so I don't know how feasible that is though.
