### ISSUE TITLE
Import error on python 3.6 (for 0.6.1)

### ISSUE THREAD

**Issue by kristofve91** [jmschrei/pomegranate#215]
I am getting the following import error on Python 3.6, using pomegranate 0.6.1:

```python
Python 3.6.0 (default, Dec 29 2016, 21:40:36) 
[GCC 5.4.1 20161202] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pomegranate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kve/.virtualenvs/p36/lib/python3.6/site-packages/pomegranate/__init__.py", line 38, in <module>
    from .hmm import *
  File "pomegranate/hmm.pyx", line 1, in init pomegranate.hmm (pomegranate/hmm.c:52722)
  File "pomegranate/base.pyx", line 6, in init pomegranate.base (pomegranate/base.c:10447)
  File "pomegranate/distributions.pyx", line 1, in init pomegranate.distributions (pomegranate/distributions.c:76643)
ModuleNotFoundError: No module named 'pomegranate.utils'
```

I am not encountering this problem using pomegranate 0.6.0, while 0.6.1 works perfectly on Python 3.5.

**Comment by jmschrei** [comment]
Howdy. This is a weird issue with pomegranate that doesn't seem to be python version specific, but I can't quite figure out. My understanding of the problem is that an old version of pomegranate is hanging out somewhere in your system, likely from back before I added in the utils file. Can you try completely removing pomegranate from your system (maybe manually going into your site-packages if package managers don't work) and then reinstall?

**Comment by kristofve91** [comment]
I have done a new install of pomegranate 0.6.1 on my pc at home (where I hadn't installed it before today) and I am getting the exact same issue there. After uninstalling, no files were left inside the site-packages folder. 

However, when I compare the contents of the pomegranate subfolder between 0.6.0 and 0.6.1, two shared objects seem to be missing in the latter: `parallel.cpython-36m-x86_64-linux-gnu.so` and `utils.cpython-36m-x86_64-linux-gnu.so`, with the latter being the reason for the `ModuleNotFoundError`. There seems to be an error during the build process.

**Comment by jmschrei** [comment]
Great. I'm glad you found the issue. Thanks for taking the time to post an update.
