### ISSUE TITLE
Is there structure learning approachs in this package?

### ISSUE THREAD

**Issue by faeahi** [jmschrei/pomegranate#218]
Hello.
I want to learn bayesian network from a dataset with continuous values and i need to use score based approachs for structure learning.
I want to know is there structure learning approachs in this package?
Thanks.

**Comment by jmschrei** [comment]
Howdy Faeahi

You're looking for a linear Gaussian Bayesian network instead of a discrete Bayesian network. pomegranate currently only supports discrete Bayesian networks unfortunately. Sorry for the inconvenience!

**Comment by faeahi** [comment]
thank you very much for your reply.

**Comment by faeahi** [comment]
Hi.

sorry but i need to ask you a question cause i think you are the only one
who can help me.
Do you know packages in python for my work?
I hava a dataset with one discrete variable and many continuous variables.
I want to learn bayesian network from this dataset and i need to use score
based approachs for structure learning.

Thanks a lot.

**Comment by faeahi** [comment]
Hi Jmschrei.

sorry but i need to ask you a question cause i think you are the only one who can help me.
Do you know packages in python for my work?
I hava a dataset with one discrete variable and many continuous variables. I want to learn bayesian network from this dataset and i need to use score based approachs for structure learning.

Thanks a lot.

**Comment by jmschrei** [comment]
You're looking for a hybrid bayesian network if you want to combine a discrete variable with continuous variables. The math behind belief propogation gets more complicated when you have both types of variables involved, so if it's possible you may want to find a way to get rid of that discrete one, such as have many networks made up of the continuous variables, with one network per value in the discrete variable. 

libpgm says it has both linear gaussian (continuous variables) and hybrid networks implemented, but I've never had terribly good luck getting the package to run. Maybe you'll have more luck!

**Comment by faeahi** [comment]
Thank you so much for your help.
i have tested libpgm but this package doesn't have score based structure
learning approach.
