### ISSUE TITLE
Enhanced Windows compiling documentation is needed

### ISSUE THREAD

**Issue by chananshgong** [jmschrei/pomegranate#225]
This worked for me for "pip install pomegranate":
 
1. You would need to download Microsoft C++ build tools.
* See https://wiki.python.org/moin/WindowsCompilers for details and links
* Notice your compiler version should fit your python version. Run python --version to tell which python version you use.
* Don't forget to select Windows 10 API in the custom menu.

2. If you get an error message "ValueError: Unknown MS Compiler version 1900":
* Remove your Python's Lib/distutils/distutil.cfg and retry
* see http://stackoverflow.com/questions/34135280/valueerror-unknown-ms-compiler-version-1900 for details

**Comment by jmschrei** [comment]
Thanks for figuring this out! I've added this information to the installation instructions.
