### ISSUE TITLE
TypeError: fit() got an unexpected keyword argument 'n_jobs'

### ISSUE THREAD

**Issue by chananshgong** [jmschrei/pomegranate#228]
According to the docs, there is an `n_jobs` parameter to control number of cores.
However, my fit methods doesn't have this parameter.

Docs:
```%timeit fit(GeneralMixtureModel(MultivariateGaussianDistribution, n_components=k), X, n_jobs=4, max_iterations=15, stop_threshold=1e-10)```

My code:
```
model = MultivariateGaussianDistribution
mixture_model = GeneralMixtureModel(model, n_components)

mixture_model.fit(data, n_jobs = 4) # fails
```
> TypeError: fit() got an unexpected keyword argument 'n_jobs'

**Comment by jmschrei** [comment]
The fit function is a parallelization wrapper and so currently supports `n_jobs` whereas the fit methods don't support `n_jobs` at this time.
