### ISSUE TITLE
very slow convergence relative to scikitlearn for multivariate GMM

### ISSUE THREAD

**Issue by chananshgong** [jmschrei/pomegranate#229]
When I compare running time of GMM fit on pomegrante and scikit-learn, the latter is much faster. I will upload test code and data soon.

**Comment by jmschrei** [comment]
Great, I'd like to see another test. Make sure that you are learning the full covariance matrix with sklearn though, not the diagonal, and that you're using a similar tolerance on when to stop EM.

**Comment by jmschrei** [comment]
Any updates on this?
