### ISSUE TITLE
support for missing observations (in HMM) ?

### ISSUE THREAD

**Issue by shpigi** [jmschrei/pomegranate#23]
Hi.
Does pomegranate support missing observations? 
I'd like to do something like:

<pre>
# make a series with a switch point 
obs1 = numpy.random.normal(0,2,100)
obs2 = numpy.random.normal(1,2,100)
obs = numpy.concatenate([obs1, obs2])
<b>
# sprinkle missing values
obs[0::10] = numpy.nan
</b>
# model = generate a pomegranate.HiddenMarkovModel with two states

model.train([obs])
</pre>

If not, what changes would be needed in order to support this?

**Comment by jmschrei** [comment]
Support for missing values has been requested in #18 . I am going to be adding it as my next feature for Bayesian networks, with the following usage:

```
network = ~some bayesian network~
dataset = ~some 2d numpy array with numpy.nan values sprinkled in~

network.bake()
network.impute( dataset ) # This will fill in the missing values using conditional expectation
```

Missing values for hidden markov models are something I had not considered. Can you point me to a good resource for what you'd like to see included?

**Comment by shpigi** [comment]
Let's assume that the observations are missing [completely at random](https://en.wikipedia.org/wiki/Missing_data#Missing_completely_at_random), otherwise things are more complicated (we need to model when the data is missing).
In that case, this [answer](http://www.quora.com/How-can-I-estimate-the-parameters-of-a-discrete-time-HMM-when-some-observations-are-missing) can serve as reference for how training should be performed with the forward-backward method.

In terms of functionality (API), viterby and train need not change. If one wanted to `impute` the missing observations, the best thing to do would probably be to run viterbi on the observation sequences (with a trained model) and then find the most likely observations where the nans are, given the expected states in those places.

note:
I think there might be another way; making the HMM have mixture output distributions that are either the original emission distribution or a 'missing' distribution which is tied across states.

**Comment by jmschrei** [comment]
An impute method for HMMs (and for Bayes nets) is really just the expectation step of EM. You'd use the forward_backward method to determine hidden state responsibilities for that observation (by using transitions and ignoring emissions for that observation), and then use MLE to calculate a value. I do not think Viterbi is the best method.

**Comment by shpigi** [comment]
What I was looking for was support for:
1) learn the HMM parameters from sequences of observations with missing data (train)
2) find the most probably sequence of hidden states given sequences of observations with missing data (viterbi)
3) find the sequence of hidden state responsibilities for a sequence of observations with missing values.

Imputation of missing observations is quite easy given 2 or 3.

I gather there are no immediate plans to support these?

**Comment by jmschrei** [comment]
No immediate plans, but they can be added sometime soon. You're basically asking that all HMM operations be allowed to take in missing data. I need to confirm that the correct thing to do is to ignore the emission probabilities, though. If you can find a more credible resource than a Quora post, that would speed up the process.

**Comment by dhuppenkothen** [comment]
I'm interested in this, too. I'm trying to model a process where I have, say, a hundred connected observations over a few hours every day and then a few hours of no observations between them. I haven't yet found anything more substantial than the Quora post, but I'm not a computer scientist, so I don't necessarily know the right words to search for.

**Comment by jmschrei** [comment]
Just merged =)
