### ISSUE TITLE
HMM plot fails with TypeError

### ISSUE THREAD

**Issue by lxkain** [jmschrei/pomegranate#230]
When executing:

```
start = np.array([1, 0, 0, 0])  # definitely start in winter
end =   np.array([0, 0, 0, 0])  # indefinite ending state
transition = np.array([[0.9, 0.1, 0.0, 0.0],
                      [0.0, 0.9, 0.1, 0.0],
                      [0.0, 0.0, 0.9, 0.1],
                      [0.1, 0.0, 0.0, 0.9]])
I = np.eye(2) * 2
distribution = [MGD([30, 80], I),
                MGD([55, 70], I),
                MGD([80, 30], I),
                MGD([60, 80], I)]
hmm = HMM.from_matrix(transition, distribution, start, end)
hmm.plot()
```

I get:

pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.plot (pomegranate/hmm.c:11302)()

TypeError: draw() missing 1 required positional argument: 'G'

**Comment by jmschrei** [comment]
This is a minor error in line 671 of hmm.pyx, where I default back to networkx if one doesn't have pygraphviz. I can push a fix for that soon, but in the meantime you can try installing pygraphviz if you have ubuntu: http://stackoverflow.com/a/17456678

**Comment by lxkain** [comment]
Great! Thank you for this awesome package!
