### ISSUE TITLE
Sampling not implemented for BayesianNetwork

### ISSUE THREAD

**Issue by katbusch** [jmschrei/pomegranate#231]
`sample()` appears in the documentation for BayesianNetwork network but it's not actually implemented.

**Comment by tbsexton** [comment]
Just to chime in, the smaple method would be a very effective way to eliminate the problems with using continuous nodes in BN's. 

#106 would be possible with an inference algorithm for limited cases (e.g. no continuous parents of discrete nodes) but more generally the only real way to go forward is to implement sampling, allowing arbitrary nodes.

**Comment by jaSunny** [comment]
#86 also refers to similar question. From me +1

**Comment by jaSunny** [comment]
@jmschrei Is there any update on this end? Or a suggestion for a workaround? thanks!

**Comment by jmschrei** [comment]
Sorry, there has not been an update on this yet. I believe that sampling is implemented for ConditionalProbabilityTables, so you could start by sampling from one table, then plug those values into the next table if it shares any of those values, and so on. You want to be sure that you didn't sample from each table independently, because that would not produce a valid sample, but instead iteratively built up the sample by feeding the sampled values from the prior variables into the next CPTs. Let me know if that doesn't make sense.

**Comment by benrhodes26** [comment]
In case it is of use to anyone, i've attached sampling code for the *specific* case where the bayesian network is a chow-liu tree (so each variable has at most one parent) and the variables are binary.

Generalising this code for non-binary, discrete variables should be straightforward. However, generalising it to the case when nodes have more than one parent would be more complex. You would need to calculate the topological ordering in a different way.

```python
sample_size = 10000
test_array = np.array([[0,1,1,1,0,1,0], [1,1,1,1,0,1,0], [1,1,1,1,1,0,0], [1,0,1,0,1,0,0],
                       [1,0,1,0,1,0,0], [1, 1, 1, 0,0,1,0]])

bn = BayesianNetwork().from_samples(test_array, algorithm='chow-liu')

# get dictionary mapping each node in network to it's children, and another
# dictionary mapping each node to it's parents
node_to_children_dict = {}
node_to_parents_dict = {}
for e in bn.edges:
    node_to_children_dict[e[0]] = node_to_children_dict.get(e[0], []) + [e[1]]
    node_to_parents_dict[e[1]] = e[0]

# get topological ordering
topological_order = []
top_nodes = [v for v in bn.states if v not in node_to_parents_dict.keys()]
current_generation = top_nodes
keep_going = True
while keep_going:
    topological_order.extend(current_generation)
    next_generation = []
    for node in current_generation:
        if node in node_to_children_dict.keys():
            next_generation.extend(node_to_children_dict[node])
            
    current_generation = next_generation
    if not current_generation:
        keep_going = False

# now let's actually perform the sampling
num_nodes = bn.state_count()
sample = np.zeros((sample_size, num_nodes))
node_to_parent_id = {c.name: int(p.name) for c, p in node_to_parents_dict.items()}

for i in range(sample_size):
    for node in topological_order:
        node_id = int(node.name)
        if node not in node_to_parents_dict.keys():
            if 1 in node.distribution.parameters[0]:
                sample[i,node_id] = rnd.uniform(0,1) < node.distribution.parameters[0][1]
            else:
                sample[i,node_id] = rnd.uniform(0,1) > node.distribution.parameters[0][0]
        else:
            # get the conditional probability table, and then find the sub-table
            # using the already sampled values of the parent nodes
            cpt = np.array(node.distribution.parameters[0])
            parent_id = node_to_parent_id[node.name]
            parent_sample_val = sample[i, parent_id]
            sub_table = cpt[cpt[:, 0]==parent_sample_val]
            if sub_table[sub_table[:, 1]==1].size != 0:
                sample[i,node_id] = rnd.uniform(0,1) < sub_table[sub_table[:, 1]==1][0, -1]
            else:
                sample[i,node_id] = rnd.uniform(0,1) > sub_table[sub_table[:, 1]==0][0, -1]
```

**Comment by jaSunny** [comment]
@jmschrei any chance this can be included?

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
