### ISSUE TITLE
Saving/Serializing with PMML

### ISSUE THREAD

**Issue by tbsexton** [jmschrei/pomegranate#232]
Apologies if this is too similar to #168 . With the introduction of [PMML v. 4.3](http://dmg.org/pmml/v4-3/BayesianNetwork.html) there's now an open standard for serializing a BN structure (basically an XML schema). 

Originally I was looking into writing a converter from PyMC3 to PMML, but after finding this package and how seamless the node hierarchy structuring is in Pomegranate (even with NetworkX natively!), I think the ability to write/read PMML would be an excellent addition.

**Comment by jmschrei** [comment]
I would love to have this. While currently all models should be able to be serialized to a JSON, I know that a lot of BNs are serialized using PMML and it would be nice to natively support that. Is there any chance you could take it on and submit a PR? Likely a `model.to_pmml` method and a `BayesianNetwork.from_pmml` class function would be sufficient.

**Comment by tbsexton** [comment]
Definitely something I will look into. The main incompatibility will be with continuous nodes from the schema, but even without that it should hopefully be fairly helpful.

**Comment by jmschrei** [comment]
Hi @tbsexton, do you think this is something you might have time to add in? If not, I'm going to close the issue.

**Comment by tbsexton** [comment]
@jmschrei Definitely looking into this; I just wrapped up a milestone in a [pymc3 BN serialization/viz/prototyping wrapper](https://github.com/usnistgov/pmml_pymcBN), and a PR for discrete BN serialization in pomegranate was my next to-do. Apologies for the long delay on this!

**Comment by jmschrei** [comment]
If you find time to submit a PR for PMML that would be great. I'm going to close this issue, though.
