### ISSUE TITLE
NaN in Baum-Welch training

### ISSUE THREAD

**Issue by sztike93** [jmschrei/pomegranate#234]
Hey,

I have been trying to test pomegranate for some Multiple Sequence Alignment task, but I get NaN even for the following easy example (http://www.statru.org/wp-content/uploads/2012/04/01_Statistical-Methods-in-Bioinformatics.pdf, page 346):

`
from pomegranate import HiddenMarkovModel as hmm
from pomegranate import State, DiscreteDistribution
import numpy as np

X1 = list("CAEFDDH")
X2 = list("CDAEFPDDH")

X = np.concatenate([X1, X2])
lengths = [len(X1), len(X2)]

AA_dict = {'A': .05, 'R': .05, 'N': .05,
           'D': .05, 'C': .05, 'E': .05,
           'Q': .05, 'G': .05, 'H': .05,
           'I': .05, 'L': .05, 'K': .05,
           'M': .05, 'F': .05, 'P': .05,
           'S': .05, 'T': .05, 'W': .05,
           'Y': .05, 'V': .05}

match0 = DiscreteDistribution(AA_dict)
match1 = DiscreteDistribution(AA_dict)
match2 = DiscreteDistribution(AA_dict)
match3 = DiscreteDistribution(AA_dict)
match4 = DiscreteDistribution(AA_dict)
match5 = DiscreteDistribution(AA_dict)
match6 = DiscreteDistribution(AA_dict)
match7 = DiscreteDistribution(AA_dict)
match8 = DiscreteDistribution(AA_dict)
match9 = DiscreteDistribution(AA_dict)
match10 = DiscreteDistribution(AA_dict)

insert0 = DiscreteDistribution(AA_dict)
insert1 = DiscreteDistribution(AA_dict)
insert2 = DiscreteDistribution(AA_dict)
insert3 = DiscreteDistribution(AA_dict)
insert4 = DiscreteDistribution(AA_dict)
insert5 = DiscreteDistribution(AA_dict)
insert6 = DiscreteDistribution(AA_dict)
insert7 = DiscreteDistribution(AA_dict)
insert8 = DiscreteDistribution(AA_dict)
insert9 = DiscreteDistribution(AA_dict)

m0 = State(match0, name='m0')
m1 = State(match1, name='m1')
m2 = State(match2, name='m2')
m3 = State(match3, name='m3')
m4 = State(match4, name='m4')
m5 = State(match5, name='m5')
m6 = State(match6, name='m6')
m7 = State(match7, name='m7')
m8 = State(match8, name='m8')
m9 = State(match9, name='m9')
m10 = State(match10, name='m10')

i0 = State(insert0, name='i0')
i1 = State(insert1, name='i1')
i2 = State(insert2, name='i2')
i3 = State(insert3, name='i3')
i4 = State(insert4, name='i4')
i5 = State(insert5, name='i5')
i6 = State(insert6, name='i6')
i7 = State(insert7, name='i7')
i8 = State(insert8, name='i8')
i9 = State(insert9, name='i9')

d1 = State(None, name='d1')
d2 = State(None, name='d2')
d3 = State(None, name='d3')
d4 = State(None, name='d4')
d5 = State(None, name='d5')
d6 = State(None, name='d6')
d7 = State(None, name='d7')
d8 = State(None, name='d8')
d9 = State(None, name='d9')

model = hmm('testHMM')
model.add_states([m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10,
                  i0, i1, i2, i3, i4, i5, i6, i7, i8, i9,
                  d1, d2, d3, d4, d5, d6, d7, d8, d9])
# create transitions from match states
model.add_transition(model.start, m0, .9)
model.add_transition(model.start, i0, .1)
model.add_transition(m0, m1, .9)
model.add_transition(m0, i0, .05)
model.add_transition(m0, d1, .05)

model.add_transition(m1, m2, .5)
model.add_transition(m1, i1, .45)
model.add_transition(m1, d2, .05)

model.add_transition(m2, m3, .8)
model.add_transition(m2, i2, .05)
model.add_transition(m2, d3, .15)

model.add_transition(m3, m4, .7)
model.add_transition(m3, i3, .15)
model.add_transition(m3, d4, .15)

model.add_transition(m4, m5, .5)
model.add_transition(m4, i4, .05)
model.add_transition(m4, d5, .45)

model.add_transition(m5, m6, .9)
model.add_transition(m5, i5, .05)
model.add_transition(m5, d6, .05)

model.add_transition(m6, m7, .95)
model.add_transition(m6, i6, .025)
model.add_transition(m6, d7, .025)

model.add_transition(m7, m8, .95)
model.add_transition(m7, i7, .035)
model.add_transition(m7, d8, .015)

model.add_transition(m8, m9, .9)
model.add_transition(m8, i8, .05)
model.add_transition(m8, d9, .05)

model.add_transition(m9, m10, .9)
model.add_transition(m9, i9, .1)

model.add_transition(m10, model.end, 1)

# create transitions from match states
model.add_transition(i0, i0, .7)
model.add_transition(i0, d1, .15)
model.add_transition(i0, m1, .15)

model.add_transition(i1, i1, .7)
model.add_transition(i1, d2, .15)
model.add_transition(i1, m2, .15)

model.add_transition(i2, i2, .7)
model.add_transition(i2, d3, .15)
model.add_transition(i2, m3, .15)

model.add_transition(i3, i3, .7)
model.add_transition(i3, d4, .15)
model.add_transition(i3, m4, .15)

model.add_transition(i4, i4, .7)
model.add_transition(i4, d5, .15)
model.add_transition(i4, m5, .15)

model.add_transition(i5, i5, .7)
model.add_transition(i5, d6, .15)
model.add_transition(i5, m6, .15)

model.add_transition(i6, i6, .7)
model.add_transition(i6, d7, .15)
model.add_transition(i6, m7, .15)

model.add_transition(i7, i7, .7)
model.add_transition(i7, d8, .15)
model.add_transition(i7, m8, .15)

model.add_transition(i8, i8, .7)
model.add_transition(i8, d9, .15)
model.add_transition(i8, m9, .15)

model.add_transition(i9, i9, .85)
model.add_transition(i9, m10, .15)

# Create transitions from delete states
model.add_transition(d1, d2, .15)
model.add_transition(d1, i1, .15)
model.add_transition(d1, m2, .7)

model.add_transition(d2, d3, .15)
model.add_transition(d2, i2, .15)
model.add_transition(d2, m3, .7)

model.add_transition(d3, d4, .15)
model.add_transition(d3, i3, .15)
model.add_transition(d3, m4, .7)

model.add_transition(d4, d5, .15)
model.add_transition(d4, i4, .15)
model.add_transition(d4, m5, .7)

model.add_transition(d5, d6, .45)
model.add_transition(d5, i5, .15)
model.add_transition(d5, m6, .4)

model.add_transition(d6, d7, .15)
model.add_transition(d6, i6, .15)
model.add_transition(d6, m7, .7)

model.add_transition(d7, d8, .15)
model.add_transition(d7, i7, .15)
model.add_transition(d7, m8, .7)

model.add_transition(d8, d9, .15)
model.add_transition(d8, i8, .15)
model.add_transition(d8, m9, .7)

model.add_transition(d9, i9, .15)
model.add_transition(d1, m10, .85)

model.bake()

model.fit(sequences=X, min_iterations=5, algorithm='baum-welch')
`

Is it because I have attributed equal emission probability for each state for each AA?

**Comment by jmschrei** [comment]
I think that may be part of the problem.  You also shouldn't concatenate the two sequences together. I think hmmlearn does things as one long sequence, but in pomegranate you just need to pass in the list. So, X = [X1, X2].

**Comment by sztike93** [comment]
Yep, that was it, the list thing :+1:
