### ISSUE TITLE
TypeError: fit() got an unexpected keyword argument 'labels'

### ISSUE THREAD

**Issue by awanger** [jmschrei/pomegranate#236]
This is a similar issue to #228. According to the docs, the HMM class has a `labels` parameter that corresponds to each sequence.
My code:
```
model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts, ends)
model.fit(sequences=data, labels=data_labels) # Unexpected keyword error
```
Do the fit methods support `labels` at this time or is it because I'm passing an incorrectly formatted argument?

**Comment by jmschrei** [comment]
Have you pulled the most recent version from github using `git clone https://github.com/jmschrei/pomegranate`? I'm going to update pip soon, but I haven't recently.

**Comment by awanger** [comment]
That seems to have worked. thank you!
