### ISSUE TITLE
Supervised HMM with 3-axis accelerometer (labelled algorithm) - Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'

### ISSUE THREAD

**Issue by nuno-s** [jmschrei/pomegranate#238]
Hi guys, i'm trying using HMM to classify surface anomalies in 3-axis accelerometer data. As i have labelled data, i'm using the labelled algorithm, but ins't working. The algorithm output is a lot of warnings or exceptions like this:

> Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 3 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 1 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 3 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
ValueError: 0 is not in list

and at the end:

> Training improvement: 0.0
Total Training Improvement: 0.0

Know i will put my code:

So i start with a pandas dataframe:

```
df_aux = pd.DataFrame({
                        'ac_x': ac_x.tolist(),'ac_y': ac_y.tolist(),'ac_z': ac_z.tolist(),'a_speed': speed.tolist(),
                        'z_anomaly': anomaly_array.tolist()})
```

next, i calculate mean and variance for each state:

`
means_0, co_0, means_1, co_1, means_2, co_2, means_3, co_3, means_4, co_4 = calculate_means_covariance(df_aux)
`

after that, i split the data frame, in list with sequences inside

```

array_treino = np.array_split((df_aux.ix[:,0:4].values),120)
array_labels = np.array_split((df_aux.ix[:,4].values),120)
```

next i define the 4 states:
```

s0 = State(MultivariateGaussianDistribution(means_0,co_0), name="0")
s1 = State(MultivariateGaussianDistribution(means_1,co_1), name="1")
s2 = State(MultivariateGaussianDistribution(means_2,co_2), name="2")
s3 = State(MultivariateGaussianDistribution(means_3,co_3), name="3")
s4 = State(MultivariateGaussianDistribution(means_4,co_4), name="4")

```
model, all transitions, and bake
```

model = HiddenMarkovModel()
model.add_states(s0, s1, s2, s3, s4)
model.add_transition(model.start, s0, 0.5)
model.add_transition(model.start, s1, 0.125)
model.add_transition(model.start, s2, 0.125)
model.add_transition(model.start, s3, 0.125)
model.add_transition(model.start, s4, 0.125)
model.add_transition(model.start, model.end, 0.125)

model.add_transition(s0, s0, 0.5)
model.add_transition(s0, s1, 0.125)
model.add_transition(s0, s2, 0.125)
model.add_transition(s0, s3, 0.125)
model.add_transition(s0, s4, 0.125)
model.add_transition(s0, model.end, 0.125)

model.add_transition(s1, s0, 0.5)
model.add_transition(s1, s1, 0.125)
model.add_transition(s1, s2, 0.125)
model.add_transition(s1, s3, 0.125)
model.add_transition(s1, s4, 0.125)
model.add_transition(s1, model.end, 0.125)

model.add_transition(s2, s0, 0.5)
model.add_transition(s2, s1, 0.125)
model.add_transition(s2, s2, 0.125)
model.add_transition(s2, s3, 0.125)
model.add_transition(s2, s4, 0.125)
model.add_transition(s2, model.end, 0.125)

model.add_transition(s3, s0, 0.5)
model.add_transition(s3, s1, 0.125)
model.add_transition(s3, s2, 0.125)
model.add_transition(s3, s3, 0.125)
model.add_transition(s3, s4, 0.125)
model.add_transition(s3, model.end, 0.125)

model.add_transition(s4, s0, 0.5)
model.add_transition(s4, s1, 0.125)
model.add_transition(s4, s2, 0.125)
model.add_transition(s4, s3, 0.125)
model.add_transition(s4, s4, 0.125)
model.add_transition(s4, model.end, 0.125)

model.bake()
```

and, at the end, fit

`model.fit(array_treino, labels=array_labels, algorithm='labeled')`

this is a example of the labels list:

![image](https://cloud.githubusercontent.com/assets/26788135/24494440/29dfcd88-152a-11e7-8415-82955821fff7.png)

and this a example of the data list

![image 1](https://cloud.githubusercontent.com/assets/26788135/24494460/4046dde6-152a-11e7-9692-549a9bdeb4a7.png)

If i use other algorithm, like "viterbi", work "fine", with poor results, but fine...

`model.fit(array_treino,algorithm="viterbi")

Result:
> `Training improvement: 746455.622252694
Training improvement: 33416.13379384292
Training improvement: 14105.733888189163
Training improvement: 5814.4975590611575
Training improvement: 4338.522381727875
Training improvement: 5953.154418974795
Training improvement: 9865.428119672695
Training improvement: 36140.442382432404
Training improvement: inf
Training improvement: -inf
Total Training Improvement: 534637.6952102616

**Comment by jmschrei** [comment]
Can you email me a zip file containing your data and the code to reproduce this error? That would be the easiest way to track down any issues. I'm concerned about the "training improvement: inf" and "-inf", which may completely mess up the parameters.

**Comment by Divye02** [comment]
I am getting the same issue! Any updates on this?

**Comment by ewhitmire** [comment]
I had the same issue. It turns out that the `labels` parameter to the `fit` function should be a list of actual HMM states (not labels or indices). In your case, that would be something like `[s0, s0, s2, s1]`. This isn't really clear in the documentation and being able to reference the states by label makes more sense in my opinion.

**Comment by ssajj1212** [comment]
I also have a similar problem that I define a model to generate samples and use predict() to generate corresponding path as label for each sample. Then I have the similar error warning when I try to use from_sample() with labeled samples and it seems the training model is difficult to trace the original model. Is there any way to solve it?

**Comment by jmschrei** [comment]
Howdy @ssajj1212, can you post a minimally reproducing example with some sample data for me to take a look at? It'll be easier for me to track down bugs that way.

**Comment by jmschrei** [comment]
I'm going to mark this as resolved. Please re-open if you encounter a similar issue.
