### ISSUE TITLE
dense_transition_matrix not working for BayesianNetwork 

### ISSUE THREAD

**Issue by katbusch** [jmschrei/pomegranate#239]
For version 0.6.1, the function `dense_transition_matrix` is raising an exception when I run it on `BayesianNetwork` using a network trained with `BayesianNetwork.from_structure`

```
pomegranate/base.pyx in pomegranate.base.GraphModel.dense_transition_matrix (pomegranate/base.c:5463)()
AttributeError: 'pomegranate.BayesianNetwork.BayesianNetwork' object has no attribute 'out_edge_count'
```

**Comment by jmschrei** [comment]
If you want the structure of the Bayesian network you can use `model.structure`. I'm not sure that the structure of a Bayesian network conceptually has a transition matrix, as that would imply a transition from one node to another like you have in a HMM. I should probably get rid of the function for Bayes nets. What were you trying to do with it?

**Comment by katbusch** [comment]
I agree it doesn't make much sense for Bayes nets and should be removed.

I was actually trying to compute KL-divergence between two networks and playing around with the methods to see which would be useful.

**Comment by jmschrei** [comment]
Alright, I'll go ahead and remove that then. I think calculating KL divergence may be difficult if you didn't have the same structure. Can you calculate the KL divergence between a marginal distribution and a conditional one?
