### ISSUE TITLE
calculate distribution of a single variable

### ISSUE THREAD

**Issue by DataTerminatorX** [jmschrei/pomegranate#244]
In discrete bayesian network, I want to calculate the distribution of a single conditioned variable, is there a quick way or method to do this?

Say, a bayesian network is like `P(A,B,C)=P(A)*P(B)*P(C|A,B)`, now I want to calculate `P(C)`. Sure I can use `P(C=Ci)= sum_{Ai, Bi} P(A=Ai,B=Bi,C))`. I wonder is there an existing built-in method to do this?

**Comment by jmschrei** [comment]
Do you mean that you want to calculate the marginal of C, or that you want to calculate the distribution over C given some other values are set? Either way, you can use `model.predict_proba({})` where you feed in a dictionary of values that you do know. This method uses the sum-product algorithm to calculate all of the marginals given an arbitrary amount of fixed knowledge.

**Comment by DataTerminatorX** [comment]
Hi @jmschrei , I think it's the marginal of C that I really want. `model.predict_proba({})` seems to generate some marginal distributions but have no information of which variable the distribution belongs to, e.g. below is one result in 'monty-hall' problem. There are three distributions corresponding to three variables `monty` `guest` and `prize` , but the results didn't claim those variables
```
[ {
    "frozen" :false,
    "class" :"Distribution",
    "parameters" :[
        {
            "A" :0.6666666666666666,
            "C" :0.0,
            "B" :0.33333333333333337
        }
    ],
    "name" :"DiscreteDistribution"
}
 {
    "frozen" :false,
    "class" :"Distribution",
    "parameters" :[
        {
            "A" :0.0,
            "C" :0.6666666666666666,
            "B" :0.3333333333333333
        }
    ],
    "name" :"DiscreteDistribution"
}
 {
    "frozen" :false,
    "class" :"Distribution",
    "parameters" :[
        {
            "A" :0.0,
            "C" :0.0,
            "B" :1.0
        }
    ],
    "name" :"DiscreteDistribution"
}]
```

**Comment by jmschrei** [comment]
You can see the ordering of the variables by inspecting model.states. For Bayesian networks this should also correspond to the ordering of nodes/states as they were added to the model in the add_node/s method. Does that clarify it? I'm mulling over having predict_proba return dictionaries to make this more intuitive, but it would break with the other interfaces.

**Comment by DataTerminatorX** [comment]
Got it. So the order of the distributions generated by `predict_proba()` is exactly the same of `model.states`. 

Thx a lot.

**Comment by jmschrei** [comment]
I would prefer not to create an excessive amount of model-specific methods in order to keep the API clean. It may be worth it to put an optional `variable` argument to `predict_proba` though, that only returns the distribution of that variable.

**Comment by jmschrei** [comment]
Closing this for now, re-open if there is an issue.
