### ISSUE TITLE
Supervised HMM fit function returns zero improvements

### ISSUE THREAD

**Issue by hisarack** [jmschrei/pomegranate#246]
Excuse me, I trying to use some stock data to experiment supervised HMM learning with **labeled** algorithm. No matter how I changed normal distribution's  mean and variance, the fit function always returns zero improvements.

```python
s1 = State( NormalDistribution( 10.0, 50.0 ), name="buyable" )
s2 = State( NormalDistribution( 200.0, 50.0 ), name="sellable" )

model = HiddenMarkovModel()
model.add_states( [s1, s2] )

model.add_transition( model.start, s1, 1 )
model.add_transition( model.start, s2, 0 )
model.add_transition( s1, s1, 0.5 )
model.add_transition( s1, s2, 0.5 )
model.add_transition( s2, s1, 0.5 )
model.add_transition( s2, s2, 0.5 )
model.bake()

def fetch_stock_dataframe(company_name, start_datetime, end_datetime):
    start_timestamp = datetime.datetime.strptime(start_datetime, '%m/%d/%Y')
    end_timestamp = datetime.datetime.strptime(end_datetime, '%m/%d/%Y')
    df = web.DataReader([company_name], 'yahoo', start_timestamp, end_timestamp)
    return df

def generate_train_data_and_label(fetched_df, future_window_length):
    # calculate moving average
    adj_closed_s = fetched_df['Adj Close']['AAPL']
    moving_avg_s = adj_closed_s[::-1].rolling(window=future_window_length, center=False).mean()[::-1]
    result_df = pd.concat([adj_closed_s, moving_avg_s], axis=1).dropna()
    
    # mark the buyable if current adj close is lower than moving averge
    # otherwise, mark as not buyable.
    states = [s1, s2]
    result_df['label'] = result_df.apply(lambda x: model.states[int(x[0] < x[1])], axis=1)
    return result_df.ix[:,0].to_frame().values, result_df['label'].to_frame().values


fetched_df = fetch_stock_dataframe('AAPL', '1/1/2015', '5/1/2015')
train_data, train_label = generate_train_data_and_label(fetched_df, 30)
print json.loads(model.to_json())['states']
print json.loads(model.to_json())['edges']
improvement = model.fit(train_data, algorithm='labeled', labels=train_label)    
print improvement
print json.loads(model.to_json())['states']
print json.loads(model.to_json())['edges']
```

The output as follow:

> [{u'distribution': {u'frozen': False, u'class': u'Distribution', u'parameters': [10.0, 50.0], u'name': u'NormalDistribution'}, u'class': u'State', u'weight': 1.0, u'name': u'buyable'}, {u'distribution': {u'frozen': False, u'class': u'Distribution', u'parameters': [200.0, 50.0], u'name': u'NormalDistribution'}, u'class': u'State', u'weight': 1.0, u'name': u'sellable'}, {u'distribution': None, u'class': u'State', u'weight': 1.0, u'name': u'None-start'}, {u'distribution': None, u'class': u'State', u'weight': 1.0, u'name': u'None-end'}]
> [[0, 1, 0.5, 0.5, None], [0, 0, 0.5, 0.5, None], [2, 1, 0.0, 0, None], [2, 0, 1.0, 1, None], [1, 1, 0.5, 0.5, None], [1, 0, 0.5, 0.5, None]]
> Training improvement: 0.0
> Total Training Improvement: 0.0
> 0.0
> [{u'distribution': {u'frozen': False, u'class': u'Distribution', u'parameters': [10.0, 50.0], u'name': u'NormalDistribution'}, u'class': u'State', u'weight': 1.0, u'name': u'buyable'}, {u'distribution': {u'frozen': False, u'class': u'Distribution', u'parameters': [200.0, 50.0], u'name': u'NormalDistribution'}, u'class': u'State', u'weight': 1.0, u'name': u'sellable'}, {u'distribution': None, u'class': u'State', u'weight': 1.0, u'name': u'None-start'}, {u'distribution': None, u'class': u'State', u'weight': 1.0, u'name': u'None-end'}]
> [[0, 1, 0.5, 0.5, None], [0, 0, 0.5, 0.5, None], [2, 1, 0.0, 0, None], [2, 0, 1.0, 1, None], [1, 1, 0.5, 0.5, None], [1, 0, 0.5, 0.5, None]]

Thanks for any help or suggestion !!

**Comment by jmschrei** [comment]
Can you provide a complete working example including import statements? It'll be easiest for me to figure out what's up if I can run the script.  Make sure that you training data is a list of your sequences (even if you only have one, it should be a list of a single list/numpy array, and that the labels follow the same format.

**Comment by hisarack** [comment]
@jmschrei This is my complete working example

```python
from pomegranate import *
import numpy as np
import pandas as pd
import datetime
import pandas_datareader as web


s1 = State( NormalDistribution( 10.0, 50.0 ), name="buyable" )
s2 = State( NormalDistribution( 200.0, 50.0 ), name="sellable" )

model = HiddenMarkovModel()
model.add_states( [s1, s2] )

model.add_transition( model.start, s1, 1 )
model.add_transition( model.start, s2, 0 )
model.add_transition( s1, s1, 0.5 )
model.add_transition( s1, s2, 0.5 )
model.add_transition( s2, s1, 0.5 )
model.add_transition( s2, s2, 0.5 )
model.bake()

def fetch_stock_dataframe(company_name, start_datetime, end_datetime):
    start_timestamp = datetime.datetime.strptime(start_datetime, '%m/%d/%Y')
    end_timestamp = datetime.datetime.strptime(end_datetime, '%m/%d/%Y')
    df = web.DataReader([company_name], 'yahoo', start_timestamp, end_timestamp)
    return df

def generate_train_data_and_label(fetched_df, future_window_length):
    # calculate moving average
    adj_closed_s = fetched_df['Adj Close']['AAPL']
    moving_avg_s = adj_closed_s[::-1].rolling(window=future_window_length, center=False).mean()[::-1]
    result_df = pd.concat([adj_closed_s, moving_avg_s], axis=1).dropna()

    # mark the buyable if current adj close is lower than moving averge
    # otherwise, mark as not buyable.
    states = [s1, s2]
    result_df['label'] = result_df.apply(lambda x: model.states[int(x[0] < x[1])], axis=1)
    return result_df.ix[:,0].to_frame().values, result_df['label'].to_frame().values


fetched_df = fetch_stock_dataframe('AAPL', '1/1/2015', '5/1/2015')
train_data, train_label = generate_train_data_and_label(fetched_df, 30)
print json.loads(model.to_json())['states']
print json.loads(model.to_json())['edges']
improvement = model.fit(train_data, algorithm='labeled', labels=train_label)
print improvement
print json.loads(model.to_json())['states']
print json.loads(model.to_json())['edges']
```

This is my train_data for supervised HMM fitting

```python
[[ 104.704758]
 [ 101.755057]
 [ 101.764636]
...
 [ 122.587966]
 [ 121.049608]]
``` 

This is my train_label for supervised HMM fitting

```python
[[ {
    "distribution" : {
        "frozen" : false,
        "class" : "Distribution",
        "parameters" : [
            200.0,
            50.0
        ],
        "name" : "NormalDistribution"
    },
    "class" : "State",
    "weight" : 1.0,
    "name" : "sellable"
}].
...
[ {
    "distribution" : {
        "frozen" : false,
        "class" : "Distribution",
        "parameters" : [
            200.0,
            50.0
        ],
        "name" : "NormalDistribution"
    },
    "class" : "State",
    "weight" : 1.0,
    "name" : "sellable"
}]]
```

**Comment by hisarack** [comment]
Before I got the zero improvement problem, I encountered another problem about ValueError exception. The detailed error message as follow:

```
Traceback (most recent call last):
  File "hmm_stock_test.py", line 47, in <module>
    improvement = model.fit(train_data, algorithm='labeled', labels=train_label)
  File "pomegranate/hmm.pyx", line 2488, in pomegranate.hmm.HiddenMarkovModel.fit (pomegranate/hmm.c:29651)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Based on the error message, It looks like Python can't decide a single boolean value when input label is a list of lists.  So I modified the hmm.pyx line 2488.

```python
if labels:
    labels = numpy.array(labels)
```
to 

```python
if labels is None:
    labels = numpy.array(labels)
```

Please correct me if you find any mistake. Thank you!

**Comment by jmschrei** [comment]
It should probably be `if labels is not None`. The reason it doesn't play well is because it expects a -list- of sequences, not a numpy.ndarray. I assumed that you were training this model on a single sequence, and so made some modifications to your code:

L38: `return result_df.ix[:,0].to_frame().values[:,0], result_df['label'].to_frame().values[:,0]`
L44: `improvement = model.fit([train_data], algorithm='labeled', labels=[train_label])`

The main issue is that you had your input sequence be a list of lists, where each inner list only had a single element. Each inner list should be the full sequence. In this case, you'd have a list of one list comprised of the sequence you extract. The label should follow the same shape. When I make those changes, I get the following output:

```
Training improvement: 141.83538654
Training improvement: 0.0
Total Training Improvement: 141.83538654
141.83538654
[{u'distribution': {u'frozen': False, u'class': u'Distribution', u'parameters': [123.64985983333337, 1.8216382318035056], u'name': u'NormalDistribution'}, u'class': u'State', u'weight': 1.0, u'name': u'buyable'}, {u'distribution': {u'frozen': False, u'class': u'Distribution', u'parameters': [111.00765497142858, 6.6661259798460435], u'name': u'NormalDistribution'}, u'class': u'State', u'weight': 1.0, u'name': u'sellable'}, {u'distribution': None, u'class': u'State', u'weight': 1.0, u'name': u'None-start'}, {u'distribution': None, u'class': u'State', u'weight': 1.0, u'name': u'None-end'}]
[[0, 0, 0.8888888888888888, 0.5, None], [0, 1, 0.1111111111111111, 0.5, None], [2, 0, 1.0, 1, None], [2, 1, 0.0, 0, None], [1, 0, 0.05714285714285714, 0.5, None], [1, 1, 0.9428571428571428, 0.5, None]]
```

Let me know if this works for you!

**Comment by hisarack** [comment]
@jmschrei  After fix line 38 and 44. Using dataset from 2015/1/1 to 2015/5/1, 
I could get the simple result as the picture below.
The lower horizontal line means we could place the order for the stock. 
Otherwise, we could sell it or don't do anything.

![2017-04-25 10 54 11](https://cloud.githubusercontent.com/assets/1573475/25392235/b6638534-2a0a-11e7-968d-22fc43b1f67b.png)

I also try unsupervised learning with the same dataset. 
Compared with above results, Unsupervised learning gets better performance in some time range
( eg, 2017 January to April ). But, supervised learning could be better in 2015.

![2017-04-25 11 07 48](https://cloud.githubusercontent.com/assets/1573475/25392743/10a0df8c-2a0c-11e7-986b-04e2ce63ef4a.png)

Thanks for your help!! 
Pomegranate is great tool 👍

**Comment by jmschrei** [comment]
I'm glad that it worked out. Usually I've found that unsupervised learning is better unless you're 100% confident in your labels, and have a lot of data. You might want to use your labelled data to initialize the parameters of your model and then refine using unsupervised training. 

Let me know if you have any other questions!
