### ISSUE TITLE
Why is this sequence impossible?

### ISSUE THREAD

**Issue by himat** [jmschrei/pomegranate#247]
Can someone help me understand why this simple code isn't working?

I have an HMM with a 1D-Gaussian for each of 3 states. Then I just try to use predict to see how likely the input sequence is, but when I do this, I get an error saying "Warning: Sequence is impossible.
[-1, -1, -1]"

This is simulating a robot's head turning, so it can only pass from looking left to looking forward to looking right and backwards.

```
s_left = State( Distribution(NormalDistribution(1.0, .2)))
s_forward = State( Distribution(NormalDistribution(0, .2)))
s_right = State( Distribution(NormalDistribution(-1.0, .2)))

model = HiddenMarkovModel()
model.add_states(s_left, s_forward, s_right)
model.add_transition(model.start, s_left, 1.0/3)
model.add_transition(model.start, s_forward, 1.0/3)
model.add_transition(model.start, s_right, 1.0/3)

model.add_transition(s_left, s_left, 0.8)
model.add_transition(s_left, s_forward, 0.2)

model.add_transition(s_forward, s_forward, 0.7)
model.add_transition(s_forward, s_left, 0.15)
model.add_transition(s_forward, s_right, 0.15)

model.add_transition(s_right, s_right, 0.8)
model.add_transition(s_right, s_forward, 0.2)

model.bake()

path = model.predict([0.1, 0.1, 0.2])
print path
```

I would think it would give back the s_forward state for all 3.

**Comment by himat** [comment]
Never mind, it looks like I was looking at old HMM code examples.
After I changed `State( Distribution(NormalDistribution(1.0, .2)))` to `State(NormalDistribution(1.0, .2))`, it worked.

**Comment by jmschrei** [comment]
Do any of the examples in the pomegranate repository have that formulation (saying Distribution(NormalDistribution...))? I need to fix that if so, it's misleading.

**Comment by himat** [comment]
Yep: http://pomegranate.readthedocs.io/en/latest/HiddenMarkovModel.html#initialization

**Comment by jmschrei** [comment]
How embarrassing. I'll fix that up quickly. Thanks for pointing it out.
