### ISSUE TITLE
pandas compatibility 

### ISSUE THREAD

**Issue by elzurdo** [jmschrei/pomegranate#248]
@jmschrei et al.
Is there any chance to make wrappers to make pomegranate pandas friendly? 
I.e, I would like to feed dataframes and get some of the predictions in dataframes.

I am currently running on some scripts and look forward to your feedback (be gentle, please, I'm a newbie)

**Comment by jmschrei** [comment]
In general, pandas support is something I would like to add in. However, this will have to be a project taken on by a contributor as there's too much core stuff for me to reasonably get to. Thanks for your PR from a while ago!
