### ISSUE TITLE
HMM fit for list of Bio.Align.MultipleSeqAlignment

### ISSUE THREAD

**Issue by sztike93** [jmschrei/pomegranate#262]
Hi,

great lib, keep up with the good work, it really helps! If I want to fit (with Baum-Welch algorithm) the HMM model to a list of [Bio.Align.MultipleSeqAlignment,](http://biopython.org/DIST/docs/api/Bio.Align.MultipleSeqAlignment-class.html) _how do I need to transform the dataset_ in order to get the fit method working?  The documentation says:

> "An array of some sort (list, numpy.ndarray, tuple..) of sequences, where each sequence is a numpy array, which is 1 dimensional if the HMM is a one dimensional array, or multidimensional if the HMM supports multiple dimensions."

Each sequence is a list of characters, each multiple alignment is a list sequences and I have a bunch of multiple alignments, so it is a list of list of char list. 

Thanks for the answer in advance!

**Comment by jmschrei** [comment]
Howdy

I'm not sure exactly what the data format is for Bio.Align.MultipleSeqAlignment internally. To fit to univariate data (like biological sequences) you need to supply a list of lists of the format similar to the following:

```
X = [['A', 'C', 'G', 'C', 'T', 'T', 'G'....], ['A', 'A', 'C', 'G', 'T'...], ['T', 'G', 'T', 'C'....], ...] 
model.fit(X)
```

**Comment by sztike93** [comment]
Hi,

wow, that was quick! But what if I have multiple alignments? For example, a data instance looks like:
```
ACGT--TG
AACGT-GT
-ACGTTTT
```

Is the following representation okay?
```
X = [[['A', 'C', 'G', 'T', '-', '-', 'T','G'], ['A', 'A', 'C', 'G', 'T', '-', 'G', 'T'], ['-', 'A', 'C', 'G', 'T', 'T', 'T', 'T']], ...] 
model.fit(X)
```

**Comment by jmschrei** [comment]
I assume that you have multiple alignments done and you'd like to create a profile HMM from that. In that case you may not want to use the fitting function but create it by hand. Essentially, you'd want to take each column and count the probabilities of each character occuring at that position in the profile ignoring the inserts/deletions ('-' symbols). Your code should probably look something like the following:

```
X = numpy.array(what you currently have)

positions = []
for i in range(X.shape[1]):
    symbols = X[:,i][X[:,i] != '-']
    distribution = DiscreteDistribution.from_samples(symbols) 
    positions.append(distribution)
```

and then build your profile HMM from those distributions. I don't have built in code for a global alignment/local alignment HMM but I can point you to prior code I've written to set it up if you need.

**Comment by sztike93** [comment]
Well, this is what I would need to do: I have multiple sequence alignments and I have unaligned sequence groups. I would like to build a HMM (estimate transition and emission probabilities) using the multiple sequence alignments to produce from the groups of unaligned sequences a multiple sequence alignment. Eventually I have to compare the results given by the HMM with other methods producing multiple sequence alignments, e.g. GA. Is the fit method good for this or am I misunderstanding the whole point of HMMs?

**Comment by jmschrei** [comment]
It is fairly typical to build a profile HMM from a multiple sequence alignment. However, HMMs are general to any type of graph structure, whereas profile HMMs are a ~specific~ structure. Just passing a bunch of data in will produce a dense network that doesn't know anything about positions or insertions or deletions. If you have it, you should read chapter 5 of _Biological Sequence Analysis_ by Durbin, Eddy, Krogh, and Mitchison, specifically section 5.2. 

You can use pomegranate to build profile HMMs. Here is a simple example of manually making a profile HMM using yahmm, which is the precursor to pomegranate: https://github.com/jmschrei/yahmm/blob/master/examples/Global%20Sequence%20Alignment.ipynb

The commands should still be the same. You may want to transition over to using a for loop to build the structure one position at a time, but it should give you an idea on how to build it. You'd want to replace the distributions I manually specified with the ones learned from data in the way above.

**Comment by sztike93** [comment]
Thanks for the great help! :)

**Comment by jmschrei** [comment]
I'm going to close this issue. Reopen if there are problems.

**Comment by sztike93** [comment]
Hey there,

quick question regarding this topic. The delete states are silent, but that, of course, means that I have to add a gap symbol ('-') to the alphabet of amino acids and forcing the emission of the delete states to be concentrated on this symbol. In the yahmm model construction example the emission of delete states is None, whereas I need it to be:   

AA = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']
delete_states = np.array([])
for i in range(1, delete_state_no):
    deleted_aa = {aa: 0 for aa in AA}
    deleted_aa["."] = 1
    delete = DiscreteDistribution(deleted_aa)
    delete_states = np.append(delete_states, State(delete, name='d' + str(i)))

I initialize the emission probabilities of the match/insert states with 20 probs, the delete states in the way above and I get when training (with baum-welch) with non-gapped sequences training improvement of NaN. Why?

**Comment by jmschrei** [comment]
You don't want to set the silent states to have an emission other than None. The way you'd use the gaps is that when calculating the match state distributions you would ignore the symbol '-'. You shouldn't be feeding the '-' symbol directly into the HMM at any point, either fitting or prediction. See my snippet of code above on an example of what you could do.
