### ISSUE TITLE
Model the weather problem in pomegranate (HMM)

### ISSUE THREAD

**Issue by prabin525** [jmschrei/pomegranate#266]
I am a fairly beginner to pomegranate. Suppose we had a problem as  that we were locked in a room for several days and were asked about the weather outside. The only piece of evidence we have is whether the person who comes into the room carrying our daily meal is carrying an umbrella or not. And let us suppose the following probabilities: 
                 Probability of Umbrella
Sunny -> 0.1
Rainy -> 0.8
Foggy-> 0.3

and the transition probabilities are
                                                     Tomorrow's Weather                                      
                                                Sunny          Rainy          Foggy
                                 Sunny         0.8             0.05            0.15
Today's Weather      Rainy        0.2             0.6              0.2
                                  Foggy        0.2             0.3              0.5

How can i model this in pomegranate? What will be the states and what will be the probability distributions.

**Comment by jmschrei** [comment]
This sounds like it would be a hidden Markov model. The hidden state is the actual weather outside, and the observed state is the presence of an umbrella. A missing piece of information is the starting probabilities for the weather. I'm going to assume it's uniform for now. You can create this in pomegranate using the following code:

```python
from pomegranate import *

sunny = State( DiscreteDistribution({'umbrella': 0.1, 'not': 0.9}), name='sunny' )
rainy = State( DiscreteDistribution({'umbrella': 0.8, 'not': 0.2}), name='rainy' )
foggy = State( DiscreteDistribution({'umbrella': 0.3, 'not': 0.7}), name='foggy' )

model = HiddenMarkovModel()
model.add_states(sunny, rainy, foggy)

model.add_transition(model.start, sunny, 0.33)
model.add_transition(model.start, rainy, 0.33)
model.add_transition(model.start, foggy, 0.34)

model.add_transition(sunny, sunny, 0.8)
model.add_transition(sunny, rainy, 0.05)
model.add_transition(sunny, foggy, 0.15)

model.add_transition(rainy, sunny, 0,2)
model.add_transition(rainy, rainy, 0.6)
model.add_transition(rainy, foggy, 0.2)

model.add_transition(foggy, sunny, 0.2)
model.add_transition(foggy, rainy, 0.3)
model.add_transition(foggy, foggy, 0.5)
model.bake()
```

Let me know if you have any other questions.
