### ISSUE TITLE
AttributeError: 'pomegranate.hmm.HiddenMarkovModel' object has no attribute 'train'

### ISSUE THREAD

**Issue by prabin525** [jmschrei/pomegranate#268]
for word,length in words.items():
	print("Training for "+ word)

	#create an HMM model for the word
	model = HiddenMarkovModel(word)

	states = [ ]
	#Multivariate normal distribution
	for i in range(0,length):
		distribution =[NormalDistribution(0,1) for x in range(0, 26)]
		states.append(State(MultivariateDistribution(distribution)))

	#Add transition
	model.add_states(states)
	model.add_transition(model.start, states[0],1.0)
	model.add_transition(states[-1],model.end,1.0)
	#General Left to RIght Model
	prev = None
	for current, next in zip(states, states[1:]):
		model.add_transition(current,current,0.4)
		model.add_transition(current,next,0.3)
		if prev:
			model.add_transition(prev,next,0.3)
		prev = current
	model.add_transition(states[-1],states[-1],0.5)
	model.bake()
	
	iter_times = 20
	for iter_i in range(1,iter_times):
		for i in range(0, SAMPLES_COUNT-1):
			model.train([mfcc_coff[word][i]])
	word_models[word] = model

	print(word_models[word])

I have done something like this but it gives me the error that  AttributeError: 'pomegranate.hmm.HiddenMarkovModel' object has no attribute 'train'

**Comment by jmschrei** [comment]
Use `fit`, not `train`. `train` was deprecated a long time ago.
