### ISSUE TITLE
TypeError: Can only concatenate tuple (not "str") to tuple

### ISSUE THREAD

**Issue by tkanchin** [jmschrei/pomegranate#271]
Hello,

Thank you for writing this Wonderful Library. Thus far, I think it is the best Bayesian Learning Library.

Today, I was training a Bayesian Network using the below code:
`model = BayesianNetwork.from_samples(train_data.as_matrix(),state_names=state_names, constraint_graph=graph_acyclic, max_parents=3, algorithm='exact')
` and I got the following error:

`TypeError: Can only concatenate tuple (not "str") to tuple`

I quickly did some debugging about this. Please update the line 1100 BayesianNetwork.pyx from
`for parents, children in constraint_graph.edges():
	parent_sets[children] += parents`

to

`for parents, children in constraint_graph.edges():
	parent_sets[children] += tuple(parents)`

Thanks,
Teja

**Comment by jmschrei** [comment]
Thanks for your kind words. I have been extremely busy recently, so apologies for taking so long to get back to you. I'm not sure that changing it to `tuple(parents)` is exactly what you want, as `'abcd'` becomes `('a', 'b', 'c', 'd')` when what you want is `('abcd',)`. I would suggest for now to make your constraint graph using only tuples, even if that tuple only has a single element.

**Comment by jmschrei** [comment]
Closing for now. Re-open if it's not resolved by passing in the appropriate tuples.
