### ISSUE TITLE
pip install fails on pomegranate-0.7.3

### ISSUE THREAD

**Issue by xkortex** [jmschrei/pomegranate#278]
Installing v 0.7.3 via pip seems problematic. The short of it is:

```
...
    x86_64-linux-gnu-gcc: error: pomegranate/fsm.c: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

<details>

pip install --upgrade numpy
Collecting numpy
  Downloading numpy-1.13.0-cp35-cp35m-manylinux1_x86_64.whl (16.9MB)
    100% |████████████████████████████████| 16.9MB 109kB/s 
Installing collected packages: numpy
  Found existing installation: numpy 1.12.0
    Uninstalling numpy-1.12.0:
      Successfully uninstalled numpy-1.12.0
Successfully installed numpy-1.13.0
(ml) ➜ pip install pomegranate
Collecting pomegranate
  Using cached pomegranate-0.7.3.tar.gz
Requirement already satisfied: numpy>=1.8.0 in /home/mike/ve/ml/lib/python3.5/site-packages (from pomegranate)
Collecting joblib>=0.9.0b4 (from pomegranate)
  Using cached joblib-0.11-py2.py3-none-any.whl
Requirement already satisfied: networkx>=1.8.1 in /home/mike/ve/ml/lib/python3.5/site-packages (from pomegranate)
Requirement already satisfied: scipy>=0.17.0 in /home/mike/ve/ml/lib/python3.5/site-packages (from pomegranate)
Requirement already satisfied: decorator>=3.4.0 in /home/mike/ve/ml/lib/python3.5/site-packages (from networkx>=1.8.1->pomegranate)
Building wheels for collected packages: pomegranate
  Running setup.py bdist_wheel for pomegranate ... error
  Complete output from command /home/mike/ve/ml/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kjrpfg37/pomegranate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpsuj26fy6pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/pomegranate
  copying pomegranate/__init__.py -> build/lib.linux-x86_64-3.5/pomegranate
  running build_ext
  building 'pomegranate.base' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/pomegranate
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/mike/ve/ml/include/python3.5m -I/home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include -c pomegranate/base.c -o build/temp.linux-x86_64-3.5/pomegranate/base.o
  In file included from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                   from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pomegranate/base.c:444:
  /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pomegranate/base.o -o build/lib.linux-x86_64-3.5/pomegranate/base.cpython-35m-x86_64-linux-gnu.so
  building 'pomegranate.BayesianNetwork' extension
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/mike/ve/ml/include/python3.5m -I/home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include -c pomegranate/BayesianNetwork.c -o build/temp.linux-x86_64-3.5/pomegranate/BayesianNetwork.o
  In file included from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                   from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pomegranate/BayesianNetwork.c:444:
  /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pomegranate/BayesianNetwork.o -o build/lib.linux-x86_64-3.5/pomegranate/BayesianNetwork.cpython-35m-x86_64-linux-gnu.so
  building 'pomegranate.FactorGraph' extension
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/mike/ve/ml/include/python3.5m -I/home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include -c pomegranate/FactorGraph.c -o build/temp.linux-x86_64-3.5/pomegranate/FactorGraph.o
  In file included from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                   from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pomegranate/FactorGraph.c:444:
  /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pomegranate/FactorGraph.o -o build/lib.linux-x86_64-3.5/pomegranate/FactorGraph.cpython-35m-x86_64-linux-gnu.so
  building 'pomegranate.distributions' extension
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/mike/ve/ml/include/python3.5m -I/home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include -c pomegranate/distributions.c -o build/temp.linux-x86_64-3.5/pomegranate/distributions.o
  In file included from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                   from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                   from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pomegranate/distributions.c:444:
  /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it by " \
    ^
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pomegranate/distributions.o -o build/lib.linux-x86_64-3.5/pomegranate/distributions.cpython-35m-x86_64-linux-gnu.so
  building 'pomegranate.fsm' extension
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/mike/ve/ml/include/python3.5m -I/home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include -c pomegranate/fsm.c -o build/temp.linux-x86_64-3.5/pomegranate/fsm.o
  x86_64-linux-gnu-gcc: error: pomegranate/fsm.c: No such file or directory
  x86_64-linux-gnu-gcc: fatal error: no input files
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pomegranate
  Running setup.py clean for pomegranate
Failed to build pomegranate
Installing collected packages: joblib, pomegranate
  Running setup.py install for pomegranate ... error
    Complete output from command /home/mike/ve/ml/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kjrpfg37/pomegranate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ok07d_5y-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/mike/ve/ml/include/site/python3.5/pomegranate:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/pomegranate
    copying pomegranate/__init__.py -> build/lib.linux-x86_64-3.5/pomegranate
    running build_ext
    building 'pomegranate.base' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/pomegranate
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/mike/ve/ml/include/python3.5m -I/home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include -c pomegranate/base.c -o build/temp.linux-x86_64-3.5/pomegranate/base.o
    In file included from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                     from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pomegranate/base.c:444:
    /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pomegranate/base.o -o build/lib.linux-x86_64-3.5/pomegranate/base.cpython-35m-x86_64-linux-gnu.so
    building 'pomegranate.BayesianNetwork' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/mike/ve/ml/include/python3.5m -I/home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include -c pomegranate/BayesianNetwork.c -o build/temp.linux-x86_64-3.5/pomegranate/BayesianNetwork.o
    In file included from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                     from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pomegranate/BayesianNetwork.c:444:
    /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pomegranate/BayesianNetwork.o -o build/lib.linux-x86_64-3.5/pomegranate/BayesianNetwork.cpython-35m-x86_64-linux-gnu.so
    building 'pomegranate.FactorGraph' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/mike/ve/ml/include/python3.5m -I/home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include -c pomegranate/FactorGraph.c -o build/temp.linux-x86_64-3.5/pomegranate/FactorGraph.o
    In file included from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                     from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pomegranate/FactorGraph.c:444:
    /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pomegranate/FactorGraph.o -o build/lib.linux-x86_64-3.5/pomegranate/FactorGraph.cpython-35m-x86_64-linux-gnu.so
    building 'pomegranate.distributions' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/mike/ve/ml/include/python3.5m -I/home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include -c pomegranate/distributions.c -o build/temp.linux-x86_64-3.5/pomegranate/distributions.o
    In file included from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                     from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pomegranate/distributions.c:444:
    /home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pomegranate/distributions.o -o build/lib.linux-x86_64-3.5/pomegranate/distributions.cpython-35m-x86_64-linux-gnu.so
    building 'pomegranate.fsm' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/mike/ve/ml/include/python3.5m -I/home/mike/ve/ml/lib/python3.5/site-packages/numpy/core/include -c pomegranate/fsm.c -o build/temp.linux-x86_64-3.5/pomegranate/fsm.o
    x86_64-linux-gnu-gcc: error: pomegranate/fsm.c: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/mike/ve/ml/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kjrpfg37/pomegranate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ok07d_5y-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/mike/ve/ml/include/site/python3.5/pomegranate" failed with error code 1 in /tmp/pip-build-kjrpfg37/pomegranate/

</details>

0.7.0. 0.7.1, and 0.7.2 work.

Let me know if you need any other details.

**Comment by jmschrei** [comment]
I think the problem lies in that I removed fsm's in 7.3, so if you have older files somewhere that pip can read them it might cause an error. Try going to your site-packages folder and delete the pomegranate folders and egg files and using pip again.

**Comment by jmschrei** [comment]
This is what I get when I try on Ubuntu:

```
jmschr@ubuntu:~/Desktop/pomegranate$ pip install pomegranate
Collecting pomegranate
  Downloading pomegranate-0.7.3.tar.gz (7.5MB)
    100% |████████████████████████████████| 7.5MB 40kB/s 
Requirement already satisfied: numpy>=1.8.0 in /home/jmschr/anaconda2/lib/python2.7/site-packages (from pomegranate)
Requirement already satisfied: joblib>=0.9.0b4 in /home/jmschr/anaconda2/lib/python2.7/site-packages (from pomegranate)
Requirement already satisfied: networkx>=1.8.1 in /home/jmschr/anaconda2/lib/python2.7/site-packages (from pomegranate)
Requirement already satisfied: scipy>=0.17.0 in /home/jmschr/anaconda2/lib/python2.7/site-packages (from pomegranate)
Requirement already satisfied: decorator>=3.4.0 in /home/jmschr/anaconda2/lib/python2.7/site-packages (from networkx>=1.8.1->pomegranate)
Building wheels for collected packages: pomegranate
  Running setup.py bdist_wheel for pomegranate ... done
  Stored in directory: /home/jmschr/.cache/pip/wheels/e7/32/98/8b89b0775c143e2520ac966981c0382c77c45723caf0cccf6a
Successfully built pomegranate
Installing collected packages: pomegranate
Successfully installed pomegranate-0.7.3
```

This is when I try to install on Windows:

```
C:\Users\Jacob>pip install pomegranate
Collecting pomegranate
  Downloading pomegranate-0.7.3-cp27-cp27m-win_amd64.whl (1.3MB)
    100% |################################| 1.3MB 123kB/s
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.0 in c:\anaconda\lib\site-packages (from pomegranate)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.17.0 in c:\anaconda\lib\site-packages (from pomegranate)
Requirement already satisfied (use --upgrade to upgrade): networkx>=1.8.1 in c:\anaconda\lib\site-packages (from pomegranate)
Requirement already satisfied (use --upgrade to upgrade): joblib>=0.9.0b4 in c:\anaconda\lib\site-packages (from pomegranate)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in c:\anaconda\lib\site-packages (from networkx>=1.8.1->pomegranate)
Installing collected packages: pomegranate
Successfully installed pomegranate-0.7.3
```

**Comment by xkortex** [comment]
This was on my first attempt at installing pomegranate. Also occurred on a fresh virtualenv. Also I'm not using anaconda, perhaps anaconda is providing some dependency?

**Comment by jmschrei** [comment]
I removed those references to fsms and pushed to changes. Can you try installing again and let me know what happens?

**Comment by jmschrei** [comment]
I'm going to assume this is resolved. Re-open if not the case.

**Comment by CermakM** [comment]
I faced this issue with `0.7.3`, when bisecting through the earlier versions, I noticed that they install `cython` as dependency, make sure that you have it installed before trying to install `0.7.3`
