### ISSUE TITLE
Can't use pomegranate 0.7.4

### ISSUE THREAD

**Issue by katbusch** [jmschrei/pomegranate#282]
I'm on Mac OS 10.12.4 and can't run pomegranate 0.7.4.  I don't get this error for pomegranate 0.7.3

I ran
```shell
mkvirtualenv pom_test
pip install numpy
pip install pomegranate
python --version
Python 2.7.10
```

Then when I run `import pomegranate` I see these errors:
```
In [1]: import pomegranate
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f115d95d8f94> in <module>()
----> 1 import pomegranate

/Users/kat/.virtualenvs/pom_test/lib/python2.7/site-packages/pomegranate/__init__.py in <module>()
     15 from .NaiveBayes import NaiveBayes
     16 from .BayesClassifier import BayesClassifier
---> 17 from .MarkovChain import MarkovChain
     18 from .hmm import HiddenMarkovModel
     19 from .BayesianNetwork import BayesianNetwork

ImportError: dlopen(/Users/kat/.virtualenvs/pom_test/lib/python2.7/site-packages/pomegranate/MarkovChain.so, 2): no suitable image found.  Did find:
	/Users/kat/.virtualenvs/pom_test/lib/python2.7/site-packages/pomegranate/MarkovChain.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/kat/.virtualenvs/pom_test/lib/python2.7/site-packages/pomegranate/MarkovChain.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by jmschrei** [comment]
That's disappointing. Can you try wiping all mentions of pomegranate from your computer and then reinstalling using pip? Basically remove all pomegranate files from your site-packages folder in your python distribution. Let me know if that helps.

**Comment by jmschrei** [comment]
I just tried it out on my Mac and it seemed to work:

```
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pomegranate
>>> pomegranate.__version__
'0.7.4'
```

**Comment by jmschrei** [comment]
Has this been resolved?

**Comment by katbusch** [comment]
Nope.  Although I don't get the error with python3, and I notice you're using python3.  Are you able to reproduce with python 2?

**Comment by jmschrei** [comment]
I get a separate issue when I try to use a python2.7 virtualenv, actually. I'm not very familiar with macs so maybe someone can point out where I went wrong:

```>>> import pomegranate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jmschreiber/anaconda/envs/py27/lib/python2.7/site-packages/pomegranate/__init__.py", line 17, in <module>
    from .MarkovChain import MarkovChain
ImportError: dlopen(/Users/jmschreiber/anaconda/envs/py27/lib/python2.7/site-packages/pomegranate/MarkovChain.so, 2): no suitable image found.  Did find:
	/Users/jmschreiber/anaconda/envs/py27/lib/python2.7/site-packages/pomegranate/MarkovChain.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/jmschreiber/anaconda/envs/py27/lib/python2.7/site-packages/pomegranate/MarkovChain.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

Is it feasible for you to clone the repository and install from source? Or at least can you try and let me know if that works for you (even if that solution wouldn't work more generally?)

**Comment by katbusch** [comment]
That looks like the same issue!

**Comment by jmschrei** [comment]
Oh, whoops. I must have been conflating this issue with someone else's, I had remembered something about the fsm file. I'll look into it more, but essentially from what I've found the issue is that it's compiling thinking that it's Ubuntu when it's not. This is likely an issue with how I'm building the wheels, but I'm not positive yet. @ewhitmire do you have any insight into this?

**Comment by ewhitmire** [comment]
We aren't building wheels for OS X right now, so it isn't a wheel issue. I just downloaded the source from pypi and it has .so files in it. The sdist was probably prepared on Linux. As a quick fix, building from the GitHub source or just deleting the .so files should work.

My best guess is that https://github.com/jmschrei/pomegranate/commit/7a960a582b301dfea1e45afe11fcf095df4311c6 is the commit that broke things. Why was that needed? I think the behavior of `package_data` changed in 3.1 and we may need to be more specific about which files to include/exclude.

**Comment by katbusch** [comment]
Maybe @nlgranger knows?

**Comment by ivanov** [comment]
I came here to report the same issue

> As a quick fix, building from the GitHub source or just deleting the .so files should work.

confirming that this worked.

**Comment by nlgranger** [comment]
ACK. I'm going to look into it.

**Comment by nlgranger** [comment]
So if I understood correctly, the sdist package which is generated on linux contains .so files. And when OSX users install the package, these files don't get regenerated?
I have just submitted a PR to include only source files in sdist (and .c files to avoid the need for cython).

@ewhitmire FYI the modification is meant to allow subclassing Model outside of pomegranate.

**Comment by ewhitmire** [comment]
That's correct. 

I've also opened #293 to track moving OS X to wheels. Having the binary wheels on pip would have avoided this issue.
