### ISSUE TITLE
Generating HMM with end state from samples?

### ISSUE THREAD

**Issue by nachtm** [jmschrei/pomegranate#285]
First of all, this repo looks great! 

I'm trying to generate HMMs with categorical distributions from sequences of actions, which seems to be possible through `HiddenMarkovModel.from_samples()`. However, in my case I'm also interested in seeing which states tend to be the last state in the sequence. 

It looks like using `HiddenMarkovModel.from_samples()` gives a model with no probability of transitioning into the end state. Is there any way to make this happen?

Thanks!

**Comment by jmschrei** [comment]
Howdy @nachtm, I don't currently support learning the end state because the `from_samples` method isn't well suited to learning a structured model (other than just dense). I suppose that learning the end probabilities for all states wouldn't be too difficult, particularly for a dense model. It shouldn't be too hard to add in. All you'd have to do is modify this line https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L3396 to optionally take in the end transitions like specified here: https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L3159. These end transitions would probably be uniform to start off with. I have a lot of my plate so I may not be able to make this (simple) change, but would be more than happy to review a PR from you on it. You'd probably be adding in a `end_state = False` parameter, where when set to true it passes the uniform `ends` vector in to the `from_matrix` method.

**Comment by nachtm** [comment]
Hi @jmschrei,

Thanks for the advice. I've done as you mentioned, and it seems to almost work, except for some reason only one state seems to be getting hooked into the end state:

```
>>> a = np.array([1,2,1,2,1,2,1])
>>> b = np.array([4,3,4,3,4,3,4])
>>> c = np.array([2,1,2,1,2,1,2])
>>> d = np.array([3,4,3,4,3,4,3])
>>> model = p.HiddenMarkovModel.from_samples(p.DiscreteDistribution, 2, [a,b,c,d],end_state=True)
>>> model
{
    "end" : {
        "distribution" : null,
        "class" : "State",
        "weight" : 1.0,
        "name" : "None-end"
    },
    "name" : "None",
    "distribution ties" : [],
    "silent_index" : 2,
    "end_index" : 3,
    "states" : [
        {
            "distribution" : {
                "frozen" : false,
                "class" : "Distribution",
                "parameters" : [
                    {
                        "1" : 0.4999999999989453,
                        "3" : 1.0547299793776935e-12,
                        "2" : 0.4999999999989453,
                        "4" : 1.054729979377701e-12
                    }
                ],
                "name" : "DiscreteDistribution"
            },
            "class" : "State",
            "weight" : 1.0,
            "name" : "s0"
        },
        {
            "distribution" : {
                "frozen" : false,
                "class" : "Distribution",
                "parameters" : [
                    {
                        "1" : 0.07039538367599431,
                        "3" : 0.42960461632400565,
                        "2" : 0.07039538367599431,
                        "4" : 0.42960461632400565
                    }
                ],
                "name" : "DiscreteDistribution"
            },
            "class" : "State",
            "weight" : 1.0,
            "name" : "s1"
        },
        {
            "distribution" : null,
            "class" : "State",
            "weight" : 1.0,
            "name" : "None-start"
        },
        {
            "distribution" : null,
            "class" : "State",
            "weight" : 1.0,
            "name" : "None-end"
        }
    ],
    "start" : {
        "distribution" : null,
        "class" : "State",
        "weight" : 1.0,
        "name" : "None-start"
    },
    "edges" : [
        [
            1,
            1,
            0.7545116478144211,
            0.5,
            null
        ],
        [
            1,
            3,
            0.24548835218557888,
            0.5,
            null
        ],
        [
            1,
            0,
            1.763746073346767e-21,
            0.5,
            null
        ],
        [
            0,
            1,
            0.1708501175656523,
            0.5,
            null
        ],
        [
            0,
            0,
            0.8291498824343477,
            0.5,
            null
        ],
        [
            2,
            1,
            0.5000093561877388,
            0.5,
            null
        ],
        [
            2,
            0,
            0.49999064381226116,
            0.5,
            null
        ]
    ],
    "class" : "HiddenMarkovModel",
    "start_index" : 2
}
>>> 
```
As you can see, state 0 is largely responsible for emitting 1 and 2, yet has no probability of transitioning to the terminal state. I can confirm that in this case `[0.5, 0.5]` is getting passed in to `from_matrix()` as `ends`. Do you have any idea what's going on? Is the best thing for me to do open a pull request so you can take a look at the diff, or would you prefer to troubleshoot a different way?

**Comment by jmschrei** [comment]
If you could open a PR with your modifications to the HMM code that would be great.

**Comment by jmschrei** [comment]
Your PR looks correct. Can you print `model.dense_transition_matrix()`? It would be easier for me to see what's going on.

**Comment by jmschrei** [comment]
Great! If you can add in one or two unit tests checking to make sure your PR works we can close both of these.

**Comment by nachtm** [comment]
I just added some unit tests. They passed on my local machine so assuming the build passes on GitHub I think we're good to go!
