### ISSUE TITLE
Errors in PyData tutorial 

### ISSUE THREAD

**Issue by orokanasaru** [jmschrei/pomegranate#286]
Similar to #283, the tutorial at https://github.com/jmschrei/pomegranate/blob/master/tutorials/PyData_2016_Chicago_Tutorial.ipynb can't be run in the current version of pomegranate.

**Comment by jmschrei** [comment]
Thanks for letting me know. I'm going to remove it soon-- it was the basis for tutorial_0, kept around because I referenced it at PyData Chicago.
