### ISSUE TITLE
error in opening DC Hydraulic Flocculation Solution.ipynb 

### ISSUE THREAD

**Issue by Cynoc** [jmschrei/pomegranate#290]
trying to open DC Hydraulic Flocculation Solution.ipynb but is giving me this error:
Unreadable Notebook: C:\Users\cbb67\Documents\GitHub\CEE4540-DC-Solutions\DC Hydraulic Flocculation Solution.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',). how do i fix this

**Comment by jmschrei** [comment]
I have no idea what that notebook is. Where did you find it?

**Comment by Cynoc** [comment]
sorry this is the wrong place

**Comment by jmschrei** [comment]
No problem, good luck!
