### ISSUE TITLE
Trouble installing Pomegranate on Python 3.6

### ISSUE THREAD

**Issue by EricSchles** [jmschrei/pomegranate#295]
In order to install Pomegranate on Python 3.6 I needed:

https://github.com/jmschrei/pomegranate/issues/114
and 
https://github.com/jmschrei/pomegranate/issues/215

Can this be reflected in the documentation somewhere?

**Comment by jmschrei** [comment]
Howdy. I just updated the ReadMe. Do you think that text is satisfactory?

**Comment by jmschrei** [comment]
Re-open if you have further suggestions!
