### ISSUE TITLE
AttributeError: 'pomegranate.distributions.NormalDistribution' object has no attribute 'probability'

### ISSUE THREAD

**Issue by cpoptic** [jmschrei/pomegranate#298]
This error is directly from Tutorial_0_pomegranate ipynb file from the Pomegranate tutorial folder.
I'm running this in a Jupyter notebook on Windows 10.

The cells prior to cell #5 execute without any issue.
Cell #5 contains the code

`x = numpy.arange(-3.5, 3.5, 0.1)
y = a.probability(x)`

and when I execute it on a Python 3 environment, it gives the error:  

> AttributeError: 'pomegranate.distributions.NormalDistribution' object has no attribute 'probability'

**Comment by jmschrei** [comment]
Howdy. Thanks for raising the error. What version of pomegranate are you using? `conda install pomegranate` seems stuck on 0.7.3. You should upgrade to 0.7.7 and try again, using either `pip install --upgrade pomegranate` or cloning the repo and installing from source.
