### ISSUE TITLE
Have distributions take in other distributions as parameters

### ISSUE THREAD

**Issue by jmschrei** [jmschrei/pomegranate#3]
Instead of taking in constants, support the ability to take in distributions as parameters, such as:

```
NormalDistribution( NormalDistribution( 4, 2 ), LognormalDistribution( 5, 2 ) )
```

This will be the core of the new Bayesian stuff added in.

**Comment by shpigi** [comment]
Have you seen [pymc](https://github.com/pymc-devs/pymc)?

**Comment by jmschrei** [comment]
I have seen pymc! It's an awesome package that I won't be able to compete with. However, it's also a bit uncertain how I would be able to use that as the backend for my distributions package. It may be possible, but a significant undertaking.

**Comment by jmschrei** [comment]
I'm going to shelve this for now. I may return to it if there is enough of a use case for it.
