### ISSUE TITLE
How to dump models?

### ISSUE THREAD

**Issue by prabin525** [jmschrei/pomegranate#307]
I want to be able to export a model and load it later so that i don't have to train it every time. How can it be done?

**Comment by jmschrei** [comment]
Every model should have a working `.to_json()` and corresponding `.from_json()` method, where `.to_json()` returns the model in a string format, and `from_json()` takes in either a string or a filename. Check out the documentation for them either on the API references online, or by calling `help(BayesianNetwork.from_json)` (for Bayesian networks, as an example).

**Comment by fengyeyou** [comment]
hi, prabin525 , canyou do this work?
network2 = BayesianNetwork.from_json(network.to_json())
