### ISSUE TITLE
Error in `os` under Python3.5

### ISSUE THREAD

**Issue by genos** [jmschrei/pomegranate#31]
It looks like `pomegranate` is not compatible with Python3.5's `os.environ`:

```python
>>> import pomegranate as pom
...
    elif os.name == 'posix':
-->       if os.environ.has_key('CFLAGS'):
...
AttributeError: '_Environ' object has no attribute 'has_key'
```

**Comment by genos** [comment]
Apologies! I encountered this error using an out of date version. Closing.

**Comment by jmschrei** [comment]
Thanks for reporting. Let me know if you find any other bugs, or having any other suggestions for improvements.
