### ISSUE TITLE
ImportError: cannot import name 'GeneralMixtureModel'

### ISSUE THREAD

**Issue by podorskaja** [jmschrei/pomegranate#315]
I seem to be able to successfully install pomegrate `pip install pomegranate --no-cache-dir`

```
Collecting pomegranate
  Downloading pomegranate-0.7.7.tar.gz (2.2MB)
    100% |████████████████████████████████| 2.2MB 12.8MB/s ta 0:00:01
Requirement already satisfied: numpy>=1.8.0 in /Users/dariapodorskaja/anaconda/lib/python3.6/site-packages (from pomegranate)
Requirement already satisfied: joblib>=0.9.0b4 in /Users/dariapodorskaja/anaconda/lib/python3.6/site-packages/joblib-0.11-py3.6.egg (from pomegranate)
Requirement already satisfied: networkx>=1.8.1 in /Users/dariapodorskaja/anaconda/lib/python3.6/site-packages (from pomegranate)
Requirement already satisfied: scipy>=0.17.0 in /Users/dariapodorskaja/anaconda/lib/python3.6/site-packages (from pomegranate)
Requirement already satisfied: decorator>=3.4.0 in /Users/dariapodorskaja/anaconda/lib/python3.6/site-packages (from networkx>=1.8.1->pomegranate)
Installing collected packages: pomegranate
  Running setup.py install for pomegranate ... done
Successfully installed pomegranate-0.7.7
```

But when I do `from pomegranate import *` I get

`ImportError: cannot import name 'GeneralMixtureModel'`

I uninstalled every .egg and every .whl related to pomegranate from my mac before doing no-cache-dir. I also have recommended numpy version. 

Any thoughts?

**Comment by jmschrei** [comment]
I started suddenly getting these errors too and I don't know why. I didn't change anything related to the compilation process to my knowledge.

**Comment by jmschrei** [comment]
@kwmsmith do you know if anything changed recently with the cython compilation process?

**Comment by jmschrei** [comment]
It looks like the issue has to do with the gfortran library: https://github.com/ContinuumIO/anaconda-issues/issues/445

I'll continue to look into it...

**Comment by podorskaja** [comment]
@jmschrei Not sure if this matters, but the ticket you mentioned seems to be about python 2.7, however I’m using 3.6

**Comment by jmschrei** [comment]
It looks like some linker stuff got messed up for me when I tried to upgrade anaconda. If you delete anaconda completely and freshly install it, it works again for me. Let me know if that helps you. I know it's kind of a pain...

**Comment by podorskaja** [comment]
@jmschrei fresh install solved the problem. Thanks.

**Comment by ukuk666888** [comment]
I have the same problem now.
I tried  `sudo -H pip uninstall pomegranate` & `sudo -H pip install pomegranate`
but still can't solve it, can you tell me how to fresh install please?

**Comment by jmschrei** [comment]
What version is it saying you're using if you run `import pomegranate; print(pomegranate.__version__)`?

**Comment by ukuk666888** [comment]
```
import pomegranate;
print(pomegranate.__version__)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-22-579eed5e7dc7> in <module>()
----> 1 import pomegranate;
      2 print(pomegranate.__version__)

/Library/Python/2.7/site-packages/pomegranate/__init__.py in <module>()
     12 from .distributions import *
     13 from .kmeans import Kmeans
---> 14 from .gmm import GeneralMixtureModel
     15 from .NaiveBayes import NaiveBayes
     16 from .BayesClassifier import BayesClassifier

ImportError: cannot import name GeneralMixtureModel
```
I run on Jupyter and show this, have the same problem
but I use `pip list` on command line, it show that my pomegranate version is 0.8.1

**Comment by jmschrei** [comment]
Is it possible for you to go and manually delete all the pomegranate files in your site-packages folder, including the .egg folder?

**Comment by ukuk666888** [comment]
I got pomegranate-0.8.1.dist-info and pomegranate these two folder in site-packages folder, I use `sudo -H pip uninstall pomegranate` and these two folder would be delete. I think the two folder are all the pomegranate related folders, there is no .egg file too in site-packages folder QAQ
