### ISSUE TITLE
Hidden Variable in Bayesian Network

### ISSUE THREAD

**Issue by sqh1107** [jmschrei/pomegranate#319]
Hi, I just want to know if pomegranate can solve the Bayesian Network problem with the hidden variable in it (like fit the missing value or missing features/ EM algorithm for solving Bayesian Network with hidden variable). 

Thank you!

**Comment by jmschrei** [comment]
Not currently, but it is something I'd like to add in when I have more development time.

**Comment by sqh1107** [comment]
Thank you! Looking forward that new function!

**Comment by jmschrei** [comment]
I will try to remember to ping you when I add it in!
