### ISSUE TITLE
Fitting HMM for sequences with multiple observations using HiddenMarkovModel.from_samples

### ISSUE THREAD

**Issue by robertmacyiii** [jmschrei/pomegranate#321]
Hi,

I want to fit an HMM for a problem where my data is structured as a list of sequences of varying length (always between length 1 and 30). In each sequence, there are multiple observed variables (always 8 observations). How do I need to format the data to work with the from_samples function? I have tried entering my data as a list of numpy arrays where each numpy array holds a sequence of observations, but I'm running into errors.

For example, a single sequence could look like this:
[[1,4,0,6,0,0,0],
 [1,4,1,3,0,0,1],
 [2,4,1,4,1,0,1]]

Thanks!

**Comment by jmschrei** [comment]
It sounds like you're saying that you have variable length sequences that are 8-dimensional. You'd want to input the data as a list of 2D numpy arrays of shape (n_observations, n_dimensions). Just to get started you might want to start off modeling it with a MultivariateGaussianDistribution. Can you post a code snippet that is failing?

**Comment by robertmacyiii** [comment]
Thanks, that was the input format I was using but I was failing I think because I was trying to model it with a DiscreteDistribution. I switched it to a MultivariateGaussianDistribution and it worked.
