### ISSUE TITLE
Bug in supervised HMM training

### ISSUE THREAD

**Issue by rasto2211** [jmschrei/pomegranate#329]
When I run this code:
```
from pomegranate import DiscreteDistribution, HiddenMarkovModel, State

words = [['a', 'b']]
labels = [['A', 'B']]

hmm = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=2,
                                     X=words, labels=labels, algorithm='labeled',
                                     emission_pseudocount=0, state_names=['A', 'B'],
                                     verbose=True)
print(hmm.states)
```
I get this output:
```
[1] Improvement: -0.4373241228998228	Time (s): 0.0001056
Total Training Improvement: -0.4373241228998228
Total Training Time (s): 0.0005
[{
    "class" : "State",
    "name" : "A",
    "distribution" : {
        "parameters" : [
            {
                "a" : 0.43129150457222876,
                "b" : 0.5687084954277711
            }
        ],
        "class" : "Distribution",
        "frozen" : false,
        "name" : "DiscreteDistribution"
    },
    "weight" : 1.0
}, {
    "class" : "State",
    "name" : "B",
    "distribution" : {
        "parameters" : [
            {
                "a" : 1.0,
                "b" : 0.0
            }
        ],
        "class" : "Distribution",
        "frozen" : false,
        "name" : "DiscreteDistribution"
    },
    "weight" : 1.0
}, {
    "class" : "State",
    "name" : "None-start",
    "distribution" : null,
    "weight" : 1.0
}, {
    "class" : "State",
    "name" : "None-end",
    "distribution" : null,
    "weight" : 1.0
}]
```
I would expect that probability of the observation 'b' for the state 'A' is going to be zero or something really small. In the output you can see that the probability of 'b' in state 'A' is actually greater than probability of 'a' which is completely strange. Am I giving it the input in a wrong format or is there really a bug in the supervised training of HMM?

Thanks for your help in advance.

**Comment by rasto2211** [comment]
It seems making these changes in the code fixed the problem for me:
```
diff --git a/pomegranate/hmm.pyx b/pomegranate/hmm.pyx
index 44594f4..ef61926 100644
--- a/pomegranate/hmm.pyx
+++ b/pomegranate/hmm.pyx
@@ -3447,13 +3447,13 @@ cdef class HiddenMarkovModel(GraphModel):
         if X_concat.ndim == 1:
             X_concat = X_concat.reshape(X_concat.shape[0], 1)
 
-        if labels is not None and None in labels:
+        if labels is not None:
             X_ = [x for x, label in zip(X, labels) if label != None]
             X_ = numpy.concatenate(X_)
 
             labels_ = [[label for label in l] for l in labels if l is not None]
             labels_ = numpy.concatenate(labels_)
-            labels_ = numpy.array([l for l in labels_ if l != name+"-start" and l != name+"-end"])
+            # labels_ = numpy.array([l for l in labels_ if l != name+"-start" and l != name+"-end"])
             label_set = numpy.unique(labels_)
 
             if distribution is DiscreteDistribution:
```
I don' really understand what was the reason behind this if:
```
if labels is not None and None in labels:
```
Why `None in labels`?

The default value of `name` is `None`. Why is that? Please change it to something more meaningful.

I believe this bug was brought by this PR #309.

**Comment by jmschrei** [comment]
Fixed.

**Comment by rasto2211** [comment]
Just for the reference, here's the commit that fixes the problem:
da39ce246dbee290b749e03260cab506ae01b9e7

**Comment by rasto2211** [comment]
Btw, did you also fix the part with name=None? If you run the code above it is going to fail because of the `name=None`. I think that the default value could be something like `name='HiddenMarkovModel'`.

**Comment by jmschrei** [comment]
Good suggestion, I didn't actually fix that part. I'll fix that soon.

**Comment by jmschrei** [comment]
It shouldn't actually be a problem, because the name is 'None' (as a string) not None (as the data type) and `None is 'None'` returns False.

**Comment by jmschrei** [comment]
Oh nevermind I see what the problem is. I've changed it to 'None' as the default value just to be consistent with the past.

**Comment by rasto2211** [comment]
@jmschrei Well, it's easy to confuse `'None'`(string) with `None`(not string) so I think it would be better if the default string would be something else.
