### ISSUE TITLE
model.plot() fails when pygraphviz is not installed

### ISSUE THREAD

**Issue by kdoroschak** [jmschrei/pomegranate#331]
If pygraphviz is not installed, then calling model.plot() on an HMM fails due to a missing argument in networkx.draw().

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-108-9d314dbffc6b> in <module>()
    ----> 1 m.plot()
    
    /homes/gws/kdorosch/software/anaconda2/lib/python2.7/site-packages/pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.plot()
        671         else:
        672             warnings.warn("Install pygraphviz for nicer visualizations")
    --> 673             networkx.draw()
        674 
        675     def bake(self, verbose=False, merge="All"):
    
    TypeError: draw() takes at least 1 argument (0 given)

**Comment by jmschrei** [comment]
Fixed
