### ISSUE TITLE
Printing an empty model 

### ISSUE THREAD

**Issue by kdoroschak** [jmschrei/pomegranate#332]
This is a pretty inconsequential bug, but fixing it could help interpretability of the errors. When an empty model is printed, it should either print without states, or throw an exception that lets the user know there are no states.

    model = pmg.HiddenMarkovModel(name="omg it's an hmm")

Calling `print model` on this empty model yields:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-113-1e691f59c9a2> in <module>()
    ----> 1 print model
    
    /homes/gws/kdorosch/software/anaconda2/lib/python2.7/site-packages/pomegranate/base.pyx in pomegranate.base.GraphModel.__str__()
        290         def __str__(self):
        291                 """Represent this model with it's name and states."""
     --> 292                 return "{}:{}".format(self.name, "".join(map(str, self.states)))
        293 
        294         def add_node( self, node ):
    
    TypeError: argument 2 to map() must support iteration

And in ipynb, if you just execute `model` expecting it to print something, you get this: 

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    /homes/gws/kdorosch/software/anaconda2/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
        670                 type_pprinters=self.type_printers,
        671                 deferred_pprinters=self.deferred_printers)
    --> 672             printer.pretty(obj)
        673             printer.flush()
        674             return stream.getvalue()
    
    /homes/gws/kdorosch/software/anaconda2/lib/python2.7/site-packages/IPython/lib/pretty.pyc in pretty(self, obj)
        381                             if callable(meth):
        382                                 return meth(obj, self, cycle)
    --> 383             return _default_pprint(obj, self, cycle)
        384         finally:
        385             self.end_group()
    
    /homes/gws/kdorosch/software/anaconda2/lib/python2.7/site-packages/IPython/lib/pretty.pyc in _default_pprint(obj, p, cycle)
        501     if _safe_getattr(klass, '__repr__', None) not in _baseclass_reprs:
        502         # A user-provided repr. Find newlines and replace them with p.break_()
    --> 503         _repr_pprint(obj, p, cycle)
        504         return
        505     p.begin_group(1, '<')
    
    /homes/gws/kdorosch/software/anaconda2/lib/python2.7/site-packages/IPython/lib/pretty.pyc in _repr_pprint(obj, p, cycle)
        699     """A pprint that just redirects to the normal repr function."""
        700     # Find newlines and replace them with p.break_()
    --> 701     output = repr(obj)
        702     for idx,output_line in enumerate(output.splitlines()):
        703         if idx:

    /homes/gws/kdorosch/software/anaconda2/lib/python2.7/site-packages/pomegranate/base.pyx in pomegranate.base.Model.__repr__()
         28 
         29         def __repr__(self):
    ---> 30                 return self.to_json()
         31 
         32         def get_params(self, *args, **kwargs):

    /homes/gws/kdorosch/software/anaconda2/lib/python2.7/site-packages/pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.to_json()
       3064                     'start' : json.loads(self.start.to_json()),
       3065                     'end'   : json.loads(self.end.to_json()),
    -> 3066                     'states' : [json.loads(state.to_json()) for state in self.states],
       3067                     'end_index' : self.end_index,
       3068                     'start_index' : self.start_index,
    
    TypeError: 'NoneType' object is not iterable

**Comment by jmschrei** [comment]
Issue should be resolved in the latest patch.
