### ISSUE TITLE
log_probabilities > 0 ?

### ISSUE THREAD

**Issue by frdpnl** [jmschrei/pomegranate#336]
Hi,
When training a HMM like so:
```
pg.HiddenMarkovModel.from_samples(
                pg.IndependentComponentsDistribution, 
                3,
                train_data,
                verbose=True,
                distributions=[ pg.NormalDistribution,
                                pg.NormalDistribution,
                                pg.NormalDistribution,
                                pg.NormalDistribution,
                                pg.NormalDistribution,
                                pg.NormalDistribution])
```
and calling the model.log_probability() method, I see results greater than 0 (such as 15,..).
That seems wrong to me, is that normal?
(This creates a problem for me because different HMM models have different ranges for log_probability()  making comparisons impossible.)
Also, I added the `distributions` keyword parameter in that method, because  `IndependentComponentsDistribution.from_samples()` requires it (hmm,pyx, line 3405):
```
distributions = [distribution.from_samples(X_concat[y == i], **from_samples_dist) for i in range(n_components)]
```
Thanks for any information.

**Comment by jmschrei** [comment]
It is possible to get probabilities above 1 (or log probabilities above 0). Consider `~Uniform(0, 0.1)`. It will return a probability of 10 at any point between 0 and 0.1, but 0 otherwise. Likewise, a normal distribution with a small variance can produce very large probabilities. You should check what the parameters of distributions you're pulling out are.

Having a `distributions` keyword does not seem like a bad idea. I'm trying to figure out how to best do this type of model stacking, and will keep it in mind.

**Comment by frdpnl** [comment]
Hi,
Thank you for the explanation. This is indeed the case.
For the ```distributions``` keyword, here is what I did (apologies for not providing a pull request), probably not the cleanest:
Added **parameter in factory:
```
@classmethod
def from_samples(cls, distribution, n_components, X, weights=None,
        labels=None, algorithm='baum-welch', inertia=None, edge_inertia=0.0,
        distribution_inertia=0.0, pseudocount=None,
        transition_pseudocount=0, emission_pseudocount=0.0,
        use_pseudocount=False, stop_threshold=1e-9, min_iterations=0,
        max_iterations=1e8, n_init=1, init='kmeans++', max_kmeans_iterations=1,
        batch_size=None, batches_per_epoch=None, lr_decay=0.0, end_state=False,
        state_names=None, name=None, verbose=False, n_jobs=1, **from_samples_dist):
```
Then, use it in the body of that function (Line: 3561):
```
distributions = [distribution.from_samples(X_concat[y == i], **from_samples_dist) for i in range(n_components)]
```
Such that I can call it like:
```
pg.HiddenMarkovModel.from_samples(
                pg.IndependentComponentsDistribution,
                components,
                train_data,
                verbose=True,
                distributions=[ pg.NormalDistribution,
                                pg.NormalDistribution,
                                pg.NormalDistribution,
                                pg.NormalDistribution,
                                pg.NormalDistribution,
                                pg.NormalDistribution]
                )
```
