### ISSUE TITLE
Negative Weights Fitted From Mixture?

### ISSUE THREAD

**Issue by msealander** [jmschrei/pomegranate#338]
I am initializing/fitting a mixture of distributions, but it is selecting negative weights. Should...that be possible? 

```python
counts = np.array([[ 1.], [ 1.],[ 1.], [ 1.],[ 2.], [ 1.], [ 1.], [ 2.], [ 3.]])

model = GeneralMixtureModel.from_samples(
    NormalDistribution,
    n_components = 2,
    X = counts)

model.weights
```

That spits out: `array([-1.0986119, -0.4054653])`

Version: '0.8.0'

**Comment by jmschrei** [comment]
Looks like those are log weights! If you take `exp(model.weights)` you'll get `[~0.33, ~0.66]`. It should return normal weights, not log weights, though, so I'll take a look at fixing that.

**Comment by msealander** [comment]
Ah! Ok, great. Thanks and great package!
