### ISSUE TITLE
pomegranate.hmm example fails

### ISSUE THREAD

**Issue by bvernot** [jmschrei/pomegranate#339]
The hmm example code is failing for me, and I'm not sure why:

    from pomegranate import *
    d1 = DiscreteDistribution({'A' : 0.35, 'C' : 0.20, 'G' : 0.05, 'T' : 40})
    d2 = DiscreteDistribution({'A' : 0.25, 'C' : 0.25, 'G' : 0.25, 'T' : 25})
    d3 = DiscreteDistribution({'A' : 0.10, 'C' : 0.40, 'G' : 0.40, 'T' : 10})
    
    s1 = State(d1, name="s1")
    s2 = State(d2, name="s2")
    s3 = State(d3, name="s3")
    
    model = HiddenMarkovModel('example')
    model.add_states([s1, s2, s3])
    model.add_transition(model.start, s1, 0.90)
    model.add_transition(model.start, s2, 0.10)
    model.add_transition(s1, s1, 0.80)
    model.add_transition(s1, s2, 0.20)
    model.add_transition(s2, s2, 0.90)
    model.add_transition(s2, s3, 0.10)
    model.add_transition(s3, s3, 0.70)
    model.add_transition(s3, model.end, 0.30)
    model.bake()

With the error (on the last line):

    Traceback (most recent call last):
      File "test.hmm.py", line 20, in <module>
        model.bake()
      File "pomegranate/hmm.pyx", line 735, in pomegranate.hmm.HiddenMarkovModel.bake (pomegranate/hmm.c:13047)
      File "/usr/local/lib/python3.5/dist-packages/networkx/classes/reportviews.py", line 178, in __getitem__
        return self._nodes[n]
    KeyError: 0

I'm using python 3.5.2, and pomegranate 0.8.0.

This seems similar to an older issue:
HiddenMarkovModel.freeze_distribution() fails #8

**Comment by bvernot** [comment]
Ah - I just noticed the warning about networkx 2.0, which is the version I have.  I'll downgrade and see if it works.  Sorry for the bother.

**Comment by bvernot** [comment]
This fixed the problem.

**Comment by elmihailol** [comment]
thank you
still need to install networkx 1.1

**Comment by GoonjanJain** [comment]
I downgraded the networkx version from 2.4 to 1.11. However, I am still receiving the problem of keyerror = 0.

Help is appreciated.

**Comment by jmschrei** [comment]
The recent versions of pomegranate should support networkx 2. What version of pomegranate do you have?

**Comment by GoonjanJain** [comment]
I have pomegranate version 0.7.3 installed in my system. I installed this yesterday only using conda-forge.

**Comment by jmschrei** [comment]
That's a super old version. You should upgrade to a newer version and try again.

**Comment by GoonjanJain** [comment]
Since I installed it yesterday using conda-forge, so I assumed that it is the latest only. Please help how to install the latest 0.11.0 version.

**Comment by jmschrei** [comment]
You can use either `pip install pomegranate` to get it or `pip install --upgrade pomegranate` to upgrade to the latest version. Alternatively you can clone the repo and install it manually.

**Comment by GoonjanJain** [comment]
Thanks Jacob.

I installed pomegranate as suggested. However, I am getting the following error on execution.

File "pomegranate\base.pyx", line 19, in init pomegranate.base
AttributeError: type object 'pomegranate.base.Model' has no attribute '__reduce_cython__'

I received this error before as well. I googled and found that this is because of installation from pip. Thus, I installed using conda-forge and the above error vanished. Since I installed it via pip again, this error reappeared.

Also, I installed the pomegranate 0.11.0. However, on Anaconda Navigator, it is still showing as 0.7.3.

Your help is highly appreciated.


Also,

**Comment by GoonjanJain** [comment]
It worked. 
I cleaned my environment and re-installed everything from scratch and it worked.
Thanks a lot Jacob.

**Comment by Ashwin-iorb** [comment]
when using print (model.predict('AC')) getting errors . can anyone help

**Comment by jmschrei** [comment]
Try `model.predict(['A'. 'C'])`?
