### ISSUE TITLE
Conflicting requirements on networkx

### ISSUE THREAD

**Issue by nehaljwani** [jmschrei/pomegranate#340]
[requirements.txt](https://github.com/jmschrei/pomegranate/blob/master/requirements.txt#L3) says: `networkx >= 1.8.1, < 2.0`
[setup.py](https://github.com/jmschrei/pomegranate/blob/master/setup.py#L63) says: `networkx >= 1.8.1`

Shouldn't both be consistent?

**Comment by jmschrei** [comment]
Yep! Fixed with the next PR.
