### ISSUE TITLE
BayesianNetwork.from_json KeyError

### ISSUE THREAD

**Issue by nikisix** [jmschrei/pomegranate#343]
Getting a key error when trying to import data with bin labels which are float-castable.
Error:
KeyError: ((u'1', u'<=40000'),)

Specifically the keys in question here are the `distribution.parameters` and `distribution.table` keys from the ConditionalDistribution class.

Ex1. distribution.parameters problem keys
{u'1': 0.2014314208611991, u'0': 0.0658922914466737, u'3': 0.16759357033908248, u'2': 0.2867065587234542, u'4+': 0.27837615862959053}

Ex2. distribution.table problem keys
[[u'0', u'40000+', u'0.0'], [u'0', u'<=40000', u'1.0'], [u'1', u'40000+', u'0.0'], [u'1', u'<=40000', u'1.0'], [u'2', u'40000+', u'0.684236372565'], [u'2', u'<=40000', u'0.315763627435'], [u'3', u'40000+', u'0.846401568188'], [u'3', u'<=40000', u'0.153598431812'], [u'4+', u'40000+', u'0.842451319228'], [u'4+', u'<=40000', u'0.157548680772']]

This problem is remediated by simply changing the keys to a non-float-castible string (i.e. appending an underscore or the like).

**Comment by jmschrei** [comment]
This issue has been resolved in the latest patch.
