### ISSUE TITLE
Possible ModuleNotFoundError: utils fix?

### ISSUE THREAD

**Issue by DOsinga** [jmschrei/pomegranate#345]
Hi,

I got this error and followed the instructions:

pip uninstall pomegranate
pip install pomegranate --no-cache-dir

and it works, but it made me wonder what's so special about utils. One thing I noticed that the other cython modules are specifically mentioned in the setup.py list:
filenames = [ "base",
              "BayesianNetwork",
              "FactorGraph",
              "distributions",
              "hmm",
              "gmm",
              "NaiveBayes",
              "MarkovChain"
            ]

Should utils be part of that too?

**Comment by jmschrei** [comment]
That's certainly a possibility. These types of installation issues are a weak point of mine, so I'll try adding it and seeing if that resolves any issues.

**Comment by jmschrei** [comment]
This should be fixed with the creation of Mac and Linux wheels. Re-open if you encounter this issue again.
