### ISSUE TITLE
"need more than 1 value to unpack" Error when running structural learning from samples in BayesianNetwork

### ISSUE THREAD

**Issue by Esperano** [jmschrei/pomegranate#346]
Hi
I am trying to run the structural learning algorithm 'greedy' with 'from_samples' method in BayesianNetowrk as follows:

model = BayesianNetwork.from_samples(X,algorithm='greedy')

I get the following error:

**File "pomegranate/BayesianNetwork.pyx", line 810, in pomegranate.BayesianNetwork.BayesianNetwork.from_samples(pomegranate/BayesianNetwork.c:14179)
ValueError: need more than 1 value to unpack**

Many thanks

**Comment by jmschrei** [comment]
Howdy, thanks for the issue. Can you provide a minimal code example that reproduces this? What is "X" in this case?

**Comment by jmschrei** [comment]
I'm going to mark this as resolved. Please re-open if you encounter further problems.

**Comment by rchari51** [comment]
Getting the same error .Minimal code is as follows:
X=[['a', 'b, 'c'], ['d', 'e', 'f']]
model = BayesianNetwork.from_samples(X)

**Comment by rchari51** [comment]
Error message is:
ValueError: need more than 1 value to unpack

**Comment by jkleckner** [comment]
@rchari51 Your example doesn't give that error on current master (after correcting the missing quote character).

**Comment by Sariel2018** [comment]
X = [0, 2, 0, 1, 0, 5, 6, 5, 7, 6]
    y = [0, 0, 0, 0, 0, 1, 1, 0, 1, 1]
    clf = NaiveBayes.from_samples(NormalDistribution, X, y)
    print(clf.predict_proba([6]))

    clf = NaiveBayes.from_samples(NormalDistribution, X, y)
File "pomegranate/NaiveBayes.pyx", line 209, in pomegranate.NaiveBayes.NaiveBayes.from_samples
ValueError: need more than 1 value to unpack
