### ISSUE TITLE
Pseudo-counts not working for HiddenMarkovModel.from_samples

### ISSUE THREAD

**Issue by wcbeard** [jmschrei/pomegranate#347]
The following gives `ValueError: Symbol 'f' is not defined in a distribution`:
```
from pomegranate import HiddenMarkovModel, DiscreteDistribution

hmm = HiddenMarkovModel.from_samples(DiscreteDistribution, 
                                     X=[['a', 'b', 'c'], ['a', 'b', 'd', 'e'], ],
                                     n_components=2, pseudocount=1)

hmm.predict_log_proba(['a', 'b', 'f'])
```
I thought that `pseudocount` or `emission_pseudocount` would work, but they don't appear to.

**Comment by jkleckner** [comment]
Is your expectation that 'f' will be added to one of the discrete distributions?

**Comment by wcbeard** [comment]
Yes, I believe so.

One way of saying what I want to do is that I may know that 'f' will be in the test set, but it is not in the training set. Even though it is not in the training set I would like to include it as a possibility in `HiddenMarkovModel.from_samples`, but it doesn't look like including `pseudocount` currently accounts for this.

I suppose that one possible way around this would be to include a dummy sequence at the beginning with every possible symbol ([a, b, c, d, e, f, ...]), but it seems a bit hacky.

**Comment by jmschrei** [comment]
Thanks for raising the issue. The appropriate solution is for me to add in a "key_set" or something where the user defines the set of keys that the user wants to model, regardless of if they are in the training set. I think sklearn does this for their partial fit methods as well. Pseudocounts wouldn't work on any arbitrary key you'd see in the future, because that's an unbounded set of values. I will look into adding a fix soon!

**Comment by davidcereal** [comment]
Hi @jmschrei, is this still on the docket to fix? I'm running into same challenge as well. I'm trying to estimate the probability of sequence B given a model estimated using from_samples on sequence A. Do you know any workaround I could implement at the moment?

**Comment by jmschrei** [comment]
A workaround would be to include a sequence that is constructed to contain all the possible symbols you'd like to see and then assign it a very low weight so the model isn't effected (even assigning a weight of 0 might work). Adding in the ability to pre-define the keys is something I'll try to add in next release.

**Comment by KevinHHHHH0325** [comment]
Hi @jmschrei, I face the same problem when I applied the from_sample function recently. The difference between my case and this post is I didn't do the prediction yet. And I got a `ValueError: Symbol '0' is not defined in a distribution`. My initialization code is `model = p.HiddenMarkovModel.from_samples(p.DiscreteDistribution, n_components=94, X=X_train, labels = y_train, algorithm = "labeled")`. I am sure "0" doesn't exist on my label data. Can you help me with that?

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
