### ISSUE TITLE
Training with multiple observations + online training

### ISSUE THREAD

**Issue by tryfonch** [jmschrei/pomegranate#351]
I want to train a HMM and I have multiple observations (of same length). According to the documentation input is:

`An array of some sort (list, numpy.ndarray, tuple..) of sequences, where each sequence is a numpy array, which is 1 dimensional if the HMM is a one dimensional array, or multidimensional if the HMM supports multiple dimensions.`

To become more specific I have 3 variables (and lets call this set batch1):
```
x1 = [2,3,4,3]
x2 = [6,5,5,7]
x3 = [9,11,9,10]
```
What is the right form of the X variable in the `model.fit()`? Is it shape(n_samples, n_features)?
Is it correct to do `X = np.stack([x1, x2, x3])` which will give `shape(3,4)` or `X = np.stack([x1, x2, x3]).T` which will give `shape(4,3)`?

Regarding the online learning here is my question.

Suppose batch2 (sliding window by 1 position to the right) is:
```
x1 = [3,4,3,4]
x2 = [5,5,7,6]
x3 = [11,9,10,10]
```

How do I train my model using this "on-line" approach? Do I train it for batch1 and then for batch2 using as input parameters (i.e. transition probs, new estimates for distributions etc.) and so on so forth for the rest of my batches OR do I simply have to do the following:
`model.fit( [ batch1, batch2, batch3, . . .] )` ??

Thanks!

**Comment by jmschrei** [comment]
The input to the model should always be a list of sequences. If your sequence is multivariate, it should be a numpy array of shape (n, d) where n is the number of observations in the sequence, and d is the number of dimensions. 

Out-of-core learning is only necessary if your whole data set does not fit in memory. You can do so by calling `model.fit(X, batch_size=n)` where `X` is a numpy memory map and n is some number of samples. If you'd like to do minibatch learning instead, just set both `batch_size` and `batches_per_epoch`.

**Comment by tryfonch** [comment]
To help other readers let's make it more practical by using the following code. 

```
import numpy as np
from pomegranate import *

x1 = np.random.normal(1, 0.5, 13)
x2 = np.random.normal(-2, 1, 13)
x3 = np.random.normal(3, 1.5, 13)

X = np.stack((x1, x2, x3), axis = 1) #input now has shape(n,d)

window = 10

states = 2
prob_start = np.array([0.5, 0.5])
trans_mat = np.array([[0.5, 0.5],
                      [0.5, 0.5]])

d1 = NormalDistribution(1, 1)
d2 = NormalDistribution(-1, 0.75)

states = [d1, d2]

model = HiddenMarkovModel.from_matrix(trans_mat, states, prob_start, merge = 'None')
model.fit(X, batch_size = window)
```

In the above example my X array has shape(13,3) i.e. 13 observations for each of the 3 features. I want to train my model in batches of window size 10. So in total I will have 4 batches, the first will contain obs 0-9, the second obs 1-10, the third 2-11 and the fourth 3-12.  Will the above train properly or do I have to make any changes in the input form of `X` ?
