### ISSUE TITLE
Error: 'GeneralMixtureModel' is not defined while parsing model with .from_json()

### ISSUE THREAD

**Issue by edvinli** [jmschrei/pomegranate#353]
When I train a model, I return the model as model.to_json():
```

     model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts)

     model.fit(sequences=data)
     model = model.to_json()
     return model
```

Then when I try to read the model somewhere else as

`model = HiddenMarkovModel.from_json(model)`

I get the error: 

>   File "pomegranate/base.pyx", line 451, in pomegranate.base.State.from_json
> 
>   File "<string>", line 1, in <module>
> 
> NameError: name 'GeneralMixtureModel' is not defined.

--------------------

Whole code:

```

def trainHMM(data,nstates=1,ncomponents=2):
    
    model = HiddenMarkovModel()
    dists = []
    
    for state in range(nstates):
        d = []
        for comp in range(ncomponents):
            mu = np.random.uniform(-0.01,0.01)
            sigma = np.random.uniform(0.1,1.0)
            d.append(NormalDistribution(mu, sigma))
        
        clf = GeneralMixtureModel(d)
        dists.append(clf)
            
    trans_mat= np.random.rand(nstates,nstates)
    trans_mat = trans_mat/trans_mat.sum(axis=1)[:,None]
    starts = np.ones(nstates)/nstates
    
    model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts)
    model.fit(sequences=data)
    model = model.to_json()
    return model


def generateSeq(model,nseq):
    model = HiddenMarkovModel.from_json(model)
    synt_data = []
    for i in range(int(nseq)):
        seq_length = np.random.uniform(20,800)
        synt_data.append(model.sample(length=seq_length))
    
    return synt_data
```

**Comment by odel4y** [comment]
I have the same issue. It seems to occur because the class name `GeneralMixtureModel` is evalued from the `State.from_json` method. The gmm is separately defined from the distributions and is not imported in the base.pyx. I tried adding `from .gmm import GeneralMixtureModel` but it did not work for me. Maybe there is a problem with that cyclic import (gmm.pyx also imports base.pyx)...

**Comment by jmschrei** [comment]
There is a problem with a cyclic import. I'll take a look at that soon, I def want this to be a feature.

**Comment by jmschrei** [comment]
This should be resolved now.
