### ISSUE TITLE
HMM - why don't I get reproducible results?

### ISSUE THREAD

**Issue by tryfonch** [jmschrei/pomegranate#354]
I am implementing a HMM and my input for the `model.fit` is a list of sequences, where each sequence is a (n,d) array (d-dimensional). My model is 
`model = HiddenMarkovModel.from_matrix(trans_prob, dists, start_prob, merge= 'None',)`, in which I have pre-specified the `trans_prob, dists, start_prob`

After re-running the my program (clearing the memory) I get different results (parameters in the HMM) for exactly the same input. 

Why is that happening?

**Comment by jmschrei** [comment]
Can you provide a quick reproducible example? That'd help with debugging a lot. Fitting should be deterministic, and I haven't experienced this problem before. Is there any randomness to the way you're initializing your parameters?
