### ISSUE TITLE
Incorrect model parameters in labeled HMM learning

### ISSUE THREAD

**Issue by margasyuk** [jmschrei/pomegranate#355]
Hello!
I have tried to perform supervised learning of HMM with multivariate gaussian emissions based on one labeled sequence:
`model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=2, X=mg,
                                       state_names=['A', 'B'], name="model", verbose=True,
                                       labels=slg, algorithm='labeled')`
This returns model with following parameters:
`{
    "class" : "HiddenMarkovModel",
    "name" : "model",
    "start" : {
        "class" : "State",
        "distribution" : null,
        "name" : "model-start",
        "weight" : 1.0
    },
    "end" : {
        "class" : "State",
        "distribution" : null,
        "name" : "model-end",
        "weight" : 1.0
    },
    "states" : [
        {
            "class" : "State",
            "distribution" : {
                "class" : "Distribution",
                "name" : "MultivariateGaussianDistribution",
                "parameters" : [
                    [
                        0.12023176743718579,
                        0.12079336465164824
                    ],
                    [
                        [
                            0.8674413717990258,
                            0.6035432792703772
                        ],
                        [
                            0.6035432792703772,
                            0.8703790237578518
                        ]
                    ]
                ],
                "frozen" : false
            },
            "name" : "A",
            "weight" : 1.0
        },
        {
            "class" : "State",
            "distribution" : {
                "class" : "Distribution",
                "name" : "MultivariateGaussianDistribution",
                "parameters" : [
                    [
                        0.1522253944894642,
                        0.14749976251742108
                    ],
                    [
                        [
                            0.8851832133872272,
                            0.608372424216693
                        ],
                        [
                            0.608372424216693,
                            0.8739908491976375
                        ]
                    ]
                ],
                "frozen" : false
            },
            "name" : "B",
            "weight" : 1.0
        },
        {
            "class" : "State",
            "distribution" : null,
            "name" : "model-start",
            "weight" : 1.0
        },
        {
            "class" : "State",
            "distribution" : null,
            "name" : "model-end",
            "weight" : 1.0
        }
    ],
    "end_index" : 3,
    "start_index" : 2,
    "silent_index" : 2,
    "edges" : [
        [
            2,
            0,
            1.0,
            0.5,
            null
        ],
        [
            2,
            1,
            0.0,
            0.5,
            null
        ],
        [
            0,
            0,
            0.9944591029023747,
            0.5,
            null
        ],
        [
            0,
            1,
            0.005540897097625333,
            0.5,
            null
        ],
        [
            1,
            0,
            0.004905777916212429,
            0.5,
            null
        ],
        [
            1,
            1,
            0.9950942220837876,
            0.5,
            null
        ]
    ],
    "distribution ties" : []
}`
In particular, means by 1st coordinate are 0.12 and 0.15 in A and B states respectively. But true values for these means:
`numpy.mean(numpy.array([mg[0].T[0].T[i] for i in range(len(mg[0].T[0].T)) if slg[0][i+1] == 'A']))
numpy.mean(numpy.array([mg[0].T[0].T[i] for i in range(len(mg[0].T[0].T)) if slg[0][i+1] == 'B']))`
are 0.74 and -0.39 respectively.
[data.zip](https://github.com/jmschrei/pomegranate/files/1479980/data.zip)

**Comment by jmschrei** [comment]
Seems like I made a mistake here, and #369 is seeing it as well. I'll take a look, thanks for reporting it!

**Comment by ishouldbedany** [comment]
Tried this on a dataset of 10k samples and 12 features, by selecting one feature and fitting a normal distribution. 5 states.

For one of the states, `np.mean(X)` and `np.std(X)` return `mu` and `sigma` of `[-2.7131, 44.3158]`. HMM's Pomegranate estimates `[-3.4091, 44.2582]`. 

For another state, np estimates are `[-11.3365, 45.17015]` and HMM's pomegranate parameters are `[-12.5772, 46.8433]`. Close enough.

I tried fitting a MultivariateGaussian on the entire dataset and just compare the 12 means. The difference between the means vectors as returned by `np.std(X, axis=0)` and HMMs pomegranate is `array([ -0.05422129,  -1.26392344,  -0.23232981, -36.44503814,
        11.25322146, -46.531402  ,  -0.21031758,   0.79242596,
        -0.40697424, -25.28738076, -12.96713972,  30.09833634])`.

For another state: `array([ -0.04655162,  -1.07486239,  -0.3800352 ,   8.22521715,
         2.30011918,   6.66245752,  -0.39892581,   0.73188   ,
        -0.13358258,  -7.38205015,   0.50847247,  31.55647561])`

Unless I am misunderstanding something, seems some differences are present. Not sure if any of these difference are expected due to some internal calculation process.

**Comment by jmschrei** [comment]
Would you mind posting the code or linking to a gist with the code you used? Thanks for helping to investigate.

**Comment by margasyuk** [comment]
Thanks for reply! It seems to be working correctly when data is passed as list of lists of 1d arrays (each sequence is a list of 1d arrays) instead of list of 2d arrays (each sequence is a 2d array):
`mg = [[i for i in j] for j in mg]`

**Comment by jmschrei** [comment]
Can you expand on that a little bit? Each sequence is a list of 1d arrays, where each array is a single sample? It should work properly if each sequence is a 2d array too...
