### ISSUE TITLE
AttributeError: 'pomegranate.distributions.Distribution' object has no attribute 'parameters'

### ISSUE THREAD

**Issue by kdoroschak** [jmschrei/pomegranate#357]
Calling `hmm.to_json()` produces this error:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-32-7f091788e73f> in <module>()
    ----> 1 hmm.to_json()

    pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.to_json()

    pomegranate/base.pyx in pomegranate.base.State.to_json()

    pomegranate/distributions.pyx in pomegranate.distributions.Distribution.to_json()

    AttributeError: 'pomegranate.distributions.Distribution' object has no attribute 'parameters'

Calling `hmm.states()` produces the same attribute error (longer traceback, so to keep things short I only posted `.to_json()`).

MWE: 

    hmm = pmg.HiddenMarkovModel("Test model")

    # States
    s1 = pmg.State(pmg.Distribution(225, 10))
    s2 = pmg.State(pmg.Distribution(pmg.NormalDistribution(0, 20)))
    s3 = pmg.State(pmg.Distribution(pmg.NormalDistribution(70, 10)))

    hmm.add_states(s1, s2, s3)

    # Transitions
    hmm.add_transition(hmm.start, s1, 0.9)
    hmm.add_transition(hmm.start, s2, 0.1)
    hmm.add_transition(s2, s3, 0.9)
    hmm.add_transition(s2, s1, 0.1)
    hmm.add_transition(s3, s2, 0.95)
    hmm.add_transition(s3, s1, 0.05)
    hmm.add_transition(s1, s3, 0.005)
    hmm.add_transition(s1, s2, 0.005)
    hmm.add_transition(s1, hmm.end, 0.99)

    hmm.bake()

    hmm.to_json()

I was on pomegranate-0.7.7, and the same issue occurs for me after upgrading to pomegranate-0.8.1.

**Comment by jmschrei** [comment]
Try

```
s1 = pmg.State(pmg.NormalDistribution(225, 10))
s2 = pmg.State(pmg.NormalDistribution(0, 20))
s3 = pmg.State(pmg.NormalDistribution(70, 10))
```

instead and let me know if that works.

**Comment by kdoroschak** [comment]
Yes that works! Thanks. I was just using the [docs here](http://pomegranate.readthedocs.io/en/latest/HiddenMarkovModel.html) so if this is reproducible or more than just me it might be worth updating.

**Comment by jmschrei** [comment]
Good catch, documentation has been updated.
