### ISSUE TITLE
No n_jobs parameter available for the predict_proba method of BayesianNetwork

### ISSUE THREAD

**Issue by rootAvish** [jmschrei/pomegranate#365]
I was reading through the pomegranate docs here: http://pomegranate.readthedocs.io/en/latest/parallelism.html on how to speed up performance during prediction and it says that all prediction methods(including `predict_proba` as in the example) contain the n_jobs parameter as an argument. I tried using it for a `BayesianNetwork` model but I get the error:

`TypeError: predict_proba() got an unexpected keyword argument 'n_jobs'`

I'm on pomegranate 0.8.1. Is the parameter available in the predict_proba method of only some particular models?

**Comment by abs51295** [comment]
Hey @jmschrei can you look into this? I am facing the same issue. Thanks.

**Comment by tuhinsharma** [comment]
#258

**Comment by abs51295** [comment]
Hey @tuhinsharma thanks for pointing the issue out. But even though, it's mentioned there that there is an  `n_jobs` parameter for `predict_proba`, I don't see it while using Bayesian Network.

**Comment by jmschrei** [comment]
Hey, thanks for pointing it out. I'm working on a big PR involving missing value support right now. Once I merge that (hopefully this week?) I'm going to hit a bunch of these issues that have cropped up. Sorry for the delay!

**Comment by abs51295** [comment]
Sure @jmschrei thanks for the update :+1:

**Comment by jmschrei** [comment]
I'm seeing now the reason I didn't add it in originally. Essentially, `predict_proba` would only take in the observed values for a single point, not many. I'm going to vectorize it. That being said, parallelization will only help by making these predictions in parallel, it won't help with a single sample.

**Comment by rootAvish** [comment]
Hey @jmschrei , thanks for integrating this feature. You said that these changes won't help with a single sample. The question is (and I'm sorry if it's idiotic), what would help me speedup `predict_proba` for a single sample?

**Comment by jmschrei** [comment]
The code for the `predict_proba` method is mostly Python that hasn't been optimized that much. I don't think there's anything on the user end that can speed it up, I'd have to work on rewriting it on my side. I'll put it on the queue of pomegranate things to do.

**Comment by abs51295** [comment]
@jmschrei This might be a dumb question, but doing less number of iterations during loopy belief propagation help in speeding up the inference? I see that default number of iterations is 100, but can decreasing it help us?

**Comment by jmschrei** [comment]
None of these questions are dumb. The inference algorithm will run for a
maximum of 100 iterations. Frequently it converges in a handful. You can
set the value to anything you’d like, you’ll just get increasingly
approximate results. If you have a tree-like Bayesian network it will only
take one iteration to converge anyway.

Can you give me a sense for the size of your network/data? I might be able
to give a better recommendation with that.
