### ISSUE TITLE
HMM model fitting with MultivariateGaussianDistribution

### ISSUE THREAD

**Issue by pingkoc** [jmschrei/pomegranate#366]
I noticed that in `HiddenMarkovModel.from_samples` you have the line
`X_concat = numpy.concatenate(X)`
If I want to fit a multivariate gaussian, my input array is going to be of shape (n_samples, n_vars).
But this X_concat is going to flatten the array and fit univariate gaussians instead.

Thank you.

**Comment by pingkoc** [comment]
I have another related issue. Please let me know if I should open another separate issue with this.

I am trying to run the following:
`num_states = 4
data = np.array([[1,2,3], [2,3,4]])
model = from_samples(MultivariateGaussianDistribution, n_components=num_states, X=data)
`
where the `from_samples` is a modification to pomegranates `model.from_samples` that does not flatten the input `X` so that when MultivariateGaussianDistribution is initialized, it is initialized with an array instead of a single variable.

I am running into this issue:
`  File "pomegranate/distributions.pyx", line 2124, in pomegranate.distributions.MultivariateGaussianDistr
ibution.from_summaries                                                                                  
  File "/home/pingkoc/anaconda3/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py", line 81, in
 cholesky                                                                                               
    check_finite=check_finite)
  File "/home/pingkoc/anaconda3/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py", line 20, in
 _cholesky                                                                                              
    a1 = asarray_chkfinite(a)
  File "/home/pingkoc/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 1215, in as
array_chkfinite                                                                                         
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
`
It seems like what is being passed into the cholesky decomposition function is an array of NaNs of size (n_vars, n_vars) which I assume to be the covariance matrix (please correct me on this)?

Thanks you for this great project.

**Comment by jmschrei** [comment]
Howdy!

Sorry for the late response. You need to have your data input be of shape (n_sequences, n_samples_in_sequence, n_dimensions). So if you have one sequence with two three-dimensional observations, (1, 2, 3) and (2, 3, 4), you would structure it as `data = [numpy.array([[1, 2, 3], [2, 3, 4])`. Essentially, the data input should be a list of numpy arrays, where each numpy array corresponds to one sequence in the training set. Thus, when you concatenate the data, you're flattening all of the sequences into one long sequence, which breaks the temporal aspect of the data, but doesn't matter when you're initializing using k-means.

Let me know if that clarifies your questions!

**Comment by pingkoc** [comment]
Got it. Thanks for the help.
