### ISSUE TITLE
Time to initiate HMM model for large (>100 states)

### ISSUE THREAD

**Issue by ptmcgrat** [jmschrei/pomegranate#368]
Hello, 

I was trying out pomegranate to solve an HMM model with a large number of states (~255). However, when i tried to initialize the model, it took longer than 15 minutes, and i killed the process. By performing some rudimentary timing using the code below, it looks like it takes ~70 seconds to initialize a model with 100 states. Is it possible to use pomegranate for HMMs with a large number of states? 

```
import timeit
from pomegranate import *
import numpy as np

def test_time(num):
    dists = []
    t_trans = []
    for i in range(0,num):
        dists.append(NormalDistribution(i,10))
        t_trans.append([1/num]*num)

    trans_mat = np.array(t_trans)
    starts = np.array([0]*num)
    ends = np.array([0]*num)
    starts[0] = 1
    ends[0] = 1
    model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts, ends)

t = []
y = []
for x in range(2,100):
    t.append(x)
    y.append(timeit.timeit("test_time(x)", "from __main__ import test_time, x", number = 5))
    

```
![figure_1](https://user-images.githubusercontent.com/4750832/33895358-550d0c36-df2e-11e7-9b58-97e087690c9e.png)

**Comment by jmschrei** [comment]
Try changing the line from 

```python
model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts, ends)
```

to

```python
model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts, ends, merge='None')
```

**Comment by ptmcgrat** [comment]
Thanks... that did the trick.

One other question if you have the chance:

Any advice on how to speed up the calculation? I'd like to perform this on (43236,720,1026) sized data. Do i understand correctly that the time to calculate goes as N^2 (where N is the number of states)? Is it possible to use the lazy Vitterbi algorithm with this library?

**Comment by jmschrei** [comment]
The time is proportional to |N||E| where|E| is the number of edges and |N| is the number of nodes. If you have a sparse graph, the algorithms will go much faster than a dense graph. Currently no support for approximate inference like that.
