### ISSUE TITLE
Exception when executing BayesClassifier.from_samples with BayesianNetwork

### ISSUE THREAD

**Issue by davidas85** [jmschrei/pomegranate#370]
In the documentation it is mentioned that this should be possible ([http://pomegranate.readthedocs.io/en/latest/NaiveBayes.html#initialization](url)), but it isn't, as the exception clearly indicates:
> File "pomegranate/BayesClassifier.pyx", line 207, in pomegranate.BayesClassifier.BayesClassifier.from_samples
> AttributeError: type object 'pomegranate.BayesianNetwork.BayesianNetwork' has no attribute 'blank'

This is because `BayesianNetwork` is a `Model` and the `.blank()` method is only defined for `Distribution` object.
Am I missing something here?
I also ran into a similar not-implemented issue when trying to feed an array (instead of dict) to `BayesianNetwork.predict_proba` and then it looks for the `.items()` method..

Thanks!

**Comment by mfilipav** [comment]
I'm also missing "from_samples" attribute when modeling params from data. Here's an example from semi-supervised learning page (http://pomegranate.readthedocs.io/en/latest/semisupervised.html) that failed for me:

import numpy
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from pomegranate import NaiveBayes, NormalDistribution

n, d, m = 50000, 5, 10
X, y = make_blobs(n, d, m, cluster_std=10)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

n_unlabeled = int(X_train.shape[0] * 0.999)
idxs = numpy.random.choice(X_train.shape[0], size=n_unlabeled)
y_train[idxs] = -1

model = NaiveBayes.from_samples(NormalDistribution, X_train, y_train, verbose=True)

>>    model = NaiveBayes.from_samples(NormalDistribution, X_train, y_train, verbose=True)
AttributeError: **type object 'pomegranate.NaiveBayes.NaiveBayes' has no attribute 'from_samples'**

**Comment by jkleckner** [comment]
@mfilipav  FYI, when I copy paste that code into my current master build it works fine.  It did fail with 0.9.0.  So you would try building and installing that.

@jmschrei  time to put out a release?

**Comment by jmschrei** [comment]
I'll be putting out a release some time in the next two months. General exam at the end of this month.

**Comment by amalih** [comment]
I'm experiencing a similar issue when trying to execute the following code:

# Loading data
data_raw =pd.read_csv('samples.data')
data_raw = np.array(data_raw)

# Splitting into samples and labels
data = data_raw[:,:-1]
target = data_raw[:,-1]
train_data = data[0:300]
train_target = target[0:300]

model = BayesClassifier.from_samples(BayesianNetwork, X=train_data, y=train_target, verbose=True)

> pomegranate/BayesClassifier.pyx in pomegranate.BayesClassifier.BayesClassifier.from_samples()
> AttributeError: type object 'pomegranate.BayesianNetwork.BayesianNetwork' has no attribute 'blank'

**Comment by jmschrei** [comment]
Bayesian networks have been supported in the format of being constructed beforehand and passed in when creating the BayesClassifier object. In 0.12.0 I added support for just specifying BayesianNetwork as the distribution. See this example:

```
n, d, m = 500, 10, 10
X = numpy.random.randint(2, size=(n, d))
y = numpy.random.randint(m, size=n)

model1 = BayesClassifier.from_samples(BayesianNetwork, X, y, verbose=True)
model2 = NaiveBayes.from_samples(NormalDistribution, X, y, verbose=True)

print(model1.log_probability(X).sum(), model2.log_probability(X).sum())
```

This should return `-3472.957630704368 -3621.4625151258274` (subject to randomness).
