### ISSUE TITLE
Surprising FactorGraph API, maybe we need more documentation

### ISSUE THREAD

**Issue by rw** [jmschrei/pomegranate#375]
The pomegranate `FactorGraph` class exposes methods for construction that are primarily concerned with manipulating the graph structure: `add_node` and `add_edge`. However, when learning this library, I expected the `FactorGraph` class to instead be an explicit bipartite graph in which users either add 'variable nodes' or 'factor nodes' (the latter of which must necessarily include edges). It appears that the inference procedure for `FactorGraph` marks `Node`s as variable or factor at runtime, which is surprising.

For comparison, note how factor graphs are constructed in the following libraries:

- `py-factorgraph` uses `g.rv(...)` to add a random variable and `g.factor(...)` to add a factor:
https://github.com/mbforbes/py-factorgraph/blob/master/examples/simplegraph.py

- `opengm2` declares the number of variables at model construction, and then uses `g.addFunction(...)` and `g.addFactor(...)` to create factors:
https://github.com/opengm/opengm/blob/master/src/examples/unsorted-examples/quick_start.cxx

Is the API design in pomegranate a result of its origin as an HMM toolbox?

**Comment by jmschrei** [comment]
Howdy!

> Is the API design in pomegranate a result of its origin as an HMM toolbox?

Pretty much. Factor graphs were originally implemented only to support Bayesian networks, not necessarily for use by themselves, as I don't know that much about them. I would be more than happy to add in (or merge a PR containing) convenience functions that help people use them.
