### ISSUE TITLE
Not able to compile the cython library.

### ISSUE THREAD

**Issue by Schiboni** [jmschrei/pomegranate#382]
Hi, hope you can help me, I am really desperate. I need to make some modification to the forward algorithm and compile my custom version of pomegranate. When i run setup.py with the command "python3 setup.py build_ext --inplace". I receive the following error:

/usr/bin/clang -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.5/pomegranateplus/utils.o -o build/lib.macosx-10.6-intel-3.5/POWERSPOTTING/codes/pomegranateplus/utils.cpython-35m-darwin.so
copying build/lib.macosx-10.6-intel-3.5/POWERSPOTTING/codes/pomegranateplus/BayesClassifier.cpython-35m-darwin.so -> POWERSPOTTING/codes/pomegranateplus
error: could not create 'POWERSPOTTING/codes/pomegranateplus/BayesClassifier.cpython-35m-darwin.so': No such file or directory

Do you have any suggestions what to do? My machine is a Mac with Sierra 10.12.6 and python 3.

Thanks in advance

**Comment by jmschrei** [comment]
Can you try removing all of the files that are not .py, .pyx, or .pxd from the library and recompile? Also, potentially try running `python3 setup.py install` instead.

**Comment by jmschrei** [comment]
Did this work out?

**Comment by vpicouet** [comment]
It seems that deleting __init__.py works!

**Comment by enjoysmath** [comment]
Well, how do you build a cython package that requires an __init__.py if you have to delete it!!!  This is driving me nuts.

**Comment by dpc10ster** [comment]
me too

**Comment by timonviola** [comment]
it also doesn't compile is ```__init__.py``` is present

**Comment by zwei-beiner** [comment]
A fix that worked for me is described here:
https://stackoverflow.com/questions/71983019/why-does-adding-an-init-py-change-cython-build-ext-inplace-behavior

Essentially, you can keep the `__init__.py` file and the setup file has to be 
```
from setuptools import Extension, setup
from Cython.Build import cythonize

extensions = [Extension("hello", ["hello.pyx"])]

setup(
    ext_modules=cythonize(extensions),
)
```

instead of 
```
# WRONG!!
from setuptools import setup
from Cython.Build import cythonize

setup(
    ext_modules=cythonize("hello.pyx"),
)
```

**Comment by jmschrei** [comment]
Thanks for the comments. I'm currently in the process of rewriting pomegranate using a PyTorch backend so hopefully that will resolve all these issues.
