### ISSUE TITLE
How to use hmmlearn HMM for recognition on 4D data?

### ISSUE THREAD

**Issue by huangteng1220** [jmschrei/pomegranate#386]
I am new to statistical analysis. I will give a detailed description of my problem as follows: I have a 4D data set as follows:

ObjectID |The number feature of every Object |The length of every feature  |Types
--------  | ----------------------------------- | --------------------------- | -----
|    1           |               100                                        |                    64                        |   1    |
|    2           |               100                                       |                    64                        |     1   |
|    3           |               100                                       |                     64                       |     2   |
|   4           |               100                                        |                      64                      |     3  |
|   ···           |               ····                                         |                       ·····                    |          |

The shape likes  (objID, num_feature of every Object, len_feature, Types),e.g.（274500，100，64，10）. How should I use pomegranate HMM for recognition on these 4D data?

**Comment by jmschrei** [comment]
Can you describe what the "types" are? When you say "length" of every feature, are you implying that the data is a sequence that is consistently length 64, with 100 features at each time step?

**Comment by huangteng1220** [comment]
The "types"  in the table is the class (e.g. car, train ,bus and so on) of the target I want to recognize. Here, I only use the number index to represent. My data is consisted of 274500 sequence data. Each sequence data is consisted of 100 row vectors and belongs to a certain types.  The length of each row vector is 64.

**Comment by jmschrei** [comment]
I'm still not sure I understand. What does "274500 sequence data" mean? Are you saying that there are 274500 sequences, of which each one is of length 100 with 64 dimensions?

**Comment by huangteng1220** [comment]
Yes, I mean there are 274500 sequences, of which each one is of length 100 with 64 dimensions

**Comment by jmschrei** [comment]
This sounds like you're trying to do a supervised learning problem on sequential data, i.e., you have a set of images and you'd like to classify them. HMMs are not great at doing classification of sequences. What you'd have to do is train one HMM per class, where to input to each HMM is a 100x64 matrix, and evaluate the probability of each sample under each HMM, assigning the label with the log probability. A conv-RNN-net might be better for this task though.
