### ISSUE TITLE
Can't seem to control distribution parameters in unsupervised HMM

### ISSUE THREAD

**Issue by Komodovaran** [jmschrei/pomegranate#388]
I'm trawling through thousands of time series, using a completely unsupervised HMM to determine approximate step changes.

To steer my analysis in the right direction, I'm doing the following:

```
import pomegranate as pg

dist = pg.NormalDistribution.(0,1)

    if force_n_states:
        best_model = pg.HiddenMarkovModel.from_samples(dist, n_components = force_n_states, X = obs)
        # best_model.fit(obs)

hidden_states = best_model.predict(obs, algorithm = "map")
```

I can see that my state finding is way too sensitive, so I try to change the NormalDistribution parameters. However, no matter how I set it, it doesn't change the outcome. Am I misunderstanding something?

**Comment by jmschrei** [comment]
Yes. When you pass a distribution in, you're just specifying the type of
distribution that you want pomegranate to build a model out of. In this
case, you're building a univariate Gaussian HMM. The initial parameters
themselves are actually set using k-means. You shouldn't even be passing in
an initialized distribution to the `from_samples` method, it should be
`pg.HiddenMarkovModel.from_samples(NormalDistribution, ...).`  If you want
to set the initial parameters of the distributions, you should construct
the model by hand by adding the states and edges to the model and then call
`model.fit`, like you had commented out.

Let me know if that makes sense!
