### ISSUE TITLE
Online decoding with POMEGRANATE

### ISSUE THREAD

**Issue by Schiboni** [jmschrei/pomegranate#389]
Hi! I am implementing a gesture recognition framework with pomegranate. I train the models off-line and i would like to decode the stream of online data from inertial sensor. Is there any way to do it with your library?

**Comment by jmschrei** [comment]
Howdy. Unfortunate there is no way to pass in the next observation in a sequence and get a prediction given the current state. You would have to rerun the algorithm from the beginning using the entire sequence observed thus far.

**Comment by Schiboni** [comment]
Thanks for your ready answer. May you suggest from any other source  an implementation of an online decoding, no matter what programming language? For example on-line Viterbi implementation? I cannot find any around, that seems weird to me.

**Comment by jmschrei** [comment]
I'm not aware of either, but I'm also not a very comprehensive source of knowledge. If you want to implement a hack in pomegranate, I'd suggest training your HMM using pomegranate, pulling out the distributions to make a `GeneralMixtureModel`, and then for each new observation using the GMM to calculate the likelihood, multiply it by the transition probability that you pull from the HMM transition matrix based on where you currently are, and transition. The only difficulty would be if there were silent states. Do you think that might work?

**Comment by Schiboni** [comment]
Something is missing from your proposal. In order to work out, i d need to pull out the last score for each state from the Viterbi algorithm to go on with the estimation. I am not sure i can do it, can't i?

**Comment by jmschrei** [comment]
I don't know off-hand how the online Viterbi algorithm works, so there could be something missing. I suppose my proposal is just a hard version of the forward algorithm.

**Comment by Schiboni** [comment]
Ok, thanks for the advice, i ll try to figure out.

**Comment by jmschrei** [comment]
Good luck! If you have a good reference for the online Viterbi algorithm I can add it to my queue

**Comment by Schiboni** [comment]
There is this master thesis here:

http://www.dcs.fmph.uniba.sk/diplomovky/obhajene/getfile.php/main.pdf?id=143&fid=289&type=application%2Fpdf
