### ISSUE TITLE
Statistics: how many parameters do I have, for model comparison?

### ISSUE THREAD

**Issue by Komodovaran** [jmschrei/pomegranate#391]
Let's say I do a 3-state model like this:
```
           cl = sklearn.cluster.KMeans(i).fit(obs).cluster_centers_

            dists = [pg.NormalDistribution(cl[0], noise),
                     pg.NormalDistribution(cl[1], noise),
                     pg.NormalDistribution(cl[2], noise)]

            trans_mat = np.array([[self_trans, trans_prob, trans_prob],
                                  [trans_prob, self_trans, trans_prob],
                                  [trans_prob, trans_prob, self_trans]])

            starts = np.array([1.0, 0.0, 0.0, 0.0])
            ends = np.array([0.0, 0.0, 0.1])
            model = pg.HiddenMarkovModel.from_matrix(trans_mat, dists, starts, ends)

            L = model.log_probability(obs)
```

And now a 4-state model like this:
```
            cl = sklearn.cluster.KMeans(i).fit(obs).cluster_centers_

            dists = [pg.NormalDistribution(cl[0], noise),
                     pg.NormalDistribution(cl[1], noise),
                     pg.NormalDistribution(cl[2], noise),
                     pg.NormalDistribution(cl[3], noise)]

            trans_mat = np.array([[self_trans, trans_prob, trans_prob, trans_prob],
                                  [trans_prob, self_trans, trans_prob, trans_prob],
                                  [trans_prob, trans_prob, self_trans, trans_prob],
                                  [trans_prob, trans_prob, trans_prob, self_trans]])

            starts = np.array([1.0, 0.0, 0.0, 0.0, 0.0])
            ends = np.array([0.0, 0.0, 0.0, 0.1])
            model = pg.HiddenMarkovModel.from_matrix(trans_mat, dists, starts, ends)

            L = model.log_probability(obs)
```

Now, since Pomegranate doesn't come with this built in, how can I compare these?

For e.g. BIC, wiki tells me that BIC = ln(n_samples) * k_params - 2 * log_probability

How many parameters am I estimating in each case above? It seems like I'm giving a whole ton of inputs.

**Comment by jmschrei** [comment]
The parameters for a dense univariate Gaussian HMM (like you specified) is 2 * n_dists for the emissions and n_dists ** 2 + 2 * n_dists if you have an explicit end state, or n_dists ** 2 + n_dists if you don't. To break it down, each normal distribution has a mean and a standard deviation, so two parameters. Then, the dense transition matrix (without considering starts and stops) is n_nodes ** 2. Then, you have n_dists start probabilities, and optionally you have n_dists end probabilities.

So, in total, you have `n_params = n_dists * 4 + n_dists ** 2` for a dense univariate Gaussian HMM.

**Comment by Komodovaran** [comment]
Thanks. Though, I'm wondering; why isn't it `n_dists` * 2 + n_dists ** 2` only? Shouldn't the start and end probabilities also be satisfied with a given transition matrix, or does the math work out to be "not always"?

**Comment by jmschrei** [comment]
The reason is because the transition matrix is typically between all character emitting states, with an additional vector of "start" probabilities, and an optional vector of "end" probabilities. If you include the silent start and stop states, it's still not the number of states squared because you can't go directly from the start to the end state, or from the end state to any other state.
