### ISSUE TITLE
how does the node_count and edge_count() work?

### ISSUE THREAD

**Issue by jennxf** [jmschrei/pomegranate#393]
I fed the bayesianNetwork 2 million tuples but when i use the edge_count or node_count function, i only got 1 edge and 2 nodes. 

this is my example data:

```
data = [(1,2),(3,4)....]
model = BayesianNetwork.from_samples(data, algorithm='exact')
model.node_count() # returns 2
model.edge_count() # returns 1
```

shouldn't i have the 2 mil edges?

Thanks

**Comment by jmschrei** [comment]
Howdy

When you use `from_samples`, you are feeding in training data, not the structure. Your data is fed in such that it has two columns, so it produces a model with two nodes (one for each variable). Only one edge could exist between those two nodes. If you're trying to feed in structure, you should use the `from_structure` method, which takes in a list of tuples where each tuple is a node in the graph and contains all of its parents. For example, `[(1, 2), (2,), (,)]` would produce a graphw here the first node is the child of the second and third, and the second node is the child of the third node.

**Comment by jennxf** [comment]
Its a little confusing. I thought the format of creating a graph was similar to that of `networkx` where we can build a graph from a list of tuples like this one: `data = [(1,2),(2,4),(3,5)]`
and the tuples are edges and the nodes are `1,2,4,5`. 

From your example, do you mean that `(1,2)` is a node and child of `(2,)`? 
The example seems to be an entirely different format of graph creation from networkx. Is there any way to make use of the networkx structure to create a graph?

**Comment by jmschrei** [comment]
Hi

Yes, it is different than networkx. I would welcome a contribution of a `from_edges()` method that takes in a list of edges and creates a graph. Feel free to submit a PR.

In your case, your data is not [(1, 2), (2, 4)...], that is your structure. Your data are the values that those variables take. That is potentially a source of confusion for you. In my example, (1, 2) means that variable 0 (the position in the list) is a child of both variables 1 and 2.
