### ISSUE TITLE
score() method of HiddenMorkovModel & GeneralMixtureModel is not working

### ISSUE THREAD

**Issue by amitkumarx86** [jmschrei/pomegranate#395]
I am trying to call score() method on HiddenMorkovModel and GenrealMixtureModel, but getting following error:
For HMM:
`hmm1 = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=3, X=X)`
`hmm1.score(X)`
**Output:**
`---------------------------------------------------------------------------`
`AttributeError                            Traceback (most recent call last)`
`<ipython-input-24-4342f03893b7> in <module>()`
`----> 1 hmm1.score(X)`

`AttributeError: 'pomegranate.hmm.HiddenMarkovModel' object has no attribute 'score'`

**For GeneralMixtureModel of hmms**
`# general mixture model`
`model = GeneralMixtureModel([hmm1, hmm2, hmm3, hmm4])`
`model.score(X)`
**Output:**
`---------------------------------------------------------------------------`
`AttributeError                            Traceback (most recent call last)`
`<ipython-input-27-c386e0c9ae4d> in <module>()`
`----> 1 model.score(X)`

`AttributeError: 'pomegranate.gmm.GeneralMixtureModel' object has no attribute 'score'`

**Note: I do not have labels of the data.**
Can you please look into the issue ?

Thanks

**Comment by jmschrei** [comment]
Howdy

There is no `score` method. Perhaps you're looking for `log_probability`?

**Comment by amitkumarx86** [comment]
In this link we have documented score() method in the bottom.
`http://pomegranate.readthedocs.io/en/latest/HiddenMarkovModel.html`

**Comment by jmschrei** [comment]
Sorry, my mistake. There is a score function, but I hadn't yet amended it to work for HiddenMarkovModels. What are you hoping to get out of this function if you dont have labels?
