### ISSUE TITLE
Freezing specific edges in HMM

### ISSUE THREAD

**Issue by NMRobert** [jmschrei/pomegranate#396]
Hi,
I've read through the documentation for the HiddenMarkovModels and I found a way to freeze all the edges in the graph using the _edge_inertia_, but is it possible to freeze a specific edge? For example, I would like particular transition probabilities to be fixed, and for the others to vary. Is there a way to do this, and if not, where would I look if I wanted to implement it within pomegranate?

Thank you!

**Comment by jmschrei** [comment]
Hi NMRobert!

I'm pretty sure you can effectively do this by setting edge specific pseudocounts, where the pseudocounts are equal to 0 for all edges except the ones you want to freeze, and you set those to high values, then toggle the `use_pseudocount=True` flag during training

example:

```
from pomegranate import *

...
model = HiddenMarkovModel()
model.add_states( as normal )
model.add_transition(a, b, 0.4, pseudocount=0) # unfrozen edge
model.add_transition(c, d, 0.6, pseudocount=999999) # frozen edge 

...
model.train(X, ... use_pseudocount=True)
```

Let me know if that works for you!

**Comment by jmschrei** [comment]
To extend on that, you'll need to manually set `pseudocount=0` for all edges that you don't want to have pseudocounts added during training. By default, it adds a count equal to the probability, so that if it is unlikely that any training sample crosses that edge the probabilities mostly just remain in tact.

**Comment by NMRobert** [comment]
Hi, that seems to work pretty well! Thank you for the prompt response and your efforts on this package.
