### ISSUE TITLE
Fit HMM with General Mixture Models

### ISSUE THREAD

**Issue by fbrouli** [jmschrei/pomegranate#398]
(not a bug, I don't understand how to do something. Pomegranate otherwise looks amazing)

Given https://github.com/jmschrei/pomegranate/pull/49, I'm sure it's already implemented, but I just can't make it to work. Basically I have sequences that were created by a simple two state markov model. At each state, the model might emit a zero or a sample from a gaussian:

```python
gaus1 = NormalDistribution(0, 0.1)
gaus2 = NormalDistribution(30, 2)
unif = UniformDistribution(0, 0)

mixture1 = GeneralMixtureModel([gaus1, unif], weights = np.array([0.7, 0.3]))
mixture2 = GeneralMixtureModel([gaus2, unif], weights = np.array([0.5, 0.5]))
sequences = [np.concatenate((mixture1.sample(60), mixture2.sample(60))) for i in range(200)]
```

I've tried creating an uninitialized mixture distribution, so I would be able to use from_samples (which is definitely my preffered option here)
```
dist = GeneralMixtureModel([NormalDistribution, UniformDistribution])
```
but it fails on "an integer is required"

On the other hand, trying to define an initial model and then using fit also fails

```python
s1 = State(GeneralMixtureModel([NormalDistribution(0, 1), UniformDistribution(0, 0)], weights = np.array([0.5, 0.5])))
s2 = State(GeneralMixtureModel([NormalDistribution(1, 1), UniformDistribution(0, 0)], weights = np.array([0.5, 0.5])))
model = HiddenMarkovModel("my_second_model")
model.add_states(s1, s2)
model.add_transition(model.start, s1, 0.5)
model.add_transition(model.start, s2, 0.5)
model.add_transition(s1, s1, 0.5)
model.add_transition(s1, s2, 0.5)
model.add_transition(s2, s1, 0.5)
model.add_transition(s2, s2, 0.5)
model.bake()
model.fit(sequences)
```

this time returning NaN as improvement, and setting all the internal distributions' parameters to NaN.

Thanks!

**Comment by jmschrei** [comment]
With the second option, you're getting an error because a uniform distribution defined between 0 and 0 is undefined in pomegranate. If you switch it to `UniformDistribution(0, 1)` it will train normally. You can't really create an uninitialized mixture model, but what you can do is initialize it using `from_samples` but pass in random weights and/or samples for the initialization step, then refine using the HMM fit step (which is basically what I do in the HMM from_samples method anyway).

Let me know if that works for you!

**Comment by fbrouli** [comment]
@jmschrei thanks!
So a quick note about UniformDistribution(0, 0) - sampling from it works (so you might want to disable it or raise a warning :) )

**Comment by jmschrei** [comment]
Good point! I'll keep this issue open for now so that I can resolve it when I have time to update pomegranate.

**Comment by fbrouli** [comment]
and your suggestions work well on my toy example - now it's time to examine it on the real data :)

**Comment by jmschrei** [comment]
Did this end up working?

**Comment by fbrouli** [comment]
well, sometimes, and very sensitive to the initial random values. But this seems to be some other issue, and probably merits its own thread.

Thanks @jmschrei (and thank you very much for writing and supporting this library)!

**Comment by jmschrei** [comment]
Great, I'm glad it worked out. You can try smoothing your data by adding pseudocounts, but otherwise it might just be an issue with the amount of data you have.
