### ISSUE TITLE
Undefined reference JointProbabilityTable._table_summarize

### ISSUE THREAD

**Issue by jkleckner** [jmschrei/pomegranate#399]
This is the only reference to _table_summarize.  What should it actually be?

https://github.com/jmschrei/pomegranate/blob/master/pomegranate/distributions.pyx#L2926

It threw an exception in a demo notebook Tutorial_1_Distributions.ipynb running all cells with using pomegranate 0.9.0 and conda installed python 3.6.1.  Let me know if more details needed.

**Comment by jkleckner** [comment]
I reproduced this with python 2.7 notebook on tag v0.9.0 on master.  Just use "run all cells".

**Comment by jmschrei** [comment]
Looks like it should be just `__summarize`. I'll fix this soon.

**Comment by jmschrei** [comment]
This has been fixed.
