### ISSUE TITLE
ZeroDivisionError in HMM Training

### ISSUE THREAD

**Issue by NMRobert** [jmschrei/pomegranate#401]
Hi,

when fitting a HMM with baum-welch, occasionally the fitting process will generate a ZeroDivision exception in the from_summaries module. This exception doesn't seem to prevent the training from occurring and process will continue, but it will continue to produce this error for each iteration which spams the console. 

```
ZeroDivisionError                         Traceback (most recent call last)
pomegranate/bayes.pyx in pomegranate.bayes.BayesModel.from_summaries()

pomegranate/distributions.pyx in pomegranate.distributions.NormalDistribution.from_summaries()

ZeroDivisionError: float division by zero
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._from_summaries'
Traceback (most recent call last):
  File "pomegranate/bayes.pyx", line 710, in pomegranate.bayes.BayesModel.from_summaries
  File "pomegranate/distributions.pyx", line 616, in pomegranate.distributions.NormalDistribution.from_summaries
ZeroDivisionError: float division by zero
```

**Comment by jmschrei** [comment]
Interesting. Can you print the model? I’m imagining that one component is
essentially becoming unused.

**Comment by NMRobert** [comment]
Hey, the model is a bit complex, but I can confirm that when this occurs, a mixture weight for a GMM component is approaching 0. I'll try to create a replicable example that's simple.

**Comment by jmschrei** [comment]
Okay. The fact that ZeroDivisionErrors are occuring is an aesthetic issue with pomegranate. I'm not sure whether a component disappearing is an algorithmic issue with pomegranate, or a consequence of the amount of data that you're using. What happens when you fit with one less component?

**Comment by jmschrei** [comment]
This issue should be fixed now. Please re-open if you still encounter the issue.

**Comment by rzu512** [comment]
The following example seems to always give division by zero error.

```python
import pomegranate as pg
import numpy as np

seqs = np.random.randint(2, size=(10, 500))
n_hidden_var = 3
model = pg.HiddenMarkovModel.from_samples(
    pg.BernoulliDistribution, n_components=n_hidden_var, 
    X=seqs, verbose=True)
```

Error:
```python
Traceback (most recent call last):
  File "test_pg.py", line 8, in <module>
    X=seqs, verbose=True)
  File "pomegranate/hmm.pyx", line 3594, in pomegranate.hmm.HiddenMarkovModel.from_samples
  File "pomegranate/distributions.pyx", line 375, in pomegranate.distributions.Distribution.from_samples
  File "pomegranate/distributions.pyx", line 205, in pomegranate.distributions.Distribution.fit
  File "pomegranate/distributions.pyx", line 531, in pomegranate.distributions.BernoulliDistribution.from_summaries
ZeroDivisionError: float division by zero
```

Tested on two machine with pomegranate installed with anaconda for python3 on Linux:
```
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
```

**Comment by jmschrei** [comment]
Thanks for the error message, sorry for the bug! I'll look at it soon
