### ISSUE TITLE
Edges in HMM model

### ISSUE THREAD

**Issue by Schiboni** [jmschrei/pomegranate#403]
Hi, given a gmm-hmm model with x mixtures for state, i am trying to create a new model, identical to the first one, but using a subset of mixtures.
For this reason, i copy the selected means and covariance matrices of the distributions for each states and also the transition matrix of the model. If i try to estimate the loglikelihood of an observation sequence, i get two different values from the two models. I noticed that the only different thing between the two model are some values in the matrix 'edges'.  The second last term of each line is the transition value of the original model before training. I have questions about it:
1) What the last two positions for each line of the edges matrix are for?
1) How do i access and change the values of the matrix?  I have tried to do model.edges it says it is NoneType.
I was not able to find the answer on the guide.

Thanks as usual for your time! 
Best regards
G S

**Comment by jmschrei** [comment]
Howdy

I'm not sure I understand the issue with different log likelihoods. If the number of mixtures, or the transitions, are different then the log likelihoods will be different. 

I currently don't have a simple way of changing the probability of a single edge. What you can do is change the underlying NetworkX graph. For example:

```python
....

model = HiddenMarkovModel()
model.add_states(s1, s2, s3)
model.add_transition(model.start, s1, 0.33)
model.add_transition(model.start, s2, 0.33)
model.add_transition(model.start, s3, 0.34)

model.add_transition(s1, s1, 0.33)
model.add_transition(s1, s2, 0.33)
model.add_transition(s1, s3, 0.34)

model.add_transition(s2, s1, 0.33)
model.add_transition(s2, s2, 0.33)
model.add_transition(s2, s3, 0.34)

model.add_transition(s3, s1, 0.33)
model.add_transition(s3, s2, 0.33)
model.add_transition(s3, s3, 0.34)

model.bake()

print(model.dense_transition_matrix())

model.graph.remove_edge(s2, s1)
model.graph.remove_edge(s2, s2)
model.graph.remove_edge(s2, s3)
model.graph.add_edge(s2, s1, probability=numpy.log(0.9), pseudocount=0.0, group=None)
model.graph.add_edge(s2, s2, probability=numpy.log(0.05), pseudocount=0.0, group=None)
model.graph.add_edge(s2, s3, probability=numpy.log(0.05), pseudocount=0.0, group=None)
model.bake()


print(model.dense_transition_matrix())
```

You'll get the following two matrices:
```
[[0.33 0.34 0.33 0.   0.  ]
 [0.33 0.34 0.33 0.   0.  ]
 [0.33 0.34 0.33 0.   0.  ]
 [0.33 0.34 0.33 0.   0.  ]
 [0.   0.   0.   0.   0.  ]]

[[0.33 0.34 0.33 0.   0.  ]
 [0.33 0.34 0.33 0.   0.  ]
 [0.9  0.05 0.05 0.   0.  ]
 [0.33 0.34 0.33 0.   0.  ]
 [0.   0.   0.   0.   0.  ]]
```

Note: You need to pass in log probabilities, not probabilities. This is an oddity I should fix in the backend of pomegranate at some point. You'll also need to remove all out edges from a node if you want to change the probabilities. Pomegranate will auto-normalize out edges to sum to a probability of 1, which may be unexpected behavior.

**Comment by Schiboni** [comment]
Sorry, i realized i have not been clear in this first post. I reformulate.

Hi, given a gmm-hmm model with x mixtures for state, i am trying to create a new model, identical to the first one, but using a subset of mixtures.
In order to accomplish this purpose i created a function that copies the selected means and covariance matrices of the distributions for each states and also the transition matrix of the model. 
To check if this function works,  i try to estimate the loglikelihood of an observation sequence with the original model and with the model i get from my function. 
For this test, the models use the same set of features then i would expect the same loglikelihod. Instead, i get two different values from the two models. This means that copying just the distributions parameters, i.e., means and covariance, and the transition matrix is not enough to create an identical model from another one. 
What am i missing? Why the the models, that i expect to have the same output, are different?

Thanks for your patience

**Comment by jmschrei** [comment]
Conceptually, a Gaussian HMM is parameterized entirely by the mus, covariances, and transitions. I'd have to see your code to determine what's going on.
