### ISSUE TITLE
Tutorials and Example

### ISSUE THREAD

**Issue by iamsurya** [jmschrei/pomegranate#407]
I'd like to start by saying this is a great library. I've been using HMMTK for MATLAB which is pretty old, and pomegranate has a lot of great resources in the examples and tutorials. Still building some confidence with understanding HMMs.

A few things: 
1) Seems like the tutorials and examples are coded for Python 2. I'm going through them in Python 3 and making changes as necessary. Would you be interested in updating (or adding a separate Python 3 tutorials folder?)
2) Cell [8] in [Tutorial0](https://github.com/jmschrei/pomegranate/blob/master/tutorials/Tutorial_0_pomegranate_overview.ipynb) mentions pomegranate's speed as being faster than numpy, but the results show numpy to be slightly faster. Is this just because the nb was saved with a bad example?
3) Cell [8] in [Tutorial1](https://github.com/jmschrei/pomegranate/blob/master/tutorials/Tutorial_2_General_Mixture_Models.ipynb) reads

> 507 1 labels, 243 0 labels
> This is fairly close to the number of underlying points from each distribution, off by 17 in each label.

However, in cell [6] we generated 250 0 values and 500 1 values => 7 off in each label. 
Further cell [10] states the below (and I can't see how you get 15.2 here). What am I missing?

> [ 242.73703674  507.26296326]
> This is slightly closer to the truth, with 15.2 off instead of 17, around 10% closer.

Edit: I'm realizing the tutorials are coded in Python 2 and I'm changing them to Python 3 so that they run for me. Would you be interested in a Python 3 version of the tutorials?

**Comment by jmschrei** [comment]
Howdy

Sorry for not getting back to this earlier. I am going to go through and try to comprehensively redo the tutorials and examples to be in python 3, and have clearer results. Thanks for the comments and the offer, though! Let me know if there's anything else I can help with.
