### ISSUE TITLE
Slow execution time in predict_proba

### ISSUE THREAD

**Issue by willsilvano** [jmschrei/pomegranate#408]
Hi,

i have model saved on my database in json format.

Then I load de the bayesian network with method `BayesianNetwork().from_json`.

After I make prediction for each row in my dataset, using method `predict_proba`.

The problem is the slow time.

Each row is during 1 second.

Is there any way to pass a list of rows to `predict_proba`  or any other way to do this faster?

Thanks.

**Comment by jmschrei** [comment]
You should be able to pass in a list of elements to make predictions for, and specify the `n_jobs` parameter to do them in parallel, if you have multiple cores.

**Comment by willsilvano** [comment]
Hello @jmschrei 

I tried this way, passing `n_job = 4` and still continues with the same performance problem, taking about 1 second for each record.

Can I pass more than one record to the prediction?

In my case each record equals one student in my data set. I currently send one student at a time, with about 50 variables for each student.

If I have a way to improve this performance I would greatly appreciate it!

Thank you.

**Comment by jmschrei** [comment]
Sorry for not being clear-- yes you should pass more than one record in for prediction at a time. `n_jobs` in this case does't parallelize the algorithm, it just runs multiple samples in parallel.
