### ISSUE TITLE
Error in hmm.pyx summarize function

### ISSUE THREAD

**Issue by anandastreit** [jmschrei/pomegranate#411]
Calling the summarize function from a parameterized HMM model returned an error. E.g, 'm.summarize(sequences=data)'. Looking at the code, I've observed that inside the 'check_input' condition, the weights are assigned to 'weights_ndarray', when it should be assigned to 'weights'.

**Comment by jmschrei** [comment]
Good catch. If you pass in `weights=numpy.ones(len(data))` that should resolve the issue for now.

**Comment by jmschrei** [comment]
This should be resolved in the latest patch.
