### ISSUE TITLE
Best way to pickle/save a Naive Bayes model

### ISSUE THREAD

**Issue by MarkPinches** [jmschrei/pomegranate#412]
Hello,

Firstly awesome work on pomegranate! - it rocks

Just a naive question, but what is the best way to pickle a naive bayes model?

Thanks

M

**Comment by jmschrei** [comment]
Howdy Mark

You should be able to do `model.to_json` and `NaiveBayes.from_json` for any model type (except using that model type instead of NaiveBayes). Let me know if that works out for you.
