### ISSUE TITLE
Inputs (or covariates) to HMM transitions

### ISSUE THREAD

**Issue by marcoslbueno** [jmschrei/pomegranate#416]
Hi, 
Is it possible to add inputs (or covariates) to the transitions of an HMM? 
The transitions would look like P(S^t | S^t-1, A^t), instead of the standard P(S^t | S^t-1), assuming we have an input variable named A.

(This type of HMM is sometimes called Input-Output HMM.)

best regards,
Marcos.

**Comment by jmschrei** [comment]
Hi Marcos

Unfortunately there is no easy way to do that right now. Potentially you could create new hidden states that correspond to the cartesian product of your original state space and A, but that seems like it might be expensive.

**Comment by jmschrei** [comment]
I'm going to close this for now, because while it is a good idea and a welcome contribution, I don't forsee myself having time to add this.
