### ISSUE TITLE
Error -model.probability([0.062, 0.114, 0.55 , 0.148, 0.06, 0.213, 0.591, 0.002, 0.041, 0.086])

### ISSUE THREAD

**Issue by Ackshay** [jmschrei/pomegranate#417]
model.probability([0.062, 0.114, 0.55 , 0.148, 0.06, 0.213, 0.591, 0.002, 0.041, 0.086])

KeyErrorTraceback (most recent call last)
<ipython-input-42-b43a70b0d780> in <module>()
----> 1 print mel.probability([0.062, 0.114, 0.55 , 0.148, 0.06, 0.213, 0.591, 0.002, 0.041, 0.086])

pomegranate/base.pyx in pomegranate.base.Model.probability()

pomegranate/BayesianNetwork.pyx in pomegranate.BayesianNetwork.BayesianNetwork.log_probability()

pomegranate/distributions.pyx in pomegranate.distributions.ConditionalProbabilityTable.log_probability()

KeyError: (0.148, 0.55)

**Comment by jmschrei** [comment]
Can you be more specific about what's going on here? BayesianNetworks don't work over continuous values yet.
