### ISSUE TITLE
Recording training improvement for HMM

### ISSUE THREAD

**Issue by ssubraveti** [jmschrei/pomegranate#419]
Is there a way to retrieve the training improvements over iteration when the fit method is called using the Baum-Welch algorithm?

**Comment by jmschrei** [comment]
Unfortunately there isn't right now. My goal is to mirror the History and Callback functionality in Keras, but I haven't gotten to it yet.

**Comment by ssubraveti** [comment]
I already assumed that existed, my bad! That would be a very useful feature indeed!! Other than that, using pomegranate has been a really awesome experience!! Great job!
