### ISSUE TITLE
Tutorial 1: Error in Monty's conditional probability table

### ISSUE THREAD

**Issue by stmax82** [jmschrei/pomegranate#42]
Not directly a bug, but...

https://github.com/jmschrei/pomegranate/blob/master/tutorials/Tutorial_1_Distributions.ipynb

The line "A', 'B', 'A', 0.5" of Monty's conditional probability table should have probability 0.0 because Monty cannot open the door the guest has chosen.

**Comment by jmschrei** [comment]
Whoops, good catch. I'll fix that soon.
