### ISSUE TITLE
Best way to stack a GMM and a HMM

### ISSUE THREAD

**Issue by yh21equn** [jmschrei/pomegranate#423]
Hello,

I want to use a GMM of a normal distribution as a state distribution of a HMM. As I don't know the parameters of the HMM, I want to learn them from the data. 

I have tried 
`gmm = GeneralMixtureModel.from_samples(NormalDistribution, n_components=2, X= someData)`
`hmm = HiddenMarkovModel.from_samples(gmm, n_components=2, X=someOtherData, labels=someLabels, algorithm="viterbi")`
but I got the error 

> TypeError: from_samples() takes at least 3 positional arguments (1 given)

When I run the code with a multivariate gaussian distribution instead of the general mixture model it works and I get quite reasonable results, but I have the specification to use a gaussian mixture model.

I have the tried specifying some start values for the transitions
`hmm = HiddenMarkovModel()`
`s1 = State(gmm)`
`s2 = State(gmm.copy())`
`model.add_states([s1, s2])`
`model.add_transition(model.start, s1, 0.5)`
`model.add_transition(model.start, s2, 0.5)`
`model.add_transition(s1, s2, 0.5)`
`model.add_transition(s1, s1, 0.5)`
`model.add_transition(s2, s1, 0.5)`
`model.add_transition(s2, s2, 0.5)`
`model.add_transition(s2, model.end, 0.5)`
`model.add_transition(s1, model.end, 0.5)`
`model.bake(verbose=True)`
`model.fit(someData, labels=someLabels, algorithm="viterbi")`
The code is running, but I don't get satisfying results, when using `model.predict(data, "viterbi") `.

I have tried running the code with 2, 4, and 6-dimensional data.

Any suggestions where I have used methods the wrong way?
What would be the correct way to stack a GMM and a HMM?

Thank you for your help

**Comment by jmschrei** [comment]
Howdy!

The second way would be the appropriate way--either initializing the GMM on the data or with random parameters before training with the HMM. However, if you copy the GMM and have equal transition parameters you're probably going to get equivalent GMMs after training as well. There are three things you can try depending on how much time you want to spend on this: 

(1) Initialize two GMMs by fitting them to two random subsets of data
(2) Initialize two GMMs manually using random values for the normal distribution means
(3) Run k-means with k=2 on the training data and initialize a GMM on each cluster.

3 is the theoretically correct way, but obviously the most work.

**Comment by yh21equn** [comment]
Hello,

thank you for your fast answer, I will try your suggestions during the next days.

I have one more question, please correct me if I am wrong, but isn't the k-means algorithm run by pomegranate if I initialize a General Mixture Model from the data using the from_samples method?

Thank you for your help!

**Comment by jmschrei** [comment]
It is, but it's also used to initialize all of the HMM components. So it needs to be run to initialize the HMM (manually), but then would automatically be run again when you initialize the GMMs.

**Comment by yh21equn** [comment]
Okay, thank you!

**Comment by yh21equn** [comment]
Hello,
I have again a question regarding my GMM-HMM: When training the model I get regularly a NaN training improvement. I have tried different fixes, that worked for others, but none worked for me.

Do you have an ideas on how to solve the problem? This is my code:

```
def multivariateGaussianCovar(numFeatures, data):
    covar = []
    for i in range(numFeatures):
        tmp = []
        for j in range(0, len(data)):
            tmp.append(data[j][i])

        covar.append(NormalDistribution.from_samples(tmp))

def getGMM(numFeatures, numComponents, data):
    mixtures = [IndependentComponentsDistribution(multivariateGaussianCovar(numFeatures, data[i])) for i in range(numComponents)]
    return GeneralMixtureModel(mixtures)

def hmm():
    model = HiddenMarkovModel()
    s0 = State(getGMM(numFeatures, centers, dataLearn1[0:8]), name="s0")
    s1 = State(getGMM(numFeatures, centers, dataLearn1[8:16]), name="s1")
    s2 = State(getGMM(numFeatures, centers, dataLearn1[16:24]), name="s2")
    s3 = State(getGMM(numFeatures, centers, dataLearn1[24:32]), name="s3")
    s4 = State(getGMM(numFeatures, centers, dataLearn1[32:40]), name="s4")
    s5 = State(getGMM(numFeatures, centers, dataLearn1[40:48]), name="s5")
    s6 = State(getGMM(numFeatures, centers, dataLearn1[48:56]), name="s6")
    s7 = State(getGMM(numFeatures, centers, dataLearn1[56:64]), name="s7")

    model.add_states([s0, s1, s2, s3, s4, s5, s6, s7])
    model.add_transition(model.start, s0, 0.5)
    model.add_transition(model.start, s4, 0.5)
    model.add_transition(s0, s1, 0.5)
    model.add_transition(s0, s0, 0.5)
    model.add_transition(s1, s1, 0.5)
    model.add_transition(s1, s2, 0.5)
    model.add_transition(s2, s2, 0.5)
    model.add_transition(s2, s3, 0.5)
    model.add_transition(s3, s3, 0.5)
    model.add_transition(s3, s4, 0.5)
    model.add_transition(s4, s4, 0.5)
    model.add_transition(s4, s5, 0.5)
    model.add_transition(s5, s5, 0.5)
    model.add_transition(s5, s6, 0.5)
    model.add_transition(s6, s6, 0.5)
    model.add_transition(s6, s7, 0.5)
    model.add_transition(s7, s7, 0.5)
    model.add_transition(s7, s0, 0.5)
    model.add_transition(s3, model.end, 0.5)
    model.add_transition(s7, model.end, 0.5)
    model.bake(verbose=True)

```

numFeatrues is between 4 and 10, centers between 2 and 8
The length of my shortest sequence is about 500.

Thank you for your help!

**Comment by jmschrei** [comment]
Without an example that fails when run it is difficult for me to assess the problem. If you're trying to fit a HMM that has multivariate Gaussian emissions with a diagonal covariance matrix I'd recommend trying `HiddenMarkovModel.from_samples(NormalDistribution, n_components=n_components, X)` where X is your list of sequences.

**Comment by remidefleurian** [comment]
Hi, 

I'm trying to build a GMM-HMM for multivariate data, and as a part of this process, wanted to perform a grid search to maximise performance based on `n_components` for both `GeneralMixtureModel` and `HiddenMarkovModel`.

With my `X` as a list of 2D sequences, and therefore `np.vstack(X)` as a single 2D vector containing all sequences, I would have hoped to perform the grid search for model training in the following way:

```
for i, j in my_grid:
    gmm = GeneralMixtureModel.from_samples(MultivariateGaussianDistribution, n_components=i, X=np.vstack(X))
    hmm = HiddenMarkovModel.from_samples(gmm, n_components=j, X=X)
```

As you mentioned above, this does not seem possible. I could specify each HMM manually, as suggested above, but this becomes impractical if `my_grid` is too large. Are you aware of any way I could easily implement this approach?

Thanks for your help!

**Comment by jmschrei** [comment]
Howdy. If you want to make a GMM-HMM, you'll need one GMM for each of the states in the HMM, rather than a single GMM. I'd recommend this process: (1) use k-means to break your data into j chunks, (2) train a GMM on each chunk, (3) build a HMM using the `from_matrix` method (uniform transitions are OK to start off with) and the trained GMM, and use `fit` to train it for a few iterations. This is ROUGHLY the same process that happens in the backend when you use HiddenMarkovModel.from_samples. However, you're currently trying to pass in a trained GMM into the HMM from_samples method, when that method takes in the callable of a distribution. Here is an outline of code that is not bug-tested, but provided just to give you a bump in the right direction.

```python
for i, j in my_grid:
    X_ = np.vstack(X)
    y_hat = KMeans(n_components=j).fit(X_).predict(X_)
    
    gmms = [GeneralMixtureModel.from_samples(MultivariateGaussianDistribution, n_components=i, X=X_[y_hat == k]) for k in range(j)] 
    hmm = HiddenMarkovModel.from_matrix(np.ones((j, j)) / float(j), gmms, starts=np.ones(j)/float(j))
```

**Comment by remidefleurian** [comment]
Amazing, thanks so much for the quick and very helpful reply. I'll give that a shot and will report back!

**Comment by remidefleurian** [comment]
Just to confirm that this works - thanks again! Just had to modify the code a tiny bit:

```python
for i, j in my_grid:
    X_ = np.vstack(X)
    y_hat = Kmeans(k=j).fit(X_).predict(X_)
    
    gmms = [GeneralMixtureModel.from_samples(MultivariateGaussianDistribution, n_components=i, X=X_[y_hat == k]) for k in range(j)] 
    hmm = HiddenMarkovModel.from_matrix(np.ones((j, j)) / float(j), gmms, starts=np.ones(j)/float(j))
    hmm.bake()
    hmm.fit(X)
```
