### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by apseyed** [jmschrei/pomegranate#43]
I tried searching for postings on this in relation to cython, with no luck. I get this error when using anaconda python or otherwise. I still receive it after upgrading numpy and cython. Any ideas appreciated:

gcc -fno-strict-aliasing -I/Users/bob/anaconda/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -I/Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/bob/anaconda/include/python2.7 -c pomegranate/base.c -o build/temp.macosx-10.5-x86_64-2.7/pomegranate/base.o
In file included from pomegranate/base.c:239:
In file included from /Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17:
In file included from /Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:
/Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning:
      "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
      [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
pomegranate/base.c:1764:8: error: 'inline' can only appear on functions
static CYTHON_INLINE double (*__pyx_f_11pomegranate_5utils__log)(double); /*proto*/
       ^
pomegranate/base.c:174:27: note: expanded from macro 'CYTHON_INLINE'
    #define CYTHON_INLINE __inline__
                          ^
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by jmschrei** [comment]
Weird! Can you post your versions of cython, numpy, scipy, and python? An issue might be that you have a partially compiled version of pomegranate which it's using as a reference. If you can find your .pyxbld folder and delete it, you can delete any cached copies you have (if you're building from the clone). Usually it lives in your home directory. If you're installing from pip, try the pomegranate folder in site packages, the associated egg folder, and reinstall using anaconda. Let me know how that goes.

**Comment by apseyed** [comment]
~/Documents/rpi/pomegranate pip show numpy
---
Name: numpy
Version: 1.10.1
Location: /Users/apseyed/anaconda/lib/python2.7/site-packages
Requires:
~/Documents/rpi/pomegranate pip show cython
---
Name: Cython
Version: 0.23.4
Location: /Users/apseyed/anaconda/lib/python2.7/site-packages
Requires:
~/Documents/rpi/pomegranate

when i tried to upgrade scipy, it errored. but reeferredt to gcc as installed via brew "  Referenced from: /usr/local/Cellar/gcc/4.9.2_1/libexec/gcc/x86_64-apple-darwin13.4.0/4.9.2/f951" and not XCode. 

but in any event:
~/Documents/rpi/pomegranate pip show scipy
---
Name: scipy
Version: 0.15.1
Location: /Users/apseyed/anaconda/lib/python2.7/site-packages
Requires:


no .pyxbld  in ~  or elsewhere.


retried from the git clone:


ld_bob/pomegranate
Storing debug log for failure in /Users/bob/.pip/pip.log
creating build/temp.macosx-10.5-x86_64-2.7

creating build/temp.macosx-10.5-x86_64-2.7/pomegranate

gcc -fno-strict-aliasing -I/Users/bob/anaconda/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -I/Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/bob/anaconda/include/python2.7 -c pomegranate/BayesianNetwork.c -o build/temp.macosx-10.5-x86_64-2.7/pomegranate/BayesianNetwork.o

In file included from pomegranate/BayesianNetwork.c:256:

In file included from /Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:

In file included from /Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:

In file included from /Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:

/Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]

#warning "Using deprecated NumPy API, disable it by " \

 ^

pomegranate/BayesianNetwork.c:1842:8: error: 'inline' can only appear on functions

static CYTHON_INLINE double (*__pyx_f_11pomegranate_5utils__log)(double); /*proto*/

       ^

pomegranate/BayesianNetwork.c:210:27: note: expanded from macro 'CYTHON_INLINE'

    #define CYTHON_INLINE __inline__

                          ^

1 warning and 1 error generated.

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /Users/bob/anaconda/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/_k/9jd0vzmn1cd8z_630yxsjwy40000gq/T/pip_build_bob/pomegranate/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/_k/9jd0vzmn1cd8z_630yxsjwy40000gq/T/pip-3q5LPe-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/_k/9jd0vzmn1cd8z_630yxsjwy40000gq/T/pip_build_bob/pomegranate
Storing debug log for failure in /Users/bob/.pip/pip.log


re: " try the pomegranate folder in site packages, the associated egg folder, and reinstall using anaconda"

try..deleting? and reinstall via anaconda not using pip?

tried:
 conda install pomegranate
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: pomegranate

thanks.

**Comment by jmschrei** [comment]
Can you try executing the following commands?

```
git clone https://github.com/jmschrei/pomegranate.git
cd pomegranate
python setup.py install
nosetests -v
```

**Comment by antiquechrono** [comment]
I ran into this but didn't have the time to post another issue. The default compiler that comes with osx is Apple's version of Clang which isn't so great. I set my compiler temporarily to use gcc48 and everything went as expected.

**Comment by jmschrei** [comment]
Excellent! I'll keep that in mind, and close this issue then. Please re-open it if you have further problems.

**Comment by apseyed** [comment]
antiquechrono, it looks like I have gcc-4.9 installed, what variable did you set and where did you set it please?

**Comment by antiquechrono** [comment]
apseyed, I just set CC to the path to wherever gcc is installed. In my case since I was doing everything on the command line I did the following which will revert when you close the terminal.

export CC=/usr/local/Cellar/gcc48/4.8.2/bin/gcc-4.8

Then you should be able to install from source or install with pip.

**Comment by jmschrei** [comment]
Thanks for the info @antiquechrono. I don't have a mac and so wasn't able to test it. I'll add this to the docs if other people encounter this issue.

**Comment by apseyed** [comment]
after setting echo $CC
/usr/local/Cellar/gcc/4.9.2_1/bin/gcc-4.9

I received the error below (building from git), but if instead of anaconda used my brew 2.7.9 version of python + pip  it completed the installation. not too surprised, I've had issues with anaconda in the past, e.g., installing matplotlib. now experimenting with the titanic example. thank you both.

building 'pomegranate.BayesianNetwork' extension
/usr/local/Cellar/gcc/4.9.2_1/bin/gcc-4.9 -fno-strict-aliasing -I/Users/bob/anaconda/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -I/Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/bob/anaconda/include/python2.7 -c pomegranate/BayesianNetwork.c -o build/temp.macosx-10.5-x86_64-2.7/pomegranate/BayesianNetwork.o
In file included from /Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:0,
                 from /Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pomegranate/BayesianNetwork.c:256:
/Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
pomegranate/BayesianNetwork.c:1842:31: warning: variable '__pyx_f_11pomegranate_5utils__log' declared 'inline'
 static CYTHON_INLINE double (*__pyx_f_11pomegranate_5utils__log)(double); /*proto*/
                               ^
In file included from /Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:27:0,
                 from /Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pomegranate/BayesianNetwork.c:256:
/Users/bob/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1634:1: warning: '_import_array' defined but not used [-Wunused-function]
 _import_array(void)
 ^
/usr/local/Cellar/gcc/4.9.2_1/bin/gcc-4.9 -bundle -undefined dynamic_lookup -L/Users/bob/anaconda/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/pomegranate/BayesianNetwork.o -L/Users/bob/anaconda/lib -o build/lib.macosx-10.5-x86_64-2.7/pomegranate/BayesianNetwork.so
ld: library not found for -lgcc_s.10.5
collect2: error: ld returned 1 exit status
error: command '/usr/local/Cellar/gcc/4.9.2_1/bin/gcc-4.9' failed with exit status 1

**Comment by jmschrei** [comment]
Excellent! Let me know if you have any other questions or concerns.

**Comment by antiquechrono** [comment]
That's pretty weird, I installed it with my anaconda installation. I updated it to python 2.7.10 though.
