### ISSUE TITLE
Multivariate hidden markov model from samples

### ISSUE THREAD

**Issue by kristinablaskova** [jmschrei/pomegranate#433]
Hello Jacob! :)

I am trying to generate a multivariate hidden markov model using from_samples and I get the following error: 
```
File "pomegranate/hmm.pyx", line 3572, in pomegranate.hmm.HiddenMarkovModel.from_samples (pomegranate/hmm.c:45060)
IndexError: boolean index did not match indexed array along dimension 0; dimension is 8690 but corresponding boolean dimension is 5173
```
The code looks as following: 
```
model = pg.HiddenMarkovModel.from_samples(pg.NormalDistribution,
    n_components = 5,
    X = observation_sequence,
    labels=hidden_sequence,
    algorithm='labeled')
```
where observation sequence is of following format:
`[[5.75379240312016, 6.02177717044245], [6.84161946071971, 7.50725082297237], [8.8507373557585, 9.63693935794127], [11.5311952310345, 11.9018999570034], [12.8223285617113, 13.142320618302]]`
where observation_sequence[i][j], means j-th features i-th value. This is a simplified sample - I work with 10 features and ±1000 sequence length.
hidden_seuqence is simply a label list (there are 5 unique labels).

I am not sure if I got the format of observation sequences correctly. Otherwise I have no idea what is wrong. Thanks for your time!

**Comment by jmschrei** [comment]
I'm going to close this for now, but feel free to re-open if you have further questions.

**Comment by jaspreetpandher** [comment]
Say I have two observation sequences O1 time stamp and O2 time stamp. Can I use the variation in O2 to make better predictions for O1 ? say improve the accuracy of my model for O1 predictions?
