### ISSUE TITLE
Defining distributions over a cyclic graphical structure

### ISSUE THREAD

**Issue by sloomba** [jmschrei/pomegranate#434]
Is it possible to define distributions for cyclic directed graphs structures as a Bayesian networks? I tried doing it, but enter into a bootstrap kinda issue while defining the CPTs for loops.

**Comment by jmschrei** [comment]
Howdy

Sorry for the late reply. I originally implemented loopy belief propogation to allow for cyclic Bayesian networks, but then did not resolve the issue for defining CPTs. The short answer is no, but the longer answer is that while the algorithmic framework is there, I hadn't worked out all the kinks before moving on.
