### ISSUE TITLE
Autogenerate API Reference missing from the docs

### ISSUE THREAD

**Issue by dmolnarqu** [jmschrei/pomegranate#435]
**API Reference** sections have no content in the docs

Example: http://pomegranate.readthedocs.io/en/latest/HiddenMarkovModel.html#api-reference

**Comment by yh21equn** [comment]
Hello 
You can switch to other versions of the Documentation at the bottom of the menu and read the API there. Just click on v:latest and then choose the docs version.

**Comment by jmschrei** [comment]
Should be fixed now. Sorry for the delay.
