### ISSUE TITLE
Bugs in HiddenMarkovModel

### ISSUE THREAD

**Issue by yh21equn** [jmschrei/pomegranate#437]
Hello,
I came across two bugs in the HiddenMarkovModel class while working with it. I am working with 8 states, where each is modeled by a Gaussian Mixture Model. I have tried learning the model with a different number of features (6, 8, 10) and a varying window size, for which I calculate the features.

The first bug I noticed is that there is a memory leak somewhere in the library. If I run a script to try different configurations, I did run out of RAM regularly (I have 8 GB of RAM). For 10 features I ran already out of RAM training only one model (hmm.fit() did never return). 

When I tried to find a work around for the first bug, I noticed the second one. I restricted the iterations of `hmm.fit()` with max_iterations, printed and stored the model in a json string, deleted the model using `del` and then tried to load the model again using `hmm.from_json()`, but I got the error `name 'GenerelMixtureModel' is not defined` .

It would be great if you could fix the bugs or if anyone could show me a way to avoid these errors.

Thank you

**Comment by jkleckner** [comment]
@yh21equn I encourage you to try your hand at debugging.  I provided a candidate script in PR #429 to set up a dev environment cleanly starting from `miniconda`.  That plus the `Makefile` from PR #424 gives you a command line way to set up your environment fully ready to type `source activate py2.7` then `jupyter notebook` or `python -u setup.py test |& tee build.out` and you're running.  For real productivity and in my opinion, `PyCharm` professional is the way to go if you use `Cython` as Pomegranate does.  I wouldn't bother programming without JetBrains tools any more...

**Comment by jkleckner** [comment]
@yh21equn Does the #447 fix allow you to save/restore the GMM-HMM?

**Comment by yh21equn** [comment]
@jkleckner I am using PyCharm and I have tried debugging, but that is difficult as the error arises first after about a quarter of an hour and I don't have the time run one debugging session for some hours.
No I am still not able to restore the GMM-HMM. Saving is possible, as it was also before.

**Comment by jkleckner** [comment]
@yh21equn Several memory leak fixes have been merged into master with #450 and #451.
Please try that version by installing pomegranate from the source tree.
Someone reported this cool way to streamline installation from source but it didn't work immediately for me: [pip install git+https://github.com/jmschrei/pomegranate.git](https://github.com/jmschrei/pomegranate/issues/333#issuecomment-336854591)

**Comment by yh21equn** [comment]
@jkleckner I still run out of memory with certain configurations of my model before the model is fully trained

**Comment by jmschrei** [comment]
@yh21equn to confirm, you've downloaded the latest code from GitHub, installed it successfully, and are still seeing these issues?

**Comment by jkleckner** [comment]
This code will install from github master:
```
conda env create --name tmp python=2.7 
source activate tmp
conda install --yes cython
pip install git+https://github.com/jmschrei/pomegranate.git
```
and this code will remove the temporary environment:
```
source deactivate
conda env remove --yes --name tmp
```

**Comment by yh21equn** [comment]
@jmschrei After downloading pomegranate a second time I still run out of memory if I train the model at once, but if I train it with shorter sequences and deleting the model in between the memory is sufficient to train the model.

**Comment by jkleckner** [comment]
@yh21equn Is it possible to extract a test case to reproduce this?

**Comment by yh21equn** [comment]
You can reproduce this with the code I send you a few weeks ago.

**Comment by jkleckner** [comment]
@yh21equn Could you put it into a gist or attach a file that can be executed?

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
