### ISSUE TITLE
problem with HMM.fit() using IndependentComponentsDistributions

### ISSUE THREAD

**Issue by dinka3737** [jmschrei/pomegranate#444]
Hello, 
I would like to fit an HMM model with IndependentComponentsDistributions of DiscreteDistributions.

# my case: 

walk_on_foot = DiscreteDistribution({100: 0.9, 0:0.1})
place_on_foot = DiscreteDistribution({100: 0.1, 0:0.9})

walk_still = DiscreteDistribution({100: 0.1, 0:0.9})
place_still = DiscreteDistribution({100: 0.9, 0:0.1})

walk_d = IndependentComponentsDistribution([walk_on_foot,walk_still])
place_d = IndependentComponentsDistribution([place_on_foot,place_still])

s1 = State( walk_d, name='walk' )
s2 = State( place_d, name='place' )

hmm = HiddenMarkovModel()

hmm.add_states(s1,s2)

hmm.add_transition( hmm.start, s1, 0.5 )
hmm.add_transition( hmm.start, s2, 0.5 )
hmm.add_transition( s1, s1, 0.9 )
hmm.add_transition( s1, s2, 0.1 )
hmm.add_transition( s2, s2, 0.9 )
hmm.add_transition( s2, s1, 0.1 )
hmm.bake()

# this works fine:
seq = [[100,0],[100,0],[0,100],[0,100]]
hmm_predictions = hmm.predict( seq )
print ("hmm pred: {}".format( ''.join( map( str, hmm_predictions ) ) ))
print
print ("hmm state 0: {}".format( hmm.states[0].name ))
print ("hmm state 1: {}".format( hmm.states[1].name ))

#output:
hmm pred: 1100
hmm state 0: place
hmm state 1: walk

# but when I try to fit the parameters:
hmm.fit(seq)

# I get this:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-429-7e0341695311> in <module>()
----> 1 hmm.fit(seq)

pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.fit (pomegranate/hmm.c:31612)()

pomegranate/hmm.pyx in pomegranate.hmm._check_input (pomegranate/hmm.c:4409)()

TypeError: 'int' object is not subscriptable

# Thank you for your help!

**Comment by jkleckner** [comment]
@dinka3737 Try `hmm.fit([seq])`

**Comment by dinka3737** [comment]
It worked!
Wow that was surprisingly easy :)
Thanks a lot!
