### ISSUE TITLE
Dependent siblings in Bayesian networks satisfying local Markov property

### ISSUE THREAD

**Issue by ilya-kolpakov** [jmschrei/pomegranate#446]
I tried to use `pomegranate` to model (the propensities for) recessive disorders in consanguineous families and it behaved as the presence of consanguinity has ho effect. The problem that occurs there can be illustrated with the following contrived example.

Assume we have a random variable `r` taking 0 and 1 with equal probaility (e.g. Bernoulli(1/2)). Now define random variables `a` and `b` as exact copies of `r` and define `s=a+b`.  Clearly, the marginal distribution of `s` is 0 and 2 with equal probabilities.

As far as I understand, this is a valid Bayesian network. Indeed, while `a` and `b` are clearly dependent they are independent conditional on `r` because neither `a` nor `b` influence given `r`. Formally, one can verify that the local Markov property
```
P(a=i,b=j|r=k) = I{i=j=k} = I{i=k AND j=k} = I{i=k}I{j=k} = P(a=i|r=k) P(b=j|r=k)
``` 
holds for all `i,j,k` from `{0,1}` where `I` denotes an indicator function.

When I am trying to this network above with `pomegranate`, however, it behaves as if `a` and `b` are sampled independently from Bernoulli(1/2). For instance, the marginal distribution of `s` inferred by `pomegranate` is not `{"0": 0.5, "2": 0.5}` but `{"0": 0.25, 1: "0.5", "2": 0.25}`

```
from pomegranate import *
from pomegranate import ConditionalProbabilityTable as CPT

from itertools import product

# Bayesian networks satisfy local markov property, e.g.
# each variable is conditionaly independent from its non-descendants
# given its parent variables. Clearly not a case here

forward1_table = [
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0],
    [1, 1, 1],
]

b_values = [0, 1]
sum_values = [0, 1, 2]
sum_table = []
for x, y, s in product(b_values, b_values, sum_values):
    p = 1 if s == (x + y) else 0
    sum_table.append([x, y, s, p])


rd = DiscreteDistribution({0: 0.5, 1: 0.5})
ad = CPT(forward1_table, [rd])
bd = CPT(forward1_table, [rd])
sd = CPT(sum_table, [ad, bd])

r = Node(rd, 'r')
a = Node(ad, 'a')
b = Node(bd, 'b')
s = Node(sd, 's')

m = BayesianNetwork('dependent_siblings')
m.add_states(r, a, b, s)
m.add_edge(r, a)
m.add_edge(r, b)
m.add_edge(a, s)
m.add_edge(b, s)
m.bake()

print(m.probability([[0, 0, 0, 0]])) # 0.5 instead of 1
print(m.probability([[1, 1, 1, 2]])) # 0.5 instead of 1

# yields {"0": 0.25, "1": 0.5, "2": 0.25}
print(m.predict_proba({}, max_iterations=1)[-1].marginal().parameters[0]) 
```

**Comment by ilya-kolpakov** [comment]
I created a small [package](https://github.com/ilya-kolpakov/bayex) that does what I need and handles [this example](https://github.com/ilya-kolpakov/bayex/blob/master/tests/test_sum_copies.py) correctly, but I am anyway quite curious why pomegranate works this way and why this issue didn't pop up earlier (as I would expect).

**Comment by jmschrei** [comment]
With respect to the probability calculations, I think that they're correct. There are two options this network can take, the first is 0 0 0 0 and the second is 1 1 1 2. So, the probability of each of these occuring should be 0.5, not 1. It's not the conditional probability of the last element given the others, it's the probability of the whole sample given the network.

With respect to the last element, the results make sense if you look at the full readout. If you know nothing about r, then both a and b have equal probabilities of occurring. Then, since according to s, a and b are both independent and uniform, the sum comes out correct according to that assumption. 

You can see that if you set r to 0 or 1 (and up max_iterations to at least 2) that you get that p(s=0
r=0) = 1 and that p(s=2|r=1) = 1.

**Comment by jmschrei** [comment]
To clarify, issues like this arise because of the use of the loopy belief algorithm. The exact algorithm may produce different results on networks that are not tree structured.

**Comment by ilya-kolpakov** [comment]
Sorry, the state probabilities are of indeed correct.

Speaking of the marginal distribution of `s`, I also noticed that it is calculated correctly if one fixes `r` as constant. In genetic models this amounts to manually iterating over shared input distributions, running the models with constant inputs and weighing the results accordingly. One could also represent siblings by one node in a graph but this option is even worse as node = person correspondence breaks down.

I am curious to see how samplers in pymc3 or stan will handle such models.
