### ISSUE TITLE
GMM returns non positive semidefinite covariances

### ISSUE THREAD

**Issue by pclucas14** [jmschrei/pomegranate#454]
Hi, 

I'm using a Gaussian Mixture Model to fit three dimensional data. After the fit, the covariances matrices returned by `model.fit(data)` are not positive semidefinite. I know this is most likely due to EM not being numerically stable, but is there an easy way to add regularization so that this issue is avoided ?

Thank you, 
Lucas

**Comment by jmschrei** [comment]
This issue should be fixed with the latest patch. Let me know if it works for you.
