### ISSUE TITLE
Missing HMM starts when creating semi-supervised HMM from_samples

### ISSUE THREAD

**Issue by robertmacyiii** [jmschrei/pomegranate#459]
I'm trying to train a semi-supervised HMM with multi-variate states and I'm running into an issue when using the HiddenMarkovModel.from_samples function. The issue is that when I use the from_samples function with semi-supervised data I get back the an error stating the starts do not exist. Below is code that reproduces the error:

```
import numpy as np
from pomegranate import HiddenMarkovModel, MultivariateGaussianDistribution

episodes = []
labelings = []

for i in range(5):
    episode = np.array([[np.random.randn() for _ in range(5)] for _ in range(20)])
    episodes.append(episode)
    labeling = None if np.random.random() < 0.5 else [np.random.choice([0,1,2]) for _ in range(20)]
    labelings.append(labeling)

model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=3, X=episodes, labels=labelings)
```

And the resulting error message:

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-17-5dd9e559d8ef> in <module>()
----> 1 model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=3, X=episodes, labels=labelings)

pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.from_samples()

pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.fit()

UnboundLocalError: local variable 'starts' referenced before assignment


```
If I make the same function call with only supervised or unsupervised data then the model is created without error.

It is only occurring when I have both labeled and unlabeled sequences in my data.

**Comment by jkleckner** [comment]
@jmschrei If semisupervised, should this be `len(starts_labeled)` ?
https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L2567

**Comment by BolunHan** [comment]
@jmschrei Same issue here. It seems simply can not fit supervised and unsupervised data at the same time.

**Comment by halolimat** [comment]
Hello all,

I see that this issue was not labeled or replied to by @jmschrei yet. Is it a bug or a limitation of pomegranate?

Thanks,
Hussein

**Comment by jmschrei** [comment]
I just pushed a commit that should fix it 1feeeb01. Can you try building from source and letting me know if that fixed your issue?

**Comment by halolimat** [comment]
That fixed the problem for me, yes!

I actually did try to fix the bug before writing here but because I saw very little improvement over the unsupervised one I though maybe there is something wrong with the algorithm other than this small fix. If you are interested I can share my scripts with you later.

Thanks so much for this great project!

**Comment by jmschrei** [comment]
As you pointed out, the user needs to pass in a list of `state_names` that match the labels passed in, and they should all be strings. I'm not sure that this is a problem but maybe worth noting here.
