### ISSUE TITLE
pip install fails on Windows

### ISSUE THREAD

**Issue by tanderberg** [jmschrei/pomegranate#46]
"pip install pomegranate" on Windows, with Anaconda and Visual C++ for Python (9.0) installed, fails as follows:

BayesianNetwork.c
  c:\anaconda\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  pomegranate\BayesianNetwork.c(1842) : error C2433: '__pyx_f_11pomegranate_5utils__log' : 'inline' not permitted on data declarations

**Comment by jmschrei** [comment]
Interesting. Is this the C compiler which comes with Anaconda, or are you using your own?

**Comment by tanderberg** [comment]
It's http://www.microsoft.com/en-us/download/details.aspx?id=44266
( essentially a bare-minimum installation of Visual Studio 2008, which is generally used to compile CPython 2.7 on Windows; see also http://docs.continuum.io/anaconda/faq#how-did-you-compile-cpython ). AFAIK, Anaconda does not include a compiler, it relies on you using the appropriate one for your platform.

**Comment by tom-christie** [comment]
I am getting a similar error with OS X 10.11.  

pomegranate/BayesianNetwork.c:1842:8: error: 'inline' can only appear on
      functions
static CYTHON_INLINE double (*__pyx_f_11pomegranate_5utils__log)(double)...
       ^
pomegranate/BayesianNetwork.c:210:27: note: expanded from macro 'CYTHON_INLINE'
    #define CYTHON_INLINE __inline__
                          ^
1 warning and 1 error generated.
error: command 'clang' failed with exit status 1

**Comment by jmschrei** [comment]
This issue should be resolved now, please re-open if not the case!

**Comment by jtorre39** [comment]
Hello, having trouble running ``` pip install pomegranate``` on a Windows 10 machine with Python 3.6.3.

I get the follow error message during installation:

```
...
   copying pomegranate\hmm.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\kmeans.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\parallel.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\utils.c -> build\lib.win-amd64-3.6\pomegranate
    copying pomegranate\utils.pxd -> build\lib.win-amd64-3.6\pomegranate
    running build_ext
    building 'pomegranate.base' extension
    error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'
```
Is it requiring Visual Studio 14.0 runtime binaries? As far as I know, there is no version 14.0.

**Comment by tanderberg** [comment]
Visual Studio 14.0 is more commonly known as Visual Studio 2015. Yes, the mix of formal version numbering and year-based branding is confusing.

**Comment by jtorre39** [comment]
Ohh right. I'll mess with my Visual Studio installation and see if the installations work after then. Thanks so much and apologies on the lack of insight on my part!
