### ISSUE TITLE
from_samples hangs

### ISSUE THREAD

**Issue by marcovc** [jmschrei/pomegranate#461]
Hi,

The from_sample routine hangs (does not return) for the degenerate case of a sample consisting of a repeatition of a single number, e.g. [3,3,3,3,3].

**Comment by jkleckner** [comment]
@marcovc As always, a simple example that can be directly run is appreciated.

**Comment by jmschrei** [comment]
Hey @marcovc , sorry that you're running into problems. As @jkleckner mentioned, a simple example would clarify what exactly the issue is so that it can be tracked down easier. Thanks!
