### ISSUE TITLE
FIX mutivariate discrete ICD Commit 324acd4 broke the build

### ISSUE THREAD

**Issue by jkleckner** [jmschrei/pomegranate#463]
A bisect of commits reveals that the `FIX mutivariate discrete ICD` patch set 324acd4 causes some tests to fail in the build.  For example: https://travis-ci.org/jmschrei/pomegranate/builds/389849084

**Comment by jkleckner** [comment]
@jmschrei  Note that a `make bigclean; make bigtest` would have revealed the failure in version `3.6` by running tests for both `2.7` and `3.6`.  Or merging it via a pull request which would have run travis on the full set of tests.

**Comment by jmschrei** [comment]
Thanks for pointing it out. I noticed the issue, but it seems random and doesn't affect the majority of functionality so I passed the buck until I had some more time. Fortunately, I think that's soon, so I'll look for a fix.

**Comment by jkleckner** [comment]
As you can see from the Travis builds, it is quite repeatable but somehow depends on the python version.  Speaking of random, could it be a change in the way that the seeds are set?  I tried the test with #439 applied but that didn't help.  You might consider reverting that to permit the Travis builds to pass and move it into a pull request until it works?

**Comment by jkleckner** [comment]
You can see that for some reason the `predict_proba()` is returning a different sort order for the 3.6 vs the 2.7 builds: https://travis-ci.org/jmschrei/pomegranate/jobs/389849092#L2186

**Comment by jmschrei** [comment]
Looks like I fixed it.
