### ISSUE TITLE
Fix example, tutorial, and benchmark notebooks

### ISSUE THREAD

**Issue by jkleckner** [jmschrei/pomegranate#467]
People often treat the included Jupyter notebooks as documentation or use it as a starting point for working on a model.  For this reason, it is highly desirable that all of them compile and execute.

The pull request #466 includes a script to build an environment to test the notebooks.  The following notebooks have errors:
```
examples/distributions_test_table.ipynb
examples/naivebayes_bayes_net.ipynb
examples/naivebayes_hmm_cheating_coin_toss.ipynb
examples/naivebayes_multivariate_male_female.ipynb
examples/naivebayes_rain_fog.ipynb
examples/naivebayes_simple_male_female.ipynb
tutorials/Tutorial_0_pomegranate_overview.ipynb
tutorials/Tutorial_1_Distributions.ipynb
tutorials/Tutorial_7_Parallelization.ipynb
tutorials/Tutorial_8_Semisupervised_Learning.ipynb
benchmarks/pomegranate_vs_hmmlearn.ipynb
benchmarks/pomegranate_vs_sklearn_gmm.ipynb
benchmarks/pomegranate_vs_sklearn_naive_bayes.ipynb
```

This was created by running 
```
./rebuildconda 2.7 pynbtest
source activate pynbtest2.7
make  EXECUTE_TIMEOUT=1800  bigclean install nbtest     >& nbtest.txt
```

With this resulting output file: [nbtest.txt](https://github.com/jmschrei/pomegranate/files/2168420/nbtest.txt)

Note that the resulting html files might have some use for documentation purposes.

**Comment by jmschrei** [comment]
This issue is out of date after my cleanup of the notebooks.
