### ISSUE TITLE
initialize parameter before from_samples()

### ISSUE THREAD

**Issue by VertexC** [jmschrei/pomegranate#469]
Hi,

In the document [from_samples](http://pomegranate.readthedocs.io/en/latest/HiddenMarkovModel.html#log-probability), it said "Regardless of the type of model, the transition matrix and start probabilities are initialized uniformly.".

Is there anyway we can initialize the model like from_matrix() first and then use from_samples() to fit the data?

Thanks!

**Comment by jmschrei** [comment]
Howdy

If you want to specify your own initialization, you can do so either by using `from_matrix` or building the model component by component using the `add_state(s)` and `add_transition` methods. You would then `bake` the model and use the `fit` method to update the parameters. Ultimately, when building a structured model, the two steps are initialization and fitting. The `from_samples` method will initialize the model uniformly randomly and then call `fit`.
