### ISSUE TITLE
Key Error when baking the network. 

### ISSUE THREAD

**Issue by jayneeee** [jmschrei/pomegranate#470]
```network = BayesianNetwork( "fire" )
network.add_states(s0, s1, s2, s3,s4, s5,s6)

network.add_transition( s0, s1 )
network.add_transition( s0, s2 )
network.add_transition( s1, s5)
network.add_transition( s2, s5 )
network.add_transition( s3, s5 )
network.add_transition( s4, s5 )
network.add_transition( s5, s6 )
```

I was trying to bake my network and I encouter 'key error'  problem. 
```
KeyError: ('M', 'LL')
```
I have multiple bin in all my states: LL, L , M , H ,HH. However I face this problem when I bake the network. There's no further description on the error I'm having here.

**Comment by jayneeee** [comment]
```
for i in name:
    df_transform[i] = pd.cut(merged_file[i], 5, labels=["HH", "H", "M" , "L" , "LL"])
    
df_transform.dropna()
df_transform = pd.concat([piTag_file[['DayOfYear','fire']],df_transform], axis =1)

cond_prob_a = df_transform.groupby('b_Anomaly')['a_Anomaly'].value_counts()/df_transform.groupby('b_Anomaly')['a_Anomaly'].count()
prob_a = cond_prob_a.reset_index(name = 'count').values

```
Above is my snippet on how i calculate the data distribution

```
array([['HH', 'HH', 0.7401574803149606],
       ['HH', 'H', 0.1141732283464567],
       ['HH', 'M', 0.0984251968503937],
       ['HH', 'L', 0.03937007874015748],
       ['HH', 'LL', 0.007874015748031496],
       ['H', 'HH', 0.6078431372549019],
       ['H', 'M', 0.1568627450980392],
       ['H', 'H', 0.11764705882352941],
       ['H', 'LL', 0.0784313725490196],
       ['H', 'L', 0.0392156862745098],
       ['M', 'HH', 0.4],
       ['M', 'M', 0.4],
       ['M', 'L', 0.16666666666666666],
       ['M', 'H', 0.03333333333333333],
       ['L', 'L', 1.0],
       ['LL', 'M', 0.4166666666666667],
       ['LL', 'L', 0.20833333333333334],
       ['LL', 'HH', 0.16666666666666666],
       ['LL', 'LL', 0.16666666666666666],
       ['LL', 'H', 0.041666666666666664]], dtype=object)
```
Here is the output of the probability. 
```
b = DiscreteDistribution(((df_transform['b_Anomaly'].value_counts())/len(df_transform)).to_dict())
a = ConditionalProbabilityTable(prob_a , [a])
```
Here is a snippet of the CDT using pomegranate method like the Asia example. 
```
s0 = State( b name="b" )
s1 = State( a, name="a" )
.... 

network = BayesianNetwork( "fire" )
network.add_states(s0, s1,s2,s3,s4,s5,s6)

network.add_transition( s0, s1 )
network.add_transition( s0, s2 )
network.add_transition( s1, s5)
network.add_transition( s2, s5 )
network.add_transition( s3, s5 )
network.add_transition( s4, s5 )
network.add_transition( s5, s6 )
```
So there are 6 nodes in total, here I'm showing part of the method I use to calculate the conditional probability table.  I suspect that the package faced error when there's no available probability for the given combination between some nodes.

**Comment by jayneeee** [comment]
Besides, my python kernel stop working when I try to initialize the DiscreteDistribution() and ConditionalProbability()

**Comment by jmschrei** [comment]
Sorry for not getting back to you sooner-- we had a paper submission due yesterday.

Yes, you need to include all combinations of keys in the `ConditionalProbabilityTable` even if those values are 0. There may be some benefit to additionally including a `SparseConditionalProbabilityTable` for cases where there are many 0's, but I don't think that I'm going to have time to add that.

`model.plot` is the method for plotting graphical models, either BayesianNetworks or HiddenMarkovModels. You might want to install pygraphviz to get better looking plots, if you don't have it installed already.

**Comment by jeev20** [comment]
> I have solved the issue by including all the combination and assigning 0 as their probability for baking. 

@jayneeee do you have a rough code snippet showing how you achieved this? I am getting the "key error" and now know that is because not all combinations are listed in my resulting dataframe. Thank you in advance!
