### ISSUE TITLE
Does a Numpy array represent one sequence per row or column?

### ISSUE THREAD

**Issue by rzu512** [jmschrei/pomegranate#475]
Hi. 

If I supply a numpy array to the X parameter of "[from_samples()](http://pomegranate.readthedocs.io/en/latest/HiddenMarkovModel.html#pomegranate.hmm.HiddenMarkovModel.from_samples)" of hidden markov model, does the method treat each row or each column of X as one sequence?

Thanks.

**Comment by jmschrei** [comment]
Data should be provided to a hidden Markov model in the form of a list of sequences. If you provide a 2D array, it will assume that your sequences are the rows and that it should build a univariate model. If you provide a list of 1D numpy arrays it will also assume that. If you provide a list of 2D numpy arrays (even if it's just a single numpy array because you only have one sequence) then it will assume it's multivariate. 

The reason that one should provide a list of elements rather than a numpy array is that HMM sequences can be variable length that numpy arrays can be bad at encoding, whereas other ML models require fixed length feature sets which numpy arrays are good at encoding.

**Comment by rzu512** [comment]
When pomegranate builds a multi-variable hidden Markov model, does it assume two different variables cannot have the same value?

I give the hidden Markov model a 2d Boolean array with shape (n_variables, length). 
The i<sup>th</sup> row as measurement of the i<sup>th</sup> observable variable. 
Each observable variable is either true or false at any time.
I want to build a multi-variable hidden Markov model that predicts the values of all the _n_ variables at time t + 1 from the values of all the _n_ variables at time t.

The json file from pomegranate describes two states. One of the state has parameters [1.0]. The other state has parameters [0.0]. I expect each hidden variable corresponds to several values of the observable variables. For example, hidden variable A might corresponds to observable variable 1 being True with an emission probability of 0.3, and observable variable 2 being False with an emission probability of 0.2.

Code I wrote:
```python
import pomegranate as pg
import h5py
n_hidden_var = 2
# seqs has dtype=bool, shape=(31765, 41250)
seqs = h5py.File('data.hdf5')['key'].value.T
model = pg.HiddenMarkovModel.from_samples(
    pg.BernoulliDistribution, n_components=n_hidden_var, X=seqs, 
    batch_size=5000, verbose=True, n_jobs=12)
with open('hmm%d.json' % n_hidden_var, 'w+') as f:
    f.write(model.to_json())
```

json file that I get:
```json
{
    "class" : "HiddenMarkovModel",
    "name" : "None",
    "start" : {
        "class" : "State",
        "distribution" : null,
        "name" : "None-start",
        "weight" : 1.0
    },
    "end" : {
        "class" : "State",
        "distribution" : null,
        "name" : "None-end",
        "weight" : 1.0
    },
    "states" : [
        {
            "class" : "State",
            "distribution" : {
                "class" : "Distribution",
                "name" : "BernoulliDistribution",
                "parameters" : [
                    1.0
                ],
                "frozen" : false
            },
            "name" : "s0",
            "weight" : 1.0
        },
        {
            "class" : "State",
            "distribution" : {
                "class" : "Distribution",
                "name" : "BernoulliDistribution",
                "parameters" : [
                    0.0
                ],
                "frozen" : false
            },
            "name" : "s1",
            "weight" : 1.0
        },
 ...
```

**Comment by jmschrei** [comment]
If you pass in input of size (n, d) it will assume that you are passing in `n` sequences of length `d` that has only one feature. If you're trying to pass in a single sequence of length `n` with `d` features you should pass in a list that has this array as the single element, like ```X = [numpy.random.randint(2, size=(n, d))]```
