### ISSUE TITLE
gcc-4.8: error: unrecognized command line option '-Wshorten-64-to-32'

### ISSUE THREAD

**Issue by Narsail** [jmschrei/pomegranate#48]
Hey guys,

i have trouble installing pomegranate. First i got the same problem as in this issue:
https://github.com/jmschrei/pomegranate/issues/43

After installing gcc 4.8.4 with homebrew (i'm running OSX) and using it for the compiling process i got the following error:

    (ENV)Davids-MacBook-Pro:~ davidmoeller$ pip install pomegranate
    Collecting pomegranate
    Using cached pomegranate-0.3.2.tar.gz
    Requirement already satisfied (use --upgrade to upgrade): cython>=0.22.1 in ./ENV/lib/python2.7/site-packages (from pomegranate)
    Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.0 in ./ENV/lib/python2.7/site-packages (from pomegranate)
    Requirement already satisfied (use --upgrade to upgrade): joblib>=0.9.0b4 in ./ENV/lib/python2.7/site-packages (from pomegranate)
    Requirement already satisfied (use --upgrade to upgrade): networkx>=1.8.1 in ./ENV/lib/python2.7/site-packages (from pomegranate)
    Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in ./ENV/lib/python2.7/site-packages (from networkx>=1.8.1->pomegranate)
    Building wheels for collected packages: pomegranate
    Running setup.py bdist_wheel for pomegranate
    Complete output from command /Users/davidmoeller/ENV/bin/python -c "import setuptools;__file__='/private/var/folders/6h/12sm_tdx4t98pz0gh2h8yc_80000gn/T/pip-build-yMxOa5/pomegranate/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/6h/12sm_tdx4t98pz0gh2h8yc_80000gn/T/tmpS3hn_hpip-wheel-:
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-intel-2.7
    creating build/lib.macosx-10.11-intel-2.7/pomegranate
    copying pomegranate/__init__.py -> build/lib.macosx-10.11-intel-2.7/pomegranate
    running build_ext
    building 'pomegranate.BayesianNetwork' extension
    creating build/temp.macosx-10.11-intel-2.7
    creating build/temp.macosx-10.11-intel-2.7/pomegranate
    /usr/local/Cellar/gcc48/4.8.4/bin/gcc-4.8 -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/Users/davidmoeller/ENV/lib/python2.7/site-packages/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pomegranate/BayesianNetwork.c -o build/temp.macosx-10.11-intel-2.7/pomegranate/BayesianNetwork.o
    gcc-4.8: error: unrecognized command line option '-Wshorten-64-to-32'
    error: command '/usr/local/Cellar/gcc48/4.8.4/bin/gcc-4.8' failed with exit status 1
  
    ----------------------------------------
    Failed building wheel for pomegranate
    Failed to build pomegranate
    Installing collected packages: pomegranate
    Running setup.py install for pomegranate
    Complete output from command /Users/davidmoeller/ENV/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/6h/12sm_tdx4t98pz0gh2h8yc_80000gn/T/pip-build-yMxOa5/pomegranate/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/6h/12sm_tdx4t98pz0gh2h8yc_80000gn/T/pip-ubIz2L-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/davidmoeller/ENV/include/site/python2.7/pomegranate:
    running install
    running build
    running build_py
    running build_ext
    building 'pomegranate.BayesianNetwork' extension
    /usr/local/Cellar/gcc48/4.8.4/bin/gcc-4.8 -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/Users/davidmoeller/ENV/lib/python2.7/site-packages/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pomegranate/BayesianNetwork.c -o build/temp.macosx-10.11-intel-2.7/pomegranate/BayesianNetwork.o
    gcc-4.8: error: unrecognized command line option '-Wshorten-64-to-32'
    error: command '/usr/local/Cellar/gcc48/4.8.4/bin/gcc-4.8' failed with exit status 1
    
    ----------------------------------------
    Command "/Users/davidmoeller/ENV/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/6h/12sm_tdx4t98pz0gh2h8yc_80000gn/T/pip-build-yMxOa5/pomegranate/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/6h/12sm_tdx4t98pz0gh2h8yc_80000gn/T/pip-ubIz2L-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/davidmoeller/ENV/include/site/python2.7/pomegranate" failed with error code 1 in /private/var/folders/6h/12sm_tdx4t98pz0gh2h8yc_80000gn/T/pip-build-yMxOa5/pomegranate

Maybe the problem depends on the failed wheel problem? Did someone had an similar error already?

best regards,
David

**Comment by Narsail** [comment]
So, i used a different approach and develop my script in a virtual environment using ubuntu with virtual box. Pomegranate is working fine there and this issue is not important anymore.

**Comment by jmschrei** [comment]
Thanks for the report. To reiterate, you were working on a mac, and gcc-4.8 did not work, but when switching to a virtual environment with gcc installed natively it worked fine?

**Comment by Narsail** [comment]
First one is correct, i was working on OSX but after running into those problems i decided to work on my script in its destination os - Ubuntu. So now it is running on ubuntu 14.04 flawless. but i wasn't able to solve the problems on the mac.
