### ISSUE TITLE
Example of Belief Propagation over Factor Graph

### ISSUE THREAD

**Issue by qillbel** [jmschrei/pomegranate#481]
Dear author,

I was looking for an example of how belief propagation works over a factor graph with this module. But I couldn't find it. Would you kindly provide me with how can i construct a factor graph and run belief propagation over it.

Thank you very much.

**Comment by jmschrei** [comment]
There isn't an example in this repository but you might find this chapter informative: http://helper.ipam.ucla.edu/publications/gss2013/gss2013_11344.pdf
