### ISSUE TITLE
BayesianNetwork.plot() Requires pygraphviz which is not working new python modules

### ISSUE THREAD

**Issue by singhsumeet4471** [jmschrei/pomegranate#484]
Hi ,

I ma trying to plot Bayesian network on windows 10 with python 3.6 , the plot function requires pygraphviz which has lot of issue installing , can you guys please provide a way around for that .

Thanks is advance.

Regards,
Sumeet Singh

**Comment by jmschrei** [comment]
There currently isn't a good alternative to pygraphviz for plotting network structures. If you use something like networkx the plots tend to be giant jumbles of nodes. There is no built-in way to visualize networks without pygraphviz, but you're free to use the graph attribute (a networkx digraph) of the BayesianNetwork object to plot however you want.
