### ISSUE TITLE
NameError: name 'numpy' is not defined

### ISSUE THREAD

**Issue by bosonnoir** [jmschrei/pomegranate#487]
The following code (in python 3.5)
```
from pomegranate import *
b = BernoulliDistribution(0.5)
b.sample()
```
raises `NameError: name 'numpy' is not defined`.

I have installed pomegranate through pip.

I am not an expert at Cython, but it could be that the file [BernoulliDistribution.pyx](https://github.com/jmschrei/pomegranate/blob/master/pomegranate/distributions/BernoulliDistribution.pyx) does not `import numpy`.

**Comment by jmschrei** [comment]
Oops, you're exactly right. I just pushed a fix. You'll have to get the most recent version manually from GitHub. Thanks for reporting.
