### ISSUE TITLE
 [QUESTION] HMM with NormalDistribution works, but GammaDistribution on same sample fails.

### ISSUE THREAD

**Issue by AlexEngelhardt** [jmschrei/pomegranate#490]
Hi Jacob,

I've switched from hmmlearn to pomegranate because I saw I could use a Gamma distribution for the states' emssions. However, when I tried running it on my data, I got it to work for a Normal distribution, but not for the Gamma. This is what I did:

    from pomegranate import HiddenMarkovModel, GammaDistribution, NormalDistribution
    import numpy as np
    
    XX = np.random.normal(loc=100, scale=100, size=1000)
    XX[200:400] = np.random.normal(loc=800, scale=400, size=200)
    XX = XX.reshape(-1, 1)
    
    # Gaussian works:
    
    model = HiddenMarkovModel.from_samples(NormalDistribution, n_components=2, X=XX)
    model.fit(XX)
    
    # Gamma doesn't work:
    
    model2 = HiddenMarkovModel.from_samples(GammaDistribution, n_components=2, X=XX)
    model2.fit(XX)
    
    # ValueError: shapes (862,1) and (862,1) not aligned: 1 (dim 1) != 862 (dim 0)

The 'shapes' in the ValueError have a different value every time I run the command. E.g., sometimes it says "shapes (141,1) and (141,1) not aligned [...]".

It feels like I've overlooked something simple. Do you have any idea on what I missed?

Thanks in advance,

Alex

**Comment by AlexEngelhardt** [comment]
Hi Jacob,

(1) and (2) were embarrassing mistakes on my part - sorry.

I tried installing pomegranate from the GitHub repo, but I got an error that `pomegranate/base.c` was not found:

    alexx@thinkpad:~/Downloads/pomegranate$ sudo python3 setup.py install
    running install
    running bdist_egg
    running egg_info
    writing pomegranate.egg-info/PKG-INFO
    writing dependency_links to pomegranate.egg-info/dependency_links.txt
    writing requirements to pomegranate.egg-info/requires.txt
    writing top-level names to pomegranate.egg-info/top_level.txt
    reading manifest file 'pomegranate.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'pomegranate/*.c'
    writing manifest file 'pomegranate.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    running build_py
    running build_ext
    building 'pomegranate.base' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/alexx/.local/lib/python3.6/site-packages/numpy/core/include -c pomegranate/base.c -o build/temp.linux-x86_64-3.6/pomegranate/base.o
    x86_64-linux-gnu-gcc: error: pomegranate/base.c: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

I also tried `pip3 install pomegranate-master.zip`, but it failed with the same error.

**Comment by jmschrei** [comment]
Howdy

Sorry that you ran into that error. Maybe the solutions in this issue will help? https://github.com/jmschrei/pomegranate/issues/314
