### ISSUE TITLE
Manually building package fails 

### ISSUE THREAD

**Issue by AlexEngelhardt** [jmschrei/pomegranate#493]
Hi Jacob,

I am working with pomegranate locally, but now have tried uploading the module to a Databricks environment.

I had to build it manually (I cloned your repo and did `python3 setup.py bdist_egg`) because I am using your latest commit cd3d2c61299445a77b0cc5dbf7118038f5428d9b, so installing from pip wasn't possible.

Now when importing pomegranate in a Databricks notebook, I get this error:

```
import pomegranate

AttributeError: type object 'pomegranate.base.Model' has no attribute '__reduce_cython__'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-3972833059749100> in <module>()
----> 1 import pomegranate

/databricks/python/lib/python3.5/importlib/_bootstrap.py in _find_and_load(name, import_)

/databricks/python/lib/python3.5/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/databricks/python/lib/python3.5/importlib/_bootstrap.py in _load_unlocked(spec)

/databricks/python/lib/python3.5/importlib/_bootstrap.py in _load_backward_compatible(spec)

/local_disk0/spark-e45e095c-82b1-478a-82b1-61d2c8599856/userFiles-d1ec1ee9-82b1-82b1-82b1-82b1478a9a11/addedFile7945009797548016438dbfs__FileStore_jars_17e33beb_478a_82b1_478a_7a478a528f44_pomegranate_0_10_0_py3_6_linux_x86_64_bbf0-920b2.egg/pomegranate/__init__.py in <module>()
      9 import os
     10 
---> 11 from .base import *
     12 from .parallel import *
     13 
```

I found cython/cython#1953, where you also commented, but I have zero experience with cython, so I don't  understand if that is relevant here. In the discussion it sounds like this issue shouldn't happen anymore with cython version >= 0.28 (I have 0.28.5 installed).

Do you have any hints on how to work around this? Let me add that I built the package locally with Python 3.7, but Databricks runs Python 3.5.

I suspect a new PyPI release from you would help me, because then I could install the package with pip instead of manually building it.

Thanks in advance for any help,

Alex

**Comment by jkleckner** [comment]
@AlexEngelhardt I don't have the cycles at the moment to dig further, but that thread and some experience I have had in the past suggests that the directory from which you run it matters.  Specifically, if I import it while in a separate directory for testing, it works but has issues when invoked directly in the source directory.

**Comment by jmschrei** [comment]
Howdy @AlexEngelhardt . Sorry you're running into build problems. I wasn't planning on releasing another version for at least another month and it's a bit of a pain to get one out due to the cython build. Is it possible that you have an old installation of pomegranate somewhere on that machine? That seems to be what causes this issue a lot. There are also other closed issues here of people overcoming this issue, maybe those will be helpful?

**Comment by AlexEngelhardt** [comment]
Hi there,

I haven't found the issue, but I found a workaround that keeps me happy for the next month(s): I've ported your E- and M-steps for the Gamma distribution to hmmlearn, which is slow, but working on Databricks.

It'll take us a few months until we run our stuff on *all* the data, so speed is currently not an issue, and I'll gladly wait for the update :)

Thanks again for your help!
