### ISSUE TITLE
Continuous HMM with Gaussian Mixture Emissions

### ISSUE THREAD

**Issue by fhopp** [jmschrei/pomegranate#494]
Hi all, 
more of an open question than an issue report: 

I am trying to build a 4-state HMM whose input sequence consists of an array of vectors, where each vector has 19 dimensions consisting of ratios of different random variables. Each vector corresponds to daily ratios of observations.

My hunch is to use Gaussian Mixture Models to model the emissions in each state and to use slightly different means and standard deviations to differentiate between certain states (my states correspond to different societal phases, e.g., conflict, social unrest, peaceful, etc.) and each observation vector captures daily ratios of different event types and news frames (e.g., protest, public statements, etc.)). 

Once the model has been trained, I would like to examine the emission probability for each of the 19 variables in each state. Further,  I would like to sample from it vectors based on the current state I am in and compare the generated vector with the actual observed vector in the test set.

To accomplish this, is this the correct plan-of-action:
1) Model each state with a General Mixture Model that consists of M different Normal Distributions (how do I assign different emission probabilities to each variable?) 

2) Train model with Baum-Welch 

I appreciate any kind of feedback and help for my M.A. thesis. 
Thanks!

**Comment by jmschrei** [comment]
Howdy

I'm not sure that you want a GeneralMixtureModel for modeling different variable, it sounds like you just want a multivariate distribution. This can be achieved either through a MultivariateGaussianDistribution, if you'd like to model the full covariance matrix, or a IndependentComponentsDistribution with whatever distribution modeling each feature that you'd like.

After training the model, you can examine the learned parameters by going through each of the states in the model and printing the distribution, like `for state in model.states; print state.distribution`. pomegranate doesn't currently allow you to sample from midway through a sequence, but if you'd like to by yourself I would suggest first running the forward-backward algorithm on what you've observed in the sequence so far (using `model.predict_proba`) and then continue manually, generating a single sample for each state and then taking the dot product of those samples and the probabilities of being in each state.

Let me know if you have any other questions

**Comment by fhopp** [comment]
Thanks for the prompt response -- yeah a multivariate does make more sense. 
I'll try that and shoot an update.
Thanks much James!
