### ISSUE TITLE
Is N_jobs working for fitting or structure learning?

### ISSUE THREAD

**Issue by marchezinixd** [jmschrei/pomegranate#497]
Is n_jobs working? I tried to put 1,2,3,4 when fitting, always the same time and result, always using only one core.
Actually setting n_jobs does not affect neither structure learning nor fitting. I'm handling a subset of my dataset that have 100 variables and 5 million rows, but the full have 5000 variables with 5 million rows. If this is not parallel it will not be possible for me to run.

**Comment by jmschrei** [comment]
Which algorithm are you using? The default, `greedy`, does not currently use multiple jobs, and I should modify the documentation to mention that. I think that using multiple cores could be added, but I don't know when I'd have time to do it. I can try a quick prototype this week but sometimes multithreading in Python doesn't give you the performance gains you'd like.

You can see that basically what is happening here https://github.com/jmschrei/pomegranate/blob/master/pomegranate/BayesianNetwork.pyx#L1705 is that you greedily go through the variables and see which one would be the best to add to the growing chain of variables in the model. https://github.com/jmschrei/pomegranate/blob/master/pomegranate/BayesianNetwork.pyx#L1711 is the compute intensive line, and what you could do is calculate those values in parallel and then take the best.

**Comment by marchezinixd** [comment]
Actually i tried greedy, exat and chow-liu. chow-liu only uses the 4 cores in the last minute. But i'll see what i can do to make this faster. Thankyou

**Comment by jmschrei** [comment]
Parallelizing BNSL is certainly underserved in pomegranate. I'm sorry this is making things difficult for you. I'll let you know if I make any progress.
