### ISSUE TITLE
Multivariate (Indep. Comp. Distribution) hidden Markov model from samples

### ISSUE THREAD

**Issue by abuettner93** [jmschrei/pomegranate#501]
I noticed that it is impossible to initialize an HMM from multivariate samples using an IndependentComponentsDistribution, using labeled or unlabeled training.

In hmm.pyx (line 3617), I can see why. The hmm.pyx 'from_samples' method uses the 'from_samples' method for the particular distribution it is given, which is fine for a MultivariateGaussian, for example, but fails for an IndependentComponentsDistribution because the hmm from_samples method does not allow the user to pass in a list (or even single type of) distribution to initialize it with. I am trying to use an ICD with discrete distributions, but cannot pass in the discrete distributions through from_samples. 

Simply put, an IndependentComponentsDistribution is a multivariate distribution, but it cannot be used as one directly in the HMM 'from_samples' method.

From hmm.pyx:
```
if distribution is DiscreteDistribution:
                keymap = numpy.unique(X_)

                distributions = []
                for label in label_set:
                    d = DiscreteDistribution({key: 1. / len(keymap) for key in keymap})
                    d.fit(X_[labels_ == label])
                    distributions.append(d)
            else:
                (THIS IS THE POINT OF FAILURE)
                distributions = [distribution.from_samples(
                    X_[labels_ == label]) for label in label_set]

            if len(label_set) != n_components:
                raise ValueError("Specified {} components, but only {} different "
                    "labels observed".format(n_components, len(label_set)))
```

From IndependentComponentsDistribution.pyx:

```
	@classmethod
	def from_samples(self, X, weights=None, distribution_weights=None,
		pseudocount=0.0, distributions=None):
		"""Create a new independent components distribution from data."""
                (THIS IS THE POINT OF FAILURE, because a list of distributions is not passed)
		if distributions is None:
			raise ValueError("must pass in a list of distribution callables")
```

**Comment by abuettner93** [comment]
Update:  I modified the code to allow for using IndependentComponentDistributions in a fairly simplistic way.

I added an optional variable to the HiddenMarkovModel.from_samples method called 'independent_dists' with a default value of None.

Then in the HiddenMarkovModel class added a check for ICD's and then passed in the list of components.


From hmm.pyx (line ~3608)
```
            if distribution is DiscreteDistribution:
                keymap = numpy.unique(X_)

                distributions = []
                for label in label_set:
                    d = DiscreteDistribution({key: 1. / len(keymap) for key in keymap})
                    d.fit(X_[labels_ == label])
                    distributions.append(d)
            else:
                if distribution is IndependentComponentsDistribution:
                    if independent_dists is None:
                        raise TypeError("Using an independent components distribution but did not pass in the distribution types!")
                        
                    distributions = [distribution.from_samples(
                    X_[labels_ == label], distributions=independent_dists) for label in label_set]
                else:
                    distributions = [distribution.from_samples(
                        X_[labels_ == label]) for label in label_set]
```

Not sure if raising the TypeError is appropriate, but I figured it was a decent stand in for now.

**Comment by abuettner93** [comment]
This fix is only for labeled training (I havent implemented it in the unlabeled training, but should work the same way). My last question is how to ensure each state (in this case a ICD with DiscreteDistributions inside) maintains values present in each ICD across all states, even those that werent fit with those values. 

Basically, if ICD1 has two DiscreteDistributions with keys (1,2,3) and (2,3,4) respectively, and ICD2 has to DDs with keys (1,2,3) and (4,5,6) is there a good way to force both ICDs/DDs to have keys (1,2,3) and (1,2,3,4,5,6)?

**Comment by abuettner93** [comment]
@jmschrei I assume there is still not support for mixing discrete and continuous distributions?

**Comment by jmschrei** [comment]
Howdy @abuettner93. Currently there is not support for mixing discrete and continuous distributions. I'm working my way through pomegranate issues right now so I'll try to get back to you with a fix for this soon.

**Comment by jmschrei** [comment]
You can indicate that you'd like the states to have IndependentComponentDistributions by passing in a list of distributions to the HMM's `from_sample` methods, with one distribution per feature. There still isn't support for mixing continuous and categorical variables unfortunately.

**Comment by tetraptych** [comment]
Thanks for the response, @jmschrei. 

Do you have an example of how to pass a list of distributions to `HiddenMarkovModel.from_samples` when `labels` is also passed? I am running into an error `AttributeError: 'list' object has no attribute 'from_samples'` (from [this line](https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L3628)) when attempting to do so. 

If `labels` is not passed, then it looks like [these lines](https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L3672-L3674) use `IndependentComponentDistributions`, as you describe above. I wonder if something similar would be possible for the labeled case?

**Comment by gurusachin** [comment]
@jmschrei  **when `labels` is passed**, it seems impossible to pass a list of distributions in the from_samples method, so that they end up running as an independentComponentDistribution. 

As rightly pointed out by @tetraptych in the above comment. Do we have any solution for this ?

**Comment by AdeLouis** [comment]
Hi, @jmschrei Thanks for pomegranate. Awesome package.

It seems I am running into the same exact issues the other users on this issue were having. Is there a current alternative since this was raised?

@gurusachin did you happen to have a way to solved this issue in your case?
