### ISSUE TITLE
Robust from_json

### ISSUE THREAD

**Issue by DeanLa** [jmschrei/pomegranate#502]
I am training many models of different classes. I save each one using `to_json()` method.
Is there an implementation to load the model robustly without prior knowledge?
Something along the lines of `pomegranate.from_json(json_string)`

**Comment by DeanLa** [comment]
If no such method exists, could this issue be marked as enhancement? I might pick it up myself.

**Comment by jmschrei** [comment]
There isn't currently one, but this sounds like a great idea. If you'd like to pick it up I'd love the contribution!

**Comment by ReiDa8684** [comment]
I tried from_json and from_yaml for a HiddenMarkovModel which I first exported with to_json and to_yaml.
In both cases I get the error: "string indices must be integers"

**Comment by jmschrei** [comment]
Should be added in to the next version (0.12.0).
