### ISSUE TITLE
variational learning hidden markov models

### ISSUE THREAD

**Issue by paulbrodersen** [jmschrei/pomegranate#507]
First of all, thanks for this fantastic package. It is an absolute pleasure to work with.
Nearly everything just works, and the API is simple, powerful, and sane (and normally you only ever get two of the three). 

Secondly, I wondered if using your framework it is possible to do variational learning for HMMs
(or whether you have any plans to supporting it in the future).
The basic idea is that you specify a conjugate prior for each parameter of the HMM,
which you then condition on when determining the updates for the the model parameters after each forward-backward pass. Section 3 in [this paper](http://www.robots.ox.ac.uk/~parg/pubs/varhmm_dsp2002.pdf) gives a nice concise overview.

The reason that I am asking is that I have a bunch of labelled data sets, so I have a pretty good idea 
of what my state occupancies, transition probabilities, and emisson parameters should be (roughly);
however, at the moment I often run into the problem that a state that I know to be rare complete takes over and has most of the sequence assigned to it.

**Comment by jmschrei** [comment]
Howdy

Sorry for the late reply. The simple answer is that I don't currently support variational learning for HMMs, and I don't have any current plans to support it. However, my main focus now is to make it easy for you to write your own extensions to pomegranate and add in this feature yourself if you'd like. I'll be keeping people aware of my additions.
