### ISSUE TITLE
Bayes Net tutorials missing

### ISSUE THREAD

**Issue by Wesserg** [jmschrei/pomegranate#513]
Hi Jacob,

Wanted to refresh my memory on the structure learning algorithms that you are using (especially the "exact" ones) but the tutorials on https://pomegranate.readthedocs.io/en/latest/BayesianNetwork.html have error 404. I found ipynb files in "tutorials/old" but they also seem not to work. Just a heads up.

Meanwhile would you be able to direct me to some more detailed description of the algorithms that you have implelemtned? "exact-dp" especially:D

Regards
Sergiusz Wesolowski

**Comment by jmschrei** [comment]
Ruh roh. If you look at the tutorials folder in the GitHub repo you should find the new tutorials, which should cover a superset of the content of the previous notebooks. I need to update those links though.

As for "exact-dp", you should check out this paper that describes the algorithm: https://www.aaai.org/ocs/index.php/AAAI/AAAI11/paper/download/3788/4000

**Comment by Wesserg** [comment]
I somehow managed to miss the new tutorials. Thanks.
