### ISSUE TITLE
Add warning message that cupy was not found

### ISSUE THREAD

**Issue by AmebaBrain** [jmschrei/pomegranate#514]
https://github.com/jmschrei/pomegranate/blob/c91c80b50c2e9ea4c5edcadad7e314c1abbb3178/pomegranate/distributions/MultivariateGaussianDistribution.pyx#L14

If you use `MultivariateGaussianDistribution` with GPU enabled and **don't** have cupy installed code defauts cupy to `object`

```
try:
	import cupy
except:
	cupy = object
```

It results into non obvious error messsage

> AttributeError: type object 'object' has no attribute 'array'
Exception ignored in: 'pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution._log_probability'
AttributeError: type object 'object' has no attribute 'array'
Exception ignored in: 'pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution._summarize'

As result pomegranate creates model with 0 for all parameters and actually couldn't calculate anything

It would be good to have more descriptive warning in exception hanler. Smth similar to
> Attention!!! GPU is enabled and MultivariateGaussianDistribution is used but cupy is not installed
Couldn't continue calculation

**Comment by jmschrei** [comment]
Good catch. If you attempt to enable a GPU without cupy installed, you will now get the following warning: `Warning: Please install cupy before attempting to utilize a GPU.`
