### ISSUE TITLE
fit() takes at least 1 positional argument (0 given)

### ISSUE THREAD

**Issue by hassheh** [jmschrei/pomegranate#515]
Here is the code. I have the latest update.

`from pomegranate import*
dists = [NormalDistribution(5, 1), NormalDistribution(1, 7), NormalDistribution(8,2)]`
`trans_mat = numpy.array([[0.7, 0.3, 0.0],[0.0, 0.8, 0.2],[0.0, 0.0, 0.9]])`
`starts = numpy.array([1.0, 0.0, 0.0])`
`ends = numpy.array([0.0, 0.0, 0.1])`
`model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts, ends)`

`from pomegranate import*`
`#s1=Sleep, s2=Meal, s3=Fasting`
`s1 = State( Distribution( NormalDistribution(5, 2) ) )`
`s2 = State( Distribution( NormalDistribution(5, 2) ) )`
`s3 = State( Distribution( NormalDistribution(5, 2) ) )`
`model = HiddenMarkovModel()`
`model.add_states(s1, s2, s3)`
`model.add_transition(model.start, s1, 1.0)`
`model.add_transition(s1, s1, 0.5)`
`model.add_transition(s1, s2, 0.5)`
`model.add_transition(s2, s2, 0.5)`
`model.add_transition(s2, s3, 0.5)`
`model.add_transition(s3, s2, 0.5)`
`model.add_transition(s3, s1, 0.5)`
`model.add_transition(s3, s3, 0.5)`
`model.add_transition(s3, model.end, 0.1)`
`model.bake()`

`sequence = sequence.reshape(sequence.shape[0], 1)`
`results = model.fit(sequence, algorithm='baum-welch')`

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> pomegranate/distributions/distributions.pyx in pomegranate.distributions.distributions.Distribution.from_summaries()
> 
> pomegranate/distributions/distributions.pyx in pomegranate.distributions.distributions.Distribution.fit()
> 
> TypeError: fit() takes at least 1 positional argument (0 given)
> 
> Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._from_summaries'
> Traceback (most recent call last):
>   File "pomegranate/distributions/distributions.pyx", line 202, in pomegranate.distributions.distributions.Distribution.from_summaries
>   File "pomegranate/distributions/distributions.pyx", line 144, in pomegranate.distributions.distributions.Distribution.fit
> TypeError: fit() takes at least 1 positional argument (0 given)

**Comment by jmschrei** [comment]
You've written:

```
s1 = State( Distribution( NormalDistribution(5, 2) ) )
s2 = State( Distribution( NormalDistribution(5, 2) ) )
s3 = State( Distribution( NormalDistribution(5, 2) ) )
```

Try: 

```
s1 = State( NormalDistribution(5, 2) )
s2 = State( NormalDistribution(5, 2) )
s3 = State( NormalDistribution(5, 2) )
```

Are you seeing the first in an example? I recall one mistakenly had similar code a while ago but I thought I fixed it.
