### ISSUE TITLE
Fitting featurized HMM for NER

### ISSUE THREAD

**Issue by jpsain** [jmschrei/pomegranate#520]
Thank you very much for this great package.

We are trying to implement supervised and unsupervised variants of a **featurized** HMM. However, we were not able to figure this out even after looking at the issues #485, #129, and #57 

What we are trying to do is to use large feature space (around 12,000 dimensions) for NER, similar to what can be seen in the figure below from [this paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.661.1919&rep=rep1&type=pdf):
![screen shot 2018-11-17 at 11 13 05 pm](https://user-images.githubusercontent.com/20939709/48668561-6e4c9a80-eabe-11e8-94bd-04fc45a7ca0c.png)

We also found [this resource](http://curtis.ml.cmu.edu/w/courses/index.php/Featurized_HMM) but we are not sure if this is feasible in pomegranate.

Best,
Joy

**Comment by jpsain** [comment]
After passing feature vectors in place of the emission nodes using the following configuration, we were able to have an improvement of 0.20 F-Scores.
**HiddenMarkovModel.from_samples(BernoulliDistribution, ...)**

**Comment by jmschrei** [comment]
Sorry for not responding to this sooner. I don't really know what a "featurized" HMM is. If what you're saying is that you want to pass in multi-dimensional inputs, you have a few options. The first is what you did, which will model each of your features independently using Bernoulli distributions. The second is that you can model each feature in your data as a different probability distribution if you think appropriate, e.g., modeling time using an exponential distribution, standard deviation using a log-normal distribution, etc. This can be done either by passing in a list of distributions in the place of `BernoulliDistribution` as you've done, or by building the model one node at a time and using `IndependentComponentDistributions`. Lastly, you can use a multivariate Gaussian distribution if you'd like to explicitly model the covariance amongst features. I'm glad to see you got a nice improvement in your scores though.

**Comment by jpsain** [comment]
Thank you so much for your response.

Unfortunately, we are getting _"Memory Error"_ while using **dense** feature vectors (600K dim.).
I was wondering if we can use **sparse** matrices.

Thank you.

**Comment by halolimat** [comment]
Hi Jacob,

We've been trying to use summarize as you suggested but it seems we are doing it wrong and that's whey we are getting very low values in comparison with NLTK's HMM.

This is the function we use to initialize the HMM and then call summarize on the data chunks:

```python

def init_HMM(state_names):
    model = HiddenMarkovModel("HMM")
    
    d1 = []
    d2 = []

    for _ in range(2):
        p = random.uniform(0, 1)
        d1.append(BernoulliDistribution(p))
        d2.append(BernoulliDistribution(1-p))

    s1 = State(IndependentComponentsDistribution(d1), name=state_names[0])
    s2 = State(IndependentComponentsDistribution(d2), name=state_names[1])

    model.add_states([s1, s2])

    p = random.uniform(0, 1)
    model.add_transition(model.start, s1, p)
    model.add_transition(model.start, s2, 1-p)

    p = np.random.dirichlet(np.ones(3),size=1)[0]
    model.add_transition(s1, s1, p[0])
    model.add_transition(s1, s2, p[1])
    model.add_transition(s1, model.end, p[2])

    p = np.random.dirichlet(np.ones(3),size=1)[0]
    model.add_transition(s2, s1, p[0])
    model.add_transition(s2, s2, p[1])
    model.add_transition(s2, model.end, p[2])

    model.bake(verbose=True)

    return model
```

We've gone through the tutorials and the code but we were not successful in doing it correctly.
If you would like, I can also share with you my code for training NLTK's HMM and Pomegranate's HMM  on the same data.

Thanks very much,
Hussein

**Comment by jmschrei** [comment]
It would be good to see your training scheme as well. There might be an issue with semi-supervised training, but I wouldn't be able to pinpoint it until I have a test example.

**Comment by halolimat** [comment]
Sure, here is my script:
https://gist.github.com/halolimat/8cb3787723eed7cd905e9b5d69559421

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
