### ISSUE TITLE
Error check crash if test data contains node values not present in training data

### ISSUE THREAD

**Issue by Pfunk55** [jmschrei/pomegranate#523]
First, thanks very much for your work on this project and making it available.

My problem is that I split my data set into train and test data and use the training data to learn the Bayesian network structure. If I then use the model to predict the test data, if the test data contains node values that were not present in the training data, the program crashes at Bayesian_Network.check_input 133. I would imagine that the preferred behavior would be to allow a flag that disables this error check; and that predict, when confronted with an unknown node value in evidence, would treat that node as if it didn't exist (predict from other node values). Not sure if there is a work around. Thanks.

**Comment by jmschrei** [comment]
You can now define a superset of keys for each column that the model will include even if they don't occur in the training set.
