### ISSUE TITLE
Add state names to DiscreteDistribution returned by .predict_proba()

### ISSUE THREAD

**Issue by thomastiotto** [jmschrei/pomegranate#527]
I am creating a model in such a way
```
model = pg.BayesianNetwork.from_samples(df.values,
	                                        algorithm='exact',
	                                        root=-1, max_parents=-1,
	                                        state_names=df.columns,
	                                        name="Breast Cancer Data",
	                                        n_jobs=8)
```
and then calling
`posterior = model.predict_proba(evidence, n_jobs=8)`

It would be very useful if the DiscreteDistribution objects returned inside `posterior` also had the State name attached, as defined when creating the model.  As it is now, the name is simply "DiscreteDistribution" for all the objects of the array.
I've had to implement a hacky workaround to keep track of the state name in `posterior`.

**Comment by jmschrei** [comment]
When you make predictions, each column of the returned matrix should correspond to the same column in your original data. What do you see as being the additional benefit of attaching the state name to the distribution?

**Comment by Tioz90** [comment]
I realise that, but it still means keeping track of state names by other means, instead of having the name baked into the object.
I am iterating over the states while generating some text that includes the state names and I'm having to use a counter to keep track of the state name, while it would be so easy to simply do something like
`state.name()` instead of `df.columns[state_counter]`.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
