### ISSUE TITLE
[Request] Usage examples/tutorial on creating BN from counts matrix

### ISSUE THREAD

**Issue by jolespin** [jmschrei/pomegranate#528]
If someone has real data in the form of counts or attributes like the iris dataset.  How could one created a network from this? 

For example, the iris dataset.  How could one connect the nodes and get the structure from the data alone? 

[![enter image description here][1]][1]

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/r55sH.png
  [2]: https://i.stack.imgur.com/Ctjuf.png

**Comment by jmschrei** [comment]
Conceptually, one can create a linear Gaussian Bayesian network (rather than a categorical / discrete Bayesian network) from continuous values. However, that's not implemented in pomegranate. Unfortunately, you'll have to either find a way to discretize your values or use another tool :(
