### ISSUE TITLE
KeyError when learning a HMM with 'from_samples()' method and 'labeled' algorithm 

### ISSUE THREAD

**Issue by maximtrp** [jmschrei/pomegranate#529]
I'm building a simple HMM using `from_samples()` method:

```
import pomegranate as pom
import numpy as np

polA_pri = list('VISYDNYVTILDEETLKAWIAKLEKAPVFAFDTETDSLDNISANLVGLSFAIEPGVAAYIPVAHDYLDAPDQISRERALELLKPLLEDEKALKVGQNLKYDRGILANYGIELRGIAFDTMLESYILNSVAGRHDMDSLAERWLKHKTITFEEIAGKGKNQLTFNQIALEEAGRYAAEDADVTLQLHLKMWPDLQKHKGPLNVFENIEMPLVPVLSRIERNGVKIDPKVLHNHSEELTLRLAELEKKAHEIAGEEFNLSSTKQLQTILFEKQGIKPLKKTPGGAPSTSEEVLEELALDYPLPKVILEYRGLAKLKSTYTDKLPLMINPKTGRVHTSYHQAVTATGRLSSTDPNLQNIPVRNEEGRRIRQAFIAPEDYVIVSADYSQIELRIMAHLSRDKGLLTAFAEGKDIHRATAAEVFGLPLETVTSEQRRSAKAINFGLIYGMSAFGLARQLNIPRKEAQKYMDLYFERYPGVLEYMERTRAQAKEQGYVETLDGRRLYLPDIKSSNGARRAAAERAAINAPMQGTAADIIKRAMIAVDAWLQAEQPRVRMIMQVHDELVFEVHKDDVDAVAKQIHQLMENCTRLDVPLLVEVGSGENWDQAH')
polA_sec = list('NNNBBBBBBNNNHHHHHHHHHHHHNBBBBBBBBBBBNNNTTTNNBBBBBBBBBNNBBBBBBNNNNNNNNNNNNNHHHHHHHHHHHHNNNNNNBBBBBHHHHHHHHHTTTNNNNNBBBBHHHHHHHHNHHHNNNNHHHHHHHHNNNNNNNHHHHHNNHHHNNNHHHNNHHHHHHHHHHHHHHHHHHHHHHHHHNNNNHHHHHHHHHNHHHHHHHHHHHHHHNBBBNHHHHHHHHHHHHHHHHHHHHHHHHHBBBNNNNNTTTTNHHHHTTTNNNNNNNNNNNNNNTTTNNHHHHHTTTNNHHHHHHHHHHHHHHHHHTTTTHHHHNNTTTBBBNNBBBBBNNBBBNNBBBBBNHHHNNBBBHHHHHHHHNNNNNNNBBBBBBBBNNHHHHHHHHHNNNHHHHHHHHNNNNHHHHHHHHHNNNNHHHNNHHHHHHHHHHHHHHHNNNNNNHHHHHHNNNTTTHHHHHHHHHHHNHHHHHHHHHHHHHHHHHBBBBNNNNNBBBNTTTTNNNHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHNNBBBBBBBBNNBBBBBBBTTTHHHHHHHHHHHHHHNNNBBBNNNBBBBBBBBHHHHN')
secondary_str_types = ['N','B','H','T']

model = pom.HiddenMarkovModel.from_samples(pom.DiscreteDistribution, n_components=len(secondary_str_types), X=np.array(polA_pri)[:,None], labels=np.array(polA_sec)[:,None], algorithm='labeled')
```

and getting a `KeyError`:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
KeyError: 'N'
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
KeyError: N
---------------------------------------------------------------------------
```

I've tried to encode `string` labels with integers and got the same error. I think it is not an expected behavior.

**Comment by ryan-lang** [comment]
I chased this for a while today and discovered that the `state_names` parameter needs to be provided when calling `from_samples()`.  If it is not provided, default state names will be used like `s0, s1`, and these will not map back to your provided `labels`, and this causes the key error.

So in this example, you'd want:

```python
model = pom.HiddenMarkovModel.from_samples(pom.DiscreteDistribution, n_components=len(secondary_str_types), X=np.array(polA_pri)[:,None], labels=np.array(polA_sec)[:,None], state_names=secondary_str_types, algorithm='labeled')
```

**Comment by A-Fisk** [comment]
Currently having this issue when passing in state names as well. 

I thought it was something to do with how I was passing in the signals and labels but I think they are what is asked in the docs. 
Signals = list with single sequence array in it
labels = list with list of labels for every observation in the signal sequence

`
from pomegranate import HiddenMarkovModel, NormalDistribution
import numpy as np

signals = np.random.poisson(100, size=(10*8640))
labels = list(np.random.randint(low=1, high=6, size=len(signals)))
n_components = len(np.unique(labels))
state_names = ["state{}".format(x) for x in range(1, n_components+1 )]

hmm = HiddenMarkovModel.from_samples(
	distribution = NormalDistribution,
	n_components = n_components,
	X = [signals],
	labels = [labels],
	algorithm = 'labeled',
	state_names = state_names
)

`

Getting a KeyError in response 

`
KeyError                                  Traceback (most recent call last)
KeyError: '3'
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
KeyError: 3
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
KeyError: '3'
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
KeyError: 3

`

If I try and pass in the labels as a list with an array in it I get 

' 
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
'

**Comment by A-Fisk** [comment]
I'm also getting this error, but I'm providing the state_names as well. Not sure if its something about how I'm feeding in the signals and labels but I think I've put them in as it says in the docs. 

Example 
```
from pomegranate import HiddenMarkovModel, NormalDistribution
import numpy as np

signals = np.random.poisson(100, size=(10*8640))
labels = list(np.random.randint(low=1, high=6, size=(len(signals))))

n_components = len(np.unique(labels))
state_names = ["state{}".format(x) for x in range(1, n_components+1 )]

hmm = HiddenMarkovModel.from_samples(
	distribution = NormalDistribution,
	n_components = n_components,
	X = [signals],
	labels = [labels],
	algorithm = 'labeled',
	state_names = state_names
)
```

output 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
KeyError: 2
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
KeyError: 2
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
KeyError: 2
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
KeyError: 2
```

If I remove the list() around the labels construct and just feed it as a list of arrays then I get 

``` 
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
``` 

Hoping there's something I've missed here.

**Comment by jmschrei** [comment]
Howdy. I have a paper deadline on the 30th I'm trying to make, but I'll get to this shortly after that. Sorry for the delay.

**Comment by A-Fisk** [comment]
Great, thanks for that, hope it makes sense and you can figure it out!

**Comment by jmschrei** [comment]
Your labels don't match your state names. Each label needs to be one of the names you give to the states in state_names. Further, because you can include silent states in your labels between observations, you must explicitly specify `{name}-start` as the first state in your label sequence, where `{name}` is the name of your model (default `None`, so `None-start` is the first name). The documentation online will soon be updated.

**Comment by A-Fisk** [comment]
Fantastic, thanks for looking into this.
