### ISSUE TITLE
Bayesian network- greedy search takes too long

### ISSUE THREAD

**Issue by karnatapu** [jmschrei/pomegranate#533]
I have a data set of 25k rows, 30 features and each feature have 10-15 states. When I run my program using from_samples using greedy search. It is taking more than an hour and still running. Is there any way to tune method? Or am i missing something here.

**Comment by TeeRev** [comment]
You are encountering the exponential explosion in computation time that is common to all Bayesian networks, not just this package. 30 features at 10 states per feature implies 10**30 possible combinations across the joint distribution.
