### ISSUE TITLE
Clustering purchase sequences using a mixture of (first-order) Markov models

### ISSUE THREAD

**Issue by sophie-mtz** [jmschrei/pomegranate#534]
Hello,

I have more of a conceptual question, as I feel like pomegranate might be able to solve this task, I'm just not sure how to get started. The idea is to model purchase sequences as Markov chains and then cluster them using Expectation Maximization.  
Since you mention the possibility to stack different types of models, is it possible to run a mixture model on a Markov model? Or is there another way you would recommend to do this?

The data contains sequences of products purchased - the goal is to cluster the customers according to those sequences.
e.g. [['X', 'Y', 'Y'], ['X', 'Z'], ['Z', 'V', 'X', 'X', 'Z'], ...]

Thanks a lot in advance!

**Comment by jmschrei** [comment]
If you have a group of Markov chains you should be able to do something like 

```
d1 = MarkovChain....
d2 = MarkovChain...
d3 = MarkovChain...

model = GeneralMixtureModel([d1, d2, d3])
```

You should then be able to fit and make predictions using `model`. When you make predictions on a sequence, the mixture model will return the chain that is most likely, effectively clustering customers by the chain that most likely explains their purchasing behavior.

Let me know if you have any other issues.
