### ISSUE TITLE
how to generate a (graph, score) dataset

### ISSUE THREAD

**Issue by shalijiang** [jmschrei/pomegranate#537]
Thanks for your contribution!

I was wondering if I could use this tool to generate a meta dataset M of {graph, score} for a given dataset D? 
So the graph_i (e.g. a Bayes net) in M is used to model dataset D, and we can compute some score_i indicating the quality of the model such as likelihood. The graphs (DAGs) could be randomly generated. 
Thanks!

**Comment by jmschrei** [comment]
I'm not sure what the question is. You can either build graphs manually, or through the `BayesianNetwork.from_structure` method which takes in a tuple, where each item in the tuple is a tuple of the parents of that node. You can calculate the probability of the data set given the model using the `probability` or `log_probability` methods, respectively.
