### ISSUE TITLE
How create a HMM with GMM emissions

### ISSUE THREAD

**Issue by danimtk** [jmschrei/pomegranate#538]
Is there any example of how to create an HMM with GMM emissions from training data? Thanks!

**Comment by markov10000** [comment]
I have the same question. If mixture Gaussian Distribution were a distribution type, things would be as simple as  
HiddenMarkovModel.from_samples(MixtureGaussianDistribution(n_components=3), n_components=5, X=X)

**Comment by jmschrei** [comment]
Unfortunately I don't think that I'll have time to add in support for defining stacked models. However, you can always write a custom distribution that is just a wrapper for a GMM with the distributions that you want. See the custom distribution tutorial for examples on how to do that.

**Comment by teoML** [comment]
@markov10000 , @danimtk  - did you try implementing such a behaviour?
