### ISSUE TITLE
Deepcopy does not work as expected

### ISSUE THREAD

**Issue by YuriOsokin** [jmschrei/pomegranate#539]
I create HMM object. Check its id. Then I do a .copy(), and recheck the id. They are equal.

**Comment by YuriOsokin** [comment]
I create HMM object. Check its id. Then do a .copy(), and recheck the id. They are equal.

**Comment by jmschrei** [comment]
You're expecting that the ID should be different if you do a deep copy?

**Comment by YuriOsokin** [comment]
I created the HMM model. I trained its .copy(). The original model changed as well. I suppose deep copy should prevent it. I checked the ID of both objects, because if they have different ID while both exist, it indicates that they are different. Do I have a flaw in my logic?

**Comment by jmschrei** [comment]
That's weird. No, you shouldn't train the second one and have the first one train. I had thought that `copy` was serializing the model and reading it back in, creating entirely new objects. Can you try serializing the model using `to_json`, reading it back in using `from_json`, and see if that works as a deep copy?
