### ISSUE TITLE
'NoneType' object has no attribute 'log_probability' in baked BayesianNetwork

### ISSUE THREAD

**Issue by bearloga** [jmschrei/pomegranate#544]
Implementing some BNs from the _Risk Assessment and Decision Analysis with Bayesian Networks_ 2nd Ed. book (chapter 8) and encountered an following error where I don't think I should.

```python
import pomegranate as pg

expert_accuracy = pg.DiscreteDistribution({'Inaccurate': 0.5, 'Accurate': 0.5})
product_quality = pg.DiscreteDistribution({'Bad': 0.5, 'Good': 0.5})
measured_product_quality = pg.ConditionalProbabilityTable(
    [['Inaccurate', 'Bad', 'Bad', 0.6],
     ['Inaccurate', 'Bad', 'Good', 0.4],
     ['Inaccurate', 'Good', 'Bad', 0.4],
     ['Inaccurate', 'Good', 'Good', 0.6],
     ['Accurate', 'Bad', 'Bad', 0.9],
     ['Accurate', 'Bad', 'Good', 0.1],
     ['Accurate', 'Good', 'Bad', 0.1],
     ['Accurate', 'Good', 'Good', 0.9]],
    [expert_accuracy, product_quality]
)

e1 = pg.Node(expert_accuracy, 'Expert 1 accuracy')
e2 = pg.Node(expert_accuracy, 'Expert 2 accuracy')
e3 = pg.Node(expert_accuracy, 'Expert 3 accuracy')
pq = pg.Node(product_quality, 'Product Quality')
m1 = pg.Node(measured_product_quality, 'Measurement 1')
m2 = pg.Node(measured_product_quality, 'Measurement 2')
m3 = pg.Node(measured_product_quality, 'Measurement 3')
```

Here's the first model which works fine:

![Model 1 diagram](https://user-images.githubusercontent.com/1807519/51499200-541d8a00-1d97-11e9-81d3-e8abe5b49528.png)

```python
model = pg.BayesianNetwork('Single expert, multiple measurements')
model.add_states(pq, e1, m1, m2, m3)
model.add_edge(pq, m1)
model.add_edge(e1, m1)
model.add_edge(pq, m2)
model.add_edge(e1, m2)
model.add_edge(pq, m3)
model.add_edge(e1, m3)
model.bake()

print(model.predict_proba([None, None, 'Good', 'Bad', 'Good']))
```

```
[{
    "class" :"Distribution",
    "dtype" :"str",
    "name" :"DiscreteDistribution",
    "parameters" :[
        {
            "Bad" :0.34653006997362445,
            "Good" :0.6534699300263755
        }
    ],
    "frozen" :false
}
 {
    "class" :"Distribution",
    "dtype" :"str",
    "name" :"DiscreteDistribution",
    "parameters" :[
        {
            "Inaccurate" :0.685424131169515,
            "Accurate" :0.3145758688304849
        }
    ],
    "frozen" :false
}
 'Good' 'Bad' 'Good']
```

So far so good! But then this other model has problems:

![Model 2 diagram](https://user-images.githubusercontent.com/1807519/51499290-b1b1d680-1d97-11e9-91e5-59846fe2bea2.png)

```python
model2 = pg.BayesianNetwork('Multiple experts, single measurement per expert')
model2.add_states(pq, e1, e2, e3, m1, m2, m3)
model2.add_edge(pq, m1)
model2.add_edge(e1, m1)
model2.add_edge(pq, m2)
model2.add_edge(e2, m2)
model2.add_edge(pq, m3)
model2.add_edge(e3, m3)
model2.bake()

print(model2.predict_proba([None, None, None, None, 'Good', 'Bad', 'Good']))
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-a94530d6021d> in <module>
----> 1 print(model2.predict_proba([None, None, None, None, 'Good', 'Bad', 'Good']))

pomegranate/BayesianNetwork.pyx in pomegranate.BayesianNetwork.BayesianNetwork.predict_proba()

pomegranate/FactorGraph.pyx in pomegranate.FactorGraph.FactorGraph.predict_proba()

pomegranate/distributions/JointProbabilityTable.pyx in pomegranate.distributions.JointProbabilityTable.JointProbabilityTable.marginal()

AttributeError: 'NoneType' object has no attribute 'log_probability'
```

That shouldn't happen, right? Or am I missing something obvious why `model` is a-OK but `model2` is not? Thanks in advance!

**Comment by MartinBagaram** [comment]
I think it is a bug. I have two models that are the same, one works and the other does not

**Comment by bearloga** [comment]
By the way, just tested this in 0.11.0 (since the issue was posted when 0.10.0 was the latest available version) and I still get the same error.

**Comment by MartinBagaram** [comment]
Same here I just installed mine and I get the error. I don't know how it is handled internally, but sometimes changing just the order of defining states and edges may work

**Comment by mrucker** [comment]
Any updates on this?

**Comment by jmschrei** [comment]
Sorry for the late reply. It looks like there's an issue when you re-use distribution objects. The model will bake fine, and plot fine, but won't turn into a factor graph properly. All I did was copy each repeated variable into its own object, and the example ran. I'm not sure what the expected output would be so I haven't checked, but this code

```python
import matplotlib.pyplot as plt
import pomegranate as pg

expert_accuracy1 = pg.DiscreteDistribution({'Inaccurate': 0.5, 'Accurate': 0.5})
expert_accuracy2 = pg.DiscreteDistribution({'Inaccurate': 0.5, 'Accurate': 0.5})
expert_accuracy3 = pg.DiscreteDistribution({'Inaccurate': 0.5, 'Accurate': 0.5})

product_quality = pg.DiscreteDistribution({'Bad': 0.5, 'Good': 0.5})

measured_product_quality1 = pg.ConditionalProbabilityTable(
    [['Inaccurate', 'Bad', 'Bad', 0.6],
     ['Inaccurate', 'Bad', 'Good', 0.4],
     ['Inaccurate', 'Good', 'Bad', 0.4],
     ['Inaccurate', 'Good', 'Good', 0.6],
     ['Accurate', 'Bad', 'Bad', 0.9],
     ['Accurate', 'Bad', 'Good', 0.1],
     ['Accurate', 'Good', 'Bad', 0.1],
     ['Accurate', 'Good', 'Good', 0.9]],
    [expert_accuracy1, product_quality]
)

measured_product_quality2 = pg.ConditionalProbabilityTable(
    [['Inaccurate', 'Bad', 'Bad', 0.6],
     ['Inaccurate', 'Bad', 'Good', 0.4],
     ['Inaccurate', 'Good', 'Bad', 0.4],
     ['Inaccurate', 'Good', 'Good', 0.6],
     ['Accurate', 'Bad', 'Bad', 0.9],
     ['Accurate', 'Bad', 'Good', 0.1],
     ['Accurate', 'Good', 'Bad', 0.1],
     ['Accurate', 'Good', 'Good', 0.9]],
    [expert_accuracy2, product_quality]
)


measured_product_quality3 = pg.ConditionalProbabilityTable(
    [['Inaccurate', 'Bad', 'Bad', 0.6],
     ['Inaccurate', 'Bad', 'Good', 0.4],
     ['Inaccurate', 'Good', 'Bad', 0.4],
     ['Inaccurate', 'Good', 'Good', 0.6],
     ['Accurate', 'Bad', 'Bad', 0.9],
     ['Accurate', 'Bad', 'Good', 0.1],
     ['Accurate', 'Good', 'Bad', 0.1],
     ['Accurate', 'Good', 'Good', 0.9]],
    [expert_accuracy3, product_quality]
)


e1 = pg.Node(expert_accuracy1, 'Expert 1 accuracy')
e2 = pg.Node(expert_accuracy2, 'Expert 2 accuracy')
e3 = pg.Node(expert_accuracy3, 'Expert 3 accuracy')
pq = pg.Node(product_quality, 'Product Quality')
m1 = pg.Node(measured_product_quality1, 'Measurement 1')
m2 = pg.Node(measured_product_quality2, 'Measurement 2')
m3 = pg.Node(measured_product_quality3, 'Measurement 3')

model2 = pg.BayesianNetwork('Multiple experts, single measurement per expert')
model2.add_states(pq, e1, e2, e3, m1, m2, m3)
model2.add_edge(pq, m1)
model2.add_edge(e1, m1)
model2.add_edge(pq, m2)
model2.add_edge(e2, m2)
model2.add_edge(pq, m3)
model2.add_edge(e3, m3)
model2.bake()

print(model2.predict([[None, None, None, None, 'Good', 'Bad', 'Good']]))
```

yields the following output:
```python
[array(['Good', 'Accurate', 'Inaccurate', 'Inaccurate', 'Good', 'Bad',
       'Good'], dtype=object)]
```

also not that I switched from

```
model2.predict([None, None, None, None, 'Good', 'Bad', 'Good'])
```

to

```
model2.predict([[None, None, None, None, 'Good', 'Bad', 'Good']])
```

where I'm passing in a list of lists. 

Let me know if that works for you!

**Comment by mrucker** [comment]
Oh boy, the man himself. Thanks for taking the time to respond. 

Unfortunately, I think my case is a little different because I'm not reusing any of my distributions. So none of the dictionary lookups used while making the FactorGraph should be broken.

I'm currently deep into the BayesianNetwork.pyx code and hope to have it figured out tomorrow. My best guess right now is that my network has relationships the FactorGraph is struggling to deal with for some reason. I've gone ahead and attached an image of my network.

I'll post more information once I figure out what my issue is. Or, in the meantime, if you have any ideas I'm open to hearing them.

Thanks!

![APRI BBN 0 5](https://user-images.githubusercontent.com/966578/56694783-7d5ef680-66b5-11e9-8edb-7bf1a98d6a82.png)

**Comment by jmschrei** [comment]
If you have code that implements that (which raises an error) I can take a stab at seeing whether I can determine the issue.

**Comment by mrucker** [comment]
It's hard to turn that offer down :). Yeah let me make a few changes and I'll get you something here soon.

**Comment by mrucker** [comment]
`import pomegranate as pm
import numpy as np

train = np.array([["a", "b", "c", "d", "e", "f", "g", "h", "i"]])

#our prior distribution p(a)
p_a = pm.DiscreteDistribution.from_samples(train[:,0])

#our conditional dependence p(b|a)
p_b = pm.ConditionalProbabilityTable.from_samples(train[:,[0,1]], [p_a])

#our conditional dependence p(c|a,b)
p_c = pm.ConditionalProbabilityTable.from_samples(train[:,[0,1,2]], [p_a, p_b])

#our conditional dependence p(d|b,c)
p_d = pm.ConditionalProbabilityTable.from_samples(train[:,[1,2,3]], [p_b, p_c])

#our conditional dependence p(d|b,c)
p_e = pm.ConditionalProbabilityTable.from_samples(train[:,[1,2,4]], [p_b, p_c])

#our conditional dependence p(g|b,c)
p_g = pm.ConditionalProbabilityTable.from_samples(train[:,[1,2,6]], [p_b, p_c])

#our conditional dependence p(f|b,c,g)
p_f = pm.ConditionalProbabilityTable.from_samples(train[:,[1,2,6,5]], [p_b, p_c, p_g])

#our conditional dependence p(i|b,c)
p_i = pm.ConditionalProbabilityTable.from_samples(train[:,[1,2,8]], [p_b, p_c])

#our conditional dependence p(h|b,c,i)
p_h = pm.ConditionalProbabilityTable.from_samples(train[:,[1,2,8,7]], [p_b, p_c, p_i])

model = pm.BayesianNetwork()

s1 = pm.State(p_a, name="a")
s2 = pm.State(p_b, name="b")
s3 = pm.State(p_c, name="c")
s4 = pm.State(p_d, name="d")
s5 = pm.State(p_e, name="e")
s6 = pm.State(p_f, name="f")
s7 = pm.State(p_g, name="g")
s8 = pm.State(p_h, name="h")
s9 = pm.State(p_i, name="i")

model.add_states(s1, s2, s3, s4, s5, s6, s7, s8, s9)

model.add_edge(s1, s2)

model.add_edge(s1, s3)
model.add_edge(s2, s3)

model.add_edge(s2, s4)
model.add_edge(s3, s4)

model.add_edge(s2, s5)
model.add_edge(s3, s5)

model.add_edge(s2, s6)
model.add_edge(s3, s6)

model.add_edge(s2, s7)
model.add_edge(s3, s7)

model.add_edge(s2, s8)
model.add_edge(s3, s8)

model.add_edge(s2, s9)
model.add_edge(s3, s9)

model.bake()

print(model.predict([[None, None, None, "d", "e", "f", "g", "h", "i"]]))`

**Comment by mrucker** [comment]
Alright, well I feel dumb. This is why you should never code alone. In the process of extracting my code and packaging it up to send to you I found a bug with my model's edges. I fixed that and now I have a new error. I'll tinker around with it some more tomorrow. Probably another bug on my part. Thanks again for your time!!!

**Comment by jmschrei** [comment]
Glad I could be of help. :)

**Comment by mrucker** [comment]
Just wanted to follow up, everything is working great today! 

The bug I hit at the end of yesterday also ended up being on my side of the world.

**Comment by bearloga** [comment]
Thanks for the clarification @jmschrei! Hm, I'm not sure how widely spread this use-case is but maybe worth noting in the documentation that CPT objects can be re-used but distribution objects can't?

**Comment by mechaman** [comment]
@mrucker Would you mind mentioning exactly what the issue was with your network? I am running into the same issue, but not re-using any distributions. Thanks!

**Comment by mrucker** [comment]
@mechaman I wish I could remember. I've moved on to other projects and no longer have access to that code. It was something with how I was passing in nodes. It made my graph dependencies incorrect. As you say, it had nothing to do with re-using distributions for me. My suggestion is to simplify your network and check things bit by bit rather than trying to trace the error back. I wasted a few days trying to trace the error back, but things were just too complex for me to get anywhere with that approach.

**Comment by medhamansi** [comment]
import math
from pomegranate import *
import pomegranate as pg
guest= pg.DiscreteDistribution({'A':1./3,'B':1./3,'C':1./3})
prize= pg.DiscreteDistribution({'A':1./3,'B':1./3,'C':1./3})
monty=pg.ConditionalProbabilityTable(
    [['A','A','A',0.0],
     ['A','A','B',0.5],
     ['A','A','C',0.5],
     ['A','B','A',0.0],
     ['A','B','B',0.0],  
     ['A','B','C',1.0], 
     ['A','C','A',0.0], 
     ['A','C','B',1.0], 
     ['A','C','C',0.0], 
     ['B','A','A',0.0], 
     ['B','A','B',0.0], 
     ['B','A','C',1.0], 
     ['B','B','A',0.5],
     ['B','B','B',0.0], 
     ['B','B','C',0.5], 
     ['B','C','A',1.0], 
     ['B','C','B',0.0], 
     ['B','C','C',0.0], 
     ['C','A','A',0.0], 
     ['C','A','B',1.0], 
     ['C','A','C',0.0],
     ['C','B','A',1.0], 
     ['C','B','B',0.0], 
     ['C','B','C',0.0], 
     ['C','C','A',0.5], 
     ['C','C','B',0.5], 
     ['C','C','C',0.0]],[guest,prize])   
    
s1=pg.State(guest,name="guest")
s2=pg.State(prize,name="prize")
s3=pg.State(monty,name="monty")
network=pg.BayesianNetwork("Monty Hall Problem")
network.add_states(s1,s2,s3)
network.add_edge(s1,s2)
network.add_edge(s1,s3)
network.bake()

beliefs=network.predict_proba({'guest':'A'})
beliefs=map(str,beliefs)
print("\n".join("{}\t{}".format(state.name,belief)for state,belief in zip(network.states,beliefs)))



beliefs=network.predict_proba({'guest':'A','monty':'B'})
print("\n".join("{}\t{}".format(state.name,belief)for state,belief in zip(network.states,beliefs)))











This is the code and i am facing the same error:

Traceback (most recent call last):
  File "Bayesian_network_monty.py", line 44, in <module>
    beliefs=network.predict_proba({'guest':'A'})
  File "pomegranate\BayesianNetwork.pyx", line 609, in pomegranate.BayesianNetwork.BayesianNetwork.predict_proba
  File "pomegranate\FactorGraph.pyx", line 345, in pomegranate.FactorGraph.FactorGraph.predict_proba
  File "pomegranate\distributions\JointProbabilityTable.pyx", line 188, in pomegranate.distributions.JointProbabilityTable.JointProbabilityTable.marginal
AttributeError: 'NoneType' object has no attribute 'log_probability'





CAN U HELP ME OUT.

**Comment by mohalikhan** [comment]
Your edges are incorrect. It should be like this
model.add_edge(s1, s3)
model.add_edge(s2, s3)
