### ISSUE TITLE
Bayesian Network - using data

### ISSUE THREAD

**Issue by karnatapu** [jmschrei/pomegranate#546]
Hello, I need a help in whether this package supports or not. Am not sure this is an issue, but thought of asking anyways.

I have decent size of data having around 30 features (col1, col2, col3..col30). Initially I thought of using greedy search algorithm to learning from data to create the BN, but later realized that algorithms takes lot of time and not feasible to end soon. So I did worked with business to come-up with a network where I have edges as a list (as below). So I fairly know, how BN looks like and have the data. I have to create a Bayesian Network, so to do the inferences, but I don't know all the conditional probabilities for each node. So do we have any way to create a BN  from data and network. Any pseudo code example wold be great.

ex: edges = [(col1, col4), (col1, col3).....]

Question 2:
If I use "from_structure" to create the model, do I have to call model.fit or model.bake? when to use fit method versus bake(). 

Appertains your time.

**Comment by karnatapu** [comment]
Thank you. Actually am getting following error if I call fit(data) method after from_structure() call. I have pandas 0.23.0 on my machine. 

Also, am getting wrong results if am inferring(query) the model. I presume this is because of model is not fitting properly. 

![img_1132](https://user-images.githubusercontent.com/36697352/52025727-ab6fd880-24c2-11e9-9dfc-f5169a28a2be.jpg)

**Comment by jmschrei** [comment]
Can you post a minimal reproducing example of the error, both in terms of code and the data? That would help me a lot in figuring out what's happening.

**Comment by jmschrei** [comment]
Please re-open if you're still having issues.
