### ISSUE TITLE
How to fit multivariate time series? Model only returns single state

### ISSUE THREAD

**Issue by Komodovaran** [jmschrei/pomegranate#547]
Say I have two time series that are caused by 2 underlying hidden states.

1. What am I doing wrong with the fitting since I only get a single state out? If I try to fit just one of the features, it works correctly. Multivariate series should be a list of features, no?

2. How can I incorporate prior knowledge, as demonstrated in the code? E.g. I can characterize the underlying distributions, but I want the correct sequence for the trace.

```
import numpy as np
import pomegranate as pg
import sklearn.cluster
import matplotlib.pyplot as plt

X1 = np.concatenate((np.random.normal(0, 1, 100), np.random.normal(5, 1, 100)))
X2 = np.concatenate((np.random.normal(30, 5, 100), np.random.normal(10, 5, 100)))

X = [X1,X2]

# number of hidden states
k = 2

# Means and sigmas are accurately determined via other methods
sigma_X1 = 1
sigma_X2 = 5
means = sklearn.cluster.KMeans(k).fit(np.column_stack(X)).cluster_centers_

d_X1 = [pg.NormalDistribution(m, sigma_X1) for m in means[:,0]]
d_X2 = [pg.NormalDistribution(m, sigma_X2) for m in means[:,1]]
dists = d_X1 + d_X2

# How do I fit this?
# pg.IndependentComponentsDistribution(X) or pg.IndependentComponentsDistribution(dists) does not work
model = pg.HiddenMarkovModel.from_samples(pg.MultivariateGaussianDistribution,
                                          init = "kmeans++",
                                          n_components = 2,
                                          X = X)
hidden_states = model.predict(np.column_stack(X), algorithm = "map")
# Plot the two variables
fig, ax = plt.subplots(nrows = 3)
ax[0].plot(X1, color = "red")
ax[1].plot(X2, color = "blue")
ax[2].plot(hidden_states)
plt.show()
```

**Comment by jmschrei** [comment]
Howdy

It looks like you're trying to fit a multivariate model to univariate data. Each of `X1` and `X2` is a univariate Gaussian, and `X` represents a data set with two univariate sequences. Thus, you'll want a univariate model, doing `pg.HiddenMarkovModel.from_samples(pg.NormalDistribution, n_components=2, X=X)`. 

If you wanted to make a HMM with two states, d_X1 and d_X2, you can either do that manually by adding in the states and edges by hand, or by using the `from_matrix` command and passing in the distributions and associated transition matrix. You should check out the tutorial on HMMs in the tutorials folder for help with both.

Looking at the signal itself, I'm not sure how well a HMM would be able to split it into two states. You have one signal that goes from 0 to 5, and one that goes from 30 to 10. The most likely states you'd get are one with a mean of ~2.5, that captures the entirety of the first sequence, and one with a mean of ~20, that captures the entirety of the second sequence. If you had four states, you'd probably be able to capture all four of those components nicely.

Let me know if you have any other questions.
