### ISSUE TITLE
pomegranate-0.10.0.tar.gz contains Cython generated .c rather than source .pyx files

### ISSUE THREAD

**Issue by mtselman** [jmschrei/pomegranate#548]
Hi, was trying to build pomegranate from source using pomegranate-0.10.0.tar.gz from PyPi, but that tarball seems to be missing many source files while containing Cython-generated .c files.

**Comment by jmschrei** [comment]
Howdy

You're getting the wheels, which are pre-built binaries that should work on your system. If you'd like the original source files, the easiest way is likely to download them directly from github.

**Comment by mtselman** [comment]
Thanks for the reply!
In our environment we build everything from source [ and do not rely on pre-built binaries ]. Got the sources from github using 0.10.0 tag, but just wanted to point out that your  tar.gz files on PyPi are not usable.

**Comment by jmschrei** [comment]
Okay, thanks for letting me know. I'll see if there's a quick fix for future releases.
