### ISSUE TITLE
Cannot capture "ignored Exception"

### ISSUE THREAD

**Issue by asapegin** [jmschrei/pomegranate#549]
My sample code always returns an exception even though I try to catch it:

<pre>
from pomegranate import *
a = ["A","B","C"]
b=["A","B","B"]
c=["A","B","C"]
d=["A","C","C"]
tdata = [a,b,c,d]
thmmodel = HiddenMarkovModel()
thmm = thmmodel.from_samples(DiscreteDistribution, 5, tdata, max_iterations=10, n_init=1)
test2 = ["A","B","D"]
try:
  lprob = thmm.log_probability(test2)
  print("lprob=",lprob)
except Exception as e:  
  print("Exception catched: ",e)
</pre>

I understand that there should be an exception if a symbol was not defined in the distribution. In my program, I want to handle such cases and therefore try to catch an exception. However, it is still not catched, rather it outputs the following:
<pre>
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel.log_probability'
Traceback (most recent call last):
  File "pomegranate/hmm.pyx", line 100, in pomegranate.hmm._check_input
ValueError: Symbol 'D' is not defined in a distribution
lprob= 0.0
</pre>

After this, a Value Error is raised although I tried to catch it:

<pre>
ValueError: Symbol 'D' is not defined in a distribution
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/databricks/python/lib/python3.5/site-packages/pomegranate/hmm.cpython-35m-x86_64-linux-gnu.so in pomegranate.hmm._check_input()

ValueError: Symbol 'D' is not defined in a distribution
</pre>

Do you have any ideas how to catch it? I run the code in Databricks Runtiome 4.3, Spark 2.3.1, Python 3

**Comment by jmschrei** [comment]
I'm not aware of how to do that. Unfortunately I think that using Cython kind of messes up error handling. Sorry about that.
