### ISSUE TITLE
GPU enabled and all dependencies installed, yet no speed up

### ISSUE THREAD

**Issue by annibauer** [jmschrei/pomegranate#550]
Hi! 
I'm trying to train an HMM and want to use my GPU. I have downloaded all necessary dependencies into my conda environment:

- cudatoolkit 10.0.130
- cupy 5.1.0
- pomegrante 0.10.0

and am on a Linux computer.
My computer has a GeForce RTX 2080 GPU.

However I see no difference in GPU memory usage when I disable or enable GPU using pomegranate and there is no speed up either when GPU is enabled. 
What other possibilities are there that could be causing my GPU to not be used by pomegranate?

Thanks in advance! 
I'd appreciate any help you can give me :)

**Comment by jmschrei** [comment]
Howdy

Currently, the only aspect of pomegranate that gets sped up by GPUs is the MultivariateGaussianDistributon object, due to its large dot product. Are you trying to speed up something else?

**Comment by annibauer** [comment]
Hey!
Thanks for your quick response!

https://pomegranate.readthedocs.io/en/latest/gpu.html
Here it mentions that HMMs as well as multivariate Gaussian mixture models can be sped up.

model = pomegranate.HiddenMarkovModel.from_samples(pomegranate.DiscreteDistribution, n_components=10, X=complete)
I'm training my model with a Discrete Distribution. If I'm understanding you correctly I have to choose a MultivariateGaussianDistribution as my probability distribution if I want to achieve a speed up?
Is that mentioned somewhere in the documentation? or is there anyother way to stick with a discrete distribution and achieve a speed up?

Thanks again!
GPU Usage — pomegranate 0.10.0 documentation<https://pomegranate.readthedocs.io/en/latest/gpu.html>
FAQ¶. Why cupy and not Theano? pomegranate only needs to do matrix multiplications using a GPU. While Theano supports an impressive range of more complex operations, it did not have a simple interface to support a matrix-matrix multiplication in the same manner that cupy does.
pomegranate.readthedocs.io


________________________________
Von: Jacob Schreiber <notifications@github.com>
Gesendet: Dienstag, 12. Februar 2019 20:43
An: jmschrei/pomegranate
Cc: annibauer; Author
Betreff: Re: [jmschrei/pomegranate] GPU enabled and all dependencies installed, yet no speed up (#550)


Howdy

Currently, the only aspect of pomegranate that gets sped up by GPUs is the MultivariateGaussianDistributon object, due to its large dot product. Are you trying to speed up something else?
