### ISSUE TITLE
Can't install Pomegranate 0.11.0: "'pomegranate/*.pyx' doesn't match any files"

### ISSUE THREAD

**Issue by alexhenrie** [jmschrei/pomegranate#554]
<pre>
$ sudo pip install pomegranate
Collecting pomegranate
  Using cached https://files.pythonhosted.org/packages/ea/aa/1ee99e690884a11d1acefd8075f389bd8f8e25193fec1593e0e9e6519dfa/pomegranate-0.11.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yrbji133/pomegranate/setup.py", line 61, in <module>
        extensions = cythonize( extensions )
      File "/usr/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 967, in cythonize
        aliases=aliases)
      File "/usr/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 812, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/usr/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 111, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pomegranate/*.pyx' doesn't match any files
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-yrbji133/pomegranate/
</pre>

This is on Arch Linux, but I suspect the same error is happening on all platforms.

**Comment by Wesserg** [comment]
I am running into a possibly similar problem
"pip3 install pomegranate."

The error does not occur if I run "pip3 install pomegranate==0.10"

Error pasted below:

```
 building 'pomegranate.distributions.NeuralNetworkWrapper' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -c pomegranate/distributions/NeuralNetworkWrapper.c -o build/temp.linux-x86_64-3.6/pomegranate/distributions/NeuralNetworkWrapper.o
    x86_64-linux-gnu-gcc: error: pomegranate/distributions/NeuralNetworkWrapper.c: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

This is on Ubuntu 18.04, python 3.6

**Comment by jmschrei** [comment]
I just added new mac and linux wheels to the repo, which should circumvent this issue. Making a new python3.6 virtual environment, I'm able to pip install pomegranate with no issues. Can you confirm?

**Comment by Wesserg** [comment]
Works for me. Thanks!

**Comment by jmschrei** [comment]
Awesome, thanks for pointing the issue out!

**Comment by alexhenrie** [comment]
It's working for me now too. Thank you!

**Comment by rosefun** [comment]
> I am running into a possibly similar problem
> "pip3 install pomegranate."
> 
> The error does not occur if I run "pip3 install pomegranate==0.10"
> 
> Error pasted below:
> 
> ```
>  building 'pomegranate.distributions.NeuralNetworkWrapper' extension
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -c pomegranate/distributions/NeuralNetworkWrapper.c -o build/temp.linux-x86_64-3.6/pomegranate/distributions/NeuralNetworkWrapper.o
>     x86_64-linux-gnu-gcc: error: pomegranate/distributions/NeuralNetworkWrapper.c: No such file or directory
>     x86_64-linux-gnu-gcc: fatal error: no input files
>     compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> ```
> 
> This is on Ubuntu 18.04, python 3.6

Thanks, I use `pip install pomegranate==0.10` and solve the problem.

**Comment by mk44214** [comment]
I was getting the same issue.. 
I did pip3 install cython followed by pip3 install pomegranate ... 

It worked.

**Comment by yanpanlau** [comment]
Thanks. Doing pip install cython solve the problem

**Comment by zachwill** [comment]
I can also confirm that this fixed my issue, too:

```
pip install cython
pip install pomegranate
```
