### ISSUE TITLE
Large number random variables issue

### ISSUE THREAD

**Issue by pkuweijia** [jmschrei/pomegranate#560]
Hello,
I want to use pomegranate to build a bayesian network for medical diagnosis and I have  more than 10000 random variables(0 or 1, such as gender, diseases or symptoms info) for each sample. And the data is about 500K rows.

So the question is , can I use pomegranate to build such a bayesian network ?  I saw the predicting process is toooooo slow.  Or how can I handle the random variables?

Thanks!

**Comment by jmschrei** [comment]
Howdy

Unfortunately, exact structure search is exponential time, and so learning the structure is infeasible past 25-30 variables, even when they're binary. 

However, you can try learning a Chow-Liu tree, which is only quadratic time. This algorithm will return the optimal tree-like Bayesian network, where each node can only have a single parent. 

Alternatively, if you have constraints that can be derived from prior knowledge, e.g., that some variables will never interact, you can get pretty massive efficiency gains using a constraint graph. You can see this tutorial for more: https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_4b_Bayesian_Network_Structure_Learning.ipynb

**Comment by pkuweijia** [comment]
Jmschrei, 

Thank you for your patience and quick response. 
I choose Bayesian network mainly because it is easy to explain，especially in the medical field.  But it seems very difficult to apply BN in practice. 

Maybe I can only try some classification algorithm.  ：(

Thanks for ur advice : )
