### ISSUE TITLE
Initializing a hidden markov model with generalized mixture model for emissions from sample

### ISSUE THREAD

**Issue by james-GA** [jmschrei/pomegranate#561]
Hey!
I have had success modelling my data with hmmlearn using their gaussian mixture hidden markov model. Due to the fat tails of my data I am looking to expand this to a students t mixture hidden markov model using pomegranate.
Can someone please help with how to set up this model from sample? So far i have this:
```
import pomegranate as pg

X = fitData
dist = pg.GeneralMixtureModel.from_samples(StudentTDistribution, 5, X)
model = pg.HiddenMarkovModel.from_samples(dist, n_components=3, X=X)

```
My StudentTDistribution class is the one provided in the custom distributions example notebook:
```

class StudentTDistribution():
    def __init__(self, mu, std, df=1.0):
        self.mu = mu
        self.std = std
        self.df = df
        self.parameters = (self.mu, self.std)
        self.d = 1
        self.summaries = np.zeros(3)

    def probability(self, X):
        return np.exp(self.log_probability(X))
        
    def log_probability(self, X):
        return scipy.stats.t.logpdf(X, self.df, self.mu, self.std)

    def summarize(self, X, w=None):
        if w is None:
            w = np.ones(X.shape[0])

        X = X.reshape(X.shape[0])
        self.summaries[0] += w.sum()
        self.summaries[1] += X.dot(w)
        self.summaries[2] += (X ** 2.).dot(w)

    def from_summaries(self, inertia=0.0):
        self.mu = self.summaries[1] / self.summaries[0]
        self.std = self.summaries[2] / self.summaries[0] - self.summaries[1] ** 2 / (self.summaries[0] ** 2)
        self.std = np.sqrt(self.std)
        self.parameters = (self.mu, self.std)
        self.clear_summaries()

    def clear_summaries(self, inertia=0.0):
        self.summaries = np.zeros(3)

    @classmethod
    def from_samples(cls, X, weights=None, df=1):
        d = StudentTDistribution(0, 0, df)
        d.summarize(X, weights)
        d.from_summaries()
        return d

    @classmethod
    def blank(cls):
        return StudentTDistribution(0, 0)
```

As far as i can tell the mixture model initializes as expected but initializing the hmm gives the error:
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-21-e75135084082> in <module>
----> 1 model = pg.HiddenMarkovModel.from_samples(dist, n_components=3, X=r.iloc[:cutPoint,3:].values)

pomegranate\hmm.pyx in pomegranate.hmm.HiddenMarkovModel.from_samples()

UnboundLocalError: local variable 'distributions' referenced before assignment

```
Is there something I am missing here or is the way I am passing the mixture model to the hmm wrong?
Btw, awesome package!

Thanks for the help!

**Comment by jmschrei** [comment]
Howdy

What you're passing in right now is a single initialized distribution. In general, you're going to want multiple distributions (one per state in the HMM). Also, you're supposed to pass in a class constructor, e.g., `NormalDistribution` rather than `NormalDistrubution(5, 2)`, or a list of constructors. 

Unfortunately, pomegranate doesn't have great support for specifying learning of stacked models using the `from_samples` method. In this case, stacked means putting a TDistribution in a Mixture in a HMM.  This means that the easiest solution is likely to specify the network initializations manually (using either `model.add_states` followed by successive calls to `model.add_transition` or `HiddenMarkovModel.from_matrix(...)` and then call `fit`.  

I haven't bug-tested this code, but it'll probably look something like this

```
from sklearn.cluster import KMeans
from pomegranate import HiddenMarkovModel

X = ... data ...
y_pred = KMeans(n_states_in_hmm).fit_predict(X)

distributions = []
for i in range(n_states_in_hmm):
    X_subset = X[y_pred == i]
    distribution = GeneralMixtureModel.from_samples(StudentTDistribution, n_components_in_mixture, X)
    distributions.append(distribution)

transitions = numpy.ones((n_states_in_hmm, n_states_in_hmm), dtype='float32') / n_states_in_hmm
starts = numpy.ones(n_states_in_hmm, dtype='float32') / n_states_in_hmm

model = HiddenMarkovModel.from_matrix(transitions, distributions, starts)
model.fit(X, verbose=True)
```

Let me know if that works out for you!

**Comment by james-GA** [comment]
Thank you very much that works as expected! Nice!!

Is it conceivable that I could change the StudentTDistribution class to estimate mu, sigma and dof parameters via maximum likelihood estimation for each hmm state? Currently the sufficient statistics only cope with mu and sigma but I would like to learn for each state in the hmm the dof parameter according to how heavy the tails are? I am not sure it is possible to determine dof by any sufficient statistics method and I have had success with maximum likelihood estimation for this purpose before. I know there are methods such as the Hill estimator but MLE seems like it would be much nicer to implement here.

**Comment by james-GA** [comment]
Also, something I noticed when passing this model a larger amount of data (size is (3000,18)) is that I start getting weird invalid value and overflow errors:
```
C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:876: RuntimeWarning: invalid value encountered in greater_equal
  return (self.a <= x) & (x <= self.b)
C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:876: RuntimeWarning: invalid value encountered in less_equal
  return (self.a <= x) & (x <= self.b)
C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\stats\_continuous_distns.py:4689: RuntimeWarning: overflow encountered in square
  lPx -= 0.5*np.log(r*np.pi) + (r+1)/2*np.log(1+(x**2)/r)
C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1694: RuntimeWarning: overflow encountered in true_divide
  x = np.asarray((x - loc)/scale, dtype=dtyp)
C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:24: RuntimeWarning: overflow encountered in square
```
Any idea what could be causing this? My data is clean of missing values or infinities?

Thanks!

**Comment by jmschrei** [comment]
I'm not aware of a technique to estimate dof, but I imagine it's possible. This is something you could include in your custom distribution if you find it. Sorry that I don't have it coded here.

What does your data look like? Is it possible to do something like divide all the values by 1000 or something?
