### ISSUE TITLE
Failure when performing a BayesModel fit 

### ISSUE THREAD

**Issue by icmoore** [jmschrei/pomegranate#562]
Was running one of the example scripts, and it failed on the last cell; see:

https://github.com/jmschrei/pomegranate/blob/master/examples/naivebayes_hmm_cheating_coin_toss.ipynb

This failure is embodied in the following simple test case:

# Test Case
d1 = DiscreteDistribution({'H':0.5, 'T':0.5})
d2 = DiscreteDistribution({'H':0.9, 'T':0.1})
model = NaiveBayes([d1, d1])

X = numpy.array([list( 'HHHHHTHTHTTTTH' ),
              list( 'HHTHHTTHHHHHTH' )])

y = numpy.array([ 1, 0 ])

model.fit(X, y)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-521382d9f0c3> in <module>
      9 y = numpy.array([ 1, 0 ])
     10 
---> 11 model.fit(X, y)
     12 

pomegranate/bayes.pyx in pomegranate.bayes.BayesModel.fit()

ValueError: could not convert string to float: 'H'

**Comment by andy6975** [comment]
Is this issue still open? I am willing to work on this. Thanks!

**Comment by jmschrei** [comment]
Any of the issues here which are open are available for you to work on. Thanks for checking!

**Comment by jmschrei** [comment]
Fixed in the next patch.
