### ISSUE TITLE
NormalDistribution probability result appears to be incorrect

### ISSUE THREAD

**Issue by Sir-Bowers** [jmschrei/pomegranate#563]
New to Pomegranate...

Created a Normal distribution with a mean of 5 and standard dev. of 0.5.

Tested the probability() method against that distribution with a value of x = 6.
Expected cumulative probability greater than 6 to be approx. **0.023**.

![image](https://user-images.githubusercontent.com/48426121/54100503-113e6280-4395-11e9-8c53-3b1a98afb3c3.png)

Got approx. **0.108** instead:

![Screenshot from 2019-03-11 00-33-30](https://user-images.githubusercontent.com/48426121/54100762-90806600-4396-11e9-98f3-a85f4fa05130.png)

Thanks,
J

**Comment by jmschrei** [comment]
Howdy

The value returned isn't the probability of 6 or greater, it's the point estimate of the probability of 6 itself.

**Comment by Sir-Bowers** [comment]
Wouldn't the point estimate be a lower probability than the cumulative prob above 6?
Am I to interpret the current result as a 10.7% probability we'll get a 6 exactly?

**Comment by Sir-Bowers** [comment]
Probability of point estimate at 6 +/- 0.01 definitely goes down (..to **0.22%**):

![image](https://user-images.githubusercontent.com/48426121/54101961-b577d780-439c-11e9-8fac-6adbb75a4fa1.png)

**Comment by jmschrei** [comment]
It's not necessarily the case that the point probability would be smaller than the percentage of the area under the point +/- some epsilon. Consider some probability distribution with a very very small variance. The point estimate probability at the mean will go above 1, but the area never will, because by definition the integral of a continuous probability distribution is 1. 

To check that pomegranate's numbers are not incorrect, I looked at the result from scipy.stats for both your initial question, and to illustrate the point I made above. 

```python
>>> from scipy.stats import norm
>>> norm.pdf(6.0, 5.0, 0.5)
0.10798193302637613
>>> norm.pdf(6.0, 6.0, 0.000001)
398942.2804014327
```

**Comment by Sir-Bowers** [comment]
Relative to the subject distribution, the probability of the area under the
point value 6 is infinitesimally small (limit). As one converges on the
point from both sides, area under the curve (and probability in this case)
must shrink.Thus the reason for the old zscore tables. When framing
probability questions like this, it's always a question of greater or less
than a point / value at the core of it.

What is the probability engine for the Normal distribution? A Zscore lookup
table, scipy.stats or something else? If scipy.stats, is it possible that
the version used has a bug that was carried over into Pomegranate?

**Comment by jmschrei** [comment]
I wrote all of the internals of pomegranate separate from scipy for efficiency reasons, though I did use scipy to confirm that I was returning the right results. I think that there is just a difference in what you're expecting it to return, versus what it actually is. These functions are returning the point along a probability density function, which you can read about for Normal Distributions here: http://mathworld.wolfram.com/NormalDistribution.html

Specifically, the equation for the probability density function for normal distributions is the following:
![image](https://user-images.githubusercontent.com/3916816/54105483-69bf3100-4390-11e9-8c96-0aac0931d10e.png)

If you go and manually implement that, you get the same result that scipy and pomegranate return.

```python
>>> (1. / (0.5 * numpy.sqrt(2 * numpy.pi))) * numpy.exp(-(6.0 - 5.0)**2 / (2 * 0.5 ** 2))
0.10798193302637613
```

I agree with your first two sentences, but I disagree with your last sentence. For generative models, one would want to know what the relative probability of emitting a certain symbol or sequence of symbols would be. Typically, the relative scale of the probability is what people care about, not the actual value. Generally, one would not say that there's a ~10.8% chance of getting exactly 6.0, but that ~6 is several orders of magnitude more likely than getting ~7.

**Comment by Sir-Bowers** [comment]
Ok. I see. That is a different way of looking at it. I will take a look at
the link you sent. Thanks. :)

One thing that would seem to go unresolved is that the Z-table (converging)
results won't match up with the result of the equation you have used. See
my earlier "sliver area" graphic and result.. It seems these approaches
lead to different results and thus different interpretations based on what
you have written. Should this be defined and clarifled for others to come?

Thanks again for Pomegranate and the support you are providing. Good stuff
my man!

**Comment by jmschrei** [comment]
If you'd like to submit a pull request to add the clarification to the documentation I'd be happy to merge it. I'm not sure whether this concern is something that frequently comes up. At least now they can refer to this thread if they are confused. :)
