### ISSUE TITLE
GMM/HMM sometimes only seem to work correctly on copies of arrays

### ISSUE THREAD

**Issue by jojomale** [jmschrei/pomegranate#564]
Hi,
While trying to create some test data for GMM/HMM, I encountered the following problem: In one case, the underlying GMM is retrieved correctly. But if I compose the (same) data in a different way, the result is only correct if I use a copy of the data array. So far, I couldn't figure out what the difference between the final data is.

 ```python
## Works without copy
c1 = [( 5, 0.5), (1, 0.25)]  # State 1 for both variables
c2 = [(10, 0.1), (3, 0.1 )]  # State 2 for both variables
cs = [c1, c2]
nc = len(cs)
nv = len(c1[0])
events = [np.concatenate([np.random.normal(*c, (dur//nc, nv)) for c in cs]) for dur in durs]
data = np.vstack(events)

fig, ax = plt.subplots(2, 1)
for e in events[::1]:
    xax = np.linspace(0, 100, e.shape[0])
    for i in range(e.shape[1]):
        ax[i].plot(xax, e[:,i])
plt.figure()
plt.hist(data, 50);

din = MultivariateGaussianDistribution # NormalDistribution
gmm = GeneralMixtureModel.from_samples(din, 2, data, verbose=True)
print([dist.mu for dist in gmm.distributions])


'''For some reason this data only works if you make a copy of it '''
fc = [(5, 10), (1, 3)]  # State 1 & 2 of first variable
A0 = [(0.5, 0.1), (0.25, 0.1)]  # State 1 & 2 of 2nd variable
ndist = len(fc) 
events = [np.array([np.random.normal(*fc, (dur//ndist, ndist)).T.flatten(), 
           np.random.normal(*A0, (dur//ndist, ndist)).T.flatten()]).T 
          for dur in durs]

events = [event for event in events]
## Enable copy here, then hmm works
data = np.vstack(events) #.copy() 

fig, ax = plt.subplots(2, 1)
for e in events[::1]:
    xax = np.linspace(0, 100, e.shape[0])
    for i in range(e.shape[1]):
        ax[i].plot(xax, e[:,i])
plt.figure()
plt.hist(data, 50);

din = MultivariateGaussianDistribution # NormalDistribution
gmm = GeneralMixtureModel.from_samples(din, 2, data, verbose=True)
print([dist.mu for dist in gmm.distributions])
```

The same happens, when using HiddenMarkovModel. The example is an adaption of the tutorial on GMMs (https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_2_General_Mixture_Models.ipynb). When using the GaussianMixture from scikit-learn, the model is retrieved correctly for both data sets without the additional copy-step.

**Comment by jojomale** [comment]
I may have found the answer:  If you check the flags of the arrays, it turns out, that the second approach results in a F_CONTIGUOUS array. When copied however, it is turned into C_CONTIGUOUS. Personally, I would appreciate at least a user warning or the like, because the seemingly wrong results on my real data almost made me give up on the api.

**Comment by jmschrei** [comment]
Howdy

Sorry for the trouble. The issue is exactly as you say. Essentially, when you transpose a numpy array, the data is ordered in the same manner in memory but a flag is toggled, and numpy knows how to use this flag to make all its operations work. When I wrote the Cython backend I was unfamiliar with this possibility, and just assumed the data was always C_CONTIGUOUS, as most ML data is. When you copy the data, it orders the data correctly because it's less efficient to operate on F_CONTIGUOUS data typically. 

You're absolutely right that silently doing the wrong thing is an awful solution. I'll see if I can add in a fix soon.
