### ISSUE TITLE
Learning emission distributions when model topology and transitions are well known in HMM

### ISSUE THREAD

**Issue by dbobr** [jmschrei/pomegranate#568]
Hello,

I've been getting some great use out of your package and am happy to have discovered it. Particularly because I'm implementing non-ergodic sparse transition models and this works very well for it. A gem, really.

I have a question about learning emissions on a defined model where the topology and the transitions are well known. Is this possible in the package currently with HMMs? What I'm really looking for is being able to define the model transitions and topology and then a "from_samples" like approach for learning emissions for the given model.

I have tried defining the model with various somewhat-random emissions for the states and then using an edge inertia of 1 when fitting, but have found that I still have a challenging time fitting the model. That is, the emissions still tend to be close to what I initialize them at. Is there a way to perturb the distributions a bit more when fitting?

Thank you for your help and thanks for the wonderful tool

**Comment by jmschrei** [comment]
Howdy

You can certainly define the structure of the network by adding in edges one at a time (or having a transition probability of 0 when you use `from_matrix`. These edges will never get added in even during a normal training procedure.

If you have a strong prior on what you want the probabilities to be, but aren't sure, you can add in pseudocounts for each edge in the `add_edge` method, corresponding to the number of fake transitions you add along that edge in the training procedure. If you balance the pseudocounts across out-edges such that their relative proportion is equal to their initial relative probabilities, you're essentially encoding your belief in those probabilities. For example, if you have out-edges with an initial 0.2 and 0.8 probability, you can add in a 0.2 and 0.8 pseudocount respectively to encode a weak belief in those probabilities. You can add in a 2000 and 8000 pseudocount to encode a strong belief in those probabilities. 

What is the current way you're defining and training the model? Setting edge inertia to 1 should be sufficient to freeze the edges, but I'm not positive that it will yield good results.

**Comment by dbobr** [comment]
I'll give the pseudocounts a try. I'm defining the model by adding the edges manually and training with Baum Welch. This could just be a problem with my model/data. But I have run into another issue along the way. It is unrelated to my initial issue and I can open another if you'd like.

In some of my states I have used GaussianKernelDensity emissions and fitting with those distributions I get the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
pomegranate/distributions/distributions.pyx in pomegranate.distributions.distributions.Distribution.from_summaries()

pomegranate/distributions/KernelDensities.pyx in pomegranate.distributions.KernelDensities.KernelDensity.fit()

TypeError: fit() takes at least 1 positional argument (0 given)
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._from_summaries'
Traceback (most recent call last):
  File "pomegranate/distributions/distributions.pyx", line 203, in pomegranate.distributions.distributions.Distribution.from_summaries
  File "pomegranate/distributions/KernelDensities.pyx", line 69, in pomegranate.distributions.KernelDensities.KernelDensity.fit
TypeError: fit() takes at least 1 positional argument (0 given)
```

Should I not be able to fit with Kernel Densities?

**Comment by jmschrei** [comment]
I think that there may be a bug in kernel densities. They were initially supported, but then I'm not sure I updated them to be used as I changed the internals. I should either remove them or update them.
