### ISSUE TITLE
Wrong return predict_proba() in Bayesian net

### ISSUE THREAD

**Issue by relue** [jmschrei/pomegranate#569]
I create a model with from_structure(X=X, structure=struct). Struct is 
struct = ((), (), (), (2,), (0,1,5,), (), (0,1,2,3,4,), (6,))
and plot of the graph looks fine.
But if I want to prict_proba for one example I get the input symbol returned instead of the demanded proba.
What do I wrong?

>>>X[1]
array([1, 1, 3, 0, 0, 2, 1, 0], dtype=int8)

>>>print(m.predict_proba(X[1]))
[1 1 3 0 0 2 1 0]

Edit:
I see, if I do m.predict_proba([1, 1, 3, 0, 0, 2, 1, None]) instead I get the results. Seems it has to be some marginal distribution. So maybe an error should be thrown or the probability of the value in the distribution should be used to prevent confusion. 

array([1, 1, 3, 0, 0, 2, 1,
       {
    "frozen" :false,
    "class" :"Distribution",
    "dtype" :"numpy.int8",
    "parameters" :[
        {
            "3" :0.26315789473684204,
            "0" :0.28947368421052616, << use this as return value, if non marginal?
            "4" :0.05263157894736858,
            "2" :0.15789473684210537,
            "1" :0.23684210526315774
        }
    ],

**Comment by jmschrei** [comment]
If you want the probability of an example, use the `probability` or `log_probability` methods. If you want to do inference to infer the marginal, use `predict_proba`. Does that clear things up?

**Comment by relue** [comment]
yes thank you
