### ISSUE TITLE
ZeroDivisionError if NormalDistribution has sigma = 0

### ISSUE THREAD

**Issue by komodovaran** [jmschrei/pomegranate#573]
This no longer works in 0.11.0 (works in 0.10.0 though):

`import pomegranate as pg; pg.NormalDistribution(1, 0)`

Traceback:
`  File "pomegranate/distributions/NormalDistribution.pyx", line 37, in pomegranate.distributions.NormalDistribution.NormalDistribution.__init__
ZeroDivisionError: float division by zero`

**Comment by jmschrei** [comment]
I did change that. Do you have a reason to want a zero variance?

**Comment by Komodovaran** [comment]
Generating noise-free hidden states has its uses, e.g.

```
import pomegranate as pg
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots(nrows = 3)
ax = ax.ravel()

for a, s in zip(ax, (0, 0.1, 0.5)):
    state_means = [1, 2]
    n = len(state_means)

    dists = [pg.NormalDistribution(m, s) for m in state_means]
    p = 0.10

    tmat = np.empty([n, n])
    tmat.fill(p)
    np.fill_diagonal(tmat, 1 - p)

    model = pg.HiddenMarkovModel.from_matrix(tmat, distributions=dists, starts=(0, 1))
    model.bake()

    a.plot(np.array(model.sample(200)))

plt.show()
```
![fig](https://user-images.githubusercontent.com/20357875/55163322-e5c7c000-5169-11e9-8fce-74a6ac0c0446.png)

**Comment by jmschrei** [comment]
That’s true. Would it be possible for your purposes to just set the
variance to be absurdly small, like 1e-16? Or do you need exact values?

**Comment by Komodovaran** [comment]
Good solution, hadn't thought of that actually. Rounding easily takes care of that then.

**Comment by jkleckner** [comment]
@Komodovaran Did you try that with the code above?  It hung for me (haven't tried to debug).

**Comment by Komodovaran** [comment]
Now is actually the first time I'm trying to run the code... and you're right. It hangs.
