### ISSUE TITLE
Question about Baum Welch Implementation and Cross Validation

### ISSUE THREAD

**Issue by ogunskool** [jmschrei/pomegranate#575]
Hi,
Excellent work on putting together the pomegranate API. I am trying to learn the parameters of a HMM model using pomegranate version 0.10.0, based on a set of observed sequences. I applied the model.fit method and explicitly set the algorithm parameter to "Baum-welch", and the training works fine but I get different model parameters (state transition matrices) every time I run the fit method (i.e. the values of the state transition probabilities after the EM algorithm converges are always fixed, but the states to which the transition probabilities are applied changes every time). I am aware that the EM algorithm converges to a local optima, but I am not sure if I should be getting the different state transitions after running the model.fit method different times. Is there a reason for this?
Because I obtain a different "optimal" hmm model each time I call the model.fit method, I tried to use the untrained hmm model as an estimator in sklearn's grid search in order to select the best "optimal" hmm model, but I get the following error:

  File "~/.local/lib/python2.7/site-packages/sklearn/model_selection/_search.py", line 625, in fit
    base_estimator = clone(self.estimator)
  File "~/.local/lib/python2.7/site-packages/sklearn/base.py", line 63, in clone
    new_object = klass(**new_object_params)
  File "pomegranate/hmm.pyx", line 225, in pomegranate.hmm.HiddenMarkovModel.__init__
TypeError: __init__() got an unexpected keyword argument 'distribution ties'

I was wondering if it was possible to use pomegranate-based estimators with sklearn's grid search and other cross validation tool boxes from sklearn, or if there was a new version of pomegranate that has sklearn's grid search functionality (or something similar) already built in . 

Thanks.

_Originally posted by @ogunskool in https://github.com/jmschrei/pomegranate/issues/173#issuecomment-478216245_

**Comment by jmschrei** [comment]
pomegranate differs from sklearn's API when it comes to the `fit` method. With sklearn, the `fit` method will fit an entirely new estimator to data. Even if the model is fit to some data set, those parameters will be wiped. With pomegranate, each successive `fit` call will simply refine the existing model. If you call it multiple times, you will get a model fit with an increasing number of iterations. It's similar to keras in this manner.

Currently, sklearn model selection functions aren't supported. Potentially, one could add this in without a big effort, but it's not currently on my queue.

**Comment by ogunskool** [comment]
Thank you for the clarification. 

Can you please clarify what the inputs for the model.score method for the HMM model are and what type of score is returned? That could help provide an insight on how I could implement a cross-validation scheme for my application. I could not find any examples from the tutorials that demonstrated how to call the score method.

**Comment by jmschrei** [comment]
`model.score` isn't going to work well for HMMs due to the variable length input of the model. It only works well for the NaiveBayes and BayesClassifier models, unfortunately.

**Comment by jkleckner** [comment]
> With pomegranate, each successive `fit` call will simply refine the existing model. If you call it multiple times, you will get a model fit with an increasing number of iterations. It's similar to keras in this manner.

If this is true for all models, perhaps mentioning this in docs/api.rst would be a good place to mention it?
