### ISSUE TITLE
Possible error in BetaDistribution.from_samples

### ISSUE THREAD

**Issue by titipata** [jmschrei/pomegranate#576]
When I use `BetaDistribution.from_samples` to approximate Beta distribution, I got the approximated parameters much further than the parameters used to generate the distribution. You can reproduce as follow:

```py
X = (np.random.randn(1000) + 5).reshape(-1, 1)
print(NormalDistribution.from_samples(X).parameters)
>> [5.046333839484424, 1.0217427726743622]
```

```py
X = np.random.beta(1, 5, size=10000).reshape(-1, 1)
print(BetaDistribution.from_samples(X).parameters)
>> [0.0, 10000.0] # error approximated parameters here
```

Now, when I would like to approximate the combination of `NormalDistribution` and `BetaDistribution`, the beta distribution never gets approximated. 

```py
X = np.hstack((np.random.beta(1, 5, size=1000), 
               np.random.randn(1000) + 5)).reshape(-1, 1)
model = GeneralMixtureModel.from_samples([NormalDistribution, BetaDistribution], 
                                         n_components=2, X=X)

>> {
    "class" : "GeneralMixtureModel",
    "distributions" : [
        {
            "class" : "Distribution",
            "name" : "NormalDistribution",
            "parameters" : [
                2.5959069991868775,
                2.532898043928428
            ],
            "frozen" : false
        },
        {
            "class" : "Distribution",
            "name" : "BetaDistribution",
            "parameters" : [
                0.0,
                0.0
            ],
            "frozen" : false
        }
    ],
    "weights" : [
        1.0,
        0.0
    ]
}
```

It seems like there might be an error somewhere in the Beta distribution function.

**Comment by jmschrei** [comment]
The confusion is that, while it's called a beta distribution, it's actually coded as a beta-binomial distribution, which is a binomial distribution with a beta prior on the parameters. Thus, the input is binary values, and the beta distribution is over the probability of returning heads. If you use non-integer inputs, you're feeding in the probability of positive. 

Sorry about that! If you tell me more about your application I might be able to suggest a workaround.

**Comment by jkleckner** [comment]
@jmschrei are there places in the code and examples where it makes sense to record this distinction?

**Comment by titipata** [comment]
@jmschrei, Ah that's why! Yes, that would be great to update the documentation since most of the documentation (e.g. Tensorflow or PyTorch) refers `Beta` as beta distribution, not beta-binomial distribution.  So, in my application, I want to approximate the bimodal distribution of beta distribution and normal distribution. I ended up writing my own log-likelihood and solve my parameters using Bayesian Optimization for now :)

It definitely would be great to have more documentation in the notebook for creating your own distribution.

PS. I'm happy to close this issue or maybe you can close it later if you want to create a relevant issue for updating the documentation.

**Comment by jmschrei** [comment]
Documentation added in.

**Comment by titipata** [comment]
Thank you so much @jmschrei!!
