### ISSUE TITLE
Can't seem to force randomness in pomegranate

### ISSUE THREAD

**Issue by komodovaran** [jmschrei/pomegranate#579]
Here I'm simulating n sequences between the two values 0.25 and 0.75, but no matter what I do I get the same sequence every time.

Seems like it's affected by e.g.
https://github.com/jmschrei/pomegranate/issues/235

If I accept the source, how can I override it in my own code?

```
import numpy as np
import pomegranate as pg
import matplotlib.pyplot as plt
import os

n_samples = 10

samples = []
for i in range(n_samples):
    seed_val = int.from_bytes(os.urandom(4), byteorder = "little")
    np.random.seed(seed_val)

    trans_mat = [[0.8, 0.2],
                 [0.2, 0.8]]

    means = [0.25, 0.75]
    starts = [0.5, 0.5]
    dists = [pg.NormalDistribution(mean, 0.01) for mean in means]

    model = pg.HiddenMarkovModel.from_matrix(trans_mat, distributions=dists, starts=starts)

    s = np.array(model.sample(100))
    samples.append(s)

fig, ax = plt.subplots(nrows = 2)
ax[0].hist(np.array(samples).ravel(), bins = 30)
ax[0].set_xlim(0,1)

[ax[1].plot(samples[i] + i*0.02, label = i) for i in range(5)]
ax[1].legend()
ax[1].set_ylim(0,1)
plt.show()
```

**Comment by Komodovaran** [comment]
Okay, found a potential solution after playing around: shuffling the order of input distributions.

Simply wedge in
```
    np.random.seed()
    np.random.shuffle(dists)
```
after `dists = ...`

It still appears to be pseudo-random, in that there are only `factorial(len(dists))` ways to configure them, but at least I can get a uniform distribution over all samples.

**Comment by jmschrei** [comment]
If you set a random seed at the start of the loop you shouldn't get randomness later on. Is that what's happening here?
