### ISSUE TITLE
conda installation requires networkx 1.11 not networkx 2.x?

### ISSUE THREAD

**Issue by reckoner** [jmschrei/pomegranate#582]
The `conda` installation lists `networkx` 1.11 as a dependency. Will this be bumped up to `networkx` 2.x any time soon?

**Comment by micknudsen** [comment]
I am trying to make a recipe (https://github.com/conda-forge/staged-recipes/pull/8715) for `pomegranate 0.11.0`. That should solve the `networkx` problem.

Unfortunately, I am having troubles making it work. Any help is greatly appreciated.

**Comment by micknudsen** [comment]
@reckoner The latest version of `pomegranate` is now available in the `conda-forge` channel.
