### ISSUE TITLE
GaussianKernelDensity API

### ISSUE THREAD

**Issue by ljmartin** [jmschrei/pomegranate#584]
Hi, 
Thanks for making pomegranate, I'm excited to use it.
Is there an API available for the `GaussianKernelDensity`? I couldn't find it on the website.

I'm confused about the usage. Maybe I need to set the bandwidth?
Using a gaussian KDE on data between 0-1 gives weird probabilities, always between 0.3-0.4. i.e.:
```
>>> from pomegranate import GaussianKernelDensity
>>> d = GaussianKernelDensity.from_samples([0.1,0.2,0.2,0.2,0.3])
>>> d.probability(0.2)
0.3981463872318232
>>> d.probability(0.1)
0.3961685233617429
>>> d.probability(0.9)
0.3119355911508377
```

Input >1 seems a bit more sensible:
```
>>> d = GaussianKernelDensity.from_samples([80,90,90,90,100])
>>> d.probability(80)
0.07978845608031838
>>> d.probability(90)
>>> 0.23936536824095517
```

Cheers

**Comment by jmschrei** [comment]
A Gaussian Kernel Density operates by, essentially, dropping a Gaussian distribution over each point. The variance of this Gaussian is equal to the `bandwidth` parameter in the kernel density. The default for this is equal to 1. You can see how, for a distribution that's roughly centered around 0.2 with a variance of 1, the probability between 0.1 and 0.2 will barely be different, whereas a distribution that's centered around 80 with a variance of 1 will have a much bigger difference between 80 and 90.

**Comment by ljmartin** [comment]
Hi @jmschrei 
Thanks for the response! How does one set the bandwidth?
So far I've tried:
```
>>> from pomegranate import GaussianKernelDensity
>>> d = GaussianKernelDensity(bandwidth=0.1).from_samples([0.1,0.2,0.2,0.2,0.3])
>>> d.probability(0.1)
0.3961685233617429
```

**Comment by jmschrei** [comment]
Try `d = GaussianKernelDensity([], bandwidth=0.1).fit([your data]) `
