### ISSUE TITLE
HiddenMarkovModel can't re-estimate the emission matrix

### ISSUE THREAD

**Issue by Super-Jolly** [jmschrei/pomegranate#586]
Originally I wanted to use the observation data to train directly, but in the end I could only get the matrix of [hidden_states_num*observation_states_num], I can't know the actual meaning of each hidden state.
So I initialized the states and gave them the name and trained with model.fit(x), 

model.fit(traindata_index, max_iterations=10, stop_threshold=1e-6, verbose=True,emission_pseudocount=0.0001)

but the result of the training was nan, and the value of the emission matrix did not change(the value is what i initialized).

[1] Improvement: nan	Time (s): 1.264
Total Training Improvement: nan
Total Training Time (s): 2.5539

**Comment by jmschrei** [comment]
Can you provide some more details about what you're trying to do? Specifically, what is it precisely you're trying to get out of the model, and what is it that's raising the error?
