### ISSUE TITLE
IdependentComponentsDistibution w LogNormal will not train

### ISSUE THREAD

**Issue by parrajeremy** [jmschrei/pomegranate#587]
Training a 2 state model on 3d data. After initializing the graph and first parameter approximations trying to fit model of data. Returns: 

[1] Improvement: nan	Time (s): 0.8166
Total Training Improvement: nan
Total Training Time (s): 1.7722

Interesting if I change the LogNormalDistibutions to NormalDistributions model trains
 
e.g. sequence
array([[4.91060617e+03, 4.02948384e+03, 9.05883547e-01],
       [4.91060617e+03, 4.02948384e+03, 9.05883547e-01],
       [4.90061190e+03, 4.09308099e+03, 1.00356296e+00],
       ...
       [7.61306509e+03, 5.88726600e+03, 1.57519840e+00],
       [7.57251220e+03, 5.92013936e+03, 1.45160819e+00]])

R_0 = 0.5
R_1 = 0.1

MU_X = 4000
SIGMA_X = 1000
LAMBDA_X = 1000

MU_Y = 8000
SIGMA_Y = 2000
THETA_Y = 25 * FT_TO_MM

MU_C = 100
SIGMA_C = 50
LAMBDA_C = 1

d0 = IndependentComponentsDistribution([LogNormalDistribution(MU_X, SIGMA_X),
                                            UniformDistribution(0, THETA_Y),
                                           LogNormalDistribution(MU_C, SIGMA_C)])

d1 = IndependentComponentsDistribution([ExponentialDistribution(LAMBDA_X),
                                            LogNormalDistribution(MU_Y, SIGMA_Y),
                                            ExponentialDistribution(LAMBDA_C)])
s1 = State(d0, name='noEvent')
s2 = State(d1, name='Screen')

model = HiddenMarkovModel()
model.add_states([s1,s2])
model.add_transition(model.start,s1, 0.999)
model.add_transition(model.start,s2, 0.01)
model.add_transition( s1, s1, R_0)
model.add_transition( s1, s2, 1-R_0)
model.add_transition( s2, s2, R_1)
model.add_transition( s2, s1, 1-R_1)
model.bake()

**Comment by jmschrei** [comment]
I am guessing that there is a negative value in your data or a value of exactly 0, neither of which the log normal distribution can handle properly but the normal distribution can.

**Comment by parrajeremy** [comment]
That would make sense. Let me purge and will return to close out.

**Comment by parrajeremy** [comment]
True. Thanks for the extra brain.
