### ISSUE TITLE
Issues of constraint graphs in BNSL 

### ISSUE THREAD

**Issue by zhangjy019** [jmschrei/pomegranate#594]
Hi, I'm new to Bayesian Network structure learning. I follow the tutorial https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_4b_Bayesian_Network_Structure_Learning.ipynb. I found that the constraint graphs work only when we use the "exact" algorithm. If we use "greedy" or "chow-liu", the constraint graphs don't work any more. Is it possible to add the constraint graphs to "chow-liu" or "greedy"?

Thanks

**Comment by jmschrei** [comment]
It is possible, but I'm not sure when I'll have time to add such in. If you'd like to try adding it in I'd be happy to review a PR.
