### ISSUE TITLE
Bayesian network in Tensorflow, doesn't work with tf.py_function

### ISSUE THREAD

**Issue by hyang428** [jmschrei/pomegranate#596]
After learning a Bayesian network from data, I try to combine the learnt model with my Tensorflow code by using:
`BN_probability=tf.py_function(model.probability, [x], tf.float32)`

 **it seems model.probability doesn't work with tf.py_function()**, appreciate for any help.

 Below is the error information:

>  File "pomegranate/base.pyx", line 151, in pomegranate.base.Model.probability
> File "pomegranate/BayesianNetwork.pyx", line 451, in pomegranate.BayesianNetwork.BayesianNetwork.log_probability
> File "pomegranate/distributions/ConditionalProbabilityTable.pyx", line 182, in pomegranate.distributions.ConditionalProbabilityTable.ConditionalProbabilityTable.log_probability
> KeyError: (0.73181605, 0.6418412) [[{{node EagerPyFunc_12}}]]
> During handling of the above exception, another exception occurred:
> UnknownError                              Traceback (most recent call last)
>

**Comment by jmschrei** [comment]
I have no idea how TensorFlow works. Sorry. This would probably be better on a tensorflow board. The error suggests that you might be trying to build a Bayesian network on continuous values, when pomegranate only currently supports categorical values.
