### ISSUE TITLE
How to define a custom distribution for pomegranate

### ISSUE THREAD

**Issue by lesshaste** [jmschrei/pomegranate#597]
In pomegranate there are a number of HMM examples includes lines such as:

    s1 = State(NormalDistribution(5, 1))

How can I define my own custom distribution in place of NormalDistribution?

**Comment by jmschrei** [comment]
https://github.com/jmschrei/pomegranate/blob/master/tutorials/C_Feature_Tutorial_5_Custom_Distributions.ipynb

**Comment by lesshaste** [comment]
Thank you so much.
