### ISSUE TITLE
kernel crashes with BayesClassifier.from_samples 

### ISSUE THREAD

**Issue by dorian821** [jmschrei/pomegranate#601]
Hi Jacob,

I'm trying to train a BayesClassifier from samples with a distinct distribution for each column and the kernel is crashing.

The distributions are in a list as:

[<class 'pomegranate.distributions.NormalDistribution.NormalDistribution'>, <class 'pomegranate.distributions.DiscreteDistribution.DiscreteDistribution'>, <class 'pomegranate.distributions.NormalDistribution.NormalDistribution'>, <class 'pomegranate.distributions.NormalDistribution.NormalDistribution'>]

The data looks like this:

array([[0.11579810326879214, True, 60.95538810220257, 70.5654456346986],
       [-0.07521766598951729, False, 16.92762307360819,
        49.025012661856245],
       [-0.2168748673358245, False, 11.366365345839275,
        29.749792173884178],
       ...,
       [0.6921283168634735, True, 99.83061756834597, 94.29295303822857],
       [0.7032511989022501, True, 96.73951436877891, 97.20814456176022],
       [0.5448964922013593, True, 78.35521260592414, 91.64178151435065]],
      dtype=object)

Any help is appreciated.

Thanks!

Dorian

**Comment by jmschrei** [comment]
What happens if you change True/False to 0/1 floats and use the Bernoulli distribution, making sure to be passing in a numpy array of type float64?

**Comment by jmschrei** [comment]
Please re-open if this is still an issue but make sure to convert to float64 when you have mixed data.
