### ISSUE TITLE
Is there some way we can get the n most likely predictions while using BayesianNetwork's predict function?

### ISSUE THREAD

**Issue by killerB97** [jmschrei/pomegranate#604]
Can the function be tweaked such that instead of returning the argmax, we can return the n most likely outcomes after sorting results.

**Comment by jmschrei** [comment]
Only the GeneralMixtureModel, BayesClassifier, and NaiveBayes models can return the n most likely predictions, using `model.predict_proba`. The other models use either dynamic programming or message passing algorithms which only give you the most likely.
