### ISSUE TITLE
Problem with the bayesian network Summarize function()

### ISSUE THREAD

**Issue by killerB97** [jmschrei/pomegranate#605]
Another small query, This is pertaining the question I posed earlier suppose I call summarize on batches of data after the initial from_structure call and a certain value of an (attribute/feature) has not been encountered before, it seems to be giving a key error. Is there any way around this?

**Comment by jmschrei** [comment]
You should either select examples for your initial batch that include all keys, or make a hand-crafted fake batch that does. Keep in mind that fitting a Bayesian network to new data is independent of the current parameters of the network, so using a fake batch won't effect training. Conceptually, it would be easy to add in a set of keys for each column as a parameter like sklearn does with partial_fit, but I just haven't done it.

**Comment by ikarthikng** [comment]
@jmschrei I have this same problem. I don't have all the keys initially since I am dealing with variable large data-set. I was wondering whether there is an update regarding this?

Is there a way to modify summarize function to dynamically update keys and model accordingly?

**Comment by jmschrei** [comment]
This probably won't be added in, sorry.
