### ISSUE TITLE
Does it usually happens that HMM has an absorbing state?

### ISSUE THREAD

**Issue by markov10000** [jmschrei/pomegranate#606]
When I using the following code to train my data, only one state is printed.

model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=5, X=X)
print(", ".join(state.name for i, state in model.viterbi(X)[1]))

**Comment by jmschrei** [comment]
It really depends on the data, but typically there isn't just one state. You could try projecting your data down to two dimensions and to see whether it supports multiple states. You could also try printing out the transition matrix to see if some states essentially are impossible to get to. It's hard for me to say anything more definitively without seeing an example.
