### ISSUE TITLE
DiscreteDistribution called with an empty dictionnary crashes kernel

### ISSUE THREAD

**Issue by Zamwell** [jmschrei/pomegranate#611]
Hi,

When DiscreteDistribution is called with an empty dictionnary, it makes the kernel crash. 

`DiscreteDistribution({})`

I don't know if this normal behavior or not, but it seems brutal.

Many thanks for the great package!

**Comment by jmschrei** [comment]
While it's true that there should probably be an error raised rather than killing the kernel, it's unclear to me why you'd want to build a distribution with no keys in it.

**Comment by jmschrei** [comment]
I've added a warning to try to exit gracefully when this happens.
