### ISSUE TITLE
enable_gpu failing

### ISSUE THREAD

**Issue by itaysason** [jmschrei/pomegranate#616]
Hi,
I am trying to use gpu and I think I found a problem in your code.
`try:
	import cupy
	from cupy import cuda
	cuda.Device().cublas_handle
	enable_gpu()

	global has_cupy
	has_cupy[0] = 1
except:
	global has_cupy
	has_cupy[0] = 0`

and  the enable gpu code is:
`cpdef enable_gpu():
	global GPU
	
	if has_cupy[0] == 0:
		raise Warning("Please install cupy before attempting to utilize a GPU.")
	else:
		GPU[0] = 1`

Notice that in the try we first running enable_gpu before we set has_cupy[0] = 1 so we fail inside the enable_gpu() and go to catch. I think by moving the enable_gpu() to the end of the try block it should solve it.

**Comment by jmschrei** [comment]
This should be fixed in v0.11.2, which I just released.
