### ISSUE TITLE
cannot import name 'GMM' from 'sklearn.mixture' 

### ISSUE THREAD

**Issue by georgevettathu** [jmschrei/pomegranate#619]
ImportError                               Traceback (most recent call last)
<ipython-input-47-14970d7aa059> in <module>
      5 
      6 from sklearn import datasets
----> 7 from sklearn.mixture import GMM
      8 from sklearn.cross_validation import StratifiedKFold
      9 

ImportError: cannot import name 'GMM' from 'sklearn.mixture' (C:\ProgramData\Anaconda37\lib\site-packages\sklearn\mixture\__init__.py)

**Comment by jmschrei** [comment]
I'm not sure how this is a pomegranate issue.
