### ISSUE TITLE
BayesianNetwork.forward_backward() fails on supply of soft evidence unless check_input set to False

### ISSUE THREAD

**Issue by nickynicolson** [jmschrei/pomegranate#62]
Example - as per the BayesianNetwork example in [pomegranate/examples/bayesnet_asia.py](https://github.com/jmschrei/pomegranate/blob/master/examples/bayesnet_asia.py) - where soft evidence is supplied (a DiscreteDistribution representing an 80:20 chance of bronchitis). The check_input part of the `forward_backward` method fails here, if the optional parameter `check_input` is set to `False` the execution can proceed.

**Comment by jmschrei** [comment]
Thanks for catching that! The Asia bayes net is also incorrect because it's initialized incorrectly (using dicts instead of lists). There is a PR fixing this which I will merge soon.

**Comment by nickynicolson** [comment]
Thanks @jmschrei - great to hear that there is progress on this. I was going to share my correction of the initialization of the Asia Bayes net but if you have an existing PR that does that I'll leave it.

**Comment by jmschrei** [comment]
Should be resolved now.
