### ISSUE TITLE
Update existing model with new data - Bayesian Network

### ISSUE THREAD

**Issue by ikarthikng** [jmschrei/pomegranate#627]
My dataset looks something like below of four columns. Initially I have 200 rows of data.

A_0, B_0, C_0, D_0
A_1, B_1, C_1, D_1
A_2, B_2, C_2, D_2
A_3, B_3, C_3, D_3
.
.
.
A_9, B_9, C_9, D_9
A_0, B_0, C_0, D_0
.
.

**My issue - Steps**

1. I train the above data using `BayesianNetwork.from_samples()` to initialize the model
2. I save the model to JSON file using `model.to_json()` method
3. When a new row of data comes in Ex: A_1, B_1, C_1, D_1. I am reading the saved JSON file containing the model and using `model.fit()` to fit the new data to the model to update the existing model.
4. Above step screws up all the conditional probability distribution in the model and gives me an output which is favoring the newly input data.
5. My assumption in this scenario was that conditional probability shouldn't change because pattern is the same, it should affect only discrete distribution. Am I wrong with this assumption?

**Things I have tried**
1. I have adjusted inertia and pseudocount from 0 to 1. This didn't work for me. Predictions were still not accurate.
2. When I read the entire dataset after new data is saved in it using `from_samples()`. It creates accurate predictions. Why is that?

I have function below which is called to fit the model.

```
def fit_data_in_model(A, B, C, D):
    # save data to the database
    set_data(A, B, C, D)
    
    model = None
    
    # Check whether there exists a JSON file with existing model
    if os.path.isfile("example_system.json"):
        # Read the JSON file and load the model
        with open("example.json") as s:
            jsonfile = json.load(s)

            obj = json.loads(jsonfile)
            obj = json.dumps(obj, sort_keys=True, indent=4)
            
            # Read the model from the JSON string
            model = BayesianNetwork.from_json(obj)
        
            # Fit the model with the new data
            model = model.fit([[A, B, C, D]])
            
            # Save the model to the JSON string
            json_structure = model.to_json()

            # Write the string to JSON file
            with open('example_system.json', 'w', encoding='utf-8') as f:
                json.dump(json_structure, f, indent=4)
               
    else:
        # Read all the data from database to initialize the model
        data_0 = get_all_data()
        data_0 = data_0.values.tolist()
        
        if(len(data_0) != 1):
            model = BayesianNetwork.from_samples(data_0, algorithm = 'exact')
            json_structure = model.to_json()

            with open('example_system.json', 'w', encoding='utf-8') as f:
                json.dump(json_structure, f, indent=4)
            
    return model
```

@jmschrei Your thoughts on this?

**Comment by jmschrei** [comment]
Yes, you are incorrect with the assumption in 5. Both marginal and conditional probabilities will be updated to reflect those in the new data set.
