### ISSUE TITLE
is there is a way to make multivariate discrete distribution for hidden Markov model

### ISSUE THREAD

**Issue by hiddenWarrior** [jmschrei/pomegranate#630]
assuming independence between variable between each discrete dimension

**Comment by hiddenWarrior** [comment]
@jmschrei

**Comment by jmschrei** [comment]
In general, you can use IndependentComponentsDistribution with a list of distributions to create a multivariate distribution from a set of univariate distributions. I think that works with a list of DiscreteDistributions---each distribution representing one feature.
