### ISSUE TITLE
Creating a conditional probability table using from_samples

### ISSUE THREAD

**Issue by Rachel741** [jmschrei/pomegranate#632]
Hi, 
I am very new to using Pomegranate and really enjoying it. I wish to put together a discrete Bayesian Network from training data, but I am having trouble creating a ConditionalProbabilityTable using the from_samples method. Could you let me know what input parameters are needed and in what form?

For example, the most simple case, a network of a child node with a single parent node. I have successfully created a DiscreteDistribution using the from_samples method for the parent node using data imported from a csv file using pandas.

data = pd.read_csv("BNdata.csv")
pdata = data["pdata"] #select column of data for parent node distribution
pnode = DiscreteDistribution.from_samples(pdata)

To create the ConditionalDistributionTable using from_samples, however, does not seem to work:

cdata = data["cdata"] #select column of data for child node distribution
cnode = ConditionalProbabilityTable.from_samples(cdata, pnode, weights=None, Pseudocount=0.0)

I get this error: ValueError: need more than 1 value to unpack

Which makes me feels as though I am just not presenting the inputs in the correct format. I haven't been able to find anything that says what the inputs should be (apart from the data and the parent nodes) or an example to demonstrate using this class method for this distribution. 

Many thanks.

**Comment by jmschrei** [comment]
Try `cnode = ConditionalProbabilityTable.from_samples(cdata, [pnode], weights=None, Pseudocount=0.0)`. The parents need to be a list, not a single distribution object.

**Comment by Rachel741** [comment]
Hi, thank you for this. I have run the code and it still gives the same error. In my example, I wish to create the conditional probability table for the child node given the parent, i.e. P(c|p). Here is a small example of the data (in columns) for c and p respectively:
...A, P
A, P
T, P
T, C
T, P...

Perhaps you could clarify what inputs are needed and in what format to create the conditional probability table using the from_samples method, please? Also, when learning the table, should the data include the child and the parent data? Sorry for the questions, I just can't find the supporting documentation. Many thanks.

**Comment by jmschrei** [comment]
Can you provide a small snippet with the correspond data that reproduces the problem? That will be the easiest way for me to give you feedback.

**Comment by Rachel741** [comment]
Hello, Thank you for getting back to me. I have solved it in the end. Thank you very much for your help and support in the meantime.

**Comment by bkatcher4** [comment]
Hello, would you be kind enough to share your solution? I am encountering the same problem. Thank you!

**Comment by Rachel741** [comment]
Hi, sure, no problem.
So, for a conditional probability table for the child node given the parent, i.e. P(c|p), and say your data looks as in the example above, with the first column being for the parent and the second for the child.

Given a parent node has already been defined, first I convert the data to numpy, although you maynot need this step:

data = data.to_numpy()

Then I used the following:

childnode = ConditionalProbabilityTable.from_samples(data, [parentnode],weights=None, pseudocount=0.0)

Hope this helps, seems to work... if you find a better way to do it I would be very interested to hear it. Thanks

**Comment by jmschrei** [comment]
The way that @Rachel741 show should be correct. Unfortunately you can't pass pandas DataFrames in to base distribution objects (though now you can pass them in to models). Further, you need to specify the parents of the distribution (the first n-2 columns, where the n-1 column is the child and the nth column is the probability).

**Comment by claudiu99lux** [comment]
I have the same problem, but @Rachel741 's solution doesn't work. I have the same error saying that I need more than 1 value to unpack. Exact same scenario, tried everything that has been said here

**Comment by jmschrei** [comment]
@claudiu99lux can you clarify? You should pass in a 2D numpy array or a list of lists in the format of a probability table with d+2 columns (with d being the number of parents) where the first d columns are the values the parents take, the d+1 column is the value the child takes, and the d+2 column is the probability of that. If you have a pandas dataframe you should convert it to that format.

**Comment by claudiu99lux** [comment]
Thank you for your clarification, I could not find anything about the parameters the function should take and their format.
