### ISSUE TITLE
How to generate conditional probability table from samples ? 

### ISSUE THREAD

**Issue by ingjpal** [jmschrei/pomegranate#634]
Hello Jacob, 

I've been trying to do a very simple task in which I want to generate a conditional probability table based on an array of three discrete binary variables.Variables 1 and 2 are parents to 3.  I've tried to execute something like: 

A = [[1, 0, 1, 0], [1, 1, 1, 0], [0, 1, 0, 0]]
table=ConditionalProbabilityTable.from_samples(A,[1,2],weights=None)

Yet I keep getting the error:
**TypeError: from_samples() takes at least 2 positional arguments (1 given)**

I suppose I'm not defining the parent vector correctly. Can you tell me what is the correct way to make this table ? 

Thanks !

**Comment by jmschrei** [comment]
Parents has to be a set of distributions. You should fit discrete distributions to each of your parent variables and then fit a conditional probability table to the child variable given the parents, e.g.

```
A = numpy.array([[1, 0, 1, 0], [1, 1, 1, 0], [0, 1, 0, 0]])
d1 = DiscreteDistribution.from_samples(A[:,0])
d2 = DiscreteDistribution.from_samples(A[:,1])
d3 = DiscreteDistribution.from_samples(A[:,2])
d4 = ConditionalProbabilityTable.from_samples(A, [d1, d2, dd3])
```

**Comment by ingjpal** [comment]
Thank you very much for the fast reply !
