### ISSUE TITLE
Draw transition matrix & graphs for Markov Chains

### ISSUE THREAD

**Issue by kushalkolar** [jmschrei/pomegranate#637]
Hi,

I think it'd be useful to get the transition matrix & draw graphs for Markov Chains, at least for first order chains. Not exactly sure how you'd visualize higher orders?

Here's a simple idea for an implementation:
https://mybinder.org/v2/gh/kushalkolar/markov_chain_with_graph/master

I'll be happy to open a PR if this could be useful!

**Comment by jmschrei** [comment]
Howdy

I took a look at your notebook and it seems interesting but I'm not sure how it would generalize past first order Markov chains. If you can think of a way that is more generalizable I'd love to see a PR.
