### ISSUE TITLE
Misleading result from BayesianNetwork.probability(list(..)) function

### ISSUE THREAD

**Issue by SebastianBelkner** [jmschrei/pomegranate#638]
To make inference within a BayesianNetwork (BN), pomegranate provides two handy functions, i.e.,

- BayesianNetwork.predict_proba(dict(..)) for calculating probabilities given the condition provided via 'dict(..)',
- BayesianNetwork.probability(list(..)) for the probability of the assignment as provided via list(..).

We don't quite understand the behaviour of the latter. 
Let us assume a BN with two nodes **A** and **B** and the following topology,
```
A --> B, WLOG A and B be binary random variables.
```

We assume that `None` is interpreted as 'not assigned' from pomegranate and it will marginalise over all possible assignments of **B**.

To calculate the probability of an assignment **A** = a1, we may use, `BayesianNetwork.probability(['a1',None])`,
which outputs the correct result. 

However, to calculate the probability for any assignment of a leaf node we get wrong results when we interpret None as 'not assigned',
`BayesianNetwork.probability([None,'b1']) = 1.0`, 
`BayesianNetwork.probability([None,'b2']) = 1.0`.

How are we to interpret the result? What does the None assignment of a Node mean? We'd be happy to get some interpretational help.
What we would wish for is from pomegranate to throw an error or emphasize that the result may be wrong when applying None to parent nodes.

A workaround is to sum over all possible assignments of A, i.e.,
`P('B'='b1') = sum_(A={a1,a2}) BayesianNetwork.probability([A,'b1'])`,
however it is unsatisfactory due to the erroneous result stated above.

**Comment by jmschrei** [comment]
Hi Sebastian

Currently pomegranate does return a probability of 1 when data is missing rather than calculate the marginal probability, which I agree is misleading. I'll look into adding something to the documentation to clarify this. If you're looking to sum over all possibilities you'd have to do that manually, but keep in mind to multiply each entry by the parent probability, i.e., `P(B = b1) = sum(A={a1, a2}) P(A=a1) P(B=b1 | A=a1)`

**Comment by SebastianBelkner** [comment]
I see, thank you for clarifying!

Of course, using conditional dependence, P(B|A) = P(A,B) / P(A) , my expression should be  the same as your,
```
P(B = b1) = sum(A={a1, a2}) P(A) P(B=b1 | A) = 

                    sum(A={a1, a2}) P(A) P(B=b1, A) / P(A) = 

                    sum(A={a1, a2})  P(B=b1, A) 
```
