### ISSUE TITLE
ImportError: No module named pomegranate

### ISSUE THREAD

**Issue by tobimichigan** [jmschrei/pomegranate#640]
I cloned thia repo:
I installed pomegrante with pip and tried with conda as well.
Also ran: git clone https://github.com/jmschrei/pomegranate.git
cd to the dir folder
and I ran python setup.py install
The only example notebook that ran successfully is : bayesnet_asia.ipynb

When I try to run one of the codes(eg bayesnet_huge_monty_hall.ipynb) through Jupyter notebook it gave this error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-15292b3d47e2> in <module>()
      1 import math
----> 2 from pomegranate import *

ImportError: No module named pomegranate

Any clues to this?

**Comment by tobimichigan** [comment]
Solution: I later discovered the Python Notebook Kernel was set to ver 2+. All I did was reset to the Kernel to Python3+ and the example scripts started to run.

**Comment by jmschrei** [comment]
Great. Good note to have here regardless.
