### ISSUE TITLE
object of type 'type' has no len()

### ISSUE THREAD

**Issue by tobimichigan** [jmschrei/pomegranate#641]
benchmarks/pomegranate_vs_sklearn_naive_bayes.ipynb, is giving this error:

TypeError                                 Traceback (most recent call last)
<ipython-input-6-1574004ef5d7> in <module>
      1 skl = GaussianNB()
----> 2 pom = NaiveBayes( NormalDistribution )
      3 evaluate_models( skl, pom )

~/anaconda3/~/NaiveBayes.pyx in pomegranate.NaiveBayes.NaiveBayes.__init__()

~/anaconda3/~site-packages/pomegranate/bayes.pyx in pomegranate.bayes.BayesModel.__init__()

TypeError: object of type 'type' has no len()

**Comment by jmschrei** [comment]
The code is now outdated. I'll try to fix it soon.

**Comment by jmschrei** [comment]
Fixed
