### ISSUE TITLE
Improving the BayesianNetwork plot() function

### ISSUE THREAD

**Issue by ptommasi** [jmschrei/pomegranate#651]
I ran in some performance issues when plotting the Bayesian Network, thus I checked the source of BayesianNetwork.pyx (line 244, `def plot(self, filename=None)`).

I don't know if there are any drawbacks, but I went down from ten-ish seconds to milliseconds by using svg format in output and not using temporary files to build the image.

The changes above are perfect for my use case, (I'm building an image and serving it using a rest service), thus I don't need a file or anything, but rather the data only (and a transparent background, my main problem).

Here's the core of my solution:

        G = pygraphviz.AGraph(directed=True, bgcolor='transparent')

        for node_id in states:
            G.add_node(node_id, color=colors['border'], fontcolor=colors['font'], style='filled', fillcolor=colors['fill'], tooltip=node_id)

        for parent_id, child_id in edges:
            G.add_edge(parent_id, child_id, color=colors['edge'])

        data = G.draw(format='svg', prog='dot')

        return data

This code allows to have a transparent background for the graph, and all the colours can be changed (here I put a `colors` dictionary, in reality I have a more complex scenario), on top of having good performances in computing it and just storing it in memory! :)

**Comment by jmschrei** [comment]
Thanks for sharing! I'll look into trying to incorporate this.

**Comment by jmschrei** [comment]
I tried getting this to work. Unfortunately, it looks like it no longer displays the image to the screen as most users might expect when they use `model.plot()`. That was the reason for the temporary file. Do you know a workaround that will still display the image when called but doesn't have a temporary file?

**Comment by ptommasi** [comment]
Sadly not on top of my head, my main use case was to pass the image through a rest service (and actually that has been troublesome too, because graphviz is difficult to install on cloud containers).

I cannot look at a solution these days, but reading the source code in _BayesianNetwork.pyx_:
```
def plot(self, filename=None):
	if pygraphviz is not None:

		G = pygraphviz.AGraph(directed=True)

		for state in self.states:
			G.add_node(state.name, color='red')

		for parent, child in self.edges:
			G.add_edge(parent.name, child.name)

		if filename is None:
			with tempfile.NamedTemporaryFile() as tf:
				G.draw(tf.name, format='png', prog='dot')
				img = matplotlib.image.imread(tf.name)
				plt.imshow(img)
				plt.axis('off')
		else:
			G.draw(filename, format='pdf', prog='dot')

	else:
		raise ValueError("must have pygraphviz installed for visualization")
```

The core of the issue is the `matplotlib.image.imread(tf.name)`. Apparently, `imread` reads a file from disk and convert it to a numpy array, and it relies on the _pillow_ library to do that ([this article](https://matplotlib.org/tutorials/introductory/images.html)). My suggestion would be to skip the matplotlib library and go directly to the pillow underlying one, I suspect there is no much logic in `imread`.

A start would be not to export in _svg_ format (as I proposed because it seemed more performant), but to _png_ instead, which seems the standard pillow format (I'd give a try to svg anyway). [Looking at this](https://stackoverflow.com/questions/8821259/python-imaging-load-jpeg-from-memory), I suspect you can: 
 - skip the line `img = matplotlib.image.imread(tf.name)`
 - read the output of `G.draw` (e.g. `data = G.draw(format='png', prog='dot')`)
 - convert it into a buffer (e.g. `import io` and then `buffer = io.BytesIO( data )`)
 - try to open the buffer with pillow (`img = Image.open(buffer)`)
 - uncharted territories here, but I suspect you should be able to do a `plt.imshow(img)`, I didn't find documentation for that

Although simple, I'm not able to test what I wrote for the next few weeks, I hope it makes sense. Basically skip matplotlib and use pillow to have the png data in memory, and reference it directly.

I'd recommend to split the plotting logic from the image creation logic, which has been my use case for looking at it. Splitting would allow a user to either save the image as a file (and then easily put in a powerpoint or paper, for example), transmit it over the network (I built a rest service to easily shows the graph in the browser) or other custom behaviours. I don't think it's important, but just nice to have!

Btw, thanks for your work! :)

**Comment by ptommasi** [comment]
I tried the code, it won't work with 'svg' format, but it works with jpg.

The relevant portion of code, after you created and populated the AGraph:
```
jpg_data = G.draw(format='jpg', prog='dot')
buffer = io.BytesIO(jpg_data)
Image.open(buffer).show()
```

And it will create the image locally and display, like before. `show()` is a blocking call, thus the program won't continue until you close the window. :)

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
