### ISSUE TITLE
HiddenMarkovModel.sample()

### ISSUE THREAD

**Issue by lxkain** [jmschrei/pomegranate#654]
When I execute the following:

```
import numpy as np                                                      
from pomegranate import HiddenMarkovModel as HMM, \ 
                        MultivariateGaussianDistribution as MGD         

start = np.array([1., 0, 0, 0])  # definitely start in winter 
transition = np.array([[0.9, 0.1, 0.0, 0.0], 
   ...:                       [0.0, 0.9, 0.1, 0.0], 
   ...:                       [0.0, 0.0, 0.9, 0.1], 
   ...:                       [0.1, 0.0, 0.0, 0.9]]) 
I = np.eye(2) * 2 
distribution = [MGD([30, 80], I), 
   ...:                 MGD([55, 75], I), 
   ...:                 MGD([80, 30], I), 
   ...:                 MGD([60, 80], I)] 
hmm = HMM.from_matrix(transition, distribution, start)                  

hmm.sample(1)                        
```

it hangs forever. Upon KeyboardInterrupt, I see:
                                   
^C---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
mt19937.pyx in numpy.random.mt19937.MT19937._legacy_seeding()

TypeError: 'numpy.random.mtrand.RandomState' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-4-f74e4587be11> in <module>
----> 1 hmm.sample(1)

~/anaconda3/lib/python3.7/site-packages/pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.sample()

~/anaconda3/lib/python3.7/site-packages/pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.sample()

~/anaconda3/lib/python3.7/site-packages/pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel._sample()

pomegranate/distributions/MultivariateGaussianDistribution.pyx in pomegranate.distributions.MultivariateGaussianDistribution.MultivariateGaussianDistribution.sample()

~/anaconda3/lib/python3.7/site-packages/pomegranate/utils.pyx in pomegranate.utils.check_random_state()

mtrand.pyx in numpy.random.mtrand.RandomState.__init__()

mt19937.pyx in numpy.random.mt19937.MT19937._legacy_seeding()

mt19937.pyx in numpy.random.mt19937.MT19937._legacy_seeding()

TypeError: Cannot cast array from dtype('O') to dtype('int64') according to the rule 'safe'

**Comment by lxkain** [comment]
pomegranate 0.11.1
numpy 1.17.2

**Comment by jmschrei** [comment]
Howdy. You need to either provide an explicit end state in your model or indicate how long the sequence should be using the length parameter. Otherwise, it will just continue sampling infinitely.

**Comment by lxkain** [comment]
Yep, I just figured this out! Thank you!

**Comment by lxkain** [comment]
Really appreciate this library and your efforts!
