### ISSUE TITLE
How can I sample the data from Bayesian Network model?

### ISSUE THREAD

**Issue by ashutoshaay26** [jmschrei/pomegranate#656]
When I am using the Bayesian Network model.sample(n) for sampling the data from learned distribution it shows me this error:  File "pomegranate/base.pyx", line 135, in pomegranate.base.Model.sample NotImplementedError     So, what's wrong in this?

**Comment by jmschrei** [comment]
There currently isn't a sampling procedure for Bayesian networks implemented. #650 has proposed a sampling approach but it hasn't been merged yet.

**Comment by sashaostr** [comment]
+1

**Comment by ashutoshaay26** [comment]
Thanks for mentioning #650
