### ISSUE TITLE
hmm-rainy-sunny.ipynb cannot load into Jupyter (unreadable notebook)

### ISSUE THREAD

**Issue by nickynicolson** [jmschrei/pomegranate#66]
Loading the file `examples/hmm_rainy_sunny.ipynb`  into Jupyter 4.0.6 on Python 3.5.1 | Anaconda 2.4.1 (64-bit) gives the error:
```
Unreadable Notebook: /home/nickyn/github/pomegranate/examples/hmm_rainy_sunny.ipynb
NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)
```

**Comment by nickynicolson** [comment]
This is a result of an unresolved merge conflict, see commit https://github.com/jmschrei/pomegranate/commit/94545a968ccef059db8bc0f95ce40c1316bbc6ab

**Comment by jmschrei** [comment]
Issue has been fixed. Thanks for pointing it out, and sorry for the delay!
