### ISSUE TITLE
Constraints from edges and groups

### ISSUE THREAD

**Issue by ingjpal** [jmschrei/pomegranate#661]
Hello !

I saw in a previous thread (https://github.com/jmschrei/pomegranate/issues/211#issuecomment-270259549) that you were going to implement the option of enforcing nodes and later learning from structure. I would like to enforce links with add_edge function , plus make groups of variables plus make the program learn from the possible links left (learn from samples). Is this possible already ? 

Thanks !

**Comment by jmschrei** [comment]
Unfortunately I haven't yet added in the ability to force arbitrary edge constraints. I don't know when I'll have time to do this.

**Comment by jmschrei** [comment]
I've added in edge constraints in the last version but forgot to close this issue.
