### ISSUE TITLE
Incorporate new data in already trained Bayesian Network

### ISSUE THREAD

**Issue by rsc18** [jmschrei/pomegranate#663]
I am trying to train the Monty hall bayesian network with group of smaller data sets. So, I have a list of smaller data sets and every time I am fitting that as model.fit([train_set]) I am getting a new model. Is there a way so that I can incorporate new data in already trained Bayesian Network.

**Comment by jmschrei** [comment]
Each time you fit a Bayesian network to new data, all of the probability tables get overwritten by the probability values derived from the new data. If you'd like to keep data from previous data sets, you can either concatenate all of the data together and fit to it, or set `inertia` to be higher, where `inertia=0.0` means completely disregard old values when fitting, `inertia=1.0` means completely disregard new data when fitting, and `inertia=0.5` means make the parameters halfway between what they were and what they would be if fit solely to this new data.

**Comment by rsc18** [comment]
Thank you.
