### ISSUE TITLE
[BUG]HMM circuit board methodology do not work with NetworkX

### ISSUE THREAD

**Issue by yipukangda** [jmschrei/pomegranate#668]
I want to add a self match state to profile HMM model as pypore [(pypore link)](https://github.com/jmschrei/PyPore/blob/master/PyPore/hmm.py), but after replacing yahmm with pomegranate, as below:

```
class HMMBoard( HiddenMarkovModel ):
	"""
	A HMM circuit board. Define the number of lanes in the circuit, with each
	lane having a start and end silent state.
	"""

	def __init__( self, n, name=None ):
		super( HMMBoard, self ).__init__( name="Board {}".format( name ) )

		self.directions = [ '>' ] * n 
		self.n = n
		for i in range( 1,n+1 ):
			start = State( None, name="b{}s{}".format(name, i) )
			end = State( None, name="b{}e{}".format(name, i) )

			setattr( self, "s{}".format( i ), start )
			setattr( self, "e{}".format( i ), end )

			self.add_state( start )
			self.add_state( end )
```

But seems the `networkX` package do not compromise with it any more, after I run the command 

```
model = ModularProfileModel(NanoporeGlobalAlignmentModule, distributions, 'align', UniformDistribution(0,100))

#ModularProfileModel and NanoporeGlobalAlignmentModule come from pypore module 
```

And got a error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-eaec881319b2> in <module>
----> 1 model = ModularProfileModel(NanoporeGlobalAlignmentModule, distributions, 'align', UniformDistribution(0,100))

<ipython-input-3-3d750b83e2e8> in ModularProfileModel(board_func, distributions, name, insert)
    142         model.add_transition( board.e2, model.end, 1.00 )
    143 
--> 144         model.bake()
    145         return model
    146 

pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.bake()

~/anaconda/lib/python3.7/site-packages/networkx/classes/reportviews.py in <genexpr>(.0)
    664 
    665     def __iter__(self):
--> 666         return (self._report(n, nbr, dd) for n, nbrs in self._nodes_nbrs()
    667                 for nbr, dd in nbrs.items())
    668 

RuntimeError: dictionary changed size during iteration
```

python version: 3.7
networkx version: 2.4
pomegranate version: 0.11.0

**Comment by jmschrei** [comment]
Howdy. I'm sorry you're running into problems with this. Unfortunately I'm not supporting that code any more. The problem is particularly difficult because pomegranate, networkx, and Python (v2 -> v3) have changed significantly since that code was released. I anticipate that the problem has to do with a dictionary somewhere in the code expecting to be iterated over as a list rather than as a generator. I expect that if you go through the PyPore code and wrap the dictionary references/iterations with lists (e.g. `for key, value in d.items()` -> `for key, value in list(d.items())` you might find the issue.

**Comment by yipukangda** [comment]
@jmschrei Thanks, I solved it by switching between py3 and py2 when necessarily.
