### ISSUE TITLE
[BUG] Segmentation Fault using HiddenMarkovModel.from_samples()

### ISSUE THREAD

**Issue by AlexMackowiak** [jmschrei/pomegranate#669]
**Describe the bug**
A segmentation fault happens every time I try to train a HiddenMarkovModel with 3 components using a MultivariateGaussianDistribution on 9415 30-dimensional vectors. I am using Python 3.4.3 and pomegranate 0.12.0 which I understand to be the latest release.

**To Reproduce**
Download `hmm_segfault.zip`, extract the files, and run `python3 train_markov.py`. I have also included a file `packages.txt` which includes the specific versions of all Python modules I have installed.

[hmm_segfault.zip](https://github.com/jmschrei/pomegranate/files/3969746/hmm_segfault.zip)
![Segfault_image](https://user-images.githubusercontent.com/21323278/70935889-d72a7d00-2006-11ea-8a0c-1f3e7bb11922.PNG)

**Comment by jmschrei** [comment]
The segmentation fault doesn't seem related to pomegranate. When I comment out all pomegranate related code (after L107) I still get a seg fault.
