### ISSUE TITLE
Loading HMM with from_json() results in: [RuntimeWarning: divide by zero encountered in log]

### ISSUE THREAD

**Issue by Narsail** [jmschrei/pomegranate#67]
For my project i store the HMMs on disks and load them when necessary. While doing this i found a bug, i think.

Principal Code:
Storing
```
      jsonFile = hmm.to_json()
      json.dump(jsonFile, file)
```
Loading
```
    jsonFile = json.load(file)
    hmm = HiddenMarkovModel.from_json(jsonFile)
```
So far so good. It is working and generating a HiddenMarkovModel. The only problem is the message in the headline. (RuntimeWarning: divide by zero encountered in log) And i get this for every stored Model. There is either an operation error on my side or the from_json() method is something not handling well.

For further tests i included on of the hmms:
[HMM_0.txt](https://github.com/jmschrei/pomegranate/files/105848/HMM_0.txt)

**Comment by jmschrei** [comment]
Can you provide some more information about the problem? Do you get the same results if you load the HMM back from a file as opposed to using one trained in the program? In which step does the divide by zero error occur, the model loading?

**Comment by Narsail** [comment]
Okay, so the problem is occurring in the loading phase of the HiddenMarkovModel.from_json(). I did the conversion to_json(), from_json() only in code and i got the same error. But i don't know where it is exactly coming from within.

Error:
RuntimeWarning: divide by zero encountered in log
  hmm = HiddenMarkovModel.from_json(model.to_json())

**Comment by Narsail** [comment]
Have you been able to reproduce it?

**Comment by jmschrei** [comment]
#71 should resolve the issue. IndependentComponentsDistribution was saving the log of the weights, as opposed to the weights themselves, which caused an error when weights were 1 and you were reloading the distribution. Try pulling the latest version.

**Comment by Narsail** [comment]
Okay. The mentioned issue is resolved. Thank you! But there is a new one. When you load the models from a JSON File, some values have changed. But i will open a new Ticket for this issue.
