### ISSUE TITLE
[Enhancement] HMM NaN improvment

### ISSUE THREAD

**Issue by lekcyjna123** [jmschrei/pomegranate#675]
Hi,

i won't ask if there is a possibility to add warning/exception in fitting HMM models, when we put incorrect learning data. I have created HMM:
```
d0=pom.DiscreteDistribution({0:0.68, 1:0.23, 2:0.09, 3:0})
d1=pom.DiscreteDistribution({0:0.73, 1:0.20, 2:0.07, 3:0})
d2=pom.DiscreteDistribution({0:0.68, 1:0.23, 2:0.09, 3:0})
d3=pom.DiscreteDistribution({0:0, 1:0, 2:0, 3:1})
distributionList3S=[d0,d1,d2,d3]
transMatrix3S=np.array([[0.95, 0.04, 0.  , 0.01],
       [0.  , 0.95, 0.04, 0.01],
       [0.  , 0.  , 0.99, 0.01],
       [0.  , 0.  , 0.  , 0.  ]])
start3S=np.array([0.75,0.25,0,0])
end3S=np.array([0,0,0,1])
model3S=pom.hmm.HiddenMarkovModel.from_matrix(transMatrix3S, distributionList3S,start3S,end3S)
```

And after that i wanted to fit model:

```
 seq=np.array([1, 0, 2, 0, 2, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 2, 2, 1, 0, 2, 0, 1, 2, 1, 1])
 val=model3S.fit([seq], verbose=True)
```

And as the result i received:
```
[1] Improvement: nan	Time (s): 0.0004015
Total Training Improvement: nan
Total Training Time (s): 0.0016
CPU times: user 2.21 ms, sys: 8 µs, total: 2.22 ms
Wall time: 1.64 ms
```

I think that in this situation should be a warning/exception raised.

-------
Edit:
sequence "seq" is incorrect  because on the end there is no digit 3. So model can't go to state with d3, and after that to end.

**Comment by jmschrei** [comment]
Your edit looks like it solved the problem. If you create a model where it is required that you go through a certain state it is impossible, using the EM algorithm implemented in pomegranate, to update the weights to make it not impossible.
