### ISSUE TITLE
How to use custom data (i.e. MNIST, OpenAI Gym)

### ISSUE THREAD

**Issue by ayaz-amin** [jmschrei/pomegranate#677]
Good day! 
I am working on a project that makes use of data other than lists and DataFrames. I have checked out the Markov Network tutorial (which shows a small example using digits), but it was not enough for me to be able to use 'real' data. I would like to be able to model 2D arrays (images and whatnot) for use in my project. I tried quite a few times, but it either requires 1D data, or I have to resort to integer data.

Take the following snippet:
```python
model.predict([[None, 1, 0, None, None], [None, None, 1, None, 0]])
```
It predicts integer values. Instead, I would like to predict tensors (such as 784 pixel arrays) instead. Is this doable?

Thanks again!

**Comment by jmschrei** [comment]
Sorry for not getting to this sooner. Unfortunately, pomegranate expects the data to be 2D where each row is an example and each column is a feature. It can't be expected to general tensors.

**Comment by ayaz-amin** [comment]
Thanks!
