### ISSUE TITLE
Possible bug in custom distributions

### ISSUE THREAD

**Issue by lw2767** [jmschrei/pomegranate#679]
# Problem

Fitting HMM with self-defined discrete distributions always uses the *entire* population even after k-means.

# Minimal example to reproduce

Poisson distribution is fully described by its first moment.

```python
import numpy as np
from scipy.stats import poisson
import json

class MyPoisson():
	def __init__(self, mu):
		self.mu = mu
		self.d = 1
		self.summaries = 0

	def log_probability(self, X):
		return poisson.logpmf(X, self.mu)

	def summarize(self, X, w=None):
		self.summaries += np.mean(X)

	def from_summaries(self, inertia=0.0):
		self.mu = self.summaries
		self.clear_summaries()

	def clear_summaries(self, inertia=0.0):
		self.summaries = 0

	@classmethod
	def from_samples(cls, X, weights=None):
		d = MyPoisson(0)
		d.summarize(X, weights)
		d.from_summaries()
		return d
    
	def to_json(self):
		infoDict = {"class": "Distribution",
					"name": "MyPoisson",
					"parameters": [self.mu]}
		return json.dumps(infoDict)
```

# Bug Displayed
Now, simulate 2 Poisson samples with mu values equal to 10 and 50 respectively:
Sample A: `12,7,11,14,6,9,8,8,6,11`
Sample B: `51,53,45,52,50,49,48,68,53,49`
Now just concatenate them:
```python
X=[12,7,11,14,6,9,8,8,6,11,51,53,45,52,50,49,48,68,53,49]
```
If we run
```python
model = HiddenMarkovModel.from_samples(MyPoisson, 2, [X], algorithm="baum-welch");
```
You would expect the HMM to have 2 states: s0=Poisson(10) and s1=Poisson(50), and the state transits from s0 to s1. Result gives 2 identical states with mu 30.5.

# Debugging Tried So Far
Running `NormalDistribution` gives the correct state inferences.
```python
model = HiddenMarkovModel.from_samples(NormalDistribution, 2, [X], algorithm="baum-welch");
```
Printing out a message in the function `MyPoisson.from_summaries` shows that the function is invoked twice (with correct means) by the k-means subsets. Then, it was called incorrectly on the entire `X` twice. The incorrect inferences overwrote the correct ones. Try the following code for example (I just removed the `weights` argument in `summarize()`, so the function throws an warning). Now, printing out `model` actually shows you the "intermediate" state inference that is correct.

```python
import numpy as np
from scipy.stats import poisson
import json

class MyPoisson():
	def __init__(self, mu):
		self.mu = mu
		self.d = 1
		self.summaries = 0

	def log_probability(self, X):
		return poisson.logpmf(X, self.mu)

	def summarize(self, X):
		self.summaries += np.mean(X)

	def from_summaries(self, inertia=0.0):
		self.mu = self.summaries
		self.clear_summaries()

	def clear_summaries(self, inertia=0.0):
		self.summaries = 0

	@classmethod
	def from_samples(cls, X, weights=None):
		d = MyPoisson(0)
		d.summarize(X)
		d.from_summaries()
		return d
    
	def to_json(self):
		infoDict = {"class": "Distribution",
					"name": "MyPoisson",
					"parameters": [self.mu]}
		return json.dumps(infoDict)
```

**Comment by jmschrei** [comment]
You need to take in and use the weight vector properly. The EM algorithm (Baum-Welch) will pass all points and their respective weights, with observations likely to come from that state having a high weight and observations unlikely to come from that state having a low weight. If you ignore weights you will incorrectly assume all points are equally likely to come from any distribution.

**Comment by lw2767** [comment]
Got it, my bad. Thanks a lot!
