### ISSUE TITLE
[BUG] HiddenMarkovModel issue with __repr__

### ISSUE THREAD

**Issue by joshdorrington** [jmschrei/pomegranate#681]
I'm having an issue, seemingly with getting HiddenMarkovModel objects to initialise properly.

```
import pomegranate
from pomegranate import *
import sys

print(sys.version)
print(pomegranate.__version__)

model=HiddenMarkovModel()

#just access the model as you would in an interactive terminal

model.__repr__()

```
```
3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0]

0.11.0

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-f9edd97e95bf> in <module>
     10 #just call model as you would in terminal
     11 
---> 12 model.__repr__()

pomegranate/base.pyx in pomegranate.base.Model.__repr__()

pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.to_json()

TypeError: 'NoneType' object is not iterable
```
I think there's also a deeper issue with getting HiddenMarkovModel to fit from samples, but I need to check I'm not just having memory issues first.

 I have used pomegranate in the past with no problems about a year ago, so I don't know if perhaps its an issue that's crept in with the latest updates.

**Comment by jmschrei** [comment]
While you're right that it shouldn't just raise a non-descript type-error, there's nothing to display because you haven't added anything to the model.

**Comment by joshdorrington** [comment]
Yes, I had remembered the syntax incorrectly, but ultimately got everything working. 
Perhaps worse than the type error, is when I tried:

`HiddenMarkovModel().get_params()`

It crashed my kernel. Obviously that's not a useful thing to try and do, which is why I closed the issue, but perhaps worth mentioning.
