### ISSUE TITLE
Negative Binomial distribution?

### ISSUE THREAD

**Issue by reckoner** [jmschrei/pomegranate#682]
Hi,

Are there any plans to implement the univariate negative binomial distribution? Thanks!

**Comment by jmschrei** [comment]
No plans right now to add in more distributions. That's not to say there never will be, but it'd probably be best for you to implement your own custom distribution for now. Is that feasible?

**Comment by reckoner** [comment]
Can you get me started on how to do that?

**Comment by jmschrei** [comment]
https://github.com/jmschrei/pomegranate/blob/master/tutorials/C_Feature_Tutorial_5_Custom_Distributions.ipynb Does this help?

**Comment by reckoner** [comment]
Yes. Let me study this in detail.

**Comment by neiljelmert** [comment]
I attempted to extend a Negative Binomial Distribution. It's not stable (and perhaps not efficient as I'm learning Cython). I'd love to collaborate, however!

I use the `(mean, dispersion)` parametrization for the distribution and use MLE to estimate both. The mean is easily estimated as the sample mean, but the dispersion is intractable and must be numerically solved. It only has one root when the sample variance is strictly larger than the sample mean, and zero roots otherwise. Moreover, the approximation methods used (`brentq` and `newton`) struggle when the dispersion is large (i.e. when the data more closely resembles a Poisson distribution) or when the sample size is small (higher probability of no roots).

I would like to add a catch which routes the fit to a Poisson when the variance is sufficiently close to the mean, but I haven't tried this yet.

Here's the `.pyx` script:

    import numpy
    import scipy

    from libc.stdlib cimport calloc
    from libc.stdlib cimport free
    from libc.string cimport memset

    from ..utils cimport _log
    from ..utils cimport isnan
    from ..utils import check_random_state
    from ..utils cimport lgamma
    from ..utils import weight_set

    from libc.math cimport sqrt as csqrt

    cimport numpy
    cimport cython # so we can use cython decorators
    from cpython cimport bool # type annotation for boolean

    DEF NEGINF = float("-inf")
    DEF INF = float("inf")

    cdef class NegativeBinomialDistribution(Distribution):
	"""A negative binomial distribution based on a mean and dispersion."""

	property parameters:
		def __get__(self):
			return [self.mu, self.theta]
		def __set__(self, parameters):

			mu, theta = parameters
			self.mu, self.theta = mu, theta

			self.log_mu = _log(mu)
			self.log_theta = _log(theta)

			self.mu_plus_theta = mu + theta
			self.log_mu_plus_theta = _log(mu + theta)

			self.r = theta
			self.var = mu + 1 / theta * mu ** 2
			self.p = (self.var - mu) / self.var

			self.r_p_params = (self.r, 1. - self.p)

	def __init__(self, double mu, double theta, bint frozen=False, double min_theta=1e-8):
		self.mu = mu
		self.theta = theta

		self.log_mu = _log(mu)
		self.log_theta = _log(theta)

		self.mu_plus_theta = mu + theta
		self.log_mu_plus_theta = _log(mu + theta)

		self.r = theta
		self.var = mu + 1 / theta * mu ** 2
		self.p = (self.var - mu) / self.var

		self.r_p_params = (self.r, 1. - self.p)

		self.name = "NegativeBinomialDistribution"
		self.frozen = frozen
		self.summaries = [0, 0, 0]

		self.min_theta = min_theta

	def __reduce__(self):
		"""Serialize distribution for pickling."""
		return self.__class__, (self.mu, self.theta, self.frozen)

	cdef void _log_probability(self, double* X, double* log_probability, int n) nogil:
		cdef int i
		cdef double mu = self.mu
		cdef double theta = self.theta
		cdef double mu_plus_theta = self.mu_plus_theta

		cdef double log_mu = self.log_mu
		cdef double log_theta = self.log_theta
		cdef double log_mu_plus_theta = self.log_mu_plus_theta
                 
                 # here is where we might route the distribution to a Poisson 
                 # when variance is sufficiently close to the mean (when theta is large)
		for i in range(n):
			if isnan(X[i]):
				log_probability[i] = 0.
			elif X[i] < 0 or mu <= 0 or theta <= 0:
				log_probability[i] = NEGINF
			else:
				log_probability[i] = lgamma(X[i] + theta) - lgamma(theta) - lgamma(X[i] + 1.) +\
					X[i] * log_mu - X[i] * log_mu_plus_theta + theta * log_theta -\
					theta * log_mu_plus_theta

	def sample(self, n=None, random_state=None):
		random_state = check_random_state(random_state)
		return random_state.negative_binomial(*self.r_p_params, n)

	def summarize(self, items, weights=None, column_idx=0):
		"""
		Take in a series of items and their weights and reduce it down to a
		summary statistic to be used in training later.
		"""

		self.n = len(items)
		self.X_ptr = <double*> calloc(self.n, sizeof(double))

		for i in range(self.n):
			self.X_ptr[i] += items[i]

		items, weights = weight_set(items, weights)
		if weights.sum() <= 0:
			return

		cdef double* items_p = <double*> (<numpy.ndarray> items).data
		cdef double* weights_p = <double*> (<numpy.ndarray> weights).data
		cdef int n = items.shape[0]
		cdef int d = 1
		cdef int column_id = <int> column_idx

		if items.ndim == 2:
			d = items.shape[1]

		with nogil:
			self._summarize(items_p, weights_p, n, column_id, d)


	cdef double _summarize(self, double* items, double* weights, int n,
		int column_idx, int d) nogil:
		cdef int i, j
		cdef double x_sum = 0.0, x2_sum = 0.0, w_sum = 0.0
		cdef double item

		for i in range(n):
			item = items[i*d + column_idx]
			if isnan(item):
				continue

			w_sum += weights[i]
			x_sum += weights[i] * item
			x2_sum += weights[i] * item * item

		with gil:

			self.summaries[0] += w_sum
			self.summaries[1] += x_sum
			self.summaries[2] += x2_sum


	def from_summaries(self, inertia=0.0,
		iteration_limit=500):
		"""
		Takes in a series of summaries, represented as a mean, a variance, and
		a weight, and updates the underlying distribution.
		"""

		# If no summaries stored or the summary is frozen, don't do anything.
		if self.summaries[0] < 1e-8 or self.frozen == True:
			return

		mu = self.summaries[1] / self.summaries[0]
		var = self.summaries[2] / self.summaries[0] - self.summaries[1] ** 2.0 / self.summaries[0] ** 2.0

		theta_guess = mu ** 2 / ( var - mu ) # method of moments estimation

		# gradient of log-likelihood w.r.t. theta
		def nll_gradient_dispersion(theta, mu):

			first_term = sum([scipy.special.polygamma(0, self.X_ptr[i] + theta) for i in range(self.n)])

			second_term = self.n * scipy.special.polygamma(0, theta)

			third_term = self.n * numpy.log( 1. + mu / theta)

			return first_term - second_term - third_term

		def nll_gradient_dispersion_newton(theta, mu, X_ptr, n):

			first_term = sum([scipy.special.polygamma(0, X_ptr[i] + theta) for i in range(n)])

			second_term = n * scipy.special.polygamma(0, theta)

			third_term = n * numpy.log( 1. + mu / theta)

			return first_term - second_term - third_term

		def d_nll_gradient_dispersion_newton(theta, mu, X_ptr, n):

			first_term = sum([scipy.special.polygamma(1, X_ptr[i] + theta) for i in range(n)])

			second_term = n * scipy.special.polygamma(1, theta)

			third_term = n * mu / (theta ** 2 + theta * mu)

			return first_term - second_term + third_term


                 # the idea here was to perform numeric MLE for theta 
                 # but due to instabilities in theta (being sampled negatively, etc.) 
                 # it wasn't working as expected. When variance < mean, there is no root to find. 
                 # Room for improvement!

		# self.var = self.mu + 1
		# if self.var > self.mu:

		if var >  mu:
			theta_hat = theta_guess
			# theta_hat = scipy.optimize.brentq(f=nll_gradient_dispersion, 
			# 								  a=self.min_theta, 
			# 								  b=100+theta_guess,
			# 								  args=(mu),
			# 								  maxiter=300)

			# X_ptr = [self.X_ptr[i] for i in range(self.n)]
			# n = len(X_ptr)
			# theta_hat = scipy.optimize.newton(func=nll_gradient_dispersion,
			# 								  x0=theta_guess,
			# 								  fprime=nll_gradient_dispersion_der,
			# 								  args=(mu, X_ptr, n),
			# 								  tol=1e-1,
			# 								  maxiter=300)

                 # use a bootstrap method to find a sample with variance > mean
		else:
			thetas = []
			for _ in range(20):

				iteration = 0
				while var < mu + 1.:

					X_bootstrap = numpy.random.choice(a=[self.X_ptr[i] for i in range(self.n)], size=200, replace=True)

					mu = numpy.mean(X_bootstrap)
					var = numpy.var(X_bootstrap)

					iteration += 1

					if iteration > iteration_limit:
						"Iteration exceeded limit."
						mu = var - 1. # instead, should route to Poisson

					theta_guess = mu ** 2 / ( var - mu )

				# theta_approx = scipy.optimize.brentq(f=nll_gradient_dispersion, 
				# 									 a=self.min_theta, 
				# 									 b=100+theta_guess,
				# 									 args=(mu),
				# 									 maxiter=300)

				# X_ptr = [self.X_ptr[i] for i in range(self.n)]
				# n = len(X_ptr)

				# theta_approx = scipy.optimize.newton(func=nll_gradient_dispersion,
				# 							  x0=theta_guess,
				# 							  fprime=nll_gradient_dispersion_der,
				# 							  args=(mu, X_bootstrap, n),
				# 							  tol=1e-1,
				# 							  maxiter=300)
				thetas.append(theta_guess)

			theta_hat = numpy.median(thetas)

		mu = 0.5 * numpy.sqrt( theta_hat ** 2 + 4 * theta_hat * var ) - 0.5 * theta_hat

		self.mu = self.mu*inertia + mu*(1-inertia)
		self.theta = self.theta*inertia + theta_hat*(1-inertia)

		self.summaries = [0, 0, 0]

		self.log_mu = _log(mu)
		self.log_theta = _log(theta_hat)

		self.mu_plus_theta = mu + theta_hat
		self.log_mu_plus_theta = _log(mu + theta_hat)

		self.r = theta_hat
		self.var = mu + 1 / theta_hat * mu ** 2
		self.p = (self.var - mu) / self.var

		self.r_p_params = (self.r, 1. - self.p)


	def clear_summaries(self):
		"""Clear the summary statistics stored in the object."""

		self.summaries = [0, 0, 0]


	@classmethod
	def blank(cls):
		return NegativeBinomialDistribution(10, 5)

**Comment by reckoner** [comment]
I'm not familiar with Cython, but are you considering the case with `n` as a continuous parameter or a discrete parameter? I don't understand how you can estimate `n` successes and `p` (probability of success) from data. Is this not fundamentally ill-posed?

**Comment by neiljelmert** [comment]
Hi @reckoner -- there are multiple parameterizations and views (see [here](https://www.johndcook.com/blog/2009/09/22/negative-binomial-distribution/) and [here](https://www.johndcook.com/blog/2009/11/03/negative-binomial-poisson-gamma/)) of  the negative binomial distribution. In practice I use the _modeling overdispersion_ and _Hierarchical Poisson-Gamma_ views.

If we forget the motivation for where the negative binomial distribution came from, we can relax the assumptions of parameter domain to be continuous. This works because now `n` and `p` are no longer directly important and we can rely on empirical summaries like mean, variance, etc. (see [here](https://www.johndcook.com/negative_binomial.pdf)). In this sense, `n` represents the dispersion (and is continuous) and `p` is treated as derived from `n` and `mu`.

Perhaps I'm misunderstanding your concern, so please update me if that's the case. In any case, I'd be happy to work with you on improving the negative binomial functionality within pomegranate.
