### ISSUE TITLE
nan KeyError with missing data

### ISSUE THREAD

**Issue by belfer24** [jmschrei/pomegranate#683]
**Describe the bug**
Trying to fit a Bayes Net with a dataset with missing data.  When I'm calling the fit function, I'm getting KeyError: nan.

**To Reproduce**
[pomegranate_test.txt](https://github.com/jmschrei/pomegranate/files/4124671/pomegranate_test.txt)

**Comment by jmschrei** [comment]
Fixed this issue in 0.12.1. Thanks for reporting.
