### ISSUE TITLE
HMM bake() function throws networkx runtime error

### ISSUE THREAD

**Issue by florianthalmann** [jmschrei/pomegranate#684]
Hi! Running into this error in lots of different situations when building or loading HMM models whenever the bake() function is called (maybe related to #671):
```
Traceback (most recent call last):
  File "src/models/test.py", line 3, in <module>
    model = HiddenMarkovModel.from_json("test.json")
  File "pomegranate/hmm.pyx", line 3308, in pomegranate.hmm.HiddenMarkovModel.from_json
  File "pomegranate/hmm.pyx", line 802, in pomegranate.hmm.HiddenMarkovModel.bake
  File "/anaconda2/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 666, in <genexpr>
    return (self._report(n, nbr, dd) for n, nbrs in self._nodes_nbrs()
RuntimeError: dictionary changed size during iteration
```
Simplest way to reproduce this is by loading the attached file (properly serialized with to_json() and looking fine) with:
```
HiddenMarkovModel.from_json("test.json")
```
(pomegranate 0.12.0, networkx 2.4)
[test.json.zip](https://github.com/jmschrei/pomegranate/files/4128446/test.json.zip)

**Comment by jmschrei** [comment]
This is related to the networkx upgrade to v2.0. By default, pomegranate will reduce the size of models by getting rid of uninformative silent states. I fixed the issue but I also switched the default mode to be to not try to simplify the model. The merging of these states was useful for research I wrote a while ago but most people probably don't want their models being messed with.
