### ISSUE TITLE
installation error with old version

### ISSUE THREAD

**Issue by kevinlib** [jmschrei/pomegranate#687]
Trying to install v0.8.1 (b/c of #384) via both pip and source on mac and linux and running into issue #333

**Comment by jmschrei** [comment]
Does the solution presented there not solve your issue?

**Comment by kevinlib** [comment]
No because if you pip install from git, it just installs the latest version of the package.

**Comment by jmschrei** [comment]
I'm not sure what the issue is. Can you try deleting all pomegranate files from your compute (including site-packages) and re-install?
