### ISSUE TITLE
check input failed for BayesianNetwork model predict() method.

### ISSUE THREAD

**Issue by bushyttail** [jmschrei/pomegranate#688]
I got this ValueError, not sure what it means

```
    pred_1 = model_1.predict(X_pred, n_jobs=-1)
  File "pomegranate/BayesianNetwork.pyx", line 537, in   
pomegranate.BayesianNetwork.BayesianNetwork.predict
  File "pomegranate/BayesianNetwork.pyx", line 592, in pomegranate.BayesianNetwork.BayesianNetwork.predict_proba
  File "pomegranate/BayesianNetwork.pyx", line 133, in pomegranate.BayesianNetwork._check_input
ValueError: State '1' does not have key '1892.0'
```

the array I passed to predict() method is like this

```
[[ nan  70.   1. ...   0.   0.   0.]
 [ nan 114.   1. ...   0.   0.   0.]
 [ nan 103.   1. ...   0.   0.   0.]
 ...
 [ nan  20.   0. ...   0.   0.   0.]
 [ nan   9.   0. ...   0.   0.   0.]
 [ nan  18.   0. ...   0.   0.   0.]]
```
the first column is what pomegranate is supposed to predict.
for what reason does my array didin't pass _check_input? Having searched the documentation and found no explanation.

**Comment by bushyttail** [comment]
`import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from pomegranate import BayesianNetwork
import seaborn, time
seaborn.set_style('whitegrid')

file = "/home/vmware/桌面/XSS/数据收集/Web安全之机器学习入门/XSS_FEATURES_10_10_PERCENT_14535-29701.csv"


X = pd.read_csv(file)# often works
X.info() # index & data types


#  ------------With Cross-validation to be added--------------------
# Importing the dataset
dataset = pd.read_csv(file)


#Splitting the dataset into the Training set and Test set
dataset_copy = dataset.copy()
# train_set = dataset_copy.sample(frac=0.75, random_state=0)
train_set = dataset_copy.sample(frac=0.9, random_state=0)
test_set = dataset_copy.drop(train_set.index)



#  DEALING WITH VARIABLES
# X -> train_dataset
# X_pred-> test_dataset
train_dataset = train_set
test_dataset = test_set

X = train_dataset
X_pred = test_dataset
print("------------")
print("train_dataset.info")
X.info() # index & data types
print("------------")
print("test_dataset.info")
X_pred.info() # index & data types



tic_1 = time.time()
# Approximate Learning: Greedy Search (pomegranate default)
# model_1 = BayesianNetwork.from_samples(X) # << Default BNSL setting
# model_1 = BayesianNetwork.from_samples(X) # << Default BNSL setting
model_1 = BayesianNetwork.from_samples(X, n_jobs=2)   # << Default BNSL setting
# n_jobs:int, optional
# The number of threads to use when learning the structure of the network.
t_1 = time.time() - tic_1
p_1 = model_1.log_probability(X).sum()

print("Greedy")
print("Time (s): ", t_1)
print("P(D|M): ", p_1)
# %memit BayesianNetwork.from_samples(X)
print(model_1.structure)
model_1.plot()


tic_2 = time.time()
model_2 = BayesianNetwork.from_samples(X, algorithm='chow-liu', n_jobs=2)  # << Default BNSL setting
t_2 = time.time() - tic_2
p_2 = model_2.log_probability(X).sum()

print("Chow-Liu")
print("Time (s): ", t_2)
print("P(D|M): ", p_2)
# %memit BayesianNetwork.from_samples(X, algorithm='chow-liu')
print(model_2.structure)
model_2.plot()


# bake the modle
model_1.bake()
print("model_1 baked")
model_2.bake()
print("model_2 baked")


X_pred['FEATURE_0'] = np.repeat(np.nan, len(X_pred.FEATURE_0))
# X_pred['FEATURE_0'] = np.repeat(np.nan, len(X_pred.FEATURE_0))

# Peek at the DataFrame contents
n = 4
dfh = X_pred.head(n)
print("take a peek")
print(dfh)
X_pred.info() # index & data types

# dataframe convert to array
# DataFrame.to_numpy()
X_pred = X_pred.to_numpy()
print("X_pred")
print(X_pred)

# pred_1 = model_1.predict(X_pred)
pred_1 = model_1.predict(X_pred, n_jobs=-1)
#  -1 means use all available resources
print("pred_1 prediction:")
print(pred_1)

pred_2 = model_2.predict(X_pred)
print("model_2 prediction:")
print(pred_2)
`
code included

**Comment by jmschrei** [comment]
My guess is either (1) that your model has integers as the keys and you're passing in floats or (1) that you did not have that key in your training data and so the model does not have a corresponding key for that column. You can check this by printing out the model and seeing what keys are stored in each distribution. You can also check your training data to see if that key occurs.
