### ISSUE TITLE
Does BayesianNetwork.add_edge() support adding a weight?

### ISSUE THREAD

**Issue by ohramireza** [jmschrei/pomegranate#690]
Hello,
I am trying to implement a BayesianNetwork where I also want to add a weight between the two nodes. I thought "add_edge()" would do but it does not. Interestingly when I define a node "Node()" I can add a weight to a node ( for example: Node(distribution, name='NodeName',weight=0.4)) but it does not seem to do anything .... to me it seems this cannot be done ... am I wrong?

Thanks,
Oscar

**Comment by jmschrei** [comment]
There are no weights in Bayesian network edges.
