### ISSUE TITLE
[BUG] Unusual Behavior of GeneralMixtureModel When Number of Distributions Doesn't Match Number of Columns in Data

### ISSUE THREAD

**Issue by a3huang** [jmschrei/pomegranate#691]
**Describe the bug**
I'm confused on the behavior of GeneralMixtureModel when the number of columns of the data does not match the number of independent component distributions passed in. When I was playing around with the API, I passed in 2 distinct component distributions along with a data matrix X into the `GeneralMixtureModel.from_samples` method.

If X has 2 columns, then it creates a mixture of 2 independent component distributions as expected.

However, if X has more than 2 columns (say 3), it seems to return a mixture of 2 univariate distributions. But the data X is multivariate as each observation is represented by a vector of length 3. This is confusing as I don't know how the data was used to estimate parameters. Was the X matrix reshaped into a 1D vector? Were some of the columns thrown away during the fitting procedure? If this wasn't the intended behavior, perhaps a warning should be shown to users.

Furthermore, when I was querying the model for probabilities, I got different results depending on the shape of the same vector passed in. Maybe this is the intended behavior, but I could not find anything that explicitly stated this in the documentation and found it very confusing when I first encountered it.

**To Reproduce**
```
# pass in 2 distributions, but X has 3 columns
# returns a univariate mixture model rather than a multivariate mixture model
X = np.random.rand(10, 3)
model = GeneralMixtureModel.from_samples(
    [NormalDistribution, LogNormalDistribution], 2, X)

# this returns a probability array of shape (3,)
model.probability(X[0])

# this returns a scalar probability that happens to be the first element of the above array
model.probability(X[:1])
```

I am using pomegranate version 0.12.0.

**Comment by jmschrei** [comment]
Howdy

Using a different number of distributions as number of dimensions when the data doesn't only have one column should (but currently doesn't) raise an error. What ends up happening is that it fits an array to the first N numbers in the flattened array, which is clearly the wrong behavior. I'll add an error message when I do my next round of additions to pomegranate. Sorry for the inconvenience.

**Comment by a3huang** [comment]
Great! Thanks for the quick response.

Also, I noticed that for univariate distributions, passing an array of shape (N,) or (N, 1) into `.probability` gives back an array of shape (N,) as expected.

However, passing an array of shape (1, N) into `.probability` gives only a scalar back. What do you think about raising in error in that scenario as well?

**Comment by jmschrei** [comment]
An error should be raised when the shape doesn't match the expected shape. However, you should expect to get a single probability back when your data only has one row.

**Comment by jmschrei** [comment]
Fixed.
