### ISSUE TITLE
Cannot serialize MarkovNetwork to JSON

### ISSUE THREAD

**Issue by a3huang** [jmschrei/pomegranate#699]
**Describe the bug**
It seems that when I call the `.from_samples` method of `MarkovNetwork`, I am unable to print the model to see what it contains. The `.to_json` method also fails.

In both cases I get the following error:
```
TypeError: Object of type int64 is not JSON serializable
```

Even when I explicitly convert the numpy array to a regular python list first, it still gives me the same error.

**To Reproduce**
```
import numpy as np
from pomegranate import MarkovNetwork

X = np.random.randint(2, size=(100, 2))
model = MarkovNetwork.from_samples(X)
model
```
Even this doesn't work
```
model = MarkovNetwork.from_samples(X.tolist())
model
```

**Version**
0.12.0

**Comment by ashwinpn** [comment]
Try using numpy.ndarray.item (See below)

[https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.item.html]

**Comment by a3huang** [comment]
@ashwinpn Hm. That seems to just take a single element of a numpy array (in this case of type int64) and return it as a python integer. The `.tolist` method basically does the same thing only on every element of the list rather than one element at a time.

Even using the `.item` method, I still end up with the same error.

**Comment by ashwinpn** [comment]
Okay, try using `Pandas`
`
import pandas as pd
pd.Series(X).to_json(orient='values')
`

**Comment by jmschrei** [comment]
Should be fixed in the next patch. Thanks for pointing this out and sorry for the late reply.
