### ISSUE TITLE
Imputation of missing values of continuous data from Bayesian network？

### ISSUE THREAD

**Issue by JuJuWei** [jmschrei/pomegranate#701]
Hello, I am trying to impute the missing value of continuous data  from Bayesian network using belief propagation or loop belief propagation algorithm. And the adjacency is known. Does pomegranate support this operation ？

**Comment by jmschrei** [comment]
Howdy. Unfortunately, pomegranate does not currently support continuous data or hybrids of continuous and discrete data. It currently only support entirely categorical/discrete data.
