### ISSUE TITLE
[BUG] HiddenMarkovModel.sample() not working because of numpy.random.mtrand.RandomState error

### ISSUE THREAD

**Issue by lucheroni** [jmschrei/pomegranate#706]
Hello.

I'm considering pomegranate for a research project which uses tied-mixture multivariate gaussian HMMs. Until now I used Murphy's Matlab toolboxes.

I cannot make pomegranate.hmm.HiddenMarkovModel.sample() work, even with very simple models.

I'm working with anaconda/spyder under win10 and python 3.6.10.
I created an empty dedicated environment with conda, and fresh-installed in it pomegranate 0.12.0. (I first installed spyder-kernels 0.5.2 as usual, then pomegranate, which loaded numpy 1.18.1 and scipy 1.3.1 among others.) 
 
The I-Python interpreter gets stuck when it runs anything like model.sample() until ctrl_c is hit, returning:
>SystemError: <class 'numpy.random.mtrand.RandomState'> returned a result with an error set

I tried the fresh-install many times.

This is the most basic code which I tried:
#-----------
import numpy as np
from pomegranate import *

numpy.random.seed(0)
nd1_simple = NormalDistribution(3, 2)
nd2_simple = NormalDistribution(1, 7)
dists1 = [nd1_simple, nd2_simple]
starts1 = numpy.array([0.9, 0.1])
trans_mat1 = numpy.array([[0.7, 0.3],[0.2, 0.8]])
model1 = HiddenMarkovModel.from_matrix(trans_mat1, dists1, starts1)
model1.bake(verbose=True)
model1.sample(10)
#---------

Thank you in advance for any help.

**Comment by jmschrei** [comment]
Hi

You should take a look at the documentation of that method: https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L1140

```
    def sample(self, n=None, length=0, path=False, random_state=None):
        Generate a sequence from the model.

        Returns the sequence generated, as a list of emitted items. The
        model must have been baked first in order to run this method.
        
        If a length is specified and the HMM is infinite (no edges to the
        end state), then that number of samples will be randomly generated.
        If the length is specified and the HMM is finite, the method will
        attempt to generate a prefix of that length. Currently it will force
        itself to not take an end transition unless that is the only path,
        making it not a true random sample on a finite model.

        WARNING: If the HMM has no explicit end state, must specify a length
        to use.

        Parameters
        ----------
        n : int or None, optional
            The number of samples to generate. If None, return only one sample.

        length : int, optional
            Generate a sequence with a maximal length of this size. Used if
            you have no explicit end state. Default is 0.

        path : bool, optional
            Return the path of hidden states in addition to the emissions. If
            true will return a tuple of (sample, path). Default is False.

        random_state : int, numpy.random.RandomState, or None
            The random state used for generating samples. If set to none, a
            random seed will be used. If set to either an integer or a
            random seed, will produce deterministic outputs.

        Returns
        -------
        sample : list or tuple
            If path is true, return a tuple of (sample, path), otherwise return
            just the samples.
   ```

Your model doesn't have an explicit end state and you haven't given a length that you want the sequence to be. Thus, the sampling procedure is bouncing back and forth between the two states forever because there's no way for it to end. You should either specify a length of the sequences you want or put an explicit end state in your model.

**Comment by lucheroni** [comment]
Thank you. I should have read that.
