### ISSUE TITLE
How do I define a Gaussian PDF with multi-dimensional covariance matrix?

### ISSUE THREAD

**Issue by HYDesmondLiu** [jmschrei/pomegranate#710]
I read the document on website but I still cannot understand how do I initialize a Gaussian PDF with covariance as a matrix?

![image](https://user-images.githubusercontent.com/43663175/77120063-28c31900-69f5-11ea-921a-a1565874e512.png)

**Comment by jmschrei** [comment]
I'm not sure what the issue is. Why can't you use `MultivariateGaussianDistribution`?
