### ISSUE TITLE
BayesianNetwork .from_samples() fails with 'nan' values

### ISSUE THREAD

**Issue by vahndi** [jmschrei/pomegranate#711]
Hi Jacob, thanks for the awesome library. I'm having some trouble with constructing a Bayesian Network from samples with null values, even when I replace them with the `'nan'` string. Example here:

    from numpy import nan
    from pandas import DataFrame
    from pomegranate.BayesianNetwork import BayesianNetwork

    data = DataFrame({
        'a': ['x', 'y', 'z', 'x', 'y', 'z'],
        'b': ['u', 'u', 'v', 'v', nan, nan]
    })

    bn_orig = BayesianNetwork.from_samples(data)
    # fails with "TypeError: '<' not supported between instances of 'NoneType' and 'str'"
    bn_nan_str = BayesianNetwork.from_samples(data.fillna('nan'))
    # fails with "TypeError: '<' not supported between instances of 'NoneType' and 'str'"
    bn_sentinel = BayesianNetwork.from_samples(data.fillna('sentinel'))
    # works

Is this a bug or intended behaviour? Is it safe to use a sentinel value here?

Thanks!

**Comment by jmschrei** [comment]
This is a bug. To circumvent this, convert your data from strings to integer encodings. The following code works:

```
data = numpy.array([[0, 0],
				    [1, 0],
				    [2, 1],
				    [0, 1],
				    [1, nan],
				    [2, nan]])

bn_orig = BayesianNetwork.from_samples(data)
```

**Comment by vahndi** [comment]
got it. thanks!
