### ISSUE TITLE
BetaDistribution.from_samples(data) returning incorrect parameters 

### ISSUE THREAD

**Issue by jmount1992** [jmschrei/pomegranate#713]
**Describe the bug**
When passing in a 1D list of numpy array into BetaDistribution.from_samples(<data>) it does not correctly fit the data it seems. The parameters simply become alpha=0 and beta=len(data). Based on this extract from the documentation, I believe I am using the method correctly.

"However, frequently we don’t know the parameters of the distribution beforehand or would like to directly fit this distribution to some data. We can do this through the from_samples class method."

**To Reproduce**
`import numpy as np`
`from pomegranate import *`
`data = np.random.beta(0.5, 1, 1000)`
`dist = BetaDistribution(data)`
`print(dist)`

result:
{
"class" :"Distribution",
    "parameters" :[
        0.0,
        1000.0
    ],
    "name" :"BetaDistribution",
    "frozen" :false
}

**Comment by jmount1992** [comment]
Current work around is using scipy.stats.beta.fit(<data>) to fit the data then create BetaDistribution(a,b)

**Comment by jmschrei** [comment]
Howdy

Sorry for the confusion. If you read the documentation you'll note that this is a Beta-Bernoulli distribution where the inputs are expected to be binary and not a simple beta distribution where the values range from 0 to 1.

```python
cdef class BetaDistribution(Distribution):
	"""A beta-bernoulli distribution.

	This object is a beta-bernoulli distribution. This means that it uses
	a beta distribution to model the distribution of values that the rate
	value can take rather than it being a single number.

	This should not be confused with a Beta distribution by itself.
        """
```
