### ISSUE TITLE
BayesianNetwork.from_structure exiting with AttributeError

### ISSUE THREAD

**Issue by theyeahman** [jmschrei/pomegranate#721]
**Describe the bug**
When trying to fit a structured Bayesian Network, an error is returned suggesting my input types are incorrect. I am new to this package but from what I can tell my inputs are correct. Is this a bug?

**To Reproduce**
![image](https://user-images.githubusercontent.com/62112568/78647304-4bd54000-78b2-11ea-880a-99b47fe7bd81.png)

**Comment by sverchkov** [comment]
I think your node indexes in the structure definition are off by 1, they should be 0-indexed. The way your structure is defined now has loops.

There should probably be a more informative error raised for that.

**Comment by jmschrei** [comment]
Yes, I suspect the issue here is that you're trying to have node 7 be a parent of itself.
