### ISSUE TITLE
Unable to pass networkx kwargs to hmm model.plot()

### ISSUE THREAD

**Issue by keoughkath** [jmschrei/pomegranate#725]
Using pomegranate v0.11.1, networkx v2.4 both installed with Conda on Linux I'm unable to pass kwargs to networkx through HMM model.plot so I'm unable to customize the figure. 

**To Reproduce**
`https://gist.github.com/keoughkath/363d875f62b39a31dde77a372b74f9a0`

Is this me doing something wrong? Thanks!

**Comment by jmschrei** [comment]
Do you have pygraphviz installed? If you look at https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L683 you'll see that kwargs is ignored (perhaps it's own issue) unless it's falling back to the networkx backend.

**Comment by keoughkath** [comment]
I do have pygraphviz installed. Ok so I have to uninstall that if I want to customize it it looks like. Thanks!
