### ISSUE TITLE
[QUESTION] SIGSEGV error in viterbi training

### ISSUE THREAD

**Issue by cvdelannoy** [jmschrei/pomegranate#726]
Hi,
Thanks a lot for developing pomegranate, it's working wonders for me! 

Not sure if this is a bug or just me trying something stupid but I can't figure it out. I'm writing a tool that produces HMMs of certain preset structures. For one of those structures, I can't train or predict using viterbi:
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
Also attached an image of the HMM structure.

Attached a yaml with the structure and some data on which this occurs, to reproduce:
```
import pomegranate as pg
import pickle

with open('hmm_error2.yml', 'r') as fh:
    hmm_txt = fh.read()
hmm = pg.HiddenMarkovModel().from_yaml(hmm_txt)
with open('data_hmm_error.pkl', 'rb') as fh:
    data = pickle.load(fh)

hmm.fit(data, algorithm='viterbi')
```
I've tried to make a minimal working example for this issue in which the network is generated from the start (my own code generates it through a GUI and frankly, is a mess atm so I think that won't help), but I just can't seem to do it. It combines  `IndependentComponentsDistribution` s (the exy_z nodes) and `MultivariateGaussianDistribution`s (the sx_y nodes) and multiple silent states, but none of that is giving issues in other occasions. I'll keep trying to zoom in on the issue here, but can you see any reason for this error at this point?

[pomegranate_error_data.zip](https://github.com/jmschrei/pomegranate/files/4504802/pomegranate_error_data.zip)
![hmm_error](https://user-images.githubusercontent.com/21309905/79776043-6e953900-8335-11ea-807a-e3fb3b8eb972.png)

**Comment by jmschrei** [comment]
Looks like that's some sort of segfault. I'm not sure exactly what the reason is but I suspect it has to do with the calls to BLAS made in the MultivariateGaussianDistribution. Can you try removing those distributions from your code that produces HMMs and see whether they work?

**Comment by cvdelannoy** [comment]
Hi Jacob,

That does not appear to be the problem; I've replaced them with IndependentComponentDistributions and NormalDistributions, but the problem persists.

I did manage to make a reduced example exhibiting the problem now; seems that it doesn't like the structure of a non-silent state between silent states:   
![small_faulty_hmm](https://user-images.githubusercontent.com/21309905/79879746-64377580-83ef-11ea-97d5-6c91e9ea7784.png)

If I allow `bake` to merge, S1 disappears but the segfault remains.

```
import pomegranate as pg
import numpy as np

data = [np.random.rand(10), np.random.rand(10), np.random.rand(10)]

# Either S1 or S2 is not silent --> no issue
hmm = pg.HiddenMarkovModel()
state_S1 = pg.State(pg.NormalDistribution(0, 1), name='S1')
state_S2 = pg.State(None, name='S2')
state_A = pg.State(pg.NormalDistribution(0, 1), name='A')
hmm.add_transition(hmm.start, state_S1, 1)
hmm.add_transition(state_S1, state_A, 1)
hmm.add_transition(state_A, state_S2, 1)
hmm.add_transition(state_S2, state_S1, 0.5)
hmm.add_transition(state_S2, hmm.end, 0.5)
hmm.bake(merge='None')
hmm.fit(data, algorithm='viterbi')

hmm = pg.HiddenMarkovModel()
state_S1 = pg.State(None, name='S1')
state_S2 = pg.State(pg.NormalDistribution(0, 1), name='S2')
state_A = pg.State(pg.NormalDistribution(0, 1), name='A')
hmm.add_transition(hmm.start, state_S1, 1)
hmm.add_transition(state_S1, state_A, 1)
hmm.add_transition(state_A, state_S2, 1)
hmm.add_transition(state_S2, state_S1, 0.5)
hmm.add_transition(state_S2, hmm.end, 0.5)
hmm.bake(merge='None')
hmm.fit(data, algorithm='viterbi')

# Both S1 and S2 silent --> segfault
hmm = pg.HiddenMarkovModel()
state_S1 = pg.State(None, name='S1')
state_S2 = pg.State(None, name='S2')
state_A = pg.State(pg.NormalDistribution(0, 1), name='A')
hmm.add_transition(hmm.start, state_S1, 1)
hmm.add_transition(state_S1, state_A, 1)
hmm.add_transition(state_A, state_S2, 1)
hmm.add_transition(state_S2, state_S1, 0.5)
hmm.add_transition(state_S2, hmm.end, 0.5)
hmm.bake(merge='None')
hmm.fit(data, algorithm='viterbi')
```

**Comment by jmschrei** [comment]
That's weird. I'm not sure exactly what the issue is off the top of my head but it probably has something to do with the silent state having a probability of 1. You could get the same model by adding an edge between None-start and A and S2 and A. Though, that could also be reduced to a simpler model of None-start -> A -> None-end with a self-loop on A. I know this is a simplified example but maybe you can modify your real model in such a manner?

**Comment by cvdelannoy** [comment]
Yeah gets weirder even. I did some more digging, it seems like it really has an issue with having to go through too many loops of non-silent and silent states. For completion's sake I figured out how many is too many for a small graph. The answer is five, it would seem:
```
# 4-sample-sequence, P_transition=1.0: works
hmm = pg.HiddenMarkovModel()
state_S1 = pg.State(None, name='S1')
state_A1 = pg.State(pg.NormalDistribution(0, 1), name='A1')
hmm.add_transition(hmm.start, state_A1, 1.0)
hmm.add_transition(state_A1, state_S1, 1.0)
hmm.add_transition(state_S1, state_A1, 0.5)
hmm.add_transition(state_S1, hmm.end, 0.5)
hmm.bake(merge='None')
hmm.fit([np.random.rand(4), np.random.rand(4), np.random.rand(4)], algorithm='viterbi')
print('scenario 1 works')


# 5-sample-sequence, P_transition=0.1: works
hmm = pg.HiddenMarkovModel()
state_S1 = pg.State(None, name='S1')
state_A1 = pg.State(pg.NormalDistribution(0, 1), name='A1')
hmm.add_transition(hmm.start, state_A1, 1.0)
hmm.add_transition(state_A1, state_S1, 0.1)
hmm.add_transition(state_A1, state_A1, .9)
hmm.add_transition(state_S1, state_A1, 0.5)
hmm.add_transition(state_S1, hmm.end, 0.5)
hmm.bake(merge='None')
hmm.fit([np.random.rand(5), np.random.rand(5), np.random.rand(5)], algorithm='viterbi')
print('scenario 2 works')

# 5-sample-sequence, P_transition=0.9: segfault
hmm = pg.HiddenMarkovModel()
state_S1 = pg.State(None, name='S1')
state_A1 = pg.State(pg.NormalDistribution(0, 1), name='A1')
hmm.add_transition(hmm.start, state_A1, 1.0)
hmm.add_transition(state_A1, state_S1, 0.9)
hmm.add_transition(state_A1, state_A1, .1)
hmm.add_transition(state_S1, state_A1, 0.5)
hmm.add_transition(state_S1, hmm.end, 0.5)
hmm.bake(merge='None')
hmm.fit([np.random.rand(5), np.random.rand(5), np.random.rand(5)], algorithm='viterbi')
```
So it's not quite the transition prob of 1, but it doesn't help :)

I don't quite know how to debug something like this, nor where the problem exactly originates, or I'd make a pull request. Do you think this can be fixed? If you don't have time but some pointers I don't mind looking.

btw, I took your advice and altered my code to avoid the silent states completely, while doing roughly the same. Thanks for thinking with me here!

as a side note: my original purpose for this structure was to have an HMM in which the states were initialized using the weights and distributions of a GMM. Is there a less convoluted way to do that perhaps?

**Comment by ekosman** [comment]
@cvdelannoy A little off-topic, how did you create these visualizations?

**Comment by cvdelannoy** [comment]
You can call `plot` on an hmm object, like so:
'''
import matplotlib.pyplot as plt
plt.figure(dpi=400)
hmm.plot()
plt.savefig('fig.svg')
'''

**Comment by ekosman** [comment]
@cvdelannoy Yea I actually figured that out before, thanks!

**Comment by jmschrei** [comment]
I'm not sure what difficulty you're encountering with transferring weights from a GMM to a HMM. You can do 

```
d1 = NormalDistribution(0, 1)
d2 = NormalDistribution(1, 1)

model = GeneralMixtureModel([d1, d2])
model.fit(... data ...)

s1 = State(d1)
s2 = State(d2)

model = HiddenMarkovModel()
model.add_states(s1, s2)
... build the rest of your model here ....
```

If they're using the same underlying distribution objects you can even interleave training of the parameters, doing one iteration of training with the GMM and then one iteration with the HMM. I don't know why you'd like to do that, but it just illustrates what can be done.

**Comment by cvdelannoy** [comment]
Yeah that's what I wanted! Also saw the same thing being done in other issues, so I'll see how it works out for me. Since the error doesn't seem to originate from pomegranate itself I'll close this one now. Thanks for the help!
