### ISSUE TITLE
Proposal: Make HMM conform to deepcopy

### ISSUE THREAD

**Issue by Narsail** [jmschrei/pomegranate#73]
Scenario:

In my project i need to concatenate (sometimes) the same model once, twice or multiple times. To achieve this, i used to save it as json and reload it to get another instance. This was necessary to get two models, the original one and the concatenated one for comparison.

This comes with two problems:
1. At the moment a bug while saving/loading is messing with my HMM edge values (explained in #72)
2. It is a workaround.

Sadly the deepcopy function is not working properly. Though it doesn't throw an error the new HMM instance is still broken.

When i use the Frontpage example for the HMM, the following is happening:

``` python
-0.505202786679
Exception TypeError: "object of type 'NoneType' has no len()" in 'pomegranate.hmm.HiddenMarkovModel.log_probability' ignored
0.0
```
with
``` python
seq = 'ACT'
hmm = initHMM('Test')
print(hmm.log_probability(seq))
# Deep copy
hmm2 = copy.deepcopy(hmm)
print(hmm2.log_probability(seq))
```

**Comment by jmschrei** [comment]
Deepcopy probably won't work because the models are cython extension classes, not python objects. I can add in a deepcopy method as `model.copy` though. Sorry for not getting to these sooner.

**Comment by Narsail** [comment]
That would be awesome. If it is too much trouble to have an copy method, i would fall back to the to_json/from_json method. No problem ;)

**Comment by Narsail** [comment]
How is your status on the copy method? I need either the copy method or the #72 solved to continue with my project. So an simple estimate when it's done would help me a lot to structure my next tasks :)

**Comment by jmschrei** [comment]
Hey, sorry, I've been on vacation this last week. Sunday at the latest is
when I'll have it done.

**Comment by Narsail** [comment]
No problem. Enjoy the rest of your vacation!

**Comment by jmschrei** [comment]
Deep copy method added using `.copy()`, uses the JSONs as a backend.
