### ISSUE TITLE
[BUG]index of in_messages in FactorGraph.predict_proba()

### ISSUE THREAD

**Issue by wyddfrank** [jmschrei/pomegranate#737]
In Loopy Belief Propagation (FactorGraph.predict_proba(), line 265), I think the index of in_messages might be k instead of i?

**Comment by jmschrei** [comment]
Oops. Looks like you're correct--thanks for the report. However, by definition there are no edges leading to marginal nodes in a factor graph and so there won't be any in messages for the marginal nodes during loopy belief propagation. Probably worth fixing or removing entirely though.

**Comment by wyddfrank** [comment]
Yes, that's right. There is no in_message for the marginal nodes in Bethe cluster graph, so this can be removed. Thanks for your reply.
