### ISSUE TITLE
Proposal: Possibility to give the HMM(names) a prefix/postfix after initialization

### ISSUE THREAD

**Issue by Narsail** [jmschrei/pomegranate#74]
Scenario:

In my project i need to concatenate (sometimes) the same model once, twice or multiple times. To do so, it is necessary to have disjoint nodes. But this is only possible with a renamed model. The error suggests that the network library has methods to add a prefix/postfix.

``` python
networkx.exception.NetworkXError: ('The node sets of G and H are not disjoint.', 'Use appropriate rename=(Gprefix,Hprefix)or use disjoint_union(G,H).')
```

**Comment by jmschrei** [comment]
I think the correct approach is to have a "prefix" and "suffix" option when doing `from_json` and `copy`, which goes through and changes the names appropriately.

**Comment by Narsail** [comment]
Thanks for that. I will try it in the next few days :)

**Comment by jmschrei** [comment]
Did this end up working?
