### ISSUE TITLE
MarkovNetwork.from_structure() not working

### ISSUE THREAD

**Issue by d4ria** [jmschrei/pomegranate#741]
Hi,
I have an issue with from_structure method for Markov Networks. First, documentation is same as in case of Bayesian Network - I should give a structure consisting of nodes' parents. But we do not have any parents in an undirected network, do we?
My dataset has 10 categorical columns. I tried the following structures inside MarkovNetwork(X=dataset_array, structure=structure) :
'''
structure1 = ((1),(0,),(1,),(2,),(3,),(4,),(5,),(6,),(7,),(8,))
structure2 = ((1,),(0,2),(1,3),(2,4),(3,5),(4,6),(5,7),(6,8),(7,9),(8,))
'''
but none of them worked. Usually Python crashes, I get the message:
"Process finished with exit code 137 (interrupted by signal 9: SIGKILL)".
How should my structure look like?

**Comment by jmschrei** [comment]
When using `from_structure` with a Markov network you should be giving a list of cliques (sets of nodes that are all connected to each other), not a list of node parents. Would you mind submitting a PR to fix the documentation?
