### ISSUE TITLE
[BUG] Segmentation fault (core dumped) in method BayesianNetwork.from_sample(...)

### ISSUE THREAD

**Issue by ekosman** [jmschrei/pomegranate#742]
I'm receiving the error when trying to call the ```from_samples``` method for a graph with more than 10 vertices. What could cause this?

BTW, the exact call is:

```python
model = BayesianNetwork.from_samples(
X=observations,
algorithm='exact',
state_names=names,
n_jobs=4)

```

**Comment by jmschrei** [comment]
It's difficult for me to debug this without an example that reproduces the error. I'm guessing that either you've run out of memory or there's an issue with your data somewhere.

**Comment by ekosman** [comment]
@jmschrei I can provide a json file with the observations and names objects. Would that be sufficient?

**Comment by jmschrei** [comment]
If you can provide the data (preferably in numpy format) and a script that fails when you run it that would be great. You can email it to me if you'd like.

**Comment by ekosman** [comment]
@jmschrei Thanks. foud out that's probably my RAM is out of resources because the exit code is (0xC0000005). Do you have any advice how can I train a model despite this limitation?

**Comment by jmschrei** [comment]
Unfortunately structure learning can take an exponential amount of memory to solve exactly. You should look into constraint graphs (described in this tutorial https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_4b_Bayesian_Network_Structure_Learning.ipynb) as a way of reducing memory overhead and speeding up the search process.

**Comment by ekosman** [comment]
@jmschrei Thanks for your support.
