### ISSUE TITLE
Can't install Pomegranate 0.12 while 0.11 works, may require updated wheels 

### ISSUE THREAD

**Issue by bruale** [jmschrei/pomegranate#745]
Facing the same problem of #554 while installing 0.12 (0.11 works).
venv on Ubuntu 18 and python 3.6  
may require updated wheels on the repo

**Comment by pomcho555** [comment]
I met similar error while installing.
venv on Ubuntu 20.04LTS and python 3.8.2

However I could install again after creating new venv installing Cython
Here is my package's version
Cython==0.29.17
networkx==2.4
numpy==1.18.4
joblib==0.14.1

**Comment by bruale** [comment]
I created a new venv-py3.6 including cython (0.29.17).
pomegranate 0.12 now  successfully installed.
thanks a lot!
