### ISSUE TITLE
Factory method to call cls, not BayesianNetwork

### ISSUE THREAD

**Issue by ekosman** [jmschrei/pomegranate#747]
Hi, I'm trying to create a class that inherits from BayesianNetwork. However, when I call ```from_samples``` on my class, it returns an instance of BayesianNetwork instead of an instance of my class. I assume its because of this:

https://github.com/jmschrei/pomegranate/blob/ee167a015b2598a37ca15856ad74eae104eebc7a/pomegranate/BayesianNetwork.pyx#L1107

I think it should be changed to:
```python
 return cls.from_structure(X, structure, weights, pseudocount, name, 
```

**Comment by jmschrei** [comment]
Yes. I need to go through and change all of these. I'll try to do that soon.

**Comment by jmschrei** [comment]
This should be fixed for all models and distributions now.
