### ISSUE TITLE
Is there any efficient way to calculate the conditional probability of a node given only 1 parent?

### ISSUE THREAD

**Issue by ekosman** [jmschrei/pomegranate#748]
Hi

I use a bayesian network and try to calculate for every node the conditional probability given 1 parent.
For nodes with 1 parent, the conditional probability table (CPT) includes only 3 columns (with columns types: parent node, current node, conditional probability) and this calculations are already provided. However for larger CPT's I can't derive the values directly. I use `predict_proba` and pass the values of the parent node. The problem with this method is that the inference is very time consuming.
I was wondering if there's a more efficient way.

Thanks in advance!

**Comment by jmschrei** [comment]
I'm not sure exactly what you're asking. Are you saying that you want to know the marginal probability of a node given that you know only one of it's parents? That's the inference task that Bayesian networks do, and unfortunately, can be time consuming because it is a tricky calculation.
