### ISSUE TITLE
HMM fiting question: Viterbi algorithm

### ISSUE THREAD

**Issue by andrzejchomiczewski** [jmschrei/pomegranate#749]
As I am researching my master thesis, I stumbled upon your package, and from the get-go I was impressed by its flexibility. Due to that, I wanted to try to fit some simple models, just to try its capabilities in reality, and stumbled upon a strange behavior (at least for me). As I try to get the most probable sequence of states for a simple HMM model, consisting of 2 states and Gaussian emissions. Somehow when I call 
```python
hmm_predictions = model.predict(X,algorithm='Viterbi')
```
I get 2 at the beginning of the sequence. Any reason or explanation for that?

**Here is the rest of the code:**
Data generation:
```python
HMM1 = hmm.GMMHMM(n_components=2,n_mix=1,covariance_type="spherical")
HMM1.startprob_ = np.array([0.3, 0.7])
HMM1.transmat_ = np.array([[0.7, 0.3],
                           [0.2, 0.8]])
HMM1.weights_ = np.array([[1],[1]])
HMM1.means_ = np.array([[[0.0]],[[1.0]]])
HMM1.covars_ = np.array([[1.0], [2.0]])
X,Z = HMM1.sample(20)
```
**Model (as you can see it has the same parameters as one, that generated the data)**
```python
dists = [NormalDistribution(0, 1), NormalDistribution(1, 2)]
trans_mat = np.array([[0.7, 0.3],
                      [0.2, 0.8]])
starts = np.array([0.3, 0.7])
model = HiddenMarkovModel.from_matrix(trans_mat, dists, starts)
```
**Output:**
```python
[2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1]
````

**Comment by IdioGuarino** [comment]
Hi, the index 2 represent the start-state. If you set N states, you obtain a model with N+2 states because pomegranate add the start-state and the stop-state with indexes, respectively, N and N+1. In your case, the start state has index 2 and the stop-state has index 3.

**Comment by andrzejchomiczewski** [comment]
It's great to know! Thank you very much for your answer. Also, if I may ask, is it possible to access emission probabilities parameters without multiple getattr on the object? I couldn't find a way to do so, and the way I designed is cumbersome to say the least.

**Comment by jmschrei** [comment]
Howdy

Yes, @IdioGuarino is correct. The states are ordered such that emitting states are first and silent states are last. Each model has a silent start and end state. Some models don't transition to this end state and so you won't see it in the path. You can get the name of each state by running `[state.name for state in model.states]`. 

If you need the parameters of each distribution you can do `model.states[i].distribution.parameters`. This is somewhat cumbersome, yes, but consistent with the modular interface of pomegranate. It would be difficult to output parameters succinctly if you had mixtures of different distributions or something more complicated like using a Bayesian network as a distribution.
