### ISSUE TITLE
[BUG] TypeError when trying to learn a bayesian network with a constraint graph

### ISSUE THREAD

**Issue by ekosman** [jmschrei/pomegranate#752]
I'm trying to prune a learned network. The way I'm doing this is firstly learn a network:
```python
model = BayesianNetwork.from_samples(X=observations,
				algorithm='exact',
				state_names=names,
				n_jobs=4,
				max_parents=3)
```

Then, I extract the edges of the graph using:
```python
edges = []
for child, parents in enumerate(model.structure):
	for p in parents:
		edges.append((child, p))
```

Lets say I want to remove the last 3 edges from this list and learn a new network. I run the following code:
```python
edges = edges[:-3]
G = nx.DiGraph(edges)

model = BayesianNetwork.from_samples(X=observations,
				 algorithm='exact',
				 state_names=names,
				 n_jobs=4,
				 constraint_graph=G)
```

I get an error:
```
File "bn_train_subset.py", line 180, in run
    model = BayesianNetwork.from_samples(X=observations,
  File "/home/eitan.k/GAStockPrediction/bayes/network/BayesianNetwork.py", line 41, in from_samples
    model = pomegranate.BayesianNetwork.from_samples(X, weights, algorithm, max_parents, root,
  File "pomegranate/BayesianNetwork.pyx", line 1094, in pomegranate.BayesianNetwork.BayesianNetwork.from_samples
  File "pomegranate/BayesianNetwork.pyx", line 1361, in pomegranate.BayesianNetwork.discrete_exact_with_constraints
TypeError: can only concatenate tuple (not "int") to tuple
```

What could cause this?

**Comment by ekosman** [comment]
I think I solved it but I'm not sure about this. The nodes of the graphs are actually group of nodes, not the nodes themselves?

I solved it by passing the nodes as tuples with single entries, e.g. (5,)

**Comment by STats43** [comment]
I think I'm having a similar issue. 
I get the error 
TypeError: Expected tuple, got int
when trying to do a graph using the constraint argument. I've defined my as you stated above
and how it is done in the example
```
train = pd.concat([y,X], axis = 1)
train = train.values
a = networkx.DiGraph()
HypNode = tuple((0,))
xVarNodes = tuple(range(1,4))
a.add_edge(HypNode, xVarNodes)
a.add_edge(xVarNodes, xVarNodes)

model = BayesianNetwork.from_samples(X_and_y_train, algorithm = 'exact', pseudocount=1,max_parents=5, constraint_graph=a)
```
I have not found a solution but another algorithm using from_samples will work fine with the same data. Also, if I only use a single `a.add_edge(xVarNodes, xVarNodes)` that will also work.

I would appreciate any suggestions to solve this issue.
Thanks,
Sean

**Comment by jmschrei** [comment]
Hi Sean

There was a bug with constraint graphs of the form you've specified but a recent PR #719 should fix it. I'll be releasing a new version soon (0.12.2) so be on the lookout for that.
