### ISSUE TITLE
[Markov Chains] Transition matrix question

### ISSUE THREAD

**Issue by bnorambuenay** [jmschrei/pomegranate#754]
Hello, I'm creating different higher order markov chains based on a training dataset, and I need to get the transition matrices. Is there any way to do it?

For example, if there are 6 possible states on the training dataset, and I'm creating a 5-order markov chain, I need the matrix formed by 6^5=7776 rows (all the possible transition of states), and 6 columns 
 (the possible states).

**Comment by jmschrei** [comment]
You can get the transition matrix from a HMM using `model.dense_transition_matrix()`. Is that what you're looking for?

**Comment by jmschrei** [comment]
Oh, sorry, I see you're talking about Markov chains. You can get the conditional probability tables from `model.distributions`, right? You'll probably care most about the first one, which should have all combinations of parent values.

**Comment by bnorambuenay** [comment]
> Oh, sorry, I see you're talking about Markov chains. You can get the conditional probability tables from `model.distributions`, right? You'll probably care most about the first one, which should have all combinations of parent values.

Finally I realized that using .probability([secuence_needed]) on the model.distributions[order] was enough. Thank you so much for the fast answer, and congratulations, pomegranate is so complete!!
