### ISSUE TITLE
[Question] HMM with conditional normal emissions 

### ISSUE THREAD

**Issue by bruale** [jmschrei/pomegranate#755]
I'm trying to set-up a HMM with conditional normal emissions in each state (i.e, performing a regression in each state, weighted by the responsibilities from the upper EM loop).
As far as I understood, labels are available just for hidden states (for semi-supervised learning) while passing both conditioning inputs and emission targets are currently not supported in HMM (while it seems to be the case e.g., for the naivebayes class). 
Is it correct? If so, turnaround suggestions?
Thanks!

**Comment by jmschrei** [comment]
Can you be a little more specific what exactly you're looking for? It's possible to write your own custom distribution that can do more complex things. If you look at this tutorial you can see how build a very complicated complex distribution, i.e. a neural network that replaces all the hidden states in a HMM. https://github.com/jmschrei/pomegranate/blob/master/tutorials/C_Feature_Tutorial_6_Deep_Models.ipynb

**Comment by bruale** [comment]
Thanks for the quick answer!
with reference to the deep model
 - def log_probability(self, X)
 - def summarize(self, X, w)
receives as input X, which is enough in a classification asset (leveraging on soft-labels by the w)
On the other hand, to perform regression, I need something like:
self.regr = LinearRegression()
    def log_probability(self, X, y):
        return scipy.stats.norm.logpdf(y, self.regr.predict(X), self.std)

    def predict(self, X):
        X = X.reshape(X.shape[0], 1)
        return self.regr.predict(X)

    def summarize(self, X, y, w=None):
        if w is None:
            w = numpy.ones(X.shape[0])
        X = X.reshape(X.shape[0],1)
        self.regr.fit(X, y, w)
        self.summaries[0] += w.sum()
        self.summaries[1] += self.regr.predict(X).dot(w)
        self.summaries[2] += (self.regr.predict(X) ** 2.).dot(w)

Indeed, it works fine as custom distribution, but I'm having problems to place it inside the HMM.

**Comment by bruale** [comment]
Maybe a possible turnaround could be to follow the approach proposed in https://github.com/jmschrei/pomegranate/issues/739, unrolling the HMM and passing the mean computed by an outer weighted regression fitting, then iterating between the two until convergence.
I'll try this way and eventually reopen the issue in case of further problems

**Comment by jmschrei** [comment]
What problems are you having placing it in a HMM? You should be able to drop custom distributions into a HMM as easily as the built-in distributions.

**Comment by bruale** [comment]
in my case, the mean of the emission distribution is different (thus not summarized) in each position of the sequence, as it is computed by the state-regressor prediction (represented by self.regr.predict(X) below) and both X (input data) and y(output target) have to be passed to the log-probability for likelihood computation, e.g., as follows:

`def log_probability(self, X, y):`
`return scipy.stats.norm.logpdf(y, self.regr.predict(X), self.std)`
 

while, as far as I understood, the HMM class manages samples constituted by X (not y) e.g., to compute the emission likelihood. 
In the Neural network for classification example, the output targets have been passed through the weights (i.e., as soft-labels), but I cannot follow the same approach while performing conditioned regression (e.g, I have to pass the targets y also to the log_probability function to compute the likelihood). As far as I understood, the labels in the HMM are referred to 'HMM states labels' not output targets.
