### ISSUE TITLE
[BUG] There might be a problem with n_jobs parameter in method predict_proba

### ISSUE THREAD

**Issue by ekosman** [jmschrei/pomegranate#757]
I use this method from retrieving the conditional probability.
I use it the following way:
```python
conditionals = model.predict_proba(obs, n_jobs=1)  # type(model): BayesianNetwork

for o, cond in zip(obs, conditionals):
    do something that depend on this pair and the actual values of it
```

When I set `n_jobs=1`, the behavior is as expected. However, if `n_jobs=4`, I get `keyError` and I assume it has something to do with the ordering of the return value of `predict_proba`.

Is this possible?

**Comment by jmschrei** [comment]
You'll need to be more specific. Is this a Bayesian network? There was an issue with earlier versions but I thought that I fixed it in v0.12.2. Can you check your pomegranate version?

**Comment by ekosman** [comment]
@jmschrei Thanks for replying

The model is indeed a BayesianNetwork and pomegranate version is 0.12.2

**Comment by jmschrei** [comment]
Would you mind providing a code snippet that reproduces the issue? Can you also try converting all your keys to integers and seeing whether that works? sklearn has a converter that should make this easy.

**Comment by ekosman** [comment]
Sure, I'll prepare some code for this.

My keys are all integers already.

Thanks for your help!

**Comment by ekosman** [comment]
@jmschrei Hi

I have a demo code which reproduces this. Before sending it I have a simple question that might make it easier to solve:
I never observe this behavior when running on a Windows machine, only ubuntu. Could it be the reason?

**Comment by jmschrei** [comment]
This suggests that there might be an issue with your compiler. The underlying code is the same for Windows and Ubuntu machines (it's what in the repo) but I provide pre-built wheels for Windows, whereas users build the code on their end for Ubuntu. This is basically because compiling code in Windows is a pain so I made it easy for users, whereas all Ubuntu has gcc built in.
