### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by STats43** [jmschrei/pomegranate#758]
**Describe the bug**
Hello I am using pomegranate 0.13.0
I am trying to learn a net using the from_samples method and apply a constraint graph. 
My code below applies three constraints. The third constraint `a.add_edge(xVarNodes, xVarNodes)` is to have nodes on the lowest level be able to connect to each other. 
```
a = networkx.DiGraph()
HypNode = tuple((0,))
SectorNode = tuple((1,))
xVarNodes = tuple(range(2,2+len(trainData.columns))

a.add_edge(SectorNode, HypNode)
a.add_edge(HypNode, xVarNodes)
a.add_edge(xVarNodes, xVarNodes)  

model = BayesianNetwork.from_samples(trainData, algorithm='exact', constraint_graph=a)
model.structure
```

**To Reproduce**
Below is code from the structure learning tutorial to reproduce the error. My code outputs the Key Error (8, 0) instead.
```
np.random.seed(6)

X = np.random.randint(2, size=(200, 15))
X[:,1] = X[:,7]
X[:,12] = 1 - X[:,7]

X[:,5] = X[:,3]

X[:,13] = X[:,11]
X[:,14] = X[:,11]

a = networkx.DiGraph()
b = tuple((0,))
c = tuple((1,))
d = tuple(range(2,15))

a.add_edge(b, c)
a.add_edge(c, d)
a.add_edge(d, d)

# a.add_edge(1,5)
print("Constraint Graph")
# plot_networkx(a)
plt.show()

print("Learned Bayesian Network")

tic = time.time()
model = BayesianNetwork.from_samples(X, algorithm='exact', constraint_graph=a)
model.structure
```

Outputs 
---> 30 model = BayesianNetwork.from_samples(X, algorithm='exact', constraint_graph=a)
     31 model.structure
     32 # model.plot()

Anaconda3\lib\site-packages\pomegranate\BayesianNetwork.pyx in pomegranate.BayesianNetwork.BayesianNetwork.from_samples()

Anaconda3\lib\site-packages\pomegranate\BayesianNetwork.pyx in pomegranate.BayesianNetwork.discrete_exact_with_constraints()

Anaconda3\lib\site-packages\pomegranate\BayesianNetwork.pyx in pomegranate.BayesianNetwork.discrete_exact_with_constraints()

Anaconda3\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
   1002             # remaining jobs.
   1003             self._iterating = False
-> 1004             if self.dispatch_one_batch(iterator):
   1005                 self._iterating = self._original_iterator is not None
   1006 

Anaconda3\lib\site-packages\joblib\parallel.py in dispatch_one_batch(self, iterator)
    833                 return False
    834             else:
--> 835                 self._dispatch(tasks)
    836                 return True
    837 

Anaconda3\lib\site-packages\joblib\parallel.py in _dispatch(self, batch)
    752         with self._lock:
    753             job_idx = len(self._jobs)
--> 754             job = self._backend.apply_async(batch, callback=cb)
    755             # A job can complete so quickly than its callback is
    756             # called before we get here, causing self._jobs to

Anaconda3\lib\site-packages\joblib\_parallel_backends.py in apply_async(self, func, callback)
    207     def apply_async(self, func, callback=None):
    208         """Schedule a func to be run"""
--> 209         result = ImmediateResult(func)
    210         if callback:
    211             callback(result)

Anaconda3\lib\site-packages\joblib\_parallel_backends.py in __init__(self, batch)
    588         # Don't delay the application, to avoid keeping the input
    589         # arguments in memory
--> 590         self.results = batch()
    591 
    592     def get(self):

Anaconda3\lib\site-packages\joblib\parallel.py in __call__(self)
    254         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    255             return [func(*args, **kwargs)
--> 256                     for func, args, kwargs in self.items]
    257 
    258     def __len__(self):

Anaconda3\lib\site-packages\joblib\parallel.py in <listcomp>(.0)
    254         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    255             return [func(*args, **kwargs)
--> 256                     for func, args, kwargs in self.items]
    257 
    258     def __len__(self):

pomegranate\BayesianNetwork.pyx in pomegranate.BayesianNetwork.discrete_exact_with_constraints_task()

pomegranate\BayesianNetwork.pyx in pomegranate.BayesianNetwork.discrete_exact_slap()

KeyError: (8, 1)

**Comment by jmschrei** [comment]
The issue appeared to be that there used to be implicit sorting when casting sets to tuples but that has gone away. I've added explicit sorts to try to resolve this problem and the example code now runs. I pushed a commit to fix it. Can you build the latest commit (0.13.1rc) and try it out?

**Comment by STats43** [comment]
Thank you Jacob. That was a very quick response! It is now working.
