### ISSUE TITLE
[QUESTION] Does `BayesianNetwork.predict_proba` can deal with soft evidence?

### ISSUE THREAD

**Issue by endlessinertia** [jmschrei/pomegranate#762]
Thanks for the nice BN implementation here, it has been very helpful for my project on diagnostic decision support system. I was wondering if the function `BayesianNetwork.predict_proba` allows to pass evidence as a distribution over the possibile values of a random variable (i.e. the so-called soft evidence). If yes, which is the proper format to do that?

For example, imagine I have a Node (random variable) named `size` which can be expressed by three possible values `['small', 'medium', 'large']`. Is there a way to represent the fact that the user is uncertain about the current value of `size` which is equally likely to be `medium` or `large`? Something like `{'size': {'small': 0.0, 'medium': 0.5, 'large': 0.5}}`. Thanks for your help.

**Comment by jmschrei** [comment]
I'm pretty sure you can pass in a DiscreteDistribution object with your soft evidence and substitute that in for a symbol of hard evidence but it's been a while since I've tried it. Let me know if it works for you.

**Comment by jbaker60** [comment]
@endlessinertia did you have success with soft evidence?  I have tried this but am not seeing different results for different evidence cases.

**Comment by endlessinertia** [comment]
@jbaker60 Yes, the function call works as suggested by Jacob. You should encapsulate your soft evidence into a `DiscreteDistribution` object, then pass it to the dictionary of evidence in `BayesianNetwork.predict_proba`. Following up with my previous example: `size_soft_evd = DiscreteDistribution({'small': 0.0, 'medium': 0.5, 'large': 0.5})`, `{'size': size_soft_evd}`. If you inspect the JSON of the model you should correctly see the new evidence distribution as you set it. The other random variables of the model will be updated accordingly as well.

**Comment by jmschrei** [comment]
Thanks for sharing!
