### ISSUE TITLE
BayesianNetwork.from_samples not working after updating pomegranate

### ISSUE THREAD

**Issue by ingjpal** [jmschrei/pomegranate#771]
Hello Jacob, 

I coded on Novemebr a couple of Bayesian Networks with pomegranate using the function from_samples. Everything worked fine back then but after upgrading both pomegranate, I get an error in which the debugger tells me that the data must be a real number and not str. I have not touched the code and actually after running it in a friend's pc in which he had not updated the version, my code still works. Hereby a couple of lines of the error I'm getting. 

  File "/Users/juan/Documents/C_TRAIN_BYSNET_CON/BYSNET_COMPLETE_CODE_1s_YesConsFULLEVAL.py", line 130, in <module>
    ,constraint_graph=a)

  File "pomegranate/BayesianNetwork.pyx", line 1063, in genexpr
  File "pomegranate/BayesianNetwork.pyx", line 1063, in genexpr

I went to see in your code what the line looks like and apparently is just checking for some nana values inside a tupple. Do you have any idea why this is happening. I there a way to downgrade the version of pomegranate ? I cannot seem to find it. 

regards, 

Juan

**Comment by jmschrei** [comment]
Hi Juan

Can you provide a code example that reproduces this error?

You can downgrade pomegranate using `pip install --upgrade pomegranate==0.13.0`.

**Comment by ekosman** [comment]
@jmschrei 
I updated from v0.11.0 to v0.13.0 yesterday, and for some reason I get different results by calling ```from_samples```.
