### ISSUE TITLE
from_samples constraint graph attribute not working for chow-liu algorithm

### ISSUE THREAD

**Issue by Piyushbalwani** [jmschrei/pomegranate#772]
Hello Jacob,

Bayesian model returns by exact algorithm satisfying constraint graph, but Bayesian model returns by chow-liu algorithm didn't satisfying constraint graph. 
`model = BayesianNetwork.from_samples(X, algorithm='chow-liu', constraint_graph=a)`

Regards,
Piyush

**Comment by Piyushbalwani** [comment]
Hi Jacob,

Please find code snippet of above issue. As in output of below sample code, it is clearly visible that chow-liu algorithm is not following the constraint graph (only edges are from root node to leaf node) :

```
no_samples=50
no_rv = 5
no_cv=1

n=np.random.randint(2,size=(no_samples,no_rv)) 
n1=np.zeros((no_samples,no_cv), dtype=int)
n1[:,0]=np.sum(n[:,0:2],axis=1)
n = np.hstack((n,n1))

a = networkx.DiGraph()
b = tuple(range(0,no_rv))
c = tuple(range(no_rv,no_rv+no_cv))
a.add_edge(b, c)

tic1 = time.time()
model = BayesianNetwork.from_samples(n, algorithm='exact', constraint_graph=a,n_jobs=-1)
print("exact  pomegranate time: ", time.time() - tic1, model.structure)

tic1 = time.time()
model = BayesianNetwork.from_samples(n, algorithm='chow-liu', constraint_graph=a,n_jobs=-1)
print("chow-liu pomegranate time: ", time.time() - tic1, model.structure)
```

```
exact pomegranate time:  0.10520672798156738 ((), (), (), (), (), (0, 1))
chow-liu pomegranate time:  0.0026345252990722656 ((), (5,), (5,), (5,), (3,), (0,))
```

**Comment by jmschrei** [comment]
Howdy

Sorry about the confusion. Chow-Liu trees currently ignore constraints. The next version of pomegranate should address this issue.

**Comment by 1021808202** [comment]
Hi，

I also find  that Bayesian model returns by exact algorithm satisfying exclude_edges and include_edges, but Bayesian model returns by chow-liu algorithm didn't satisfying exclude_edges and include_edges.

Please check it  and I hope that will be helpful.

**Comment by jmschrei** [comment]
I've added an error message to address this.
