### ISSUE TITLE
Setting values without knowing the probabilities

### ISSUE THREAD

**Issue by kennysmith12** [jmschrei/pomegranate#773]
Hi.
I have using this module to train a bayesian network.

I have this csv:
c1, c2, c3, c4   # the columns names
```
1, 0, 0, 1
1, 0, 1, 1
1, 1, 0, 0
0, 0, 1, 0
0, 1, 0, 0
.
.
.

```
I have the edges of the network. I know that c1 -> c3, c2->c3, c2->c4.

How can I build a bayesian network using pomegranate? All of the documentation that i find for ```
example (take from this  repository):
guest = DiscreteDistribution({'A': 1./3, 'B': 1./3, 'C': 1./3})
prize = DiscreteDistribution({'A': 1./3, 'B': 1./3, 'C': 1./3})
monty = ConditionalProbabilityTable(
        [['A', 'A', 'A', 0.0],
         ['A', 'A', 'B', 0.5],
         ['A', 'A', 'C', 0.5],
         ['A', 'B', 'A', 0.0],
         ['A', 'B', 'B', 0.0],
         ['A', 'B', 'C', 1.0],
         ['A', 'C', 'A', 0.0],
         ['A', 'C', 'B', 1.0],
         ['A', 'C', 'C', 0.0],
         ['B', 'A', 'A', 0.0],
         ['B', 'A', 'B', 0.0],
         ['B', 'A', 'C', 1.0],
         ['B', 'B', 'A', 0.5],
         ['B', 'B', 'B', 0.0],
         ['B', 'B', 'C', 0.5],
         ['B', 'C', 'A', 1.0],
         ['B', 'C', 'B', 0.0],
         ['B', 'C', 'C', 0.0],
         ['C', 'A', 'A', 0.0],
         ['C', 'A', 'B', 1.0],
         ['C', 'A', 'C', 0.0],
         ['C', 'B', 'A', 1.0],
         ['C', 'B', 'B', 0.0],
         ['C', 'B', 'C', 0.0],
         ['C', 'C', 'A', 0.5],
         ['C', 'C', 'B', 0.5],
         ['C', 'C', 'C', 0.0]], [guest, prize])

s1 = Node(guest, name="guest")
s2 = Node(prize, name="prize")
s3 = Node(monty, name="monty")

model = BayesianNetwork("Monty Hall Problem")
model.add_states(s1, s2, s3)
model.add_edge(s1, s3)
model.add_edge(s2, s3)
model.bake()
```
In this example, the probabilities are known,
how can I use pomegranate to build a network without giving the probabilities (only the structure), and fit the data

**Comment by jmschrei** [comment]
You should use the `BayesianNetwork.from_structure(X, structure, ...)` method: https://pomegranate.readthedocs.io/en/latest/BayesianNetwork.html#pomegranate.BayesianNetwork.BayesianNetwork.from_structure

The `structure` tuple should have `d` tuples within it, where `d` is the total number of variables you're modeling. Each inner tuple should contain all the parents for that variable, or be empty if it has no variables. In your case it would be `((), (), (0, 1), (1))`.

**Comment by kennysmith12** [comment]
Thanks :)
