### ISSUE TITLE
[BUG] NormalDistribution outputs probabilities higher than 1

### ISSUE THREAD

**Issue by shay-zakov** [jmschrei/pomegranate#776]
Hello,

Certain instances of NormalDistribution can produce probabilities higher than 1. The code below reproduces an example. I'm using pomegranate 0.13.3, python 3.6, windows 10.

``` python
import pomegranate

dist = pomegranate.distributions.NormalDistribution(0, 0.3)
dist.probability(0)
# prints "1.3298076013386395"
```

Best,

  Shay

**Comment by jmschrei** [comment]
Howdy Shay

That's not a bug. The integral of a probability distribution must be 1. Thus, if the variance for a normal distribution is small enough, the probability value for a given input might be more than 1. Consider a uniform distribution between 0 and 2. At each point in that range the probability will be 0.5. Now, if the range shrinks to 0 and 1 the probability will be 1 for each point. If the range shrinks to 0 and 0.5 the probability will be 2 at each point.

**Comment by shay-zakov** [comment]
Right, thanks for the replay!
I guess the accurate term would then be "probability density" rather than "probability" (as the latter must not be grater than 1), but of course the probability itself is not really useful for continuous probability distributions (since it is typically 0 for any given value).

S.
