### ISSUE TITLE
Fitting HMM with labelled sequences

### ISSUE THREAD

**Issue by vvbauman** [jmschrei/pomegranate#777]
I've created a HMM using from_matrix() and I can make predictions  using this model. When I try to use fit() with labels, I get the following message:
`Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
TypeError: unhashable type: 'numpy.ndarray'`
What do I need to do to fix this?

When I try to use fit() without labels (I would prefer to use with labels but I tried without), all of my predictions are -1 and the message I get is:
`Warning: Sequence is impossible.`

Code is below (for attempting to fit using labelled sequences... seqs_vals are my sequences (each 1000 length) and seqs_labs are their respective labels (each 1000 length)):
`transition_mat= np.array([[0.9, 0.1, 0.0, 0.0], [0.0, 0.9, 0.1, 0.0], [0.0, 0.0, 0.9, 0.1, 0.0], [0.1, 0.0, 0.0, 0.9]])`
`start_probs= np.array([1.0, 0.0, 0.0, 0.0])`
`distribs= [pg.UniformDistribution(0,1), pg.UniformDistribution(0,1), pg.UniformDistribution(0,1), pg.UniformDistribution(0,1)]`
`model= pg.HiddenMarkovModel.from_matrix(transition_probabilities= transition_mat, distributions= distribs, starts= start_probs)`
`model.fit(sequences= [seqs_vals], labels=[seqs_labs], algorithm= 'labeled', verbose= True)`

**Comment by IcookBits** [comment]
Have you tried with _.from_samples()_ ?

**Comment by vvbauman** [comment]
Yes and that doesn't work either - my iPython console appears to reset when I try it (?)

I've been able to get the training without labels to work by feeding in my sequences as np.arrays. For example...
`model.fit(sequences= np.asarray(seqs_vals))`

When I try this with labels, my iPython console resets.

**Comment by zimmaz** [comment]
For labeled training you need to add '{modelName}-start' at the beginning of each label sequence (here your model has no name so it would be 'None-start')  as noted in the documentation:

> This option can be specified using `model.fit(sequences, labels=labels, state_names=state_names)` where labels has the same shape as sequences and state_names has the set of all possible labels.

**Comment by jmschrei** [comment]
Yes, please make sure that you are including all hidden state names, including the model start and end states. Please re-open if that doesn't solve the problem.
