### ISSUE TITLE
[QUESTION] multivariate fitting of hmm, emission distributions fail

### ISSUE THREAD

**Issue by cvdelannoy** [jmschrei/pomegranate#779]
When training an HMM on multiple features, it seems that the emission distributions are not fitted correctly; in the example, instead of fitting the means of the two features, which both clearly contain enough signal to discern the states,  it ends up returning a 2d gaussian with 2 similar mean values that hold the middle between the actual mean values for the features. Of course the resulting HMM doesn't perform so well. Individually these features allow for perfect fitting. 

Since it's a pretty basic thing I'm hesitant to call it a bug and I assume I'm doing something wrong but I can't figure it out...could you help me out?

minimal example:
```
import numpy as np
import pomegranate as pg
import matplotlib.pyplot as plt
from itertools import chain

np.random.seed(1)

nb_features = 2  # <- change to 1 to verify that the accuracy hits 1.0
seq_len = 100
nb_seqs=20
nb_states = 2

# generate test data
X_raw = np.random.random([nb_seqs, nb_features, seq_len])
for i in range(nb_features):
    X_raw[:, i, :] += i * 10
X_raw = [np.squeeze(x, axis=0) for x in np.split(X_raw, X_raw.shape[0], axis=0)]

# Introduce one state transition per sequence in data
X, labels = [], []
for xc in X_raw:
    lab = np.zeros(xc.shape[1], dtype=int)
    start_switch = np.random.randint(0, xc.shape[1])
    lab[start_switch:] = 1
    xc[:, start_switch:] += 10
    X.append(xc.T)
    lab = ['None-start'] + [f's{l}' for l in lab] + ['None-end']
    labels.append(lab)

# Train hmm
hmm, history = pg.HiddenMarkovModel.from_samples(distribution=pg.MultivariateGaussianDistribution,
                                                 n_components=nb_states, X=X,
                                                 labels=labels,
                                                 return_history=True)
y_num = [hmm.predict(x) for x in X]
yh = []
for y in y_num:
    yh.append([f's{s}' for s in y])

# Training accuracy
acc = np.mean(list(chain.from_iterable([ np.array(pred) == np.array(lab[1:-1])
                                         for pred, lab in zip(yh, labels) if lab is not None])))
print(f'accuracy : {acc}')  # accuracy : 0.703

for it in range(nb_states):
    print(f'state {it} levels: {hmm.states[it].distribution.parameters[0]}')

# state 0 levels: [0.6704186104947405, 1.1090031159850435] --> should be [0, 10]
# state 1 levels: [13.417950409835198, 13.413794830081645] --> should be [10, 20]

# Plot: dots are samples, line is hidden path
plt.figure()
for i in range(nb_features):
    plt.scatter(np.arange(seq_len), X[-2][:,i])
plt.plot(np.arange(seq_len), hmm.predict(X[-2]))
plt.show()

```
![image](https://user-images.githubusercontent.com/21309905/85065911-40ee3400-b1ae-11ea-9cc9-a798c563eb51.png)

**Comment by cvdelannoy** [comment]
Okay got it, for some reason it doesn't like that the input is a list of sequences; if I wrap it in a numpy array (so now it's a numpy array of n x d numpy arrays) it's working fine...shouldn't the list be be fine too?

**Comment by cvdelannoy** [comment]
I feel like I'm slowly going mad now, MultivariateGaussianDistribution shows the same behavior:
```
X = np.vstack([np.random.normal(0,1,10), np.random.normal(10,1,10)]).T
pg.MultivariateGaussianDistribution.from_samples(X).mu # array([5.00845023, 5.09494375])
```

**Comment by jmschrei** [comment]
The issue is that you're transposing the matrix which numpy handles by
changing the metadata while leaving the underlying data in the same order.
It is an efficient solution but, because Cython operates on the underlying
data, messes up programs like pomegranate. I believe automatically checking
for this issue was recently contributed but I haven't released a new
version yet. If you add .copy() to the end of your transposed numpy arrays
it will work.

**Comment by cvdelannoy** [comment]
Ahh that makes sense. Valuable lesson, thanks a lot!
