### ISSUE TITLE
IndependentComponentsDistribution vs NormalDistribution

### ISSUE THREAD

**Issue by mcreixell** [jmschrei/pomegranate#780]
Hi,

I have a data set with ~50k variables and ~200 observations (stored as `d` below) and was wondering what the correct implementation of GMM with a strict diagonal correlation would be. The only way I could make my code work without getting in an error is by doing:

`gmm = GeneralMixtureModel.from_samples(NormalDistribution, X=d, n_components=ncl)`

but with this I'm not using `IndependentComponentsDistribution` at all. Is this equivalent to using `IndependentComponentsDistribution` with `NormalDistribution` for each feature? If not, could you help me out with the proper way to write this?

Thanks!

**Comment by jmschrei** [comment]
Howdy. 

The code you wrote uses an IndependentComponentsDistribution in the background but, for simplicity, allows you to define what distribution you'd like each column to be, just as you say. The result is what you want--- a GMM with a diagonal covariance.

**Comment by mcreixell** [comment]
Great, thanks for the clarification!
