### ISSUE TITLE
[Question] KeyError Exception during HiddenMarkovModel.from_samples

### ISSUE THREAD

**Issue by IcookBits** [jmschrei/pomegranate#781]
I have a dataset composed of a sequence of binary observable variables associated with a label, like this.

```
trainset = [ [0,0,1,0],[0,0,1,0],[0,0,0,1],...,]
labels = [ 0,1,2,...,]
states = 3 # number of unique labels
```
I am trying to train an HMM in this way
```
model = HiddenMarkovModel.from_samples(distribution = MultivariateGaussianDistribution, n_components = states,
                                       X= [trainset],
                                       labels = [labels],
                                       algorithm = 'labeled')
```
When I ran this model, I get this Exception

`Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize' KeyError: 3
`
I figure out that the exception is raised when there are no observations for the _state 3._ 
But , _state 3_ is in my labels. Can someone help me, please? thanks

**Comment by IcookBits** [comment]
```
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
KeyError: 3
[1] Improvement: 0.0	Time (s): 5.241
Total Training Improvement: 0.0
Total Training Time (s): 18.5254
```

**Comment by jmschrei** [comment]
In that case, is the issue that you have the value "3" in your labels but you're defining only 3 states (0, 1, and 2)?

**Comment by IcookBits** [comment]
Actually the states are 4 (from 0 to 3).
I solved the issue passing a list of state_names like this  

`state_names = ['None-state','s0','s1',...]`

I have 1 more question...
Considering that the observable variable are **binary** and the hidden states are **labels** ( thery are 0,1,2,... but could be a,b,c,...) ,
Is a `MultivariateGaussianDistribution` good to fit this model?
