### ISSUE TITLE
[BUG] pip install fails if cython is not installed

### ISSUE THREAD

**Issue by cvdelannoy** [jmschrei/pomegranate#782]
Hi! Not sure if this is the right place to report, but the pip install is failing for me if cython is not installed before pomegranate, because it'll get stuck trying to find the NeuralNetworkWrapper.c file. I'm guessing it's a general issue, but just in case: I run into it on linux, using pip in a conda env.

Installing using the conda package works just fine btw.

**Comment by lekcyjna123** [comment]
I had the same issue on Arch. I installed pomegranate in standard env (without conda).

**Comment by bnaul** [comment]
It looks like the wheels for 0.13.3 didn't get uploaded; @jmschrei is it possible to get those on PyPI? Thanks!

**Comment by jmschrei** [comment]
Yes, I must've forgotten to upload the wheels for this version. I'll be releasing a new version soon and I'll make sure the wheels are up for that. Sorry, everyone! You can try getting an earlier version and that should work.
