### ISSUE TITLE
Trouble installing Pomegranate on Windows 10, Python 3.6.3 - Cannot open source file: 'pomegranate/distributions/NeuralNetworkWrapper

### ISSUE THREAD

**Issue by bevcon** [jmschrei/pomegranate#783]
I've been trying to install Pomegranate on Windows 10, Python 3.6.3 from pip install, and also tried installing it in VENV, but failed. I've uninstalled and reinstalled Microsoft VS Buildtools to see if this changes anything, but it didn't help. The main issues looks to be that it cannot find source files needed.

The errors I get is the following:

**Comment by bevcon** [comment]
building 'pomegranate.distributions.NeuralNetworkWrapper' extension
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\bevcon\appdata\local\programs\python\python36-32\include -Ic:\users\bevcon\appdata\local\programs\python\python36-32\include -Ic:\users\bevcon\appdata\local\temp\pip-install-1i0vzi41\pomegranate\.eggs\numpy-1.19.0-py3.6-win32.egg\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcpomegranate/distributions/NeuralNetworkWrapper.c /Fobuild\temp.win32-3.6\Release\pomegranate/distributions/NeuralNetworkWrapper.obj
    NeuralNetworkWrapper.c
    c1: fatal error C1083: Cannot open source file: 'pomegranate/distributions/NeuralNetworkWrapper.c': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
ERROR: Failed building wheel for pomegranate


Running setup.py install for pomegranate ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\bevcon\appdata\local\programs\python\python36-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Bevcon\\AppData\\Local\\Temp\\pip-install-1i0vzi41\\pomegranate\\setup.py'"'"'; __file__='"'"'C:\\Users\\Bevcon\\AppData\\Local\\Temp\\pip-install-1i0vzi41\\pomegranate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Bevcon\AppData\Local\Temp\pip-record-1dni2s3_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\bevcon\appdata\local\programs\python\python36-32\Include\pomegranate'
         cwd: C:\Users\Bevcon\AppData\Local\Temp\pip-install-1i0vzi41\pomegranate\
    Complete output (339 lines):


   ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\bevcon\appdata\local\programs\python\python36-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Bevcon\\AppData\\Local\\Temp\\pip-install-1i0vzi41\\pomegranate\\setup.py'"'"'; __file__='"'"'C:\\Users\\Bevcon\\AppData\\Local\\Temp\\pip-install-1i0vzi41\\pomegranate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Bevcon\AppData\Local\Temp\pip-record-1dni2s3_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\bevcon\appdata\local\programs\python\python36-32\Include\pomegranate' Check the logs for full command output.

**Comment by bevcon** [comment]
I can confirm that the installation goes through without errors if you pre-install Cython.

**Comment by jmschrei** [comment]
Thanks for the report. Looks like I'll need the pip installation to install Cython force even outside dev mode.

**Comment by jmschrei** [comment]
I'm going to close this and keep #782 open until I fix it, because these are all related to the same issue.
