### ISSUE TITLE
pip install codec issues on Ubuntu 14.04

### ISSUE THREAD

**Issue by narendramukherjee** [jmschrei/pomegranate#79]
I've been having issues with installing pomegranate on Ubuntu 14.04, here's what pip install gives me:
...
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pomegranate/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bGdNcT-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pomegranate
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 104: ordinal not in range(128)
...

I understand that this is probably a C issue (which I don't understand much about) and I've tried the following:
1. Updating setuptools (sudo pip install --upgrade setuptools)
2. Trying to change the codec used by gcc to utf-8 instead of ascii (I don't think I succeeded doing this).
3. export LC_ALL=C (suggested by some posts on StackOverflow which were about trying to pip install numpy etc and giving a similar error)
4. Pulling pomegranate from github and doing python setup.py install

None of these helped - step 3 changed the error to this:
...
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pomegranate/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-YKw7pt-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pomegranate
Storing debug log for failure in /home/narendra/.pip/pip.log
...

Here's my gcc version:
...
narendra@spokeyspikes:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
... 

Any hints on how to go about handling this? Thanks so much in advance!

**Comment by jmschrei** [comment]
I've never seen this type of error before. Sorry that I can't be of more help.

**Comment by saketkc** [comment]
@narendramukherjee  The `pip` version seems you are using looks like it's too old(Stable is 8.0+). Not sure if that is causing it.

You might do want to try virtualenv/conda.

**Comment by narendramukherjee** [comment]
Thanks for the idea, I've been able to get the install to work with conda :)
