### ISSUE TITLE
[BUG]Undefined variable 'Node'

### ISSUE THREAD

**Issue by Kyr1e** [jmschrei/pomegranate#790]
**Describe the bug**
I encountered an error when I was trying to build a Bayesian Network.
Undefined variable 'Node'
Then I changed 'Node' to 'State', the same error occurred.
Undefined variable 'State'

I have successfully installed pomegranate (using conda install pomegranate) and tested it using the code below:
from pomegranate import *
print(NormalDistribution(0, 1).probability(0))
output: 0.3989422804015919

I have no idea how to solve this problem
**To Reproduce**
The code is from the docs of Bayesian Networks(first example)

from pomegranate import *
guest = DiscreteDistribution({'A': 1./3, 'B': 1./3, 'C': 1./3})
prize = DiscreteDistribution({'A': 1./3, 'B': 1./3, 'C': 1./3})
monty = ConditionalProbabilityTable(
        [['A', 'A', 'A', 0.0],
         ['A', 'A', 'B', 0.5],
         ['A', 'A', 'C', 0.5],
         ['A', 'B', 'A', 0.0],
         ['A', 'B', 'B', 0.0],
         ['A', 'B', 'C', 1.0],
         ['A', 'C', 'A', 0.0],
         ['A', 'C', 'B', 1.0],
         ['A', 'C', 'C', 0.0],
         ['B', 'A', 'A', 0.0],
         ['B', 'A', 'B', 0.0],
         ['B', 'A', 'C', 1.0],
         ['B', 'B', 'A', 0.5],
         ['B', 'B', 'B', 0.0],
         ['B', 'B', 'C', 0.5],
         ['B', 'C', 'A', 1.0],
         ['B', 'C', 'B', 0.0],
         ['B', 'C', 'C', 0.0],
         ['C', 'A', 'A', 0.0],
         ['C', 'A', 'B', 1.0],
         ['C', 'A', 'C', 0.0],
         ['C', 'B', 'A', 1.0],
         ['C', 'B', 'B', 0.0],
         ['C', 'B', 'C', 0.0],
         ['C', 'C', 'A', 0.5],
         ['C', 'C', 'B', 0.5],
         ['C', 'C', 'C', 0.0]], [guest, prize])

s1 = Node(guest, name="guest")
s2 = Node(prize, name="prize")
s3 = Node(monty, name="monty")

model = BayesianNetwork("Monty Hall Problem")
model.add_states(s1, s2, s3)
model.add_edge(s1, s3)
model.add_edge(s2, s3)
model.bake()

**Comment by Kyr1e** [comment]
Well, I just found that this problem might be related to the compiler(I'm currently using VS Code), because I put the following statements:
probability = model.probability([["A", "C", "B"]])
print(probability)
and the output is 0.11111111111111109(although the errors still occurred)
the outcome is the same as the correct answer:
print((1./3)*(1./3)*(1.0))

**Comment by jmschrei** [comment]
That's weird. I've never seen this issue before elsewhere. Maybe try using `State` instead of `Node`? It's just a renaming of the same object used for HMMs.

**Comment by Kyr1e** [comment]
> That's weird. I've never seen this issue before elsewhere. Maybe try using `State` instead of `Node`? It's just a renaming of the same object used for HMMs.

Thank you very much for your reply, the model worked well although this error occurred (It must be due to the settings of my compiler). Nothing wrong related to pomegranate. lol
