### ISSUE TITLE
[FEATURE] TOP-M assignments for bayesian networks

### ISSUE THREAD

**Issue by ekosman** [jmschrei/pomegranate#791]
Is there any intention to implement an algorithm for finding the M most probable configurations for bayesian networks?
For examaple:
https://www.sciencedirect.com/science/article/pii/0888613X94900310
http://proceedings.mlr.press/v31/chen13a.pdf

**Comment by jmschrei** [comment]
Howdy. 

Good question. That's an interesting feature but, unfortunately, my time is limited to the point where I can barely keep up with bug reports and PRs so it's unlikely I'll have time to add it in. If you'd like to take a stab at adding it in a way that doesn't change the current API I'd be happy to review a PR.

**Comment by ekosman** [comment]
I need it for my project so I'll probably have to implement this anyway. However, I can't think of good tests for this one..

**Comment by jmschrei** [comment]
It's okay to write unit tests using small randomized data sets (with a set seed) that you hand-verify, as well.
