### ISSUE TITLE
Misunderstanding about weights in BayesianNetwork.from_samples

### ISSUE THREAD

**Issue by ekosman** [jmschrei/pomegranate#795]
The 'weights' parameter specifies that the dimensions should be `(n_nodes)` but the descriptions says: `The weight of each sample as a positive double`. It's confusing because the number of nodes and the number of samples are different things. Which one I should use? I assume this should be `(n_samples)` instead, because of this:
https://github.com/jmschrei/pomegranate/blob/d7cf6660c67e2c92b5d7131465029823206bba2c/pomegranate/BayesianNetwork.pyx#L1088

Thanks in advance

**Comment by jmschrei** [comment]
That is a typo in the documentation. It should be of shape `(n_samples)`, like you say. Would you mind opening a PR to fix it?

**Comment by ekosman** [comment]
@jmschrei Just did.
