### ISSUE TITLE
[BUG] Key error when using from_structure in BayesianNetwork

### ISSUE THREAD

**Issue by AdirthaBorgohain** [jmschrei/pomegranate#799]
**Describe the bug**
When I try and use from_structure in BayesianNetwork the following error comes up: ```AttributeError: 'NoneType' object has no attribute 'keys'```. What might be the reason behind this? I cannot seem to understand.
**To Reproduce**
```
from pomegranate import BayesianNetwork

data = [[1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1],
        [1, 1, 0, 0, 1],
        [0, 1, 0, 1, 0]]
network_structure = ((4, 3), (3, 2), (4, 3), (), (1,))
BayesianNetwork.from_structure(data, structure=network_structure, 
                               name='Bayesian Network', state_names=['1','2','3','4','5'])
```

**Comment by AdirthaBorgohain** [comment]
I kind of figured out something I guess? Is it because of a cyclic component in the graph?

**Comment by jmschrei** [comment]
Potentially. In general, Bayesian networks are typically acyclic, and in pomegranate, they have to be.
