### ISSUE TITLE
Nan values while fitting GMM

### ISSUE THREAD

**Issue by UditGupta10** [jmschrei/pomegranate#800]
I am fitting 1D data using .from_samples(), with Normal distribution and 2 components. I expect 2 sets of distribution parameters, ie. mu0, sigma0, mu1, sigma1. But in one particular case the function returns only one set of parameters whereas other one is Nan. This might be a peculiar case. Want to understand when is such outcome expected. Can we say that there is only 1 component as opposed to 2 specified in the parameters. 
Function: 
np.random.seed(101)
GeneralMixtureModel.from_samples(NormalDistribution, X=data, n_components=2)
Data to replicate this: 
array([[ 1.05436459],
       [-0.40140454],
       [ 0.83528929],
       [ 0.97575146],
       [ 1.03733207],
       [ 1.05436459],
       [ 1.05436459],
       [ 1.18369007],
       [ 1.05436459],
       [ 1.05436459],
       [ 0.92377272],
       [ 1.07113867],
       [ 1.07113867],
       [ 1.01446097],
       [ 0.49622524],
       [ 0.99331936],
       [ 1.02613552],
       [ 1.01446097],
       [ 1.05436459],
       [ 1.01446097],
       [ 1.01446097],
       [ 0.88974429],
       [ 0.99331936],
       [ 0.88974429],
       [ 1.01446097],
       [ 1.05436459],
       [ 0.97575146],
       [ 0.83528929],
       [ 0.92377272],
       [ 1.18369007]])

**Comment by mranahmd** [comment]
As you said, it seems more to be a peculiar case; given the data points, number of mixture components and initialisation. (And it may not really be an issue specific to pomegranate.)

You can have an idea of the problem by looking at the data points. However, this may not be always feasible, so lets try another way. 

*Note: This is purely for your understanding and not the best nor the most optimal way for model selection.*

If you just switch to a random initialisation for the given case:
```
import numpy
numpy.random.seed(101)
from pomegranate import *

data=numpy.array([[ 1.05436459], [-0.40140454], [ 0.83528929], [ 0.97575146], [ 1.03733207], [ 1.05436459], [ 1.05436459], [ 1.18369007], [ 1.05436459], [ 1.05436459], [ 0.92377272], [ 1.07113867], [ 1.07113867], [ 1.01446097], [ 0.49622524], [ 0.99331936], [ 1.02613552], [ 1.01446097], [ 1.05436459], [ 1.01446097], [ 1.01446097], [ 0.88974429], [ 0.99331936], [ 0.88974429], [ 1.01446097], [ 1.05436459], [ 0.97575146], [ 0.83528929], [ 0.92377272], [ 1.18369007]])

GeneralMixtureModel.from_samples(NormalDistribution, X=data, n_components=2, init='random')
```

Then you would obtain something like:
```
 GeneralMixtureModel.from_samples(NormalDistribution, X=data, n_components=2, init='random')
{
    "class" : "GeneralMixtureModel",
    "distributions" : [
        {
            "class" : "Distribution",
            "name" : "NormalDistribution",
            "parameters" : [
                1.010225791051774,
                0.08103655756983803
            ],
            "frozen" : false
        },
        {
            "class" : "Distribution",
            "name" : "NormalDistribution",
            "parameters" : [
                0.23710997277951,
                0.5485897458850847
            ],
            "frozen" : false
        }
    ],
    "weights" : [
        0.9159152830895161,
        0.08408471691048398
    ]
}
```

The parameters of the Gaussian Mixture point to the same problem with the data points.

**Comment by jmschrei** [comment]
Yes I think this is an issue with a poor initialization. TBF, pomegranate should handle it more gracefully by not returning NANs, but you should be able to get around it with multiple initializations. Sorry about that!
