### ISSUE TITLE
HMM optimization

### ISSUE THREAD

**Issue by lekcyjna123** [jmschrei/pomegranate#802]
Hi, 
today i have looked into code of HMM in looking for a way to speed up fitting this models with DiscreteDistributions and i have a question. Why should be always checked input?
https://github.com/jmschrei/pomegranate/blob/d7cf6660c67e2c92b5d7131465029823206bba2c/pomegranate/hmm.pyx#L2590-L2591
I thought that sequences doesn't change between iterations of loop? 
When i had profiled running of HMM fit function _check_input take half of fitting time, so i think that here is a place to possible optimization, because _check_input iterate over each sequence and copy each symbol.

Profile result:
[1] Improvement: 253389.81343831721     Time (s): 0.9487
[2] Improvement: 213.1332476385287      Time (s): 0.9735
[3] Improvement: 76.93109403923154      Time (s): 0.935
[4] Improvement: 44.39238843484782      Time (s): 0.9858
[5] Improvement: 28.537198789825197     Time (s): 0.948
[6] Improvement: 17.950176118465606     Time (s): 1.004
[7] Improvement: 11.243089165887795     Time (s): 0.9343
[8] Improvement: 7.315842745301779      Time (s): 0.9407
Total Training Improvement: 253789.3164752493
Total Training Time (s): 8.6180
         5061275 function calls (4967615 primitive calls) in 14.847 seconds

   Ordered by: internal time

ncalls | tottime | percall | cumtime  | percall | filename:lineno(function)
-|- |-|-|-|-
12177   | 3.759   | 0.000  |  5.109 |   0.000 | hmm.pyx:65(_check_input)
2951   | 3.527   | 0.001 |   3.527   | 0.001 | {built-in method posix.stat}
3508002 |   1.345  |  0.000   | 1.345  |  0.000 | utils.pyx:459(_check_nan)
24353/12177 |   0.626 |   0.000  |  1.852  |  0.000 | parallel.py:248(__call__)
670   | 0.626   | 0.001 |   0.626  |  0.001 | {built-in method io.open_code}
24353/12177 |   0.491 |   0.000 |   2.336 |   0.000 | _parallel_backends.py:569(__init__)
12177    |0.453   | 0.000   | 0.498   | 0.000 | hmm.pyx:2646(summarize)
24345/12177   | 0.382 |   0.000  |  0.859   | 0.000 | {method 'summarize' of 'pomegranate.hmm.HiddenMarkovModel' objects}

**Comment by lekcyjna123** [comment]
I go a little bit deeper reading code, so i want to ask if i correctly understand. In _check_input we transcode keys from input sequence to generic symbols, which should be type of double? So how about when i move transcoding into line 2541?
https://github.com/jmschrei/pomegranate/blob/d7cf6660c67e2c92b5d7131465029823206bba2c/pomegranate/hmm.pyx#L2540-L2545

**Comment by jmschrei** [comment]
I think that I was having it check the input each time because I was trying to support arbitrary inputs, including each batch being a new set of data that the mode hadn't seen before. It might be easier to have the user specify if they want check_input to be True or False and use that instead of hardcoding it. That way the user can turn it off when they know they have clean inputs.
