### ISSUE TITLE
Does the library support hirechical HMM 

### ISSUE THREAD

**Issue by ashraf-01** [jmschrei/pomegranate#805]
**Describe the bug**
Hi all 

I have some dataset with sequence of triplets as follows Y_k= (T_k,P_k,V_k), timestamp in some unit , some price , some volume 
now by adding some intermediate features as for example locations classified as local extremes e_n at price , and volume level , based of that you have some idea about how trend is behaving up / down / flat , now am effectively creating indicator variables and I wanna link them with other set of features , so basically am having features estimated in using the other intermediate features 
which means , that standard HMM can not capture the two sets and the correlation among the two sets as each set behaves differently one of the way to link these together is create hierarchical structure where each set of indicators is working on a different time scale i.e. multiplicity of scale length and different stochastic process at each scale , of course what you gain automatically is non-linear correlation among different levels , so lesser-moving correlations captured at the top of the hierachicy 
...etc then how do I implement such thing using promgenate dedicated HMM module ?
your help is highly appreciated

**Comment by jmschrei** [comment]
Howdy

I didn't follow your example exactly, but hierarchical HMMs are not supported in pomegranate right now.
