### ISSUE TITLE
[BUG] matplotlib not installed raises pygraphviz Exception

### ISSUE THREAD

**Issue by matt-chv** [jmschrei/pomegranate#808]
**Describe the bug**
if matplotlib is not available when calling model.plot() an exception that pygraphviz is missing will be raised

  File "pomegranate/BayesianNetwork.pyx", line 250, in pomegranate.BayesianNetwork.BayesianNetwork.plot

**To Reproduce**
run the code provided by minelminel on Jun 29 at:
https://github.com/jmschrei/pomegranate/issues/136

with one modification:
model.plot("network.pdf") just after model.bake()
on venv without matplotlib it will raise obfuscating Exception.

** Bug fig suggestion **
remove on line 40 the import matplotlib from the same try statement as pygraphviz

**Comment by jmschrei** [comment]
I extended the bug to include matplotlib. I don't want to require matplotlib for the main functionality of pomegranate.
