### ISSUE TITLE
[FEATURE] Dockerfile for the project

### ISSUE THREAD

**Issue by davidalami** [jmschrei/pomegranate#809]
Howdy!
The installation of pomegranate via pip frequently leads to a broken package, finally I built mine from source, downgrading python to version 3.6. I think this is not a bug, just a little problem with reproducibility, so I propose to create a Dockerfile allowing users to deploy the application without try-and-errors. 
Maybe we already have one (I saw the project on a mybinder.org)?

**Comment by jmschrei** [comment]
Can you provide some more information? I don't think that installing from pip should lead to a broken package if you have Cython and a working C compiler installed correctly. I also provide pre-built wheels for Windows, so you shouldn't even need Cython there.

**Comment by davidalami** [comment]
Sorry, it was too long ago, so I cannot provide more information. Thank you for your response, I will close the issue.
