### ISSUE TITLE
clf.weights return the wrong prior weights

### ISSUE THREAD

**Issue by Mriv31** [jmschrei/pomegranate#814]
I am fitting a General Mixture Model (called clf in the attached screenshot) containing two exponential distributions. When I print clf, it displays the right fitted weights for each distribution. However, clf.weights contain strange negative values. 
Thanks,
Martin

![Capture d’écran du 2020-09-13 16-03-46](https://user-images.githubusercontent.com/24370506/93019979-dc8b1700-f5da-11ea-86a4-75dc1c34bb6d.png)

**Comment by jmschrei** [comment]
Hi Martin

Those are the log priors. I realize it's a little confusing but if you
exponentiate them (e.g. numpy.exp(model.weights)) you'll get probabilities.
See
https://github.com/jmschrei/pomegranate/blob/master/pomegranate/bayes.pyx#L98

**Comment by Mriv31** [comment]
Hi Jacob,

Thank you for your prompt answer ! I should have seen that...

Pomegranate is great !

Best,

Martin.

Le 13/09/2020 à 19:07, Jacob Schreiber a écrit :
> Hi Martin
>
> Those are the log priors. I realize it's a little confusing but if you
> exponentiate them (e.g. numpy.exp(model.weights)) you'll get 
> probabilities.
> See
> https://github.com/jmschrei/pomegranate/blob/master/pomegranate/bayes.pyx#L98
>
