### ISSUE TITLE
Diagonal Covariance Matrix in MultivariateGaussianDistributions

### ISSUE THREAD

**Issue by priscilla-amorim** [jmschrei/pomegranate#817]
Hello! I'm currently implementing an audio diarization system based on HMM-GMM models. Usually, audio data is highly dimensional (I'm using MFCC-19 features), so working with a full covariance matrix can be impracticable. I've found some discussions about this issue (#414) in 2018, but couldn't find any further updates. 

As commented in #227, there is any update in specifying "covariance_type=..." in MultivariateGaussianDistributions?

Thanks

**Comment by jmschrei** [comment]
You can use IndependentComponentsDistribution with NormalDistributions to get a diagonal covariance matrix. If you do `HiddenMarkovModel.from_samples(NormalDistribution....)` on multivariate data, you will get an diagonal covariance matrix. Unfortunately, you can't do a HMM-GMM using the `from_samples` method, but if you initialize the GMM with an IndependentComponentsDistribution with normal distributions (a hassle, I know) you will get the same thing.

Let me know if you have any other questions
