### ISSUE TITLE
Exception AttributeError in training a HMM (code was working with yahmm)

### ISSUE THREAD

**Issue by narendramukherjee** [jmschrei/pomegranate#82]
Here's a reduced example of the general setup I had been using with yahmm (the model wasn't converging to the right parameters - I'll post about that later - but it was running without errors):

[test_pomegranate.txt](https://github.com/jmschrei/pomegranate/files/133667/test_pomegranate.txt)

Here's the error I get when I try to run this:
...
Exception AttributeError: '__exit__' in 'pomegranate.hmm.HiddenMarkovModel._train_loop' ignored
Total Training Improvement: 0.0
...

Any suggestions? Thanks a lot in advance!

**Comment by jmschrei** [comment]
pomegranate doesn't allow you to just define new distributions with a log_probability method right now. You need a C-exposed property on a cython extension object, in order to make multithreaded training work properly.

That being said, I could probably add in a poisson distribution fairly quickly.

sorry for the delay in the answer

**Comment by narendramukherjee** [comment]
Thanks so much for the reply Jacob - I am planning to run neural data (which is basically activity counts) through the HMM setup, hence the use of a Poisson distribution. Right now I am trying out a MCMC based approach (using PyMC), but I'm having issues with diagnosing convergence there. If/whenever you can setup a poisson distribution in pomegranate, I would love to try out an EM based approach too..

**Comment by jmschrei** [comment]
PoissonDistribution should be working now. I'm going to close this issue now, but feel free to re-open it if there are any other issues!

**Comment by narendramukherjee** [comment]
I forgot to mention this the last time - I had tested the code with the already implemented DiscreteDistribution (for a different dataset) and the same error had popped up. I tried the PoissonDistribution today, and the error came up again - I am pasting the code here again (I have commented out my definition of the PoissonDistribution, and am using the version you implemented last time). 

And here's the error:
...
Exception AttributeError: '__exit__' in 'pomegranate.hmm.HiddenMarkovModel._train_loop' ignored
Total Training Improvement: 0.0
...

The code:
[test_pomegranate.txt](https://github.com/jmschrei/pomegranate/files/160104/test_pomegranate.txt)
