### ISSUE TITLE
Bayesian Networks training from samples with incomplete information. 

### ISSUE THREAD

**Issue by ingjpal** [jmschrei/pomegranate#820]
Hello Jacob, 

One of the added value of bayesian statistics is that conditional probability tables can come from different data bases so that the evidence does not have to be present for every single instance. I was wondering if the Bayesian Networks from pommegrande will accept for the from_samples training method an imcomplete data set. Something for example like: 

[['A', 'B', None],
  ['A', None, 'C'],
  [None, 'B', 'A'],
  ['A' 'B' 'C'],
  ['A' 'B' 'None']
  ['A' 'B' 'A']]

Cheers, 

Juan

**Comment by jmschrei** [comment]
Yes, you can learn Bayesian networks on incomplete data sets. See https://github.com/jmschrei/pomegranate/blob/master/tutorials/C_Feature_Tutorial_4_Missing_Values.ipynb
