### ISSUE TITLE
[QUESTION] Parsing equivalent emissions

### ISSUE THREAD

**Issue by b2jia** [jmschrei/pomegranate#821]
Is there an architecture in Pomegranate that supports the interpretation of equivalent emission sequences?

This is a bit difficult to explain, but a simple example would be - for an HMM with 2 states (states = {S1, S2}), 4 unique emission symbols (symbols = {A, B, C, D}) but instead of each state emitting only one "symbol", it can emit all possible combinations less than the emission length of such symbols for emissions (emissions = {A, B, C, D, AA, AB, AC, AD, BA, BB, BC, BD, ..., AAA, AAB, AAC, AAD ... AAAA, AAAB, AAAC, AAAD, ... DDDD})  - I would like the HMM to decode a Viterbi path for an emission sequence 'ABCD'. The HMM will have to be able to interpret an emission sequence 'ABCD' and recognize that an emission 'A' + 'BCD' is equivalent to 'AB' + 'CD', 'A' + 'BC' + 'D', or even the canonical 'A' + 'B'+'C'+'D'.

**Comment by jmschrei** [comment]
I'm not sure what the best strategy would be for this, but I would suggest that you might consider having two separate HMMs, each with one state per observation ('A', 'B', 'C', 'D') and different sets of transition matrices between these states. I think that it will be difficult to get one model to understand that subsequences of observations are equivalent-- best to just break it down into the smallest unit.
