### ISSUE TITLE
Custom JSON Backends

### ISSUE THREAD

**Issue by Theelgirl** [jmschrei/pomegranate#825]
Will it be possible to add a feature to let us pass our own json backend for to_json and from_json methods? I was thinking of using ujson or orjson myself considering that those can be many times faster for dumps and loads than the stdlib json.

It seems that since using a model's to_json or from_json methods calls to_dict https://github.com/jmschrei/pomegranate/blob/2e8810c79c90c6e993bc9f106ad06da400ccf65a/pomegranate/base.pyx#L63 and since that to_dict method raises a NotImplementedError https://github.com/jmschrei/pomegranate/blob/2e8810c79c90c6e993bc9f106ad06da400ccf65a/pomegranate/base.pyx#L41 you still have time to consider letting us pass our own backend before releasing it.

Edit:
I see now that a different class has the methods implemented https://github.com/jmschrei/pomegranate/blob/2e8810c79c90c6e993bc9f106ad06da400ccf65a/pomegranate/base.pyx#L482 so adding user-passed backends could change some stuff there, but I think that as long as json is the default if no backend is specified, it shouldn't be backwards-incompatible.

**Comment by Theelgirl** [comment]
@jmschrei Any thoughts on this?

**Comment by jmschrei** [comment]
I don't think that I will add in custom JSON backends, but it should be fairly straightforward for you to write your own functions, based on the ones I have written, that take a pomegranate model and serialize/deserialize it using your own custom backends.
