### ISSUE TITLE
KeyError: ('Y', 'Home', 'lost')

### ISSUE THREAD

**Issue by kmvenkatesh04** [jmschrei/pomegranate#827]
I'm getting a key error while executing model.bake() in pomegranate
Below is my code to regenerate the error

TLoc = DiscreteDistribution(getDiscreteProba(df,'Location'))
Aswin = ConditionalProbabilityTable([['Home', 'Y', 1.0],
 ['Home', 'N', 0.0],
 ['Away', 'Y', 0.6428571428571429],
 ['Away', 'N', 0.35714285714285715]],[TLoc])
Toss = ConditionalProbabilityTable([['Home', 'Y', 'lost', 0.4883720930232558],
 ['Home', 'Y', 'won', 0.5116279069767442],
 ['Home', 'N', 'lost', 0.0],
 ['Home', 'N', 'won', 0.0],
 ['Away', 'Y', 'lost', 0.5925925925925926],
 ['Away', 'Y', 'won', 0.4074074074074074],
 ['Away', 'N', 'lost', 0.5333333333333333],
 ['Away', 'N', 'won', 0.4666666666666667]] ,[Aswin, TLoc])
Bat = ConditionalProbabilityTable([['Home', 'Y', 'lost', '2nd', 0.9523809523809523],
 ['Home', 'Y', 'lost', '1st', 0.047619047619047616],
 ['Home', 'Y', 'won', '2nd', 0.09090909090909091],
 ['Home', 'Y', 'won', '1st', 0.9090909090909091],
 ['Home', 'N', 'lost', '2nd', 0.0],
 ['Home', 'N', 'lost', '1st', 0.0],
 ['Home', 'N', 'won', '2nd', 0.0],
 ['Home', 'N', 'won', '1st', 0.0],
 ['Away', 'Y', 'lost', '2nd', 0.6875],
 ['Away', 'Y', 'lost', '1st', 0.3125],
 ['Away', 'Y', 'won', '2nd', 0.0],
 ['Away', 'Y', 'won', '1st', 1.0],
 ['Away', 'N', 'lost', '2nd', 0.5],
 ['Away', 'N', 'lost', '1st', 0.5],
 ['Away', 'N', 'won', '2nd', 0.2857142857142857],
 ['Away', 'N', 'won', '1st', 0.7142857142857143]],[Toss, Aswin, TLoc])
Result = ConditionalProbabilityTable([['Home', 'Y', 'lost', '2nd', 'won', 0.75],
 ['Home', 'Y', 'lost', '2nd', 'draw', 0.2],
 ['Home', 'Y', 'lost', '2nd', 'lost', 0.05],
 ['Home', 'Y', 'lost', '1st', 'won', 0.0],
 ['Home', 'Y', 'lost', '1st', 'draw', 1.0],
 ['Home', 'Y', 'lost', '1st', 'lost', 0.0],
 ['Home', 'Y', 'won', '2nd', 'won', 0.5],
 ['Home', 'Y', 'won', '2nd', 'draw', 0.5],
 ['Home', 'Y', 'won', '2nd', 'lost', 0.0],
 ['Home', 'Y', 'won', '1st', 'won', 0.85],
 ['Home', 'Y', 'won', '1st', 'draw', 0.05],
 ['Home', 'Y', 'won', '1st', 'lost', 0.1],
 ['Home', 'N', 'lost', '2nd', 'won', 0.0],
 ['Home', 'N', 'lost', '2nd', 'draw', 0.0],
 ['Home', 'N', 'lost', '2nd', 'lost', 0.0],
 ['Home', 'N', 'lost', '1st', 'won', 0.0],
 ['Home', 'N', 'lost', '1st', 'draw', 0.0],
 ['Home', 'N', 'lost', '1st', 'lost', 0.0],
 ['Home', 'N', 'won', '2nd', 'won', 0.0],
 ['Home', 'N', 'won', '2nd', 'draw', 0.0],
 ['Home', 'N', 'won', '2nd', 'lost', 0.0],
 ['Home', 'N', 'won', '1st', 'won', 0.0],
 ['Home', 'N', 'won', '1st', 'draw', 0.0],
 ['Home', 'N', 'won', '1st', 'lost', 0.0],
 ['Away', 'Y', 'lost', '2nd', 'won', 0.0],
 ['Away', 'Y', 'lost', '2nd', 'draw', 0.36363636363636365],
 ['Away', 'Y', 'lost', '2nd', 'lost', 0.6363636363636364],
 ['Away', 'Y', 'lost', '1st', 'won', 0.6],
 ['Away', 'Y', 'lost', '1st', 'draw', 0.0],
 ['Away', 'Y', 'lost', '1st', 'lost', 0.4],
 ['Away', 'Y', 'won', '2nd', 'won', 0.0],
 ['Away', 'Y', 'won', '2nd', 'draw', 0.0],
 ['Away', 'Y', 'won', '2nd', 'lost', 0.0],
 ['Away', 'Y', 'won', '1st', 'won', 0.5454545454545454],
 ['Away', 'Y', 'won', '1st', 'draw', 0.18181818181818182],
 ['Away', 'Y', 'won', '1st', 'lost', 0.2727272727272727],
 ['Away', 'N', 'lost', '2nd', 'won', 0.0],
 ['Away', 'N', 'lost', '2nd', 'draw', 0.0],
 ['Away', 'N', 'lost', '2nd', 'lost', 1.0],
 ['Away', 'N', 'lost', '1st', 'won', 0.75],
 ['Away', 'N', 'lost', '1st', 'draw', 0.0],
 ['Away', 'N', 'lost', '1st', 'lost', 0.25],
 ['Away', 'N', 'won', '2nd', 'won', 0.0],
 ['Away', 'N', 'won', '2nd', 'draw', 0.5],
 ['Away', 'N', 'won', '2nd', 'lost', 0.5],
 ['Away', 'N', 'won', '1st', 'won', 0.4],
 ['Away', 'N', 'won', '1st', 'draw', 0.4],
 ['Away', 'N', 'won', '1st', 'lost', 0.2]], [Bat, Toss, Aswin, TLoc])

s1 = Node(TLoc, name="Location")
s2 = Node(Aswin, name="Aswin")
s3 = Node(Toss, name="Toss")
s4 = Node(Bat, name="Bat")
s5 = Node(Result, name="Result")

model = BayesianNetwork("Winning probablity of Aswin Playing in the game")
model.add_states(s1, s2, s3, s4, s5)
model.add_edge(s1, s2)
model.add_edge(s2, s3)
model.add_edge(s3, s4)
model.add_edge(s4, s5)

model.bake()

**Comment by jmschrei** [comment]
I think you haven't used `add_edge` enough. Your `Result` variable should have edges from each of the other variables, not just from `Bat`.
