### ISSUE TITLE
KeyError: ('True', 'True', 'True', 'True', False)

### ISSUE THREAD

**Issue by elhamsaeedy** [jmschrei/pomegranate#832]
Hi 
I receive KeyError: ('True', 'True', 'True', 'True', False), when model.bake()
Please take a look at my code as below:

# pit model
# If any of the 4 adjacent cells has pit (with Bernoulli(0.2), the middle cell weill feel breeze)
Padjcell1=DiscreteDistribution({'True':0.2,'False':0.8})
Padjcell2=DiscreteDistribution({'True':0.2,'False':0.8})
Padjcell3=DiscreteDistribution({'True':0.2,'False':0.8})
Padjcell4=DiscreteDistribution({'True':0.2,'False':0.8})

Padjcells=[Padjcell1,Padjcell2,Padjcell3,Padjcell4]
breeze=ConditionalProbabilityTable(
                                 [[True,False,False,False,True,1],
                                  [True,False,False,False,False,0],
                                  [False,True,False,False,True,1],
                                  [False,True,False,False,False,0],
                                  [False,False,True,False,True,1],
                                  [False,False,True,False,False,0],
                                  [False,False,False,True,True,1],
                                  [False,False,False,True,False,0],
                                  [True,True,False,False,True,1],
                                  [True,True,False,False,False,0],
                                  [True,False,True,False,True,1],
                                  [True,False,True,False,False,0],
                                  [True,False,False,True,True,1],
                                  [True,False,False,True,False,0],
                                  [False,True,True,False,True,1],
                                  [False,True,True,False,False,0],
                                  [False,True,False,True,True,1],
                                  [False,True,False,True,False,0],
                                  [False,False,True,True,True,1],
                                  [False,False,True,True,False,0],
                                  [True,True,True,False,True,1],
                                  [True,True,True,False,False,0],
                                  [True,True,False,True,True,1],
                                  [True,True,False,True,False,0],
                                  [True,False,True,True,True,1],
                                  [True,False,True,True,False,0],
                                  [False,True,True,True,True,1],
                                  [False,True,True,True,False,0],
                                  [True,True,True,True,True,1],
                                  [True,True,True,True,False,0],
                                  [False,False,False,False,False,1],
                                  [False,False,False,False,True,0]],Padjcells)

# State objects hold both the distribution, and a high level name.
p1=State(Padjcell1, name="Padjcell1")
p2=State(Padjcell2, name="Padjcell2")
p3=State(Padjcell3, name="Padjcell3")
p4=State(Padjcell4, name="Padjcell4")
p5=State(breeze, name="breeze")

PitModel = BayesianNetwork("Pits Model")

# Add the five states to the network 
PitModel.add_states(p1, p2, p3, p4, p5)

# Add edges which represent conditional dependencies, where the second node is 
# conditionally dependent on the first node (Breeze is dependent on 4 adjacent cells)
PitModel.add_edge(p1, p5)
PitModel.add_edge(p2, p5)
PitModel.add_edge(p3, p5)
PitModel.add_edge(p4, p5)

PitModel.bake()

**Comment by elhamsaeedy** [comment]
I noticed my typo in defining the probability dirstibutions. After changing to below, model.bake() complies.
Padjcell1=DiscreteDistribution({True:0.2,False:0.8})
Padjcell2=DiscreteDistribution({True:0.2,False:0.8})
Padjcell3=DiscreteDistribution({True:0.2,False:0.8})
Padjcell4=DiscreteDistribution({True:0.2,False:0.8})

**Comment by jmschrei** [comment]
Great, thanks for letting me know!
