### ISSUE TITLE
[QUESTION] - GMM Using Only One Component

### ISSUE THREAD

**Issue by AndyTza** [jmschrei/pomegranate#833]
I was trying to perform a GMM on a given weighted dataset that can possibly be either drawn from a single gaussian or is perhaps multimodal. I was hoping to estimate the BIC for each mixture component, however, starting at n_clusters=1 (instead of two) 

```
for n_cluster in range(1,5):
    model = GeneralMixtureModel.from_samples([NormalDistribution], n_cluster, X, weights=W)
>>> ValueError: must have at least two distributions for general mixture models
                                              
```
Are there any current methods to work around this? I know this can be done via `sklearn.mixture`, however, in the case of our dataset we need to consider the data with our weights (sklearn currently does not support this feature).

Thanks!

**Comment by jmschrei** [comment]
Howdy

First, I think it should be:

```
for n_cluster in range(1,5):
    model = GeneralMixtureModel.from_samples([NormalDistribution], n_cluster, X, weights=W)
```

I can't remember if pomegranate will allow you to make a mixture with a single component but it should be fairly trivial to calculate by hand, right? Just fit a normal distribution to the data in the same way, e.g. `NormalDistribution.from_samples, X, weights=W`, calculate the log probability, and then penalize by the number of parameters, (i.e., 2).
