### ISSUE TITLE
[BUG] Bayesian Network Plot not working under Windows 10

### ISSUE THREAD

**Issue by AvyChanna** [jmschrei/pomegranate#841]
When trying to plot a Bayesian Network using `model.plot()` I get the following error.

```
Traceback (most recent call last):
  File "pom.py", line 73, in <module>
    plot(model)
  File "pom.py", line 66, in plot
    G.draw(tf.name, format='png', prog='dot')
  File "C:\Users\<usename>\AppData\Roaming\Python\Python38\site-packages\pygraphviz\agraph.py", line 1518, in draw
    fh = self._get_fh(path, 'w+b')
  File "C:\Users\<username>\AppData\Roaming\Python\Python38\site-packages\pygraphviz\agraph.py", line 1547, in _get_fh
    fh = open(path, mode=mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\<username>\\AppData\\Local\\Temp\\tmphkr6xyon'
```

I suspect that the problem lies in [pomegranate/BayesianNetwork.pyx Line 252](https://github.com/jmschrei/pomegranate/blob/2e8810c79c90c6e993bc9f106ad06da400ccf65a/pomegranate/BayesianNetwork.pyx#L252). `tempfile.NamedTemporaryFile()` returns a file-like object. Using argument `tf.name` in `G.draw(...)`, pygraphviz tries to open that file again, while `tf` is already open, hence the permission error.

## Reproduction

Used monty hall problem

```python
from pomegranate import *
import matplotlib.pyplot as plt
guest = DiscreteDistribution({'A': 1./3, 'B': 1./3, 'C': 1./3})
prize = DiscreteDistribution({'A': 1./3, 'B': 1./3, 'C': 1./3})
monty = ConditionalProbabilityTable(
        [['A', 'A', 'A', 0.0],
         ['A', 'A', 'B', 0.5],
         ['A', 'A', 'C', 0.5],
         ['A', 'B', 'A', 0.0],
         ['A', 'B', 'B', 0.0],
         ['A', 'B', 'C', 1.0],
         ['A', 'C', 'A', 0.0],
         ['A', 'C', 'B', 1.0],
         ['A', 'C', 'C', 0.0],
         ['B', 'A', 'A', 0.0],
         ['B', 'A', 'B', 0.0],
         ['B', 'A', 'C', 1.0],
         ['B', 'B', 'A', 0.5],
         ['B', 'B', 'B', 0.0],
         ['B', 'B', 'C', 0.5],
         ['B', 'C', 'A', 1.0],
         ['B', 'C', 'B', 0.0],
         ['B', 'C', 'C', 0.0],
         ['C', 'A', 'A', 0.0],
         ['C', 'A', 'B', 1.0],
         ['C', 'A', 'C', 0.0],
         ['C', 'B', 'A', 1.0],
         ['C', 'B', 'B', 0.0],
         ['C', 'B', 'C', 0.0],
         ['C', 'C', 'A', 0.5],
         ['C', 'C', 'B', 0.5],
         ['C', 'C', 'C', 0.0]], [guest, prize])

s1 = Node(guest, name="guest")
s2 = Node(prize, name="prize")
s3 = Node(monty, name="monty")

model = BayesianNetwork("Monty Hall Problem")
model.add_states(s1, s2, s3)
model.add_edge(s1, s3)
model.add_edge(s2, s3)
model.bake()
model.plot()
plt.show()
```

## Solution 

I could solve it by using `tf` directly in Line 253 and 254, since these methods can take file like objects too.

```python
with tempfile.NamedTemporaryFile(mode='w+b') as tf: # w+b is default mode already, just to make sure
	G.draw(tf, format='png', prog='dot')
	img = matplotlib.image.imread(tf)
	plt.imshow(img)
	plt.axis('off')
```

## Details

Python - Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Graphviz - 2.42.2
Pygraphviz - pygraphviz-1.5-cp38-cp38-win32
Graphviz and pygraphviz downloaded from [here](https://github.com/CristiFati/Prebuilt-Binaries/)

**Comment by CisterMoke** [comment]
Ah it seems I created an issue for the same bug:
https://github.com/jmschrei/pomegranate/issues/886

**Comment by MaheshGithub76** [comment]
@AvyChanna I ran into the same problem as you on windows 10 machine. However, for me, changing tf.name to tf in lines 253 and 254 of BayesianNetwork.pyx did not resolve the issue. 

I'm still getting the permission denied error

**Comment by AvyChanna** [comment]
@MaheshGithub76 Can you reproduce the issue with the following code, so we can be sure that the error originates from these lines only. I suppose that would be helpful for the author to fix this.

```py
import pygraphviz
import tempfile
import matplotlib.pyplot as plt
import matplotlib.image as matimg

def plot(model):
	G = pygraphviz.AGraph(directed=True)

	for state in model.states:
		G.add_node(state.name, color='red')

	for parent, child in model.edges:
		G.add_edge(parent.name, child.name)
		with tempfile.NamedTemporaryFile() as tf:
			G.draw(tf, format='png', prog='dot')
			img = matimg.imread(tf)
			plt.imshow(img)
			plt.axis('off')
			plt.show()

# Instead of graph.plot(), call plot(graph). This should work
```

Keep in mind that this bug also affects other types of graphs. Markov Chains don't work for me either, because of the same error. `tempfile` opens the file and will not close it till the code exits from `while` clause. Then matplotlib also tries to open it but windows won't let it.

**Comment by MaheshGithub76** [comment]
@AvyChanna I got it working. I had some issues with my setup.py file and it was not compiling the edited pyc file into a python module extension file (pyd file). So was basically using the older version of the pyd file. Once I debugged the setup.py file, the plot function started working. Nevertheless thanks for your reply and offer to help

**Comment by ioannoug** [comment]
I have just spotted this issue with pygraphviz 1.7.
Python=3.8.0
Pygraphviz and Graphviz installed using these instructions: https://pygraphviz.github.io/documentation/stable/install.html#windows-install

If I use the plot() function suggested by @AvyChanna, it works fine though!

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
