### ISSUE TITLE
[BUG] Plot not working on BayesianNetwork

### ISSUE THREAD

**Issue by creyD** [jmschrei/pomegranate#844]
**Describe the bug**
I installed the library + pygraphviz and matplotlib and still when I cast ` model.plot()` even on the example Monty Hall problem it doesn't print anything in the console. I wrapped a `print()` statement around it, but it as expected prints None.

**To Reproduce**
Code the monty hall problem, run `model.plot()` after the last line (`model.bake()`)

**Comment by jmschrei** [comment]
I'm not sure what the issue is, on your end. The `plot` command shouldn't print anything -- you do `print(model.structure)` to get the set of parents for each node in the graph. Can you try plotting a network outside the context of a jupyter notebook?

**Comment by creyD** [comment]
I did in fact only try it outside of a jupyter notebook.

**Comment by creyD** [comment]
How should I interpret [this documentation](https://pomegranate.readthedocs.io/en/latest/BayesianNetwork.html#pomegranate.BayesianNetwork.BayesianNetwork.plot) then? Doesn't 'draw' mean that it prints it in the console or a file?

**Comment by ctwardy** [comment]
(New user, not a maintainer.)

@creyD -
I tested this today on OS X.
* In jupyter with `%matplotlib inline`, running `model.plot()` creates the model in the output cell, as expected. 
* In ipython console, running `model.plot()` does nothing.  Following it with `plt.show()` displays the image in a new window. (After `import matplotlib.pyplot as plt` of course.)

The pomegranate code is:
```python
if filename is None:
				with tempfile.NamedTemporaryFile() as tf:
					G.draw(tf.name, format='png', prog='dot')
					img = matplotlib.image.imread(tf.name)
					plt.imshow(img)
					plt.axis('off')
```
One could add a `plt.show()` in here, but I'm not sure what that would do to the notebook integration. Possibly model.plot() could autodetect, or accept a parameter. But pomegranate has no way of knowing what backend/env you're working with, so maybe just documenting that you might need a `plt.show()` to render it.

**Comment by jmschrei** [comment]
In the same way that pyplot commands don't themselves produce figures (e.g. plt.plot or plt.hist), the pomegranate command does not itself do that. This is useful if you want to do things like, say, produce a multi-panel figure where the pomegranate plot is just one of the panels. You need to do `plt.plot()` after calling pomegranate.
