### ISSUE TITLE
[BUG] Installation via pip while missing cython fails

### ISSUE THREAD

**Issue by t4y** [jmschrei/pomegranate#845]
On Ubuntu 20.04, using `python3 -m pip install pomegranate` to install pomegranate 0.13.5 fails similarly to what is described in #782 : building wheels fails with `x86_64-linux-gnu-gcc: error: pomegranate/distributions/NeuralNetworkWrapper.c: No such file or directory`

After Installing cpython first, the installation runs fine.

**Comment by jmschrei** [comment]
Thanks for reporting this. I'm trying to revamp the wheel system to produce a more comprehensive set of wheels, so people don't encounter this issue. Sorry for the inconvenience.

**Comment by jmschrei** [comment]
btw I've added this to the README for future people that encounter this issue.

**Comment by jmschrei** [comment]
This should be fixed now.
