### ISSUE TITLE
When trying to bake: AttributeError: 'list' object has no attribute 'distribution'

### ISSUE THREAD

**Issue by ioannoug** [jmschrei/pomegranate#846]
I am trying to create a Bayesian network from data that I have placed in a dictionary. I am doing this because I want the script to accommodate dynamic structures which are specified in some spreadsheets that are used as input files for creating the dictionary and ultimately, the network states.
(I am actually refactoring someone else's code that is using static graphs whose properties are specified in the script itself. I want to pass all those properties as input parameters to my new script.)

I initialise the model:
`model = pg.BayesianNetwork("real")`

Add the states from a list I've build previously:
`model.add_states(listofnodes)`

Add the edges based on the data structure I've specified in the dicitonary `nodes`:
```
for k,v in nodes.items():
    if nodes[k]['priors'] != []:
        for i in nodes[k]['priors']:
            model.add_edge(i, k)

```
I can verify that the edges are correct when I run `model.edges`.

But whenever I bake, I get this:
```
  File "pomegranate\BayesianNetwork.pyx", line 310, in pomegranate.BayesianNetwork.BayesianNetwork.bake

AttributeError: 'list' object has no attribute 'distribution'

```
I am trying to debug this, and I can't figure out how to do it. The original (static) code gets past this point and by eyeballing the states generated from both scripts (original/static and new/dynamic), there doesn't seem to be a(n obvious, at least) difference.

I understand that the error implies that the `distribution` attribute is not properly defined or not found in one or more of the `node` objects. Is there another check I can do to figure this out?

**Comment by jmschrei** [comment]
Howdy. Sorry for the late reply. `model.add_states` doesn't take in a list of nodes, but rather just the nodes themselves. This is a design choice I thought looked cool when I implemented it but have since somewhat regretted. See cell [4] in this tutorial: https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_4_Bayesian_Networks.ipynb
