### ISSUE TITLE
Parent nodes exhibit unexpected dependency

### ISSUE THREAD

**Issue by ensbergj** [jmschrei/pomegranate#849]
Greetings,

This issue may be related to https://github.com/jmschrei/pomegranate/issues/848.

I am using python 3.6.3 with pomegranate version 0.13.5 and I am getting unexpected behavior from the BayesianNetwork predict_proba method when using correlated data.  Specifically, I have a simple three-node BN with two parent nodes (A & B) and one child node (C). The training data is such that the value of C is random, but will be 1 whenever A is 1 or B is 1. When I construct the BN using DiscreteDistribution and ConditionalProbabilityTable, the resulting BN appears to predict that the probability of B changes given observations of A.  Since A and B are both parent nodes, based on the structure provided, I would have expected P(B) = P(B|A=1), but this does not appear to be the case.  The issue manifests when A and B are highly/perfectly correlated with each other. 

The issue can be reproduced with the following code:

from pomegranate import *
import pandas as pd
import numpy as np

df = pd.DataFrame()
df['a'] = np.random.randint(0,2,1000)
df['b'] = df['a']
df['c'] = np.random.randint(0,2,1000)
df['c'].loc[(df['a'] == 1) | (df['b'] == 1)] = 1

print(df['c'].value_counts())
print(df['c'].loc[(df['a'] == 1)].value_counts())

num_0_a = df['a'].value_counts()[0]
num_1_a = df['a'].value_counts()[1]
num_0_b = df['b'].value_counts()[0]
num_1_b = df['b'].value_counts()[1]

dist_a = DiscreteDistribution({0:num_0_a/(num_0_a+num_1_a), 1:num_1_a/(num_0_a+num_1_a)})
dist_b = DiscreteDistribution({0:num_0_b/(num_0_b+num_1_b), 1:num_1_b/(num_0_b+num_1_b)})

data = []
for a in df['a'].unique():
    mask_a = df['a'] == a
    for b in df['b'].unique():
        mask_b = df['b'] == b
        for c in df['c'].unique():
            mask_c = df['c'] == c
            data.append([a,b,c,len(df.loc[mask_a & mask_b & mask_c].index)/len(df.index)])

dist_c = ConditionalProbabilityTable(data, [dist_a, dist_b])

sa = Node(dist_a, name="a")
sb = Node(dist_b, name="b")
sc = Node(dist_c, name="c")

model = BayesianNetwork("Test")
model.add_states(sa, sb, sc)
model.add_edge(sa, sc)
model.add_edge(sb, sc)
model.bake()

print(model.predict_proba({}))
print(model.predict_proba({'a':1})) 

Which produces the following output:

1    779
0    221
Name: c, dtype: int64
1    527
Name: c, dtype: int64
[{
    "class" : "Distribution",
    "dtype" : "int",
    "name" : "DiscreteDistribution",
    "parameters" : [
        {
            "0" : 0.41962439380301114,
            "1" : 0.5803756061969888
        }
    ],
    "frozen" : false
}
 {
    "class" : "Distribution",
    "dtype" : "int",
    "name" : "DiscreteDistribution",
    "parameters" : [
        {
            "0" : 0.41962439380301114,
            "1" : 0.5803756061969888
        }
    ],
    "frozen" : false
}
 {
    "class" : "Distribution",
    "dtype" : "numpy.int64",
    "name" : "DiscreteDistribution",
    "parameters" : [
        {
            "0" : 0.19606129181916598,
            "1" : 0.803938708180834
        }
    ],
    "frozen" : false
}]
[1
 {
    "class" : "Distribution",
    "dtype" : "int",
    "name" : "DiscreteDistribution",
    "parameters" : [
        {
            "0" : 0.0,
            "1" : 1.0
        }
    ],
    "frozen" : false
}
 {
    "class" : "Distribution",
    "dtype" : "numpy.int64",
    "name" : "DiscreteDistribution",
    "parameters" : [
        {
            "0" : 0.0,
            "1" : 1.0
        }
    ],
    "frozen" : false
}]

Note that the probabilities of B change when evidence of A=1 is provided.  Given that A and B are both parent nodes in the specified model structure, I would have expected the probabilities of B to be governed by the DiscreteProbability (cond_b) regardless of the value of A.

Apologies if I am missing something obvious and thank you in advance!

**Comment by jmschrei** [comment]
In a Bayesian network with this structure, A and B are only independent if you know C. Otherwise, A and B are dependent.

**Comment by ensbergj** [comment]
Thanks for the quick response!

This behavior is a bit surprising.  Based on the structure of the BN DAG, my understanding is that A and B both parent nodes and are not conditionally dependent on each other even though they are both connected by the same child C.  As such, I was expecting that information should not be able to propagate from child (C) to parent (B) (or in this case, from parent, A, to child, C,  back to parent, B).  Is this the wrong way to think about the direction of information flow in pomegranate BNs?  Is there any way to create a BN structure in pomegranate that will give the behavior described (i.e., A and B are independent regardless of whether C has been observed, or more generally that information can only be propagated in the directions suggested by the network structure)?

Thank you in advance for your help.

**Comment by jmschrei** [comment]
If A and B share a common child, by definition they cannot be completely independent with a standard conditional probability table. Logical ORs/ANDs can be used in the place of conditional probability tables to decrease the parameterization, but I don't think that renders the parents independent. For instance, in an extreme example, imagine that C was only 1 when both A and B were 1. If you knew that C was 1, that would propagate backward through the network. One of the reasons that Bayesian networks are so popular is that inference flows both ways.
