### ISSUE TITLE
[QUESTION] Is there multinomial distributions in pomegranate?

### ISSUE THREAD

**Issue by JuanCarlosCamara** [jmschrei/pomegranate#850]
Hello,

I´m trying to implement logic from a paper which needs a multinomial distribution conditioned by another distribution modeled by Dirichlet. I have followed the documentation and, even though I´m able to create my Dirichlet distribution, I don´t see any Multinomial Ditribution or a similar one that can be used for my purpose.

Could you please confirm or let me know if it is possible to get this approach?

Thanks and best regrads,
Juan Carlos Cámara

**Comment by jmschrei** [comment]
A discrete distribution can be used as a multinomial, but for your purposes I think it would probably be easier to create a custom multinomial distribution. https://github.com/jmschrei/pomegranate/blob/master/tutorials/C_Feature_Tutorial_5_Custom_Distributions.ipynb
