### ISSUE TITLE
Cumulative probability functions

### ISSUE THREAD

**Issue by JohnMrziglod** [jmschrei/pomegranate#851]
Thank you very much for creating this amazing library. It helps me a lot to parallelize some code in my scripts.

Is there an easy way to get the cumulative probability from a distribution for given values? So basically the equivalent to this scipy snippet:
```python
from scipy.stats import gamma

samples = [3, 4, 5, 6, 7, 4, 3, 4, 2, 3, 4, 10, 7, 5, 6, 5]

params = gamma.fit(samples, floc=0)
g = gamma(*params)
g.cdf(8) # 0.9370043498990848
```

**Comment by jmschrei** [comment]
Unfortunately, there is not right now. I'd suggest extracting the parameters from pomegranate and making scipy objects, as you did, and then using the cdf function there.
