### ISSUE TITLE
[BUG] Installation fails with pip in a clean virtual environment

### ISSUE THREAD

**Issue by paulbrodersen** [jmschrei/pomegranate#853]
**Describe the bug**
Installation with pip in a clean virtual environment fails with errors. Log attached.

**To Reproduce**

```shell
mkvirtualenv --python=/usr/bin/python3 test
pip install cython --no-cache-dir
pip install pomegranate --no-cache-dir
```

**Problem cause**

In the current build order, pomegranate is being build before scipy is installed. As a consequence, the dependency `ddot` from `scipy.linalg.cython_blas` is not available during compilation. 

**Solution**

Force installation of scipy before pomegranate. A working installation via pip is then:

```shell
mkvirtualenv --python=/usr/bin/python3 test2
pip install cython
pip install scipy
pip install pomegranate
```
[pomegranate_bug_report.txt](https://github.com/jmschrei/pomegranate/files/5710281/pomegranate_bug_report.txt)

**Comment by paulbrodersen** [comment]
Potentially related to #852.

**Comment by jmschrei** [comment]
This should be fixed now.
