### ISSUE TITLE
Importing module is 'not allowed without gil'

### ISSUE THREAD

**Issue by guilya** [jmschrei/pomegranate#856]
Hi there,
i'd like to add a feature or two to pomegranates BayesianNetwork-module. I am however new to Cython and am indeed running into problems right at the start:

`
import pyximport`
`pyximport.install()`
`import BayesianNetwork`

leads to multiple messages of the type

`Error compiling Cython file:`
`BayesianNetwork.pyx:2718:31: Converting to Python object not allowed without gil`

finally resulting in

`command 'gcc' failed with exit status 1`

I'm working with spyder, but I don't think it's a technical issue, it's just me who doesn't know how to get started. Let me know if you need further system specifications.
Thank you :)

**Comment by jmschrei** [comment]
Howdy. I'm not sure exactly what you're doing, but you shouldn't need to do `import pyximport`. You should build the package using `python setup.py develop` in the root directory when you're done making changes and then import it as a normal package.

**Comment by guilya** [comment]
Thank you for your reply! 
I was following [this](https://stackoverflow.com/questions/17955194/how-to-reload-a-cython-module-interactively-using-pyximport) post, hoping for a way to debug pyx-files, but this seems not to be possible, at least with spyder.
In that case, sorry for bothering ;)

**Comment by jmschrei** [comment]
Right, when importing directly from a pyx file you will need to do that. If you build the package first you can treat it like a normal Python package. Think about it like importing directly from a .c file versus the compiled file. It's a bit unnatural for Python users, but that's Cython for you. Good luck!
