### ISSUE TITLE
Training a bayesian network via iterator

### ISSUE THREAD

**Issue by ekosman** [jmschrei/pomegranate#858]
Hi

Is it possible to add a method to train a BN via an iterator?
I want to train a network where the number of samples is very big for being stored in memory. Training via an iterator would solve this issue.

**Comment by jmschrei** [comment]
Howdy

Do you mean fit the parameters of a network with a known structure, or jointly learning the structure and parameters from an iterator? The answer is yes to the former, and no to the latter. You can use `model.summarize`, like in the other models, for a Bayesian network with a known structure. In pomegranate you cannot learn the structure of a Bayesian network from an iterator, though theoretical approaches do exist that are not implemented.

**Comment by ekosman** [comment]
@jmschrei 
I meant, like in `from_samples` that jointly performs structure and parameters learning. So I understand it is not implemented.

**Comment by jmschrei** [comment]
That's right. I'd recommend learning the structure on a subset of the data and then subsequently learning the parameters, in an out-of-core manner using `model.summarize`, on the entire data set. The structure will be good, albeit likely suboptimal, but the parameters will be optimal for the data given the structure.

**Comment by ekosman** [comment]
@jmschrei 
Ok, as I understand, both `fit` and `from_summaries` let me train the model batch-wise?

This might be a good work-around for this purpose.
