### ISSUE TITLE
Question: Sampling from conditional probability

### ISSUE THREAD

**Issue by MetaDev** [jmschrei/pomegranate#86]
Hello,
I don't know if this is the appropriate place to ask this, please tell me if it isn't.
For my master thesis I would like estimate conditional probabilities of multiple random variables which can be both discrete and continuous (mixture of continuous and discrete variables). I think this could be done using pomegranate by doing density estimation on this mixture and on the joint distribution of the evidence variables. The result would a fraction of 2 mixture of distributions, but not a closed form distribution. Thus, to sample from the conditional distribution I would have to resort rejection sampling (or an optimised MCMC method). Is this correct?

**Comment by jmschrei** [comment]
pomegranate currently doesn't support conditional distributions which are conditional on continuous distributions, unfortunately. It's something I want to add soon though. The idea sounds plausible though. You might consider PyMC, which is more fully fledged in this area.

**Comment by MetaDev** [comment]
Than, if I may, a suggestion. PyMC also supports distribution mixtures, HMM, etc. But there are no factory methods to create them. It would be great if pomegranate (which has a very clear interface) would be able to integrate with the (optimised) sampling methods of PyMC. Maybe, by converting a pomegranate model into a PyMC model.

**Comment by jmschrei** [comment]
That seems like a reasonable idea. However, if I had to time to set that up, I'd also have the time to implement it in pomegranate. I'll actually have some time today to work on these issues. If you can provide a sample code snippet that you'd like to see work, I can see if I can get it implemented soon.

**Comment by MetaDev** [comment]
I haven't yet used pomegranate, I am in the phase of searching the most complete library for my problem. But with conditional distributions I would have it all. What I do have, is my current code in which I do exactly what I mentioned in my first post, but only for mixture of gaussians. What would help you best? The GMM code, or more illustrative pseudo-code?

**Comment by jmschrei** [comment]
Illustrative psueodocode for what I have. Basically, if you have something like this:

```Python
a = NormalDistribution( 5, 2 )
b = ConditionalGaussianDistribution( w=[5], w0=2, sigma=2 )
```
That would specify a parent distribution which is a normal, and a conditional normal distribution centered around a linear regression of the parents. Whatever would be most convenient for you.

**Comment by jmschrei** [comment]
I'm not sure exactly what you're asking. GMMs are implemented in pomegranate (and I think faster than sklearn). Are you looking for Conditional Gaussian Mixture Models?

**Comment by MetaDev** [comment]
Conditional GMMs I have. 
I'll phrase it differently, given data with both discrete and continuous variables e.g. d=[c1,c2,d1,d2].
I would like to be able to do this:

#k component mixture model, to model the continuous data [d1,d2], the multivariate is 2 dimensional to model vector [d1,d2]

gmm=MixtureDistribution(MultivariateGaussianDistribution1, MultivariateGaussianDistribution2, ..., MultivariateGaussianDistributionk)

#discrete distribution

cat1=DiscreteDistribution([(0,0.1),(1,0.3),(2,0.6)])
cat2=DiscreteDistribution([(0,0.6),(1,0.4)])

#new model defines the join distribution of both continuous and discrete data -> p(d)
#I don't think this is possible, yet, in pomegranate
#I think that is maybe why it wasn't exactly clear what I intended, I mixed distribution mixture with mixed joint distribution...

d_model=JointDistribution( gmm,cat1,cat2)

#fit the model parameters with data

d_model.from_sample(data)

#now given that I know (approximately) the joint probability, I would like to know for example the joint probability of [c1,c2] given that d1=1 and d2=0

cond_d = ConditionalDistr(d_model,[np.nan,np.nan,1,0] )

**Comment by jmschrei** [comment]
I'm sorry, I'm still not perfectly understanding what you mean. Are you saying that you want a to be able to define `A`, a conditional distribution, to have both continuous and discrete parents? Basically, a Bayesian network with both discrete and continuous variables in it?

**Comment by MetaDev** [comment]
Yes, that would be it I think. Not really related to distribution mixture, my mistake.

**Comment by jmschrei** [comment]
Sure, I'd like to look at the paper just to make sure we're on the same page.

**Comment by MetaDev** [comment]
There's 2 approaches I've found:
The one I tried: Appendix A in [](http://www.gaussianprocess.org/gpml/chapters/RW.pdf)
or Chapter 2 in [](http://bengio.abracadoudou.com/cv/publications/pdf/rr02-12.pdf)

**Comment by MetaDev** [comment]
Did you make progress towards the conditional distribution?

**Comment by jmschrei** [comment]
I haven't had much time to get into something as in depth as this yet, prospective student visit days are this week. I'll return to this issue soon.

**Comment by jmschrei** [comment]
This completely fell off my radar, I'm sorry! If I worked on this soon, would it be of use to you, or did you complete your thesis?

**Comment by MetaDev** [comment]
No problem.
And thank you for getting back to me, but my thesis is finished.
Good luck with your library.

**Comment by jaSunny** [comment]
Dear @jmschrei what is your process on this topic? Would be also highly interested. thanks!

**Comment by jmschrei** [comment]
Hi @jaSunny. Can you describe exactly what it is you'd like implemented?

**Comment by jaSunny** [comment]
The [sample() method](https://pomegranate.readthedocs.io/en/latest/BayesianNetwork.html#pomegranate.BayesianNetwork.BayesianNetwork.sample) would be awesome or a possibilty to migrate the pomegranate model to PyMC so sampling can be done there. :)
