### ISSUE TITLE
FactorGraph.plot() requires pygraphviz while docs say it only relies on networkx

### ISSUE THREAD

**Issue by virginie-do** [jmschrei/pomegranate#864]
Hi, I created a Bayesian network `model` and since I can't install pygraphviz, I tried to plot it with `model.graph.plot()`,
since the documentation states that FactorGraph.plot() "relies on networkx’s built-in graphing capabilities (and not Graphviz) and thus can’t draw self-loops."

However, I get the following error:
`ValueError: must have pygraphviz installed for visualization`.

Is it possible to still plot my model with this method?

Otherwise, how can I simply extract the networkx DiGraph (model.graph will return a pomegranate FactorGraph) ?

**Comment by jmschrei** [comment]
Hi

Plotting a graph without pygraphviz will generally produce difficult-to-read graphs. I think that the documentation is wrong, in this case. If you're interested in manually plotting it you should look at the plot function and see if you can modify that to make a plot using whatever software you have. https://github.com/jmschrei/pomegranate/blob/master/pomegranate/FactorGraph.pyx#L46
