### ISSUE TITLE
CPT.sample() only samples one case

### ISSUE THREAD

**Issue by guilya** [jmschrei/pomegranate#865]
Hi there,
when using the `sample`-method of conditional probability tables for n>1 and without specifying each parent state, the missing parent states are only generated once for all the samples, so that all samples returned are samples of the very same case (which then moreover is unknown).
When using this method, I would expect the missing parent states to also be sampled, following their respective marginal distributions.
So I am wondering: Is this on purpose?

**Comment by guilya** [comment]
btw the reason I found this is that I wanted to feed the `from_sample()`-method with samples from an actual CPT, to recreate the very same table. The respective samples however seem not compatible: While `sample(n)` returns a list, `from_samples()` expects a two-dimensional object. This also seems counter-intuitive to me, but maybe there is a reason? The respective docs are quite short, unfortunately.
I'd like to 'fix' this if it is indeed considered an issue.

**Comment by jmschrei** [comment]
That does sound like an issue. Unfortunately, I'm no longer actively adding new features to pomegranate, so I don't think I'll be able to fix this. I'd be happy to review a PR from you, though.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
