### ISSUE TITLE
[QUESTION] - Accessing penalty & |M| for a learned BN

### ISSUE THREAD

**Issue by ctwardy** [jmschrei/pomegranate#866]
Is there a way to extract penalty and |M| from a learned BN? 

It's calculated during learning, but as far as I can tell, locally at each node, and never stored. I would like to be able to get that.  

The algorithms try to maximize:

	P(D|M) + penalty * |M|

We can get P(D|M) from `model.log_probability()`, and we know the default penalty, but what about |M|?  It would be handy to store, so we don't have to walk the model structure adding up CPT sizes.

**Comment by jmschrei** [comment]
Unfortunately, the code as it stands doesn't keep track of |M|. If you keep
track of the number of categories possible for each variable, say in a
variable `sizes`, you can easily calculate M as something like
`numpy.sum([numpy.prod([sizes[parent] for parent in parents]) * sizes[i]
for i, parents in enumerate(model.structure)])` I haven't bug tested this,
but it should be pretty close.

**Comment by ctwardy** [comment]
That seems to have  done it, thank you.
