### ISSUE TITLE
[BUG]HMM model.from_samples can't work

### ISSUE THREAD

**Issue by KIIIIK** [jmschrei/pomegranate#867]
I have a dataset now. X_train is a np.ndarray, shape is (908, 105), n_samples=908, n_features=105.y_train also is a np.ndarray, shape is (908,), values is 0 or 1.
now i want to use HMM train the dataset.
My code is fllows:
`
X_ = X_train.values.tolist()

y = [[i] for i in y_train]

model = pg.HiddenMarkovModel()

model.from_samples(distribution=pg.GammaDistribution, n_components=2, X=X_, labels=y, algorithm='labeled')
`
when i run this codes, it raise error, the error is :
IndexError: boolean index did not match indexed array along dimension 0; dimension is 95340 but corresponding boolean dimension is 908
I really don't know what should i do.
Can you help me?Please!

**Comment by KIIIIK** [comment]
When i modify my code as follow,it also raise an error.
`
X_ = X_train.values.tolist()

y = [[i for i in y_train]]

model = pg.HiddenMarkovModel()

model.from_samples(distribution=pg.GammaDistribution, n_components=2, X=X_, labels=y, algorithm='labeled')
`
The error is :
IndexError: boolean index did not match indexed array along dimension 0; dimension is 105 but corresponding boolean dimension is 908

**Comment by jmschrei** [comment]
Your labels need to be one label for each observation in your sequence, where the label is the hidden state that the observation belongs to, not one label for the entire sequence. HMMs aren't discriminative models.
