### ISSUE TITLE
v0.14.1 wheels require NumPy 1.20

### ISSUE THREAD

**Issue by alexhenrie** [jmschrei/pomegranate#870]
Pip does not install a usable copy of Pomegranate 0.14.1 unless NumPy 1.20 or later is installed:

```
$ sudo rm -rf /usr/lib/python3.9/site-packages/numpy* /usr/lib/python3.9/site-packages/pomegranate* && rm -rf ~/.local/lib && sudo pip3 install numpy==1.19.5 pomegranate==0.14.1 && python3 -c 'import pomegranate'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/pomegranate/__init__.py", line 11, in <module>
    from .base import *
  File "pomegranate/base.pyx", line 1, in init pomegranate.base
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

This was not a problem with Pomegranate 0.14.0. I don't know what the best way to fix it is :-( The simplest solution would be to increase Pomegranate's minimum NumPy requirement to 1.20 in requirements.txt.

**Comment by jmschrei** [comment]
I think this might be because you have a previous copy of pomegranate and it doesn't refresh all the pre-compiled code. Can you try doing a complete uninstall and then reinstalling?

**Comment by alexhenrie** [comment]
I was careful to delete all copies of Pomegranate before installing (see the `rm -rf` commands above).

**Comment by jmschrei** [comment]
Looks like other people are reporting this as an issue too. I'll release 0.14.2 tonight with a numpy requirement.

**Comment by ahujasushant** [comment]
I have tried 0.14.2 still not working

**Comment by jmschrei** [comment]
Going forward, pomegranate will require numpy=1.20.0. This seems to be an issue across many packages.
