### ISSUE TITLE
Discrete Bayesian Networks

### ISSUE THREAD

**Issue by miwslb** [jmschrei/pomegranate#876]
I can't seem to specify a DiscreteDistribution output from a ConditionalProbabilityTable 

For example

```
d1 = DiscreteDistribution({'A':0.6,'B':0.2,'C':0.1,'D':0.1})
d2 = DiscreteDistribution({'E':0.6,'F':0.2,'G':0.1,'H':0.1})
d3 = ConditionalProbabilityTable([['I','J','K'],
                                  ['A','E',0.2,0.4,0.4], . . .
                                  . . . ],[d1,d2])
```

This syntax for d3 is not correct, but I can't find out from the documentation what the correct syntax would be for returning a discrete distribution from the conditional probability table. It seems I can't specify a 2D table at all, only a single-column continuous output.

The table I would like to input is:
```
d1 | d2 | I   | J   | K   |
--------------------------|
 A | E  | 0.2 | 0.4 | 0.4 |
 B | E  | 0.1 | 0.5 | 0.4 |
 C | E  | 0.3 | 0.6 | 0.1 |
 D | E  | 0.4 | 0.4 | 0.2 |
 A | F  | 0.5 | 0.2 | 0.3 |
 B | F  | 0.6 | 0.2 | 0.2 |
 C | F  | 0.7 | 0.1 | 0.2 |
 D | F  | 0.8 | 0.1 | 0.1 |
 A | G  | 0.7 | 0.2 | 0.1 |
 B | G  | 0.6 | 0.3 | 0.1 |
 C | G  | 0.5 | 0.4 | 0.1 |
 D | G  | 0.4 | 0.5 | 0.1 |
 A | H  | 0.3 | 0.5 | 0.2 |
 B | H  | 0.2 | 0.4 | 0.4 |
 C | H  | 0.1 | 0.5 | 0.4 |
 D | H  | 0.2 | 0.5 | 0.3 |

```
Have a missed something here?
Thanks
Mike

**Comment by jmschrei** [comment]
Hi Mike

You need to change your table to be in long form. Basically, it should be:

```python

d1 = DiscreteDistribution({'A':0.6,'B':0.2,'C':0.1,'D':0.1})
d2 = DiscreteDistribution({'E':0.6,'F':0.2,'G':0.1,'H':0.1})
d3 = ConditionalProbabilityTable(
    [['A', 'E', 'I', 0.2],
     ['A', 'E', 'J', 0.4],
     ['A', 'E', 'K',0.4],
     ['B', 'E', 'I', 0.1] ..., [d1, d2])
```

**Comment by miwslb** [comment]
Thanks for responding so quick, and for developing/maintaining pomegranate!
 
That syntax works for me. For some reason I just couldn't see it before.

Cheers
Mike
