### ISSUE TITLE
HMM Training example from docs does not work

### ISSUE THREAD

**Issue by tkerwin** [jmschrei/pomegranate#88]
I'm seeing this error:

> In [1]: from pomegranate import HiddenMarkovModel as HMM
> 
> In [2]: hmm = HMM()
> 
> In [3]: hmm.train( [[5, 2, 3, 4], [5, 7, 2, 3, 5]], distribution_inertia=0.3, edge_inertia=0.25 )
> Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel.log_probability'
> TypeError: object of type 'NoneType' has no len()
> Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel.log_probability'
> TypeError: object of type 'NoneType' has no len()
> Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._baum_welch_update'
> TypeError: object of type 'NoneType' has no len()
> Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel.log_probability'
> TypeError: object of type 'NoneType' has no len()
> Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel.log_probability'
> TypeError: object of type 'NoneType' has no len()
> Training improvement: 0.0
> Total Training Improvement: 0.0
> Out[3]: 0.0

I'm running this on linux with numpy 1.9.0, scikit-learn 0.17.1, and python 3.4.1

**Comment by jmschrei** [comment]
Where in the docs is this a training example? You need to define the graphical model of the HMM using states and edges before training it.

**Comment by tkerwin** [comment]
I see, thank you. I confused the training call with the training from hmmlearn, which doesn't require you to explicitly set up the states and edges.  Sorry for the confusion.

**Comment by jmschrei** [comment]
You're welcome!

It's true that you don't have to pass in anything, but you do need to define the number of components in hmmlearn, the covariance type, and some other attributes. It's just that since they infer the dense transition matrix and emission probabilities that they can set reasonable defaults.
