### ISSUE TITLE
Fitting a mixture model with distributions not in documentation

### ISSUE THREAD

**Issue by matty22396** [jmschrei/pomegranate#880]
Hi there, I am planning on using pomegranate for my college thesis where I am exploring multiple mixture distributions on a set of data. I am wondering if there is any flexibility to use distributions which aren't currently included in the documentation. For example if I wanted to fit a mixture of Weibull distributions to the data is there any way you know of to do this in pomegranate or am I currently limited to the univariate distributed listed in the docs.

Thanks

**Comment by jmschrei** [comment]
Yes, see this tutorial on defining your own custom distributions and passing them into built-in models: https://github.com/jmschrei/pomegranate/blob/master/tutorials/C_Feature_Tutorial_5_Custom_Distributions.ipynb

**Comment by matty22396** [comment]
Exactly what I needed thanks a lot!
