### ISSUE TITLE
Getting parameters of a custom mixture model

### ISSUE THREAD

**Issue by matty22396** [jmschrei/pomegranate#881]
Hi I followed along tutorial 5 to create custom distribution and the example code you show how to create a student t distribution. At the end I can print modeln and get the properties of the normal mixture model like this:
`{
    "class" : "GeneralMixtureModel",
    "distributions" : [
        {
            "class" : "Distribution",
            "name" : "NormalDistribution",
            "parameters" : [
                -1.99507244143243,
                1.0194587936902184
            ],
            "frozen" : false
        },
        {
            "class" : "Distribution",
            "name" : "NormalDistribution",
            "parameters" : [
                1.9091667163020318,
                1.036554908610072
            ],
            "frozen" : false
        }
    ],
    "weights" : [
        0.4933023809069253,
        0.5066976190930746
    ]
}`

But when I run the modelt command I get an error message stating
`AttributeError: 'StudentTDistribution' object has no attribute 'to_dict'`

I will be fitting mixture models to data using distributions not included out of the box and will then need to be able to get the properties of each component in the mixture.

**Comment by jmschrei** [comment]
You can always directly access the distribution objects using `model.distributions[i]` to get the i-th distribution in the mixture. This sounds like a printing issue. You can just implement a `to_dict` method on your custom distribution.

**Comment by matty22396** [comment]
Hi thanks I am now trying to access the weights of components in the mixture model. When I print the details of the model my output shows the specified weight for each component like so: 

`"weights" : [
        0.5584856226977167,
        0.2857176170808492,
        0.1557967602214341
    ]`

Obviously these sum to 1 like they should.
When I use model.weights to then access this array directly it returns an array of negative numbers as follows:

`array([-0.5825264 , -1.25275131, -1.85920294])`

can you help me distinguish what these values I am getting when I call model.weights and how do I get the array of weights shown when I call the entire model details on its own?

**Comment by lipinoelbreve** [comment]
I've had the same issue as matty22396. To access the weights I first loaded the model as json:
(Suppose you have the fitted model stored in the variable _model_ )

import json
model_json = json.loads( str(model)  )
weights = model_json[ "weights" ]

Hope that works

**Comment by matty22396** [comment]
Hi thanks for the quick reply. This solves the problem thanks so much!

**Comment by jmschrei** [comment]
Those values are the log weights. Unfortunately, I wasn't consistent about which ones were log weights and which ones were the actual weights. Doing `numpy.exp(model.weights)` should also work.
