### ISSUE TITLE
Question: Directly accessing model parameters as variables

### ISSUE THREAD

**Issue by matty22396** [jmschrei/pomegranate#882]
Hi, after fitting a mixture model I want to use the parameters found (such as mu and sigma for a normal distribution) to create the CDF of the model using scipy. To do this I'm just printing the details of the model and manually entering the parameters of weights, means and sigma into my next line of code. Is there an easier way to directly access the value of the mean for say the first component in a normal mixture model with 2 components. 

`
model2 = GeneralMixtureModel.from_samples(NormalDistribution, 2, X)
print(model2)

#after print i can view the parameters needed to recreate the components in scipy

x = numpy.arange(0, 0.6, 0.0001)
y_cdf1 = ss.norm.cdf(x, 0.0844, 0.0077) # the normal pdf
y_cdf2 = ss.norm.cdf(x, 0.3395, 0.1468) # the normal pdf
y_cdf = 0.4639*y_cdf1 + 0.5361*y_cdf2
plt.figure()
plt.plot(x, y_cdf, label='cdf')
`
So if I could iteratively access the parameters of the fitted model it would make my code a lot easier to implement.

**Comment by jmschrei** [comment]
If `model` is your mixture model, you can do `model.distributions` to get a list of the underlying distributions. For each distribution, you can either access `mu` and `sigma` directly using, say, `model.distributions[0].mu`, or you can get a list of the parameters using `model.distributions[0].parameters`.
