### ISSUE TITLE
[BUG] HMM bake: 'dist' referenced before assignment

### ISSUE THREAD

**Issue by anneborcherding** [jmschrei/pomegranate#883]
**Describe the bug**
If I create an HMM that has only silent states, the `bake()` function crashes with the following error: 
`UnboundLocalError: local variable 'dist' referenced before assignment` in [line 1045 of hmm.pyx](https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L1045). Tis happens because there are no non-silent states in the model and such the distribution is never set (see [here](https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L1040-L1043)). I think it would be nice to add an error message at this place or to fall back to a default value.

**To Reproduce**
```
from pomegranate.hmm import HiddenMarkovModel

model = HiddenMarkovModel()
model.bake()
```

I am aware that this is not the way you are supposed to use this functions, but as it happens, people use functions in a wrong way...

**Comment by jmschrei** [comment]
Good catch. I'll try adding in an error to the next version.

**Comment by jmschrei** [comment]
I've added a check to the beginning of the `bake` method. It should be in 0.14.6.
