### ISSUE TITLE
[DOC]  HMM.fit return value documented as double but it's the model itsel

### ISSUE THREAD

**Issue by carueda** [jmschrei/pomegranate#884]
Just reporting a documentation discrepancy:

`hmm .fit` return value documented as `double` - "The total improvement in fitting the model to the data" - https://github.com/jmschrei/pomegranate/blob/aac593abc2dc6ef3499042a0e8124d8c7b3abfd5/pomegranate/hmm.pyx#L2505-L2509

but it actually returns the model itself - https://github.com/jmschrei/pomegranate/blob/aac593abc2dc6ef3499042a0e8124d8c7b3abfd5/pomegranate/hmm.pyx#L2662-L2664

**Comment by jmschrei** [comment]
Thanks for pointing this out. It used to return the total improvement until I added in chaining to be more consistent with other libraries. The issue will be fixed in the next release.
