### ISSUE TITLE
[Feature Request] Add TRUE BetaDistribution support

### ISSUE THREAD

**Issue by rayleizhu** [jmschrei/pomegranate#885]
Thanks for open-sourcing such an awesome library. I'd like to request TRUE BetaDistribution support. 

The BetaDistribution included currently is actually beta-binomial distribution. But the true BetaDistribution is useful for modeling skewed distributions, or a mixture of them (an example is given below, I currently use Gaussian  Mixture to model the two-modal distribution, but it looks not good.).

![image](https://user-images.githubusercontent.com/19933627/111093731-98220900-8574-11eb-839d-223387f9067f.png)

Related issue: https://github.com/jmschrei/pomegranate/issues/576

**Comment by jmschrei** [comment]
Howdy

Thanks for pointing this out. You're correct that the current implementation is for a beta binomial and should probably be renamed. Unfortunately, I'm not actively adding in new features right now. If you'd like to take a stab at it, I'd be happy to look at a PR.

Thanks

**Comment by matty22396** [comment]
Hi I am also in need of beta distribution but having trouble coding it myself, did you attempt to create a custom distribution for it @rayleizhu ?

**Comment by rayleizhu** [comment]
> Howdy
> 
> Thanks for pointing this out. You're correct that the current implementation is for a beta binomial and should probably be renamed. Unfortunately, I'm not actively adding in new features right now. If you'd like to take a stab at it, I'd be happy to look at a PR.
> 
> Thanks

Hi, @jmschrei , I've added the TrueBetaDistribution in my fork and sent the PR.

**Comment by rayleizhu** [comment]
> Hi I am also in need of beta distribution but having trouble coding it myself, did you attempt to create a custom distribution for it @rayleizhu ?

@matty22396 please check my fork.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
