### ISSUE TITLE
[BUG] BN files are huge because recursive

### ISSUE THREAD

**Issue by ctwardy** [jmschrei/pomegranate#892]
Pomegranate BN files are _much_ larger than they need to be, because each node lists parent distributions recursively back to root nodes.  This makes files huge and hard to read. 

Consider a three-node binary network A ➛ B ➛ C.  Node C recursively includes both B and A. Verbatim below. In summary, C's definition says:
* C is a Distribution of type CPT with (table shown) and...
  *  Parents of type CPT with (table shown, though already defined in B), and in turn
     * Parents of type Discrete with (parameters shown, though defined in A).

If C itself is a common parent of 6 other nodes, _each_ of them will repeat this entirely, none of which is necessary, because C is already defined. 

I'm happy to help make this more concise -- what constraints does the rest of `pomegranate` impose? If I can understand this I can also help write I/O to standard BN formats. 

 ```json
{'class': 'State',
   'distribution': {'class': 'Distribution',
    'name': 'ConditionalProbabilityTable',
    'table': [['T', 'T', '0.75'],
     ['T', 'F', '0.25'],
     ['F', 'T', '0.5'],
     ['F', 'F', '0.5']],
    'dtypes': ['str', 'str', 'float'],
    'parents': [{'class': 'Distribution',
      'name': 'ConditionalProbabilityTable',
      'table': [['T', 'F', '0.25'],
       ['T', 'T', '0.75'],
       ['F', 'F', '0.5'],
       ['F', 'T', '0.5']],
      'dtypes': ['str', 'str', 'float'],
      'parents': [{'class': 'Distribution',
        'dtype': 'str',
        'name': 'DiscreteDistribution',
        'parameters': [{'T': 0.75, 'F': 0.25}],
        'frozen': False}]}]},
   'name': 'C',
   'weight': 1.0}]}
```

**To Reproduce**
The following will duplicate the network. Then use `net.to_dict()` or `net.to_json()` or `net.to_yaml()` to show the recursion at C.

```python
a = bn.DiscreteDistribution({'T': 3/4, 'F': 1/4})
b = bn.ConditionalProbabilityTable([['T','T',3/4],
                                    ['T','F',1/4],
                                    ['F','T',1/2],
                                    ['F','F',1/2],
                                    ], [a])
c = bn.ConditionalProbabilityTable([['T','T',3/4],
                                    ['T','F',1/4],
                                    ['F','T',1/2],
                                    ['F','F',1/2],
                                    ], [b])

A = bn.Node(a, name='A')
B = bn.Node(b, name='B')
C = bn.Node(c, name='C')

net = bn.BayesianNetwork("A->B->C")
net.add_nodes(A,B,C)
net.add_edge(A,B)
net.add_edge(B,C)
```

**Comment by jmschrei** [comment]
Yeah, I think this can be improved by first storing each of the distributions as a list and then storing the edges. If you'd like to take a stab at it that would be great. I'd also appreciate conversions to/from other formats.

**Comment by ctwardy** [comment]
Cool. I'll start looking into this. I'll probably have questions, as I haven't yet had to really learn the whole non-BN distribution system it's built on.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
