### ISSUE TITLE
[TASK] minor: README should say how to install dependencies

### ISSUE THREAD

**Issue by ctwardy** [jmschrei/pomegranate#893]
## Issue
The README mentions dependencies, but doesn't not that `conda install --file requirements.txt` will get them, and is needed before `python setup.py install`.  

Also, `pandas` is needed to run `test_naive_bayes.py`.  Not sure if the solutions is to rewrite w/o pandas or mention pandas as a requirement.

** Side note: **

FYI: The first error I got running `python setup.py install` before installing dependencies involved `pomegranate/base.c`.  If `setup.py` fails to import `Cython`, it switches the install to look for `.c` extensions instead of `.px*`.  Not sure if that's an issue - the `base.c` is mentioned in the README as a cache issue when using `pip install`.

**Comment by jmschrei** [comment]
Added some info to the README.
