### ISSUE TITLE
[TASK] Fix NumPy deprecations

### ISSUE THREAD

**Issue by ctwardy** [jmschrei/pomegranate#894]
**Describe the bug**
Compiling under Python 3.8 produces _lots_ of NumPy deprecation warnings. 

Testing produces more, and at least one RunTime warning (MacOS):
```
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject`.  
```

**To Reproduce**
At least on MacOS:
* git clone to a clean Python 3.8 venv (I use conda virtual ends).
  * I expect any Python 3.x will do
* `conda install --file requirements.txt`
* `conda install nose pandas`
* `python setup.py test`

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
