### ISSUE TITLE
Help needed creating custom beta distribution

### ISSUE THREAD

**Issue by matty22396** [jmschrei/pomegranate#895]
I am trying to create a custom beta distribution for the simple beta distribution. I have tried to follow the tutorial which shows how to create a student T distribution but am getting confused with the from_summaries function in the example. I am implementing it using the scipy.stats.beta distribution and my goal is to use the fitted model to get the parameters for a and b of each component in a beta mixture model. 
Can anyone guide me on what the from_summaries function for a beta distribution would look like, or if anyone has created custom distributions in the past, please show me extra examples other than the student t distribution included in the github tutorials.
Thanks

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
