### ISSUE TITLE
Neural HMM which replace transition process with neural network

### ISSUE THREAD

**Issue by prescientlyd** [jmschrei/pomegranate#896]
I really liked the implementation of Neural HMM in this package. If I understand correctly, the transition process still follows the classical HMM structure, while the emission process  is replaced with a neural network. I was wondering whether the other way around could work or not. In other words, a transition process that is replaced with a neural network, and an emission process remains to be the same structure. Is such design plausible from a theory perspective? Can it be implemented using Pomegranate?

**Comment by jmschrei** [comment]
Sure. In theory, one could come up with a new transition matrix that's based on each example. I've seen cool work on this (on vacation so I can't find the link right now). However, by definition having a transition matrix that is not constant means that the distribution modeled by the HMM is non-stationary, which can make training significantly more difficult. In theory, one could have one neural network that calculates hidden state memberships (as implemented in pomegranate) and a second one that calculates transition probabilities. This would likely be a nightmare to train, but is theoretically possible. pomegranate does not support a neural network estimating the transition matrix directly, unfortunately.

**Comment by andre-vauvelle** [comment]
@prescientlyd check out https://papers.nips.cc/paper/2019/hash/1d0932d7f57ce74d9d9931a2c6db8a06-Abstract.html, might be similar to what you're looking for.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
