### ISSUE TITLE
Creating CPT's from samples

### ISSUE THREAD

**Issue by MaheshGithub76** [jmschrei/pomegranate#897]
I'm working on a discrete Bayesian network. Can you create CPT's for the entire Bayesian network model including the root nodes at once or does the CPT needs to be computed separately for each of the nodes separately?

Can you pass in pandas dataframe into ConditionalProbabilityTable.from_samples method to compute the CPT's for the nodes?

Thanks

**Comment by jmschrei** [comment]
I'm not sure what you mean, precisely, with the first question. You can learn an entire Bayesian network (structure + parameters) from a data set using the `from_samples` method. If you have the structure of the network and need to learn the parameters you can either use `from_structure` (if all you have is the structure) or `model.fit` if you have the model as a pomegranate object and just need to update the parameters. In each case you would update (+ sometimes learn) all of the CPTs.

I think you can pass a pandas dataframe in. You should try it. :)

**Comment by MaheshGithub76** [comment]
Apologies for not offering enough clarity on my first question. I do know the structure of my network. I would certainly perform some structure learning to identify any hidden dependencies mainly statistical correlations, but late. For now I want to learn the parameters and do some inferencing (similar to query option in bnlearn/pgmpy) for the network that I have. I will try both the from_structure method and model.fit method. Wondering if there are any examples that you can point me to. The monty hall example does not include any of these methods as the CPT's are exclusively defined.

Thanks much for all your help

**Comment by jmschrei** [comment]
https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_4b_Bayesian_Network_Structure_Learning.ipynb might provide more insight into the structure learning methods.
