### ISSUE TITLE
[improvement] Define a distribution mixture  for each state in HiddenMarkovModel.from_samples

### ISSUE THREAD

**Issue by oniram-reach** [jmschrei/pomegranate#899]
Currently it is  possible define a distribution mixture  for each state using HiddenMarkovModel.from_samples?
If not, is there an alternative for me to use a distribution mixture  for each state learning transitions from data?

**Comment by jmschrei** [comment]
Unfortunately, there currently isn't a way to define that using `from_samples`. You should instead use the `from_matrix` command, which will look something like this:

```python
d11 = NormalDistribution(2, 1)
d12 = ExponentialDistribution(2)

d1 = GeneralMixtureModel([d11, d12])

d21 = NormalDistribution(2, 8)
d22 = ExponentialDistribution(8)

d2 = GeneralMixtureModel([d21, d22])

starts = numpy.ones(2, dtype='float32') / 2.
transitions = numpy.ones((2, 2), dtype='float32') / 2.

model = HiddenMarkovModel.from_matrix(transitions, [d1, d2], starts)
model.fit(data)
```

I wrote that free-hand so there might be small bugs, but that's the gist of how the code should look. Let me know if you encounter any issues.

**Comment by oniram-reach** [comment]
Thanks! 
This works and helps me!

Another question is:

Where / How do you calculate the B matrix (emission probability) in training ? (I couldn't identify it in code)

You follow Rabiner's tutorial theory?

Rabiner's defines B matrix how sum pdf of each mixture multiplied by mixture coefficient: [https://drive.google.com/file/d/1G6WgHw1ELUw7S2jQuRLhvqugTL5F43Zh/view](url)
