### ISSUE TITLE
[QUESTION] How to create the CPT for multinomial variables/nodes

### ISSUE THREAD

**Issue by sneakyPad** [jmschrei/pomegranate#900]
I was following the tutorial of the Monty Hall Problem and was wondering how I can calculate the conditional probability table for it. I have experimented with Panda's crosstab function and got it to work, but I doubt that this is the right way to go. I'm a novice at Bayesian networks and I am probably missing an important fact.  

I figured that I can learn the CPT with the function `from_samples` like it is done in one of the tutorials:
```python 
model = BayesianNetwork.from_samples(X, algorithm='exact')
```
However, looking at the data this seems only to work for binary values (node has been observed or not). 
How would I do that with multinomal variables? Let's say for example for the Monty Hall Problem or is there any helper function to calculate CPTs?

Thanks!

**Comment by jmschrei** [comment]
It should work for multinomial data just as easily as binary. What makes you think that isn't the case?

**Comment by sneakyPad** [comment]
I think I was a bit confused by the example and mixed up the feature value with the probability. That's why I didn't give it a try with my data. I've just tried it and it works as expected!

Thank you for clarifying this to me!
