### ISSUE TITLE
How to make sure of positive definite (symmetric ) covariance matrix  Using MultivariateGaussianDistribution()

### ISSUE THREAD

**Issue by SeagirlTech** [jmschrei/pomegranate#904]
As in the ScikitLearn GaussianMixture model, **reg_covar=1e-06** adds Non-negative regularization to the diagonal of covariance, which ensures covariance matrices are positive definite.
`sklearn.mixture.GaussianMixture(n_components=1, *, covariance_type='full', tol=0.001, reg_covar=1e-06, max_iter=100, n_init=1, init_params='kmeans', weights_init=None, means_init=None, precisions_init=None, random_state=None, warm_start=False, verbose=0, verbose_interval=10)`

How to set this kind of constraint to get positive definite covariance matrices in pomegranate MultivariateGaussianDistribution?

`from sklearn import datasets
iris = datasets.load_iris()
import pomegranate
pomegranate.gmm.GeneralMixtureModel.from_samples(pomegranate.MultivariateGaussianDistribution, n_components=3, X=iris.data)`

Note: These codes are for examples, In my project using 20News dataset up to 40 topics it's working fine, but I need 60 topics, which gives **numpy.linalg.LinAlgError: 114-th leading minor of the arr is not positive definite** 
  
![Screenshot from 2021-04-19 17-20-50](https://user-images.githubusercontent.com/16258103/115214574-3a657b80-a135-11eb-89a9-a3e366cfaa01.png)

**Comment by jmschrei** [comment]
There are a few things you can do, but I'd suggest either decreasing the size of the model or increasing the inertia. The gist is that you have a component that is not well supported by the data. I had thought I fixed this issue, but apparently some cases still exist. Sorry about that.

**Comment by SeagirlTech** [comment]
> What else can I do Instead of reducing the number of clusters? because It's required to test for a fixed 60 clusters. Thank you.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
