### ISSUE TITLE
AttributeError: 'pomegranate.distributions.PoissonDistribution.Pois' object has no attribute 'keys'

### ISSUE THREAD

**Issue by phunghuyPanasonic** [jmschrei/pomegranate#905]
```
pairs = {}
for i, col in enumerate(merged_stops.columns):
if "_Process1" in str(col):
    pairs[col.split("_")[0]] = []
    pairs[col.split("_")[0]].append((i, col))
elif "_Process2" in str(col):
    pairs[col.split("_")[0]].append((i,col))

nodes = []
models = []
testNB = BayesianNetwork()
models.append(testNB)
stop_means = merged_stops.mean()
for col in merged_stops.columns:
    node = State(PoissonDistribution(int(round(stop_means[col],0))), name=str(col))
    testNB.add_node(node)
    nodes.append(node)

for _, pair in pairs.items():
    testNB.add_transition(nodes[pair[0][0]], nodes[pair[1][0]])

testNB.bake()
testNB.fit(X_train, y_train)
```

`AttributeError: 'pomegranate.distributions.PoissonDistribution.Pois' object has no attribute 'keys'`

Explanation
1) merged_stops is a numerical dataframe with columns such as **"1_Process1", "2_Process1", "1_Process2", "2_Process2"**
2) each column contains integer values signifying number of errors for that CODE_PROCESS
3) I am trying to build a bayesian network where each CODE_PROCESS column of above dataframe is a node. Node type is a Poisson distribution whose parameter is the column-average error count
4) There should be an edge from CODEXX_PROCESS1 to CODEXX_PROCESS2 signifying downstream process' dependence on upstream

I got the above error when trying to bake the graph before fitting it to the data
What could have brought about this error?
I am using pomegranate version = 0.13.3

**Comment by jmschrei** [comment]
Bayesian networks in pomegranate only supports DiscreteDistribution and ConditionalProbabilityTables --- sorry!
