### ISSUE TITLE
No simple way to grab emission probabilities associated with each state 

### ISSUE THREAD

**Issue by ddubocan** [jmschrei/pomegranate#906]
Hi,

Pomegranate has been great for me in generating HMMs. 

My one issues is that there is no simple, straightforward way to return the emission probabilities associated with each state.

I am aware that if I print the model I can see the emission probabilities, but is there anyway to get the emission probabilities as a matrix or dictionary associated with each state in a simple to manipulate python object?

Thanks!

**Comment by jmschrei** [comment]
I'm not sure exactly what you mean. You can select state objects from `model.states` and from those you can select distribution objects, e.g., `model.states[0].distribution`. Is that what you're looking for?

**Comment by ddubocan** [comment]
I appreciate the prompt response! That is precisely what I am looking for.
`hmm.states[x].distribution.parameters`  where x is the state label (0,1....) gave me exactly what I needed.

Thanks!
