### ISSUE TITLE
[BUG] JointProbabilityTable ignores n samples

### ISSUE THREAD

**Issue by bdatko** [jmschrei/pomegranate#910]
**Describe the bug**
`JointProbabilityTable.sample()` only returns 1 sample regardless of requested samples.
Expected to have the requested number of samples from the joint probability table.
`pomegranate.__version__ = '0.13.5'`

**To Reproduce**
```python
JointProbabilityTable([["heads", 0.2], ["tails", 0.8]], ).sample(10)
('tails',)
```

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
