### ISSUE TITLE
[BUG] sample() not returning the path with emissions?

### ISSUE THREAD

**Issue by kaylairish** [jmschrei/pomegranate#911]
**Describe the bug**
When I call `sample()`, I am getting the list of emissions, but the path looks weird. I am expecting the hidden states paired with the emissions but get a big warning that "Creating an ndarray from ragged nested sequences is deprecated" and then the path returned is a long list of repeated information about the model I created. 

I am new to pomegranate, so I may just be reading the documentation incorrectly and missing something. When I generate sample with path=True, should I expect an additional list of states that match with my emissions?

**To Reproduce**
fair_dist = pomegranate.DiscreteDistribution({'1':1/6, '2':1/6, '3':1/6, '4':1/6, '5':1/6, '6':1/6})
loaded_dist = pomegranate.DiscreteDistribution({'1':1/10, '2':1/10, '3':1/10, '4':1/10, '5':1/10, '6':1/2})

fair = pomegranate.State(fair_dist, name="fair")
loaded = pomegranate.State(loaded_dist, name="loaded")

model = pomegranate.HiddenMarkovModel()

model.add_states([fair, loaded])
model.add_transition(model.start, fair, 0.50)
model.add_transition(model.start, loaded, 0.50)
model.add_transition(fair, fair, 0.95 * 0.98)
model.add_transition(fair, loaded, 0.05 * 0.98)
model.add_transition(loaded, fair, 0.10)
model.add_transition(loaded, loaded, 0.90)
model.add_transition(fair, model.end, 0.02)

model.bake()

sample = model.sample(n=1, path=True, random_state=2)

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
