### ISSUE TITLE
Trouble initializing GeneralMixtureModel.from_samples() with MultivariateGaussianDistribution to embed with HMM

### ISSUE THREAD

**Issue by tracktorr1** [jmschrei/pomegranate#912]
Trying to initialize multivariate gaussian in GMM `from_samples` and am getting "ValueError: need more than 1 value to unpack" 

My input data is list of numpy array lists of MFCC sequences for speech: 
```
GMM = GeneralMixtureModel.from_samples(MultivariateGaussianDistribution, n_components=3, X=X)
X = [numpy.array([[-64.11, 31.28, ...], [-66.83, 33.45, ...], ... [-62.03, 54.89, ...]]), numpy.array([ ... ]), ...]
```

I have 400 files of spoken sentences so I assume for each file to append every new numpy array list of MFCC frames sequence?

I need `GeneralMixtureModel.from_samples()` to use HMM emissions but that means to have GMM element initialized for each HMM state.

**Comment by lipinoelbreve** [comment]
I'm not understanding the dimension of the X array you are passing

As far as I know, when fitting a GMM from samples, you should pass a **n** x **k** array, with n observations and k features.
Your X array seems to be in 3 dimensions (a list of 2 dimension arrays), so it seems that each observation is a matrix.

I'm not sure if you can pass matrices as observations to the from_samples method. Maybe you should unfold the matrix to a **1** x **k** array (try numpy reshape)

**Comment by tracktorr1** [comment]
I use multivariate, so does it not build across **k** dimension, not 3rd dimension? When I set GMM for each HMM state then the **n** may be any size? 

```
states = []
for s in range(0, numStates):
    X = data[s]  # n observations of k number of features
    GMM = GeneralMixtureModel.from_samples(MultivariateGaussianDistribution, n_components=3, X=X)
    states.append(GMM)

HMM = HiddenMarkovModel.from_matrix(transitions, states, starts, state_names)
```

**Comment by jmschrei** [comment]
@lipinoelbreve is correct. When you train a GeneralMixtureModel you should be passing in a data matrix `X` that has two dimensions: the number of examples, and the number of features. When you train an HMM you should pass in a list, where each item in that list is a sequence in the form of a 2D matrix.
