### ISSUE TITLE
[SPEED ISSUE]

### ISSUE THREAD

**Issue by organic-chemistry** [jmschrei/pomegranate#913]
**Describe the bug**
Hello, I am working with HMM with a high number of hidden states ~ 2000.
I am a bit surprised because I use the method from_samples to initialise the network, with only labeled samples, and I stopped it after ~12h and it was not finished.
If I do the same with ~ 200 states it finish in about 10 minutes.
I use as emission distribution a DiscreteDistribution.
Do you see any specific reason why it does not scale well?
I know I could initiate it myself by given it the transition matrix, but I really like the way the api from_sample work.
Here is a small code to reproduce my setup:
**To Reproduce**
```
import time
from pomegranate import *
import numpy as np

#Generate N states system with a fixed sample size independent from the number of state
def generate_n_states(ns=100):
    state_names = [str(i) for i in range(ns)]
    seq = np.random.randint(0,ns,size=50000)
    em = np.random.normal(loc=seq) 
    seq =['None-start'] + [str(s) for s in seq]
    return state_names,seq,em

times=[]
n_states = [10,50,100,200]
for n_state in n_states:
    state_names,seq,em = generate_n_states(n_state)
    t0=time.time()
    model = HiddenMarkovModel.from_samples(NormalDistribution,n_components=len(state_names),
                                   X=[em],
                                   labels=[seq],algorithm="labeled",
                                   state_names=state_names)
    times.append(time.time()-t0)
    print(f"N states: {n_state}, time: {times[-1]:.2f}")
```

it outputs:

```
N states: 10, time: 0.76
N states: 50, time: 13.34
N states: 100, time: 61.31
N states: 200, time: 427.53
```

![image](https://user-images.githubusercontent.com/29305032/116974559-9942fd00-acbe-11eb-95a3-7c88a04ccd37.png)

I would have expected rather a constant time as the sequence that I use has a constant size, but it seems it scales as the square of the number of state.
I don't understand why.
Thanks!

**Comment by jmschrei** [comment]
Howdy

Thanks for the report. The issue ended up being somewhat complex. At a high level, you're correct that the labeled training algorithm should only take linear time. Unfortunately, the current implementation involves calculating the log probability of the training set as a convergence criterion, and a forward pass through the model is quadratic with respect to the number of states in the model (https://en.wikipedia.org/wiki/Forward_algorithm see Complexity). More specifically, it's linear with the number of edges in the model, which can be sub-quadratic, but the basic learning algorithms all assume a dense graph. Although one could consider removing that calculation from fully labeled training, if you ever want to do inference you'll have to accept quadratic time for inference.

However, I was able to find a fairly large speed improvement. pomegranate has built-in functionality to simplify graphs, e.g., merging silent states when the edge between them has a 100% probability. This function can be very slow and is also linear with the number of edges. It's also unnecessary when the user defines the graph. So, I set the default option to not do any merging and that seemed to dramatically speed up the code (200 states went from ~430 seconds to ~110 seconds). v0.14.5 should have this speedup when it's done building.

**Comment by jmschrei** [comment]
If you have a graph that is very sparse, such as each node having <=6 out-edges, all of these algorithms should be very fast. Let me know if that's not the case.

**Comment by organic-chemistry** [comment]
Hello,
I modified my script to generate a sequence with only transition to the next integer:
For example with 5 states I train the HMM with : 0,1,2,3,4,0,1,2,3,4,....
```python
def generate_n_states(ns=100,one_transition=False):
    state_names = [str(i) for i in range(ns)]
    seq_length=50000
    
    if one_transition:
        seq = np.concatenate([list(range(ns))]*int(seq_length//ns))
    else:
        seq = np.random.randint(0,ns,size=seq_length)
    em = np.random.normal(loc=seq) 
    seq =['None-start'] + [str(s) for s in seq]
    return state_names,seq,em

import time

n_states = [10,50,100,200]
times_dp={}
for one_transition in [True,False]:
    times=[]
    for n_state in n_states:
        state_names,seq,em = generate_n_states(n_state,one_transition=one_transition)
        t0=time.time()
        model = HiddenMarkovModel.from_samples(NormalDistribution,n_components=len(state_names),
                                       X=[em],
                                       labels=[seq],algorithm="labeled",
                                       state_names=state_names,n_jobs=6)
        times.append(time.time()-t0)
        print(f"N states: {n_state}, time: {times[-1]:.2f}")
    times_dp[one_transition]=times
```

For the training times on sequence which are 50000 long I obtain for the case with  transitions to the next integer:
N states: 10, time: 0.42
N states: 50, time: 5.02
N states: 100, time: 17.09
N states: 200, time: 63.24

And for the case with random transitions:
N states: 10, time: 0.80
N states: 50, time: 12.76
N states: 100, time: 44.04
N states: 200, time: 158.91

Is it the kind of speed up you had in mind?
Best

**Comment by jmschrei** [comment]
Yes, that looks about right.

Given that resolving the issue would be challenging for the above reasons, I'm going to close this issue. Sorry you're encountering the issue. Let me know if you have thoughts on a way to resolve it while still doing a forward pass after fitting the distributions.
