### ISSUE TITLE
"Updating" existing parameters in a bayesian network with new data?

### ISSUE THREAD

**Issue by ronikobrosly** [jmschrei/pomegranate#915]
Hello, thank you for putting together this fantastic package! I have a question related to parameter learning.

Let's say I have a fully-defined bayesian network with parameters / conditional probability tables that were generated by experts that I manually typed in (I didn't have any data initially). In the future I come across data, and I'd like to "update" the parameters with this new data. That doesn't mean throw away the the old parameters and do parameter learning with the new data only. I'd like to tweak the new parameters. 

Is there a way to do this in pomegranate? Or do you have a suggestion on how to do this another way? Thank you!

**Comment by ronikobrosly** [comment]
Or @jmschrei if there isn't a built in method to do this (starting to suspect there isn't one), is there a point in the code you could point me to for me to hack a solution? Like maybe when `baking` a bayesian network there is a spot in the code that allows for initialization values and I could plug in the old parameters, or something like that?

**Comment by jmschrei** [comment]
You can use `inertia` to define how you'd like to mix old and new parameters. Setting `inertia` to 1 means that you ignore new data and setting it to 0 means you ignore old data and do MLE solely on the new data.

**Comment by ronikobrosly** [comment]
Oh interesting, thanks for pointing that out @jmschrei ! So to recap, the process would look like this?

```
<manually specify CPDs through expert opinions>
model.bake()

model.fit(X, inertia = 0.5)
```

**Comment by jmschrei** [comment]
Yes, that's right. You'll probably need to tune the inertia to get the right balance between expert knowledge and data, but that's the code you'd use.

**Comment by ronikobrosly** [comment]
Thanks a million!
