### ISSUE TITLE
Request: Get weights from GeneralMixtureModel

### ISSUE THREAD

**Issue by os-git-team** [jmschrei/pomegranate#917]
Hi, I am currently working with your really helpful framework. My problem is, I am getting other weights with 'model.weights' than these, which are used for the actual model (these are also do not sum up to 1). 
Is there a way to get these weights, which are used for the model?
Best regards Stefan

**Comment by lipinoelbreve** [comment]
model.weights return the logarithm of your weight.

You can retrieve those and then your weights would be e^(model.weights)
Or you can get the weights by converting the model into json and then extracting the weights: json.loads(str(model))['weights']

Hope it helps

**Comment by os-git-team** [comment]
Perfect! Thank you :)
