### ISSUE TITLE
model for wind turbine prediction

### ISSUE THREAD

**Issue by sdementen** [jmschrei/pomegranate#918]
hello,

I am wondering if an HMM could be useful for the following case: detection of partial availability of a wind park.

I observe the total electricity production P(t) on a given hour t, I also have an approximate observation Wa(t) of the real windspeed W(t). There is a function (called the power curve) that give the expected production Pe(t) in function of the wind speed Pe(t) = powercurve(W(t)) + small noise. On a given time, the wind park may only be partially available with a percentage a(t) (eg 50% if 50% of the wind turbines of the park are in maintenance/outage).

So, we have
```
W(t) = unobserved wind speed
Wa(t) = observed approximate wind speed = W(t) + noise
Pe(t) = unobserved full electricity production = powercurve(W(t)) + noise
Pa(t) = observed full approximate electricity production = powercurve(Wa(t))
P(t) = observed real (partial) electricity production = Pet(t) * a(t)
a(t) = unobserved partial availability of the wind park (taking values in i / N for i=0,...,N with N the number of wind turbines in the park).
```

Can I model this as an HMM and unhide the a(t) (hence detect when the wind park is partially available) from a time series of P(t), Wa(t) or P(t), Pa(t) ?
I have tried modeling the P(t),Pa(t) as a MultivariateGaussianDistribution with N states (expecting to see the HMM capture the different distributions approximating like P(t) = 0% * Pa(t), P(t) = 50% * Pa(t) and P(t) = 100% * Pa(t) (if N=2) but with no much success. 
I think I am not "getting it"...

**Comment by jmschrei** [comment]
I think that HMMs would work for this problem as long as you manually defined the distributions of the underlying states and then didn't do any training. The problem with training is that you begin to lose physical connections between a(t) and the other variables. For example, let's say that each turbine produces some amount of energy + noise and all you have is the total energy production. If each turbine produces ~10 units, you'd want your state corresponding to 1 turbine active to be like N(10, 1), the state for 2 turbines active to be N(20, 1)... etc. You can then use that model to decode any time series of power observations. But once you start training the model you might get weird things like 1 turbine is N(5, 3.7) and 2 turbines is N(25, 0.8), which is not physically possible.
