### ISSUE TITLE
Bayesian Network Reverse Chain Rule

### ISSUE THREAD

**Issue by priamai** [jmschrei/pomegranate#919]
Hi there,
I do a lot of simple bayesian inference with Excel and I am wondering if I can achieve this very simple case via your Bayesian Network.
Known probabilities:

```
p(MDB|REV) = 25%
p(MDB|~REV)= 1%
p(REV|PPT)=95%
p(REV|~PPT)=0.05%
p(PPT)=1%
```
All variables MDB,REV,PTT are binary.
I calculate the following via simple Bayes chain rule:
```
p(REV|MDB)
p(REV|~MDB)
p(MDB)
p(REV)
```
Which in this specific case, solved:

```
p(REV|MDB)=20.15%
p(REV|~MDB)=0.76%
p(MDB)=1.24%
p(REV)=1.00%
```
Any help would be great.

**Comment by jmschrei** [comment]
Yes. You can create a Bayesian network using these variables. Please see the tutorials for guidance.
