### ISSUE TITLE
Add functions/classes to readthedocs with autoclass

### ISSUE THREAD

**Issue by achalddave** [jmschrei/pomegranate#92]
It would be helpful to be able to easily read through the various classes and their methods on the readthedocs website, similar to http://hmmlearn.readthedocs.org/en/latest/api.html. It seems this would be straightforward, and would require adding a file similar to https://raw.githubusercontent.com/hmmlearn/hmmlearn/master/doc/api.rst. Not entirely sure if that's all that's required, though - I'm not too familiar with readthedocs setup.

**Comment by jmschrei** [comment]
This is an excellent idea. I've been meaning to add more to the documentation, but this seems like a much better way of going about it.

**Comment by jmschrei** [comment]
So I've added the files and adding sphinx to the readthedocs site, and while it seems to be working on my local machine it's not working on the readthedocs site (see the Naive Bayes section). Any insight from anyone on how to turn this on properly?

**Comment by jmschrei** [comment]
Added!
