### ISSUE TITLE
Weights in Bayesian networks

### ISSUE THREAD

**Issue by sherwinfarrell** [jmschrei/pomegranate#920]
Hi,

Would anyone be able to tell me what are the weights used for in the bn.from_samples and bn.fir methods?

**Comment by jmschrei** [comment]
If you'd like to weight some examples more heavily than others. In the context of a BN it essentially corresponds to the number of times that example occurs in the data set.

**Comment by sherwinfarrell** [comment]
Since I'm using it for censored data it seems like the right way to go. Also are there any papers published for the structural learning algorithms like the greedy algorithm and the exact algorithm in specific?

Thanks a ton for the help

**Comment by jmschrei** [comment]
I didn't publish a paper on the greedy algorithm, but the gist is that the exact algorithm uses dynamic programming to find the optimal topological sort of the variables as well as the optimal parents given that sort. The greedy algorithm greedily does the topological sort but optimally finds parents given that sort. You can read this for the exact algorithm: https://www.jair.org/index.php/jair/article/view/10835

**Comment by sherwinfarrell** [comment]
Thank you so much for all the help, it was quite useful !!
