### ISSUE TITLE
Supervised Sequence Labeling: Boolean index error when using `from_samples` method

### ISSUE THREAD

**Issue by YYYasin19** [jmschrei/pomegranate#922]
Hello, 

I am trying to solve a task where I have 3 sequences (shape: 3 x `[n_observations, 7]`) and their labels (shape: 3 x `[n_observations, 1]`) and now want to predict for a new, given sequence the corresponding labels.

My code looks as follows:

```python
model = HiddenMarkovModel().from_samples(MultivariateGaussianDistribution, n_components=4, X=sequences, labels=sequences_labels, algorithm='labeled')`
```
where `sequences = [sequence1, sequence2, sequence3]` and `sequences_labels` accordingly.

After running the above code, I get the following error:
```python
IndexError: boolean index did not match indexed array along dimension 1; dimension is 7 but 
corresponding boolean dimension is 1
```
at 
```python
/pomegranate/hmm.pyx:3615 in pomegranate.hmm.HiddenMarkovModel.from_samples
```

Does anyone have an idea what is causing the error?
Thanks in advance!

PS: Sorry if there is a similar issue, I could't find one.

**Comment by jmschrei** [comment]
I think that the label dimension should be a list of vectors, not a list of 2D matrices with one dimension being of size 1. Can you try that?

**Comment by YYYasin19** [comment]
Thank you, that was really the issue! 

I will not get the following warning during training, but it seems to get through.
```python
Exception ignored in: 'pomegranate.hmm.HiddenMarkovModel._labeled_summarize'
Traceback (most recent call last):
  File "<...>/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
KeyError: 0
```
