### ISSUE TITLE
Supervised HMM: MultivariateDistribution has no attribute 'parameters'

### ISSUE THREAD

**Issue by YYYasin19** [jmschrei/pomegranate#923]
Hey, 

I am trying to train a HiddenMarkovModel supervised on a Left-to-Right topology and have used the following code for modeling 3 states.
My data is multi-dimensional (and therefore the idea to use `MultivariateDistribution`).

```python
s1 = State(MultivariateDistribution(), name="Phase 1")
s2 = State(MultivariateDistribution(), name="Phase 2")
s3 = State(MultivariateDistribution(), name="Phase 3")

model_man = HiddenMarkovModel(start=s1, end=s3)
# model_man.add_states([s1,s2,s3])

model_man.add_transitions(s1, [s1,s2,s3], [0.5,0.5,0.0])
model_man.add_transitions(s2, [s1,s2,s3], [0.0,0.5,0.5])
model_man.add_transitions(s3, [s1,s2,s3], [0.0,0.0,1.0])

model_man.bake()
model_man.fit(sequences, labels=sequences_labels, algorithm="labeled")
```

Which  results in the following error:
```python
AttributeError: 'pomegranate.distributions.distributions.Multivaria' object has no attribute 
'parameters'
```

-------------------
Note: Using `MultivariateGaussianDistribution` won't work as well and results in the following error:
```python3
LinAlgError: 1-dimensional array given. Array must be at least two-dimensional
```
-------------------

Do I have a wrong understand of what the distributions represent?

Thanks in advance for you help!

**Comment by jmschrei** [comment]
When you write out the model by hand by hand you have to add in the states, and inside the states the distributions have the be fully defined including the parameters. This is in contrast to the `from_samples` method where you just need to pass the distribution type and it will learn the parameters. This is so you can create your own models with pre-defined parameters and use them for inference, or as a known starting point for EM. `MultivariateDistribution` is only a base class for multivariate distributions, such as multivariate Gaussian distributions, to inherit from.

**Comment by YYYasin19** [comment]
Makes sense, I now first initialized the distributions with `from_samples` on the different data states.

Unfortunately, I get the following error during inference now everytime:
```python
/home/.../pomegranate/hmm.pyx:2308 in 
 pomegranate.hmm.HiddenMarkovModel.predict
[Errno 2] No such file or directory: '/home/.../pomegranate/hmm.pyx' 
TypeError: 'NoneType' object is not iterable
```

Does this have anything to do with the distributions?

**Comment by jmschrei** [comment]
Unfortunately, I don't know what the source of that error is. It doesn't look like an issue with the composition of the HMM, but rather with the installation. Is it possible for you to completely wipe pomegranate from your system and re-install it?

**Comment by YYYasin19** [comment]
Hey, 

sorry for the late reply. Unfortunately, that doesn't seem to solve the issue.
I will try to validate all datapoint and algorithm inputs again.

In the meantime: Is there a code example of Supervised HMM training with a Left-to-Right / Custom model topology? How would one normally perform this?

**Comment by jmschrei** [comment]
I don't know exactly what you mean by a "custom model topology." You can create an HMM with any structure by using the `add_states` function initially and then the `add_edge` method iteratively. The basic HMM tutorial should have several examples. https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_3_Hidden_Markov_Models.ipynb
