### ISSUE TITLE
[BUG] HMM n_states = 8 but return a transition matrix 10*10

### ISSUE THREAD

**Issue by zihuaihuai** [jmschrei/pomegranate#924]
**Describe the bug**
HMM = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=8, X=[X_stack], verbose =False, random_state = random_state)
transition_matrix = HMM.dense_transition_matrix()
transition_matrix.shape

**Comment by jmschrei** [comment]
The first two states are the start and end states, which are silent.
