### ISSUE TITLE
[BUG] fixed random state doesn't generate eterministic results

### ISSUE THREAD

**Issue by zihuaihuai** [jmschrei/pomegranate#925]
When I run the same script twice, and by fixing the random state to a certain integer, the transition matrix of HMM is not the same.

**Comment by jmschrei** [comment]
I really need more information than this, sorry. What method are you calling? Is it a fixed data set or a randomly generated one? Are the numbers different or just the order of rows and columns in the matrix?

**Comment by zihuaihuai** [comment]
sorry for not describing the issues clearly. The method is HMM.from_samples(X, ..., random_statet = 0). When I fixed the input, the methods gave me different models with different transition matrices, thus influencing my post hoc analysis. I tried to control every other variable I could imagine, the input the parameters, and the running machine

**Comment by horaceg** [comment]
I had exactly the same observation. In order to fix it, I used a single call to `np.random.seed(0)` before calling the method and it works.

I wonder if it isn't due to the way that `RandomState` works in `numpy`, cf https://scikit-learn.org/stable/common_pitfalls.html#controlling-randomness

**Comment by jmschrei** [comment]
Thanks for the report. The issue was that k-means (specifically, the initialization step of k-means) did not accept a random seed and so the initialization for the HMM changed each time. I've added a change to make the HMM pass its random state to k-means.

**Comment by jmschrei** [comment]
I'll try to release v0.14.6 in the next few days which will contain this fix. If the issue persists after you download that version, please re-open the issue.
