### ISSUE TITLE
Kmeans docs state default stop_threshold of 0.1 but it is actually 1e-3

### ISSUE THREAD

**Issue by mparker2** [jmschrei/pomegranate#926]
Hi @jmschrei, 

Thanks for maintaining pomegranate🙂
The docstring for Kmeans.fit states:

https://github.com/jmschrei/pomegranate/blob/e113f3e599ebda81666cb818b8dfc7b65106e4fc/pomegranate/kmeans.pyx#L356-L359

but in fit definition:

https://github.com/jmschrei/pomegranate/blob/e113f3e599ebda81666cb818b8dfc7b65106e4fc/pomegranate/kmeans.pyx#L334

I'm not sure which is a better default though 🤷

**Comment by jmschrei** [comment]
Oops. Fixed.
