### ISSUE TITLE
How to create emission matrix by observations and its emission probabilities and then initialize a HMM?

### ISSUE THREAD

**Issue by SummerDoctor** [jmschrei/pomegranate#930]
Hi,

I am creating a hybrid model of ANN and HMM.

I got emission probilities of each observation, P(x|a). I need to use these emission probabilities to create the emission matrix and then initialize a continuous HMM. How could I do so?

As far as I know, the emission matrix should has distribution parameter values to express the distribution of observations. I want to use the emission probabilities to create emission matrix, instead of generate distribution from observation values.

Thx!

**Comment by jmschrei** [comment]
Have you seen the tutorial here? https://github.com/jmschrei/pomegranate/blob/master/tutorials/C_Feature_Tutorial_6_Deep_Models.ipynb

**Comment by SummerDoctor** [comment]
Thank you very much!
