### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [jmschrei/pomegranate#931]
Problem
---------
On aarch64, ‘pip install pomegranate’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi. 

Resolution
-----------
On aarch64, ‘pip install pomegranate’ should download the wheels from pypi 

@jmschrei, @Team Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
