### ISSUE TITLE
Implementing bayes net

### ISSUE THREAD

**Issue by slala2121** [jmschrei/pomegranate#936]
Hi,

I tried following the tutorials but I'm running into issues implementing this kind of structure below. I get IndexError: list index out of range. 

Would you be able to provide a small sample code for this structure?

Thanks.

Screen Shot 2021-08-16 at 7.49.44 PM.png

**Comment by jmschrei** [comment]
I implement a Bayesian network with a structure like this in the tutorial here: https://github.com/jmschrei/pomegranate/blob/master/tutorials/B_Model_Tutorial_4_Bayesian_Networks.ipynb

Can you be more specific with the code you're using and the full error message?

**Comment by slala2121** [comment]
The Monty Carlo sample has 2 parent nodes leading into 1 child node. I'm interested in a bayes net that has 1 parent node with 2 children node. I'll provide sample code shortly.

**Comment by slala2121** [comment]
Here's the code:

`diabetes_state=State(DiscreteDistribution({'0':0.8,'1':0.2}),'diabetes')

glucose_dist=ConditionalProbabilityTable([['0','0',0.75],
                                            ['0','1',0.2],
                                            ['0','2',0.05],
                                          ['1','0',0.05],
                                            ['1','1',0.25],
                                            ['1','2',0.7]
                                         ])
glucose_state=State(glucose_dist,'glucose')


bp_dist=ConditionalProbabilityTable([['0','0',0.9],
                                            ['0','1',0.05],
                                            ['0','2',0.05],
                                          ['1','0',0.1],
                                            ['1','1',0.2],
                                            ['1','2',0.7]
                                         ])
bp_state=State(bp_dist,'bp')


pom_model = BayesianNetwork()
pom_model.add_states(diabetes_state,glucose_state,bp_state)
pom_model.add_edge(diabetes_state,glucose_state)
pom_model.add_edge(diabetes_state,bp_state)

    
pom_model.plot()

pom_model.bake()`



Error message:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-373-ea2c54134744> in <module>()
     29 pom_model.plot()
     30 
---> 31 pom_model.bake()

/Users/sayeril/opt/anaconda3/envs/ele364_prob_env/lib/python3.6/site-packages/pomegranate/BayesianNetwork.pyx in pomegranate.BayesianNetwork.BayesianNetwork.bake()

TypeError: 'NoneType' object is not iterable

**Comment by slala2121** [comment]
Here's the code:

`
diabetes_state=State(DiscreteDistribution({'0':0.8,'1':0.2}),'diabetes')

glucose_dist=ConditionalProbabilityTable([['0','0',0.75],
['0','1',0.2],
['0','2',0.05],
['1','0',0.05],
['1','1',0.25],
['1','2',0.7]
])
glucose_state=State(glucose_dist,'glucose')

bp_dist=ConditionalProbabilityTable([['0','0',0.9],
['0','1',0.05],
['0','2',0.05],
['1','0',0.1],
['1','1',0.2],
['1','2',0.7]
])
bp_state=State(bp_dist,'bp')

pom_model = BayesianNetwork()
pom_model.add_states(diabetes_state,glucose_state,bp_state)
pom_model.add_edge(diabetes_state,glucose_state)
pom_model.add_edge(diabetes_state,bp_state)

pom_model.plot()

pom_model.bake()
`

Error message:
TypeError Traceback (most recent call last)
in ()
29 pom_model.plot()
30
31 pom_model.bake()

lib/python3.6/site-packages/pomegranate/BayesianNetwork.pyx in pomegranate.BayesianNetwork.BayesianNetwork.bake()

TypeError: 'NoneType' object is not iterable

**Comment by slala2121** [comment]
Ok, I realized I'm not passing in the diabetes_dist into the conditional probability table objects so I think that resolves it.
