### ISSUE TITLE
Finding the number of iterations that train() runs till convergence? Also, issue with the output printed at every iteration

### ISSUE THREAD

**Issue by narendramukherjee** [jmschrei/pomegranate#94]
2 questions:
1. I am running the train function (with baum-welch) - I am wondering if there's a way I can get the number of iterations that the train loop runs till convergence and the log-likelihood of the model at every iteration step from model instance? Something like a list containing the log likelihood at every iteration step - the length of this list gives the number of iterations. I want to run several seeds and fix the maximum number of iterations to a manageable number and pick the seeds that have hit the stop threshold before the iterations reach that maximum.

2. Every iteration of the train loop prints an output of this kind:
...
hmm:  -1071.56869799 -9.30763231015 -1080.8751549
hmm:  -1071.69600328 -9.18032344342 -1080.8751549
hmm:  -1071.82331108 -9.05301459842 -1080.8751549
hmm:  -1071.95061963 -8.92570582563 -1080.8751549
hmm:  -1072.07792841 -8.79839729261 -1080.8751549
hmm:  -1072.20523726 -8.67108955602 -1080.8751549
hmm:  -1072.33254612 -8.54378446468 -1080.8751549
hmm:  -1072.459855 -8.41648815939 -1080.8751549
...
This is probably coming from (hmm.pyx):
with gil:
	print( "hmm: ", f[(i+1)*m + k], b[(i+1)*m + k], log_sequence_probability)

Is there some way to suppress this from printing? This makes it difficult to see the training improvement at every iteration with verbose=True

Thanks so much!

**Comment by jmschrei** [comment]
Ruh roh. That was a mistake from me debugging. The latest code has the fix for the printing issue, checking it out should fix that problem.

For the main issue, it may be possible for fit to return a history of the log probability/improvement at each iteration. Would that be helpful?

**Comment by narendramukherjee** [comment]
Thanks for the reply, I will pull the new code right away!

Yes, getting the log probability/improvement at each iteration would indeed be helpful for me to run several seeds and see which ones converged in a finite number of iterations (that I put into max_iterations)..

**Comment by narendramukherjee** [comment]
So, I think I was just too used to yahmm to appreciate the speedup afforded by pomegranate's parallel processing - I might not need to terminate seeds within max_iterations now and can run them till they converge. I am just used to specifying the maximum iterations in every implementation of Baum Welch I've run (like hmmlearn) because the iterations were slow, but  that is no longer a problem with pomegranate. In case I still feel the need for the training improvements at every step, I'll update this issue. Thanks for your help Jacob as always!
