### ISSUE TITLE
Memory consumption while using train() in parallel with n_jobs > 1

### ISSUE THREAD

**Issue by narendramukherjee** [jmschrei/pomegranate#95]
I've been running a dataset containing 30 sequences with 2000 observations each through train/fit with baum-welch. I see the memory consumption creeping up with iterations - this increase becomes really significant when I set n_jobs to be larger than 1 (I am using an 8 core processor): with n_jobs = 6, the memory consumption hits the RAM limit really soon. Is this supposed to happen, or am I doing something wrong in assigning n_jobs?

Thanks!

**Comment by jmschrei** [comment]
Theoretically it shouldn't happen, but implementation wise I may be copying data. I'm planning on revamping the HMM training methods soon to include out of core training soon, so I'll take a look at this as well.

**Comment by narendramukherjee** [comment]
Thanks for the reply Jacob - could you post an update when you've looked at this issue?

**Comment by jmschrei** [comment]
I've found the issue and will be resolving it today (hopefully). Memory leaks because I wasn't freeing all the pointers.

**Comment by narendramukherjee** [comment]
Thanks Jacob, I am looking forward to trying the new version as soon as the issue is fixed :)

**Comment by jmschrei** [comment]
An issue I ran into today took longer to resolve than expected, so I'll finish it tomorrow!

**Comment by jmschrei** [comment]
Let me know if the new version fixes the memory leak for you.

**Comment by narendramukherjee** [comment]
The new version doesn't seem to fix the memory leak - I am posting my code and some data here so that you can try it too, and see if you come up with the same results.
Code:
[pomegranate_test.txt](https://github.com/jmschrei/pomegranate/files/185285/pomegranate_test.txt)


Data: (There are 30 trials/sequences, each on a separate line, with 2000 emissions each - the emissions are all discrete integers)
[data.txt](https://github.com/jmschrei/pomegranate/files/185286/data.txt)

Just looking at the code while it runs using the top command, I see the memory consumption growing - it hits about 97-98% of total memory before the system kills the task. Again, as previously, the growth is much faster if I use n_jobs>1 - I have tried using n_jobs = 1 and running several seeds (aka different initial parameters) with the multiprocessing module: that hits the same bottleneck.

**Comment by narendramukherjee** [comment]
I am wondering if a sensible fix to this for my application would be to tone down the number of iterations (setting max_iterations to something like 500-1000 for instance) and run a large number of seeds (different initializations). Keeping max_iterations within a reasonable number seems to help with the memory leak issue - the consumption only grows as the number of iterations to convergence goes up. So I can run a number of different initializations and pick the ones that hit the convergence criterion within max_iterations - this was the issue I brought up in #94. I cannot do this unless I know how many iterations the model took to hit the convergence criterion - would it be possible to add the number of iterations run by the model to the model instance? I mean, just passing the value of the iterations variable here to a self.iterations variable?
...
while improvement > stop_threshold or iteration < min_iterations:
				if iteration >= max_iterations:
					break 
...   

Let me know what your thoughts are on the whole issue, and thanks for helping out!

**Comment by jmschrei** [comment]
I've been able to reproduce the error and am hunting down the issue right now. It's def a memory leak on my part but I'm not entirely sure where it's coming from.

The majority of training usually happens in the first ~3-5 iterations with Baum Welch so it may not be terribly unreasonable to only run it for 10. That's not a solution to the memory leak though. You can pass in max_iterations=10, min_iterations=10 to ensure that it runs for exactly 10 iterations.

**Comment by jmschrei** [comment]
Memory leak found. I was looking in the wrong place (as is often the case with memory leaks). I was not freeing the forward matrix in the log probability calculation, or the forward/backward matrices at the end of summarization. I'll submit a patch as soon as I finish some documentation.

**Comment by narendramukherjee** [comment]
Ah thanks so much for all that Jacob, that was really helpful! So excited to try the new version soon!

**Comment by jmschrei** [comment]
I forgot to mention this was fixed yesterday. Let me know if it works for you.

**Comment by narendramukherjee** [comment]
It works perfectly now Jacob, thank you so much for all the help! I am closing this issue now.
