### ISSUE TITLE
[BUG] BayesianNetwork docs mention `score()` method but none exists

### ISSUE THREAD

**Issue by mxndrwgrdnr** [jmschrei/pomegranate#954]
The docs describe a `BayesianNetwork.score()` method [here](https://pomegranate.readthedocs.io/en/latest/BayesianNetwork.html#pomegranate.BayesianNetwork.BayesianNetwork.score), but none exists in the code.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
