### ISSUE TITLE
Difference between probabilities in Pomegranate and other tools?

### ISSUE THREAD

**Issue by objMihail2** [jmschrei/pomegranate#956]
I found differences between result probabilities in Pomegranate and other tools - OpenMarkov and, probably, BNLearn. Below is simplest example. So, it is like bug or my code for Pomegranate is incorrect? I checked it several times. The code prototype was Asia example (https://github.com/jmschrei/pomegranate/blob/master/examples/bayesnet_asia.ipynb).

![OpenMarkov](https://user-images.githubusercontent.com/97360723/148656814-29193f6f-c3c1-45f4-8b13-dffe26b1c6ae.png)

![Untitled2](https://user-images.githubusercontent.com/97360723/148656828-f5f50ae9-3df9-4bd2-8962-dd4eb146988a.png)

**To Reproduce**

Pomegranate code:
[PomegranateCode.txt](https://github.com/jmschrei/pomegranate/files/7833845/PomegranateCode.txt)

Pomegranate result output: 
[Result.txt](https://github.com/jmschrei/pomegranate/files/7833847/Result.txt)

**Comment by jmschrei** [comment]
pomegranate uses the loopy belief propogation algorithm which is simple to code and usually faster in practice on large networks but only provides approximate probabilities. bnlearn probably uses the exact algorithm, which is more complicated

**Comment by jmschrei** [comment]
It's also possible that the algorithm, which is iterative, hasn't yet converged. You can check this by increasing max_iterations in the prediction call. On a tree-structured network the loopy belief propagation algorithm is guaranteed to converge to the exact solution but I don't think that holds on other types of networks.

**Comment by objMihail2** [comment]
Thanks! Glad to hear it's not a bug, but feature :) I couldn't find any big differences in probabilities, but support of large networks will be very useful.
