### ISSUE TITLE
HiddenMarkovModel from_samples() raises the error in 'labeled' mode

### ISSUE THREAD

**Issue by kirlf** [jmschrei/pomegranate#957]
I'm trying to implement supervised HMM model, and therefore I'd like to use your library. If I understand correctly this can be done via ``` from_samples()``` method with ``` algorithm='labeled' ``` option. But I'm obtaining the following error, unfortunately:

``` python

/usr/local/lib/python3.7/dist-packages/pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.from_samples()

/usr/local/lib/python3.7/dist-packages/pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.from_matrix()

IndexError: index 2 is out of bounds for axis 0 with size 2
```

**To Reproduce**

Small piece of my code:

``` python
from pomegranate import MultivariateGaussianDistribution as mvgauss
from pomegranate import HiddenMarkovModel as hmm

X_train, y_train = create_features(df_train, label=KPI)
seq_len = 365*24 # sequence length

X_super_hmm = [X_train.to_numpy()[i*seq_len:seq_len*(i+1), :] for i in range(2)]
# X_super_hmm[0].shape
# >>> (8760, 2)
# X_super_hmm[1].shape
# >>> (8760, 2)

y_super_hhm = [y_train.to_numpy()[i*seq_len:seq_len*(i+1)] for i in range(2)]
# y_super_hhm[0].shape
# >>> (8760, )
# y_super_hhm[1].shape
# >>> (8760, )

n_components = 2

model = hmm.from_samples(distribution = mvgauss, 
                        n_components=n_components, 
                        X=X_super_hmm,
                        labels= y_super_hhm, 
                        algorithm='labeled')
```

The same with:

```python 
model = hmm.from_samples(distribution = mvgauss, 
                        n_components=n_components, 
                        X=X_super_hmm,
                        labels=[list(i) for i in y_super_hhm], 
                        algorithm='labeled')
```

Could you point me what's wrong with dimensions? 

Whole traceback:

``` python

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-40-65abf2c9ba4a> in <module>()
      6                         X=X_super_hmm,
      7                         labels=[list(i) for i in y_super_hhm],
----> 8                         algorithm='labeled')

1 frames
/usr/local/lib/python3.7/dist-packages/pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.from_samples()

/usr/local/lib/python3.7/dist-packages/pomegranate/hmm.pyx in pomegranate.hmm.HiddenMarkovModel.from_matrix()

IndexError: index 2 is out of bounds for axis 0 with size 2

```

I have also mentioned that numbers in ``` index 2 is out of bounds for axis 0 with size 2 ``` are related with ``` n_components``` parameter. Is this number of HMM states or something else?

I'll appreciate your help!

P.S. 
``` pomegranate-0.14.7 ```

**Comment by kirlf** [comment]
And additional question. Is this matrix of features or observations:

``` X array-like or generator
An array of some sort (list, numpy.ndarray, tuple..) of sequences, where each sequence is a numpy array, which is 1 dimensional if the HMM is a one dimensional array, or multidimensional if the HMM supports multiple dimensions. Alternatively, a data generator object that yields sequences.
```

Maybe, I don't understand correctly. I try to train the model with stable features (day of year, hour) with respect to some target vector (KPI). My goal: prediction of the KPI by these features (w/o available measurements).  

Can this task be covered by ```HiddenMarkovModel.from_samples()```, or I'm wrong?

I'll appreciate your response!

**Comment by jmschrei** [comment]
Unfortunately, I probably won't be able to provide much help unless you can give an exact reproducible example. 

Hidden Markov models can be thought of as sequential clustering. Like normal clustering, you can use EM (called Baum-Welch here) to infer the cluster parameters during training. Unlike normal clustering, the assignment for each observation depends on the previous and next observation in the sequence. If you have labels for each observation in the sequence you can (theoretically) derive cluster parameters easily but if you have the labels you're usually better off training an explicitly supervised model.

**Comment by kirlf** [comment]
Thanks for response!

I see now that ```n_components``` should be equal to length of labels in considered mode. Maybe, it is reasonable to add some explanation or example into documentation?

BR
