### ISSUE TITLE
Expedite Bayesian Network from_json( ) and from_dict( ) deserialization process

### ISSUE THREAD

**Issue by wjianga** [jmschrei/pomegranate#958]
Hi. Thanks for this amazing package.

I recently built a Bayesian Network model using from_structure() and serialized it into a JSON file and a Python pickled dict binary file. When I tried to deserialize it using from_json() and from_dict() respectively for prediction, the time it took was longer than building a model from raw data. Is there any way to speed up the deserialization process? Otherwise, I will have to build a new model using from_structure( ) every time I want to make predictions.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
