### ISSUE TITLE
[BUG] GMM call to from_samples gives an error about dimensions of input array.

### ISSUE THREAD

**Issue by hassell-nmm** [jmschrei/pomegranate#959]
**Describe the bug**
Attempting to train a GeneralMixtureModel from samples of data and a "ValueError: need more than 1 value to unpack" issue.  I seek to see how GMMs work on choosing distributions over data sets.  I use multiple distributions and all the training data for calling from_samples, passing the data as an array:

          Xarray-like, shape (n_samples, n_dimensions)

**To Reproduce**
```
import pomegranate as pm
import numpy as np

distributions = [pm.NormalDistribution, pm.LogNormalDistribution, pm.ExponentialDistribution, \
                          pm.UniformDistribution, pm.PoissonDistribution, pm.BetaDistribution, \
                          pm.GammaDistribution]

a = np.array([[1,2,3,4,5], [7,8,9,10,11]])

model = pm.GeneralMixtureModel.from_samples(distributions, \
                                            n_components=3, \
                                            X=a)
```

**Comment by cleitonmoya** [comment]
Same error here.

```
import numpy as np
from pomegranate import GeneralMixtureModel, PoissonDistribution

X = np.array([13, 14,  8, 10, 16, 26, 32, 27, 18, 32, 36, 24, 22, 23, 22, 18, 25])
model = GeneralMixtureModel.from_samples(PoissonDistribution, n_components=2, X=X)
```

**Comment by KawasiroNitori** [comment]
I got the same problem, but solved like this:

'Shape' method of 'datagenerator' class in io.py uses 'shape' method of numpy,

and this needs well-defined dimensions of numpy-array type.

So I recommend you to use

 X = X .reshape(-1,1).

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
