### ISSUE TITLE
Adding new distributions

### ISSUE THREAD

**Issue by mandolinraman** [jmschrei/pomegranate#964]
Hello,

I apologize if this is already in the documentation but couldn't confirm. I'd like to add a new distribution for my problem, specifically an autoregressive Gaussian model with memory `M`: `P(X[n] | X[n - M : n])` and use it as a emission model for an HMM. If I implement a subclass of `Distributions` with the methods `log_probability`, `summarize` and `from_summaries` and `clear_summaries` will that be enough?

Thanks a lot!

**Comment by jmschrei** [comment]
Howdy. That should be enough. Read this tutorial for more: https://github.com/jmschrei/pomegranate/blob/master/tutorials/C_Feature_Tutorial_5_Custom_Distributions.ipynb
