### ISSUE TITLE
[Question] ICD combining multivariate and univariate distributions

### ISSUE THREAD

**Issue by seyuboglu** [jmschrei/pomegranate#965]
Is it possible to create an ICD combining multivariate distributions and univariate distributions?

Specifically, I'd like to fit a mixture model to some d + 1 dimensional data where the first d dimensions vary as a multivariate gaussian with non-identity covariance matrix and the last dimension is a discrete distribution. For example, this could look something like:

```python
import pomegranate as pg
model = pg.GeneralMixtureModel.from_samples(
  [pg.MultivariateGaussianDistribution, pg.DiscreteDistribution],
  n_components=5, 
  X=x
)
```

Looking at the implementation at [here](https://github.com/jmschrei/pomegranate/blob/0652e955c400bc56df5661db3298a06854c7cce8/pomegranate/gmm.pyx#L559) it seems like this is not currently possible, but I just wanted to confirm. 

If not, would it be straightforward for me to subclass `GeneralMixtureModel` and add support?

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
