### ISSUE TITLE
can't fit network using constraints graph with one variable in one of it's nodes

### ISSUE THREAD

**Issue by dolevamir** [jmschrei/pomegranate#966]
**Describe the bug**
I need to train a network (from samples) end enforce a structure where there is one node that can't be parents to other nodes. I've tried using the constraint graph but get the following error when fitting the network

TypeError: 'int' object is not iterable

I guess that it requires at least 2 elements in each constraint node? is there a different way to go about this? I couldn't gather anything else from the documentation

**To Reproduce**
```
numpy.random.seed(6)

X = numpy.random.randint(2, size=(200, 3))

a = networkx.DiGraph()
b = tuple((0, 1, 2))
c = 3

a.add_edge(b, c)
print("Constraint Graph")
plot_networkx(a)
plt.show()

print("Learned Bayesian Network")

model = BayesianNetwork.from_samples(X, algorithm='exact', constraint_graph=a)

plt.figure(figsize=(16, 8))
model.plot()
plt.show()
```

**Comment by dolevamir** [comment]
@jmschrei do you have any input on the above issue?

**Comment by arainboldt** [comment]
I'm also trying to utilize the `from_samples` method with constraints and encountering difficulties. It would be nice to know why this doesn't work. 

I get the following error when I run the above code:

```
     16 plt.show()
     18 print("Learned Bayesian Network")
---> 20 model = BayesianNetwork.from_samples(X, algorithm='exact', constraint_graph=a)
     22 #plt.figure(figsize=(16, 8))
     23 model.plot()

File ~/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/pomegranate/BayesianNetwork.pyx:1536, in pomegranate.BayesianNetwork.BayesianNetwork.from_samples()

File ~/.cache/pypoetry/virtualenvs/ml-XNmo5OXX-py3.8/lib/python3.8/site-packages/pomegranate/BayesianNetwork.pyx:2184, in pomegranate.BayesianNetwork.discrete_exact_with_constraints()

TypeError: can only concatenate tuple (not "int") to tuple
```

**Comment by jmschrei** [comment]
@dolevamir @arainboldt my recollection is that each of the entries has to be a tuple, even if there's only a single element in it. So, try

```python
a = networkx.DiGraph()
b = tuple((0, 1, 2))
c = tuple((3,))
```

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
