### ISSUE TITLE
[Question] How can I build the Bayesian Network with structure and data

### ISSUE THREAD

**Issue by reeingal** [jmschrei/pomegranate#967]
The `BayesianNetwork` class has the `from_samples()` method to learn the structure and fit the dataset. And I can use the `include_edges`, `exclude_edges` and `constrain_graph` parameters to guide the structure learn from dataset.

I am wondering that are there any methods to build `BayesianNetwork` if I have a structure want to test, and let it fit the dataset to learn network parmeters.

In official document, I see that I can use `DiscreteDistribution`, `ConditionalProbabilityTable` to build the `BayesianNetwork`, but it seems that I should give the distribution when I initial these objects.

Anyone can help me? Thank you.

**Comment by jmschrei** [comment]
Good question! This is exactly what BayesianNetwork.from_structure does. You pass in the structure as a set of tuples and all it does is learn the parameters of the tables.

**Comment by jmschrei** [comment]
I would recommend adding some fake training examples with sample weight of 0 to the `from_structure` call to make sure all the cases are fleshed out. There are better solutions, such as passing in a set of keys for all variables, but I'm about to rewrite pomegranate so it'll have to wait until then.

**Comment by jmschrei** [comment]
Good question! This is exactly what BayesianNetwork.from_structure does.
You pass in the structure as a set of tuples and all it does is learn the
parameters of the tables.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
