### ISSUE TITLE
Feature Request: Implementing sample() in MarkovNetworks

### ISSUE THREAD

**Issue by profPlum** [jmschrei/pomegranate#969]
Hi, it would be really helpful if this sample method existed. Without it, it is hard to compare to BayesianNetworks & other distributions.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
