### ISSUE TITLE
ImportError: no module named utils 

### ISSUE THREAD

**Issue by fpdx** [jmschrei/pomegranate#97]
(Hi. I hope this is appropriate here, otherwise let me know where to post this, I'm not an expert)
After installation in debian stable (by `sudo pip install pomegranate`), I get the following error while importing pomegranate in ipython:
```
In [1]: import pomegranate

ImportError                               Traceback (most recent call last)
<ipython-input-2-f115d95d8f94> in <module>()
----> 1 import pomegranate
/usr/local/lib/python2.7/dist-packages/pomegranate/__init__.py in <module>()
     36     pyximport.install()
     37 
---> 38 from .hmm import *
     39 from .BayesianNetwork import *
     40 from .FactorGraph import *
/home/fpdx/pomegranate/hmm.pyx in init pomegranate.hmm (pomegranate/hmm.c:53433)()
/home/fpdx/pomegranate/distributions.pxd in init pomegranate.base (pomegranate/base.c:22885)()
/home/fpdx/pomegranate/distributions.pyx in init pomegranate.distributions (pomegranate/distributions.c:65203)()

ImportError: No module named utils
```
Do you know what is it missing?

The end of the installation gave this :
```...
Installing cython script to /usr/local/bin 
    Installing cygdb script to /usr/local/bin`
    Installing cythonize script to /usr/local/bin
  Found existing installation: joblib 0.8.3
    Not uninstalling joblib at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pomegranate cython joblib networkx
Cleaning up...
```
To check the installation and versions:
```
$ pip show pomegranate
---
Name: pomegranate
Version: 0.3.7
Location: /usr/local/lib/python2.7/dist-packages
Requires: cython, numpy, joblib, networkx
```
```
$ pip show joblib
---
Name: joblib
Version: 0.9.4
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```
```
$ pip show cython
---
Name: Cython
Version: 0.23.4
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```
```
$ pip show networkx
---
Name: networkx
Version: 1.11
Location: /usr/local/lib/python2.7/dist-packages
Requires: decorator
```
```
$ pip show numpy
---
Name: numpy
Version: 1.8.2
Location: /usr/lib/python2.7/dist-packages
Requires: 
```

As a side note, if I repeat `import pomegranate` right after this error multiple times, I get the error with highlighted line changes to 
` ---> 39 from .BayesianNetwork import *`
next `import pomegranate`: 
`---> 44 from .gmm import *`
next `import pomegranate`:
`---> 45 from .NaiveBayes import *`
and next `import pomegranate` doesn't give an error. But then ipython cannot stand it:
```
In [6]: pomegranate.NormalDistribution(1,2)
Segmentation fault
```

**Comment by fpdx** [comment]
after full upgrade by pip of numpy, cython (and ipython), now pomegranate works.

**Comment by jmschrei** [comment]
I was just about to respond and say this is a really old error which I experienced a while ago, and that updating everything would probably help. Let me know if you encounter any other bugs!

**Comment by dflatow** [comment]
@fpdx I'm still having this issue even after I upgrade numpy, vython and ipython...
