### ISSUE TITLE
Means for clusters in HMM

### ISSUE THREAD

**Issue by malonzm1** [jmschrei/pomegranate#971]
Can I fix the gaussian means for the clusters in HMM? (I'm not sure if this is the right space for this question but I don't know any other forum for pomegranate).

**Comment by jmschrei** [comment]
Do you mean only learn the variances and HMM transitions, or only learn the HMM transitions?

**Comment by malonzm1** [comment]
Thanks. Only learn the variances and HMM transitions. Is this possible?

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
