### ISSUE TITLE
Segmentation fault when using n_jobs with HiddenMarkovModel.from_samples

### ISSUE THREAD

**Issue by malonzm1** [jmschrei/pomegranate#973]
When I try to run this code,
`model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=5, X=diffs, n_jobs=4)`
it returns a Segmentation fault.

Pls. advise.

Thanks and good day.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
