### ISSUE TITLE
Question re model.forward_backward(sequence)

### ISSUE THREAD

**Issue by malonzm1** [jmschrei/pomegranate#975]
Hi!

I understand `model.forward_backward(sequence)` returns the transition probability matrix. I just wanted to clarify the order. If I had 3 hidden states (with start and end) will the row/column names then be "start:s0:s1:s2:end" or "s0:s1:s2:start:end" or something else?

Thanks and good day.

**Comment by denklewer** [comment]
You can see the order in model.states 
` state_list = [state.name for state in model.states] 
start and end are usually last columns.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
