### ISSUE TITLE
Can the model state distributions be fixed?

### ISSUE THREAD

**Issue by malonzm1** [jmschrei/pomegranate#976]
Hi!

Can the model state distributions be fixed? Only fit the transition probability matrix?

Thanks and good day.

**Comment by jmschrei** [comment]
Yes. Pass `frozen=True` when constructing the distribution. If you're training a HMM you can also pass `distribution_inertia=1.0` into the `from_samples` or `fit` methods.

**Comment by jmschrei** [comment]
Glad that it's working.
