### ISSUE TITLE
[BUG] BayesianNetwork.from_samples() creates a faulty network

### ISSUE THREAD

**Issue by haaksb** [jmschrei/pomegranate#986]
**Describe the bug**

When running:
import pomegranate
model=pomegranate.BayesianNetwork.from_samples(df)
model.sample(1)

I get a sample that is simply long rows of something I believe is the input: 

array([['0        2.0\n1        2.0\n2        1.0\n3        1.0\n4        2.0\n5        2.0\n6        2.0\n7        2.0\n8        2.0\n9        2.0\n10       1.0\n11       2.0\n12       1.0\n13       2.0\n14       2.0\n15       2.0\n16       1.0\n17       2.0\n18       2.0\n19       2.0\n20       1.0\n21       1.0\n22       1.0\n23    ..... and so on. df only has 12 columns.

It is worth noting that this worked until quite recently, as I have trained models using from_samples() before. Loading those models I saved still works, and those models give natural samples.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
