### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by saulpierotti-ebi** [jmschrei/pomegranate#987]
Thank you for the very nice package. I have a few feature requests.

 It would be useful to have the possibility to specify inequality constraints as well as tied parameters. For example, I would want a model to have state A and state B, both with Gaussian emissions. I would like the emission variances to be equal, and the emission means to be respectively a `c` and `-c`, with c trainable.

On the same note, it would be useful to freeze only some parameters of a distribution and not the whole distribution. For example, I may want to freeze the mean of a Gaussian but not the variance.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
