### ISSUE TITLE
[BUG] Import fails after installing v0.14.8 

### ISSUE THREAD

**Issue by megawattfs** [jmschrei/pomegranate#989]
**Describe the bug**
Import failed with error message "ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject."

**To Reproduce**
I ran the installation and attempted to import pomegranate from a Jupyter notebook (see photo attached):
!pip install pomegranate
import pomegranate
![image](https://user-images.githubusercontent.com/45794019/185759828-4476376e-e667-46e2-bc10-737c9fc46a8f.png)

**Comment by megawattfs** [comment]
Note: I tried a few earlier versions and had the same problem. I have used Pomegranate without incident before.

**Comment by dolevamir** [comment]
you might need to revert to an older version of numpy in order to solve this

**Comment by megawattfs** [comment]
Even with numpy 1.20.0 (the minimum required) it is still like this--I have tried with several versions of numpy and several versions of pomegranate

**Comment by jmschrei** [comment]
Sorry that you're encountering issues. I'm currently rewriting pomegranate from the ground up using PyTorch, so all these installation issues should be resolved then.

**Comment by li-xie** [comment]
I had the same problem with 14.8. I had to go through the following steps to get rid of the error:
pip uninstall -y numpy
pip uninstall -y scipy
pip uninstall -y setuptools
pip install setuptools
pip install  numpy
pip install scipy

**Comment by amyfonget** [comment]
Has anyone found a solution? I tried li-xie's suggestion but that didn't change things for me.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
