### ISSUE TITLE
Saving multiple models

### ISSUE THREAD

**Issue by wes-lewis** [jmschrei/pomegranate#991]
**Describe the bug**
I'm training thousands of GMMs for a current project. I know I can save one model at a time to JSON, but I'd like to avoid having 1000+ JSON files to load. Is there a way to use the to_JSON functionality for a list of multiple GMMs, as a tuple or array? This seems preferable to pickling, given the weaknesses of pickle.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
