### ISSUE TITLE
Which HMM method returns a result for "What is the probability that the model generated the sequence" ?

### ISSUE THREAD

**Issue by teoML** [jmschrei/pomegranate#994]
Hi, I trained several HMMs and now I am looking for the method which gives me the probability of a trained HMM model generating a given sequence. My intention is to find out which model most probably generated the given the sequence. Which method to use to achieve this?

**Comment by jmschrei** [comment]
`model.probability` will give you P(sequence|model). Using Bayes rule you can just calculate `model.probability` for each HMM and choose the one with the highest probability.

**Comment by teoML** [comment]
Thanks for your reply! Is  `model.log_probability() `doing the same, but returning the log ? I tried running `np.exp()` to the result of it and it is not showing the same number as the output of the `model.probability(seq)`.

**Comment by teoML** [comment]
@jmschrei , by the way, I tried creating a sequence with length = 1000 using the `hmm.sample(length=1000)` method and after calling `hmm_model.probability(input_sampled_seq)` I get a probability of 0 - why is that possible?
