### ISSUE TITLE
The transition matrix doesn't seem to get updated when HHM is initialized with model name, start state and end state.

### ISSUE THREAD

**Issue by li-xie** [jmschrei/pomegranate#998]
**To Reproduce**
Windows 10
python 3.10.2
numpy 1.23.3
scipy 1.9.1
networkx 2.8.7
joblib 1.2.0
pomegranate 0.14.8 
When I run an example from the tutorial as below:
```
from pomegranate import *

s1 = State( NormalDistribution( 3, 1 ), name="s1" )
s2 = State( NormalDistribution( 6, 2 ), name="s2" )

model = HiddenMarkovModel('test', s2, s1)
model.add_states( [s1, s2] )
model.add_transition( s1, s2, 0.2 )
model.add_transition( s2, s1, 0.5 )
model.add_transition( s1, s1, 0.8 )
model.add_transition( s2, s2, 0.5 )
model.bake()
model.fit( [[5, 2, 3, 4, 7, 3, 6, 3, 5, 2, 4], [5, 7, 2, 3, 5, 1, 3, 5, 6, 2]])
tm = model.dense_transition_matrix()
print(f'transition matrix after fitting is: [[{tm[0,0]}, {tm[0,1]}],[{tm[1,0]},{tm[1,1]}]]')
```
The output is:
`transition matrix after fitting is: [[0.8, 0.2],[0.5,0.5]]`
The transition matrix doesn't seem to be updated. However, if I omit the model name during initialization and use `model = HiddenMarkovModel(s2, s1)` , the transition matrix gets updated. Did I misunderstand anything? Can anyone try to see if this behavior can be duplicated?
Thanks in advance!

**Comment by smalik89** [comment]
Good question! I also had a similar issue- how do you view the original transition matrix vs. the final transition matrix? Sometimes model.dense_transition_matrix() outputs one or the other.

**Comment by jmschrei** [comment]
You are not initializing the HMM correctly. Please see the tutorials for advice.

**Comment by smalik89** [comment]
@jmschrei  what am I missing?

**Comment by jmschrei** [comment]
Please see the tutorial folder in the repo.

**Comment by jmschrei** [comment]
Thank you for opening an issue. pomegranate has recently been rewritten from the ground up to use PyTorch instead of Cython (v1.0.0), and so all issues are being closed as they are likely out of date. Please re-open or start a new issue if a related issue is still present in the new codebase.
